INSERT IGNORE INTO `permissions` (`key`, `label`) VALUES
('orders.view','عرض الطلبات'),
('orders.create','إنشاء الطلبات'),
('orders.update','تعديل الطلبات'),
('orders.cancel','إلغاء الطلبات'),
('orders.refund','استرداد الطلبات'),
('invoice.view','عرض الفواتير'),
('invoice.issue','إصدار الفواتير'),
('invoice.void','إلغاء الفواتير'),
('payments.view','عرض المدفوعات'),
('payments.refund','استرداد المدفوعات'),
('inventory.view','عرض المخزون'),
('inventory.adjust','تعديل أرصدة المخزون'),
('inventory.transfer','تحويل المخزون'),
('purchase.view','عرض المشتريات'),
('purchase.create','إنشاء طلب شراء'),
('purchase.approve','اعتماد طلبات الشراء'),
('users.view','عرض المستخدمين'),
('users.manage','إدارة المستخدمين'),
('roles.manage','إدارة الأدوار والصلاحيات'),
('branches.manage','إدارة الفروع'),
('departments.manage','إدارة الأقسام'),
('settings.billing','إدارة الفوترة والاشتراك'),
('settings.integrations','إدارة التكاملات'),
('reservations.manage','إدارة الحجوزات'),
('pos.manage','إدارة نقاط البيع'),
('reports.financial','عرض التقارير المالية'),
('audit.view','عرض سجل التدقيق');
