CREATE TABLE IF NOT EXISTS `electronicInvoices` (
  `id` int AUTO_INCREMENT NOT NULL,
  `restaurantId` int NOT NULL,
  `orderId` int NOT NULL,
  `customerId` int,
  `invoiceNumber` varchar(80) NOT NULL,
  `invoiceType` enum('simplified','tax') NOT NULL DEFAULT 'simplified',
  `status` enum('issued','cancelled','refunded') NOT NULL DEFAULT 'issued',
  `currencyCode` varchar(3) NOT NULL DEFAULT 'SAR',
  `sellerName` varchar(180) NOT NULL,
  `sellerTaxNumber` varchar(64),
  `customerName` varchar(180),
  `customerTaxNumber` varchar(64),
  `subtotal` decimal(12,2) NOT NULL DEFAULT '0',
  `discountAmount` decimal(12,2) NOT NULL DEFAULT '0',
  `taxAmount` decimal(12,2) NOT NULL DEFAULT '0',
  `total` decimal(12,2) NOT NULL DEFAULT '0',
  `itemsSnapshotJson` text NOT NULL,
  `qrPayload` text,
  `issuedAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdByUserId` int,
  `createdAt` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT `electronicInvoices_id` PRIMARY KEY(`id`),
  CONSTRAINT `electronic_invoices_restaurant_number_uidx` UNIQUE(`restaurantId`,`invoiceNumber`),
  CONSTRAINT `electronic_invoices_order_uidx` UNIQUE(`orderId`),
  INDEX `electronic_invoices_customer_issued_idx` (`customerId`,`issuedAt`),
  CONSTRAINT `electronicInvoices_restaurantId_restaurants_id_fk` FOREIGN KEY (`restaurantId`) REFERENCES `restaurants`(`id`),
  CONSTRAINT `electronicInvoices_orderId_orders_id_fk` FOREIGN KEY (`orderId`) REFERENCES `orders`(`id`),
  CONSTRAINT `electronicInvoices_customerId_users_id_fk` FOREIGN KEY (`customerId`) REFERENCES `users`(`id`),
  CONSTRAINT `electronicInvoices_createdByUserId_users_id_fk` FOREIGN KEY (`createdByUserId`) REFERENCES `users`(`id`)
);
