import { Link } from "wouter";
import { Camera, ShieldCheck, Store, UserPlus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";

const labels: Record<string, string> = { burger: "برجر", desserts: "حلويات", coffee: "قهوة", meals: "وجبات", drinks: "مشروبات", other_food: "أطعمة ومشروبات" };

export default function ContentMarketplace() {
  const market = trpc.platform.publicContentMarket.useQuery(undefined, { retry: false });
  return <main dir="rtl" className="min-h-screen bg-[#0b0f17] px-4 py-6 text-white sm:px-8">
    <div className="mx-auto max-w-7xl">
      <header className="flex flex-wrap items-center justify-between gap-4 border-b border-white/10 pb-6">
        <div><p className="text-xs font-black tracking-[.18em] text-orange-400">NFOOD · CREATOR MARKET</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">سوق نفود للمحتوى</h1><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-300">سوق عام لصور الأكل والمشروبات الحديثة، بعد مراجعة المصدر والسلامة. لا نعرض اسم مطعم محدد ولا هوية صانع المحتوى.</p></div>
        <div className="flex gap-2"><Link href="/customer-register"><Button className="rounded-xl bg-orange-500 text-white hover:bg-orange-400"><UserPlus className="ms-2 h-4 w-4" />سجّل كصانع محتوى</Button></Link><Link href="/customer-studio"><Button variant="outline" className="rounded-xl border-white/20 bg-white/5 text-white hover:bg-white/10"><Camera className="ms-2 h-4 w-4" />استوديو التصوير</Button></Link></div>
      </header>
      <section className="grid gap-3 py-6 md:grid-cols-3"><Card className="border-white/10 bg-white/5 text-white"><CardContent className="p-4"><ShieldCheck className="h-6 w-6 text-emerald-400" /><p className="mt-3 font-black">صور حديثة فقط</p><p className="mt-1 text-xs leading-6 text-slate-300">يلزم التقاط الصورة من كاميرا Studio، مع تحقق من وقت الالتقاط وبيانات الجهاز المتاحة.</p></CardContent></Card><Card className="border-white/10 bg-white/5 text-white"><CardContent className="p-4"><Store className="h-6 w-6 text-orange-400" /><p className="mt-3 font-black">يوجد مطاعم نشطة</p><p className="mt-1 text-xs leading-6 text-slate-300">تظهر الصور للمطاعم المؤهلة دون كشف قائمة المطاعم أو ربط العرض بمطعم واحد.</p></CardContent></Card><Card className="border-white/10 bg-white/5 text-white"><CardContent className="p-4"><Camera className="h-6 w-6 text-sky-400" /><p className="mt-3 font-black">طعام وشراب فقط</p><p className="mt-1 text-xs leading-6 text-slate-300">المقاطع ممنوعة، والمحتوى غير الغذائي أو غير الآمن أو المعدل يُرفض.</p></CardContent></Card></section>
      <section><div className="mb-4 flex items-end justify-between"><div><h2 className="text-xl font-black">المحتوى المعتمد</h2><p className="mt-1 text-xs text-slate-400">معاينات مائية فقط حتى اعتماد عملية الشراء وحقوق صانع المحتوى.</p></div><span className="rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-bold text-emerald-300">مراجعة قبل النشر</span></div>{market.isLoading ? <p className="py-16 text-center text-sm text-slate-400">جارٍ تحميل السوق...</p> : market.isError ? <p className="py-16 text-center text-sm text-rose-300">تعذر تحميل السوق حاليًا.</p> : (market.data ?? []).length === 0 ? <div className="rounded-3xl border border-dashed border-white/15 p-16 text-center text-sm text-slate-400">لا توجد صور معتمدة منشورة بعد. سجّل الآن وابدأ من كاميرا Studio.</div> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{market.data?.map((item) => <Card key={item.id} className="overflow-hidden border-white/10 bg-white/5 text-white"><div className="relative aspect-[4/3] bg-slate-900"><img src={item.publicUrl} alt={item.title} className="h-full w-full object-cover opacity-80" /><span className="pointer-events-none absolute inset-0 grid place-items-center text-sm font-black text-white/70">NFOOD · معاينة مائية</span></div><CardHeader className="pb-2"><CardTitle className="text-base">{item.title}</CardTitle><p className="text-xs text-slate-400">{labels[item.contentCategory] ?? "أطعمة ومشروبات"}</p></CardHeader><CardContent className="flex items-center justify-between pt-0"><span className="font-black text-orange-300">{item.price} {item.currencyCode}</span><span className="text-[10px] text-slate-400">صورة حديثة موثقة</span></CardContent></Card>)}</div>}</section>
      <footer className="mt-10 rounded-3xl border border-orange-400/20 bg-orange-400/5 p-5 text-sm leading-7 text-slate-300"><p className="font-black text-orange-300">شروط سوق نفود لصناع المحتوى</p><p className="mt-2">يُسمح ببيع صور الأطعمة والمشروبات فقط. يجب التقاط الصورة مباشرة من كاميرا Studio وقت الرفع، ولا تُقبل الصور القديمة أو الفيديوهات أو صور الأشخاص أو المحتوى غير الأخلاقي أو المعدل بما يضلل المشتري. تُراجع كل صورة قبل ظهورها العام، وقد يُطلب إذن الموقع للتحقق من السياق. لا تُسلّم النسخة الأصلية إلا بعد اعتماد الشراء وحفظ حق صانع المحتوى.</p></footer>
    </div>
  </main>;
}
