import { useMemo } from "react";
import { Link, useParams } from "wouter";
import Barcode from "react-barcode";
import { BriefcaseBusiness, Copy, CreditCard, ExternalLink, Globe2, Mail, MapPin, MessageCircle, Phone, Share2, ShoppingBag } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { useLanguage } from "@/contexts/LanguageContext";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

function safeExternal(url?: string | null) { return url && /^https?:\/\//i.test(url) ? url : undefined; }
const profileCopy = {
  ar: { unavailable: "الملف العام غير متاح", unavailableHint: "قد يكون الرابط غير صحيح أو أن صاحب الملف عطّل المشاركة.", back: "العودة", defaultProfile: "ملف عميل", share: "مشاركة الملف", email: "البريد", links: "روابط التواصل", services: "الخدمات", products: "المنتجات والوصفات", paymentMethods: "طرق الدفع", visit: "زيارة الخدمة", digitalCard: "بطاقة التواصل الرقمية", copy: "نسخ الرابط", copied: "تم نسخ الرابط", welcome: "مرحبًا بك في صفحتي العامة." },
  en: { unavailable: "Public profile unavailable", unavailableHint: "The link may be incorrect or the owner may have disabled sharing.", back: "Back", defaultProfile: "Customer profile", share: "Share profile", email: "Email", links: "Contact links", services: "Services", products: "Products & recipes", paymentMethods: "Payment methods", visit: "Visit service", digitalCard: "Digital contact card", copy: "Copy link", copied: "Link copied", welcome: "Welcome to my public profile." },
  fr: { unavailable: "Profil public indisponible", unavailableHint: "Le lien est peut-être incorrect ou le propriétaire a désactivé le partage.", back: "Retour", defaultProfile: "Profil client", share: "Partager le profil", email: "E-mail", links: "Liens de contact", services: "Services", products: "Produits et recettes", paymentMethods: "Modes de paiement", visit: "Visiter le service", digitalCard: "Carte de contact numérique", copy: "Copier le lien", copied: "Lien copié", welcome: "Bienvenue sur mon profil public." },
  ur: { unavailable: "عوامی پروفائل دستیاب نہیں", unavailableHint: "لنک غلط ہو سکتا ہے یا مالک نے شیئرنگ بند کر دی ہے۔", back: "واپس", defaultProfile: "کسٹمر پروفائل", share: "پروفائل شیئر کریں", email: "ای میل", links: "رابطے کے لنکس", services: "خدمات", products: "مصنوعات اور ترکیبیں", paymentMethods: "ادائیگی کے طریقے", visit: "خدمت دیکھیں", digitalCard: "ڈیجیٹل رابطہ کارڈ", copy: "لنک کاپی کریں", copied: "لنک کاپی ہو گیا", welcome: "میرے عوامی پروفائل میں خوش آمدید۔" },
} as const;

type Product = { name: string; description?: string; imageUrl?: string; price?: string; currency?: string; type?: string };
type PaymentMethod = { name: string; label?: string; imageUrl?: string; instructions?: string; enabled?: boolean };

export default function CustomerPublic() {
  const { slug = "" } = useParams<{ slug: string }>();
  const { direction, language } = useLanguage();
  const copy = profileCopy[language as keyof typeof profileCopy] ?? profileCopy.en;
  const profile = trpc.platform.publicCustomerProfile.useQuery({ slug }, { enabled: Boolean(slug), retry: false });
  const data = profile.data;
  const publicUrl = useMemo(() => window.location.href, [slug]);
  const shareWhatsApp = () => { window.open(`https://wa.me/?text=${encodeURIComponent(`${data?.displayName ?? "الملف العام"} ${publicUrl}`)}`, "_blank", "noopener,noreferrer"); };
  const share = async () => { if (navigator.share) await navigator.share({ title: data?.displayName ?? "الملف العام", text: data?.bio ?? "", url: publicUrl }); else { await navigator.clipboard.writeText(publicUrl); toast.success(copy.copied); } };

  if (profile.isLoading) return <div className="min-h-screen bg-[#f7f8fb] p-6"><div className="mx-auto max-w-3xl animate-pulse rounded-[2rem] bg-white p-8 shadow-sm"><div className="h-44 rounded-3xl bg-slate-100" /><div className="mx-auto mt-[-3rem] h-24 w-24 rounded-full bg-slate-200" /><div className="mx-auto mt-5 h-6 w-48 rounded bg-slate-100" /></div></div>;
  if (profile.isError || !data) return <div className="flex min-h-screen items-center justify-center bg-[#f7f8fb] p-6"><Card className="max-w-md rounded-3xl"><CardContent className="p-8 text-center"><h1 className="text-xl font-black">{copy.unavailable}</h1><p className="mt-2 text-sm text-slate-500">{copy.unavailableHint}</p><Link href="/"><Button className="mt-6 rounded-xl bg-[#e76f3c]">{copy.back}</Button></Link></CardContent></Card></div>;

  const links = [["Instagram", safeExternal(data.instagramUrl), "#e1306c"], ["Twitter / X", safeExternal(data.twitterUrl), "#111827"], ["Facebook", safeExternal(data.facebookUrl), "#2563eb"], ["LinkedIn", safeExternal(data.linkedinUrl), "#0a66c2"]].filter(([, url]) => url) as Array<[string, string, string]>;
  const products = (data.products ?? []) as Product[];
  const paymentMethods = (data.paymentMethods ?? []) as PaymentMethod[];
  const visiblePaymentMethods = paymentMethods.filter((method) => method.enabled !== false);

  return <main dir={direction} className="min-h-screen bg-[#f7f8fb] px-4 py-6 text-slate-900 sm:px-6"><div className="mx-auto max-w-4xl"><div className="overflow-hidden rounded-[2rem] border border-white bg-white shadow-[0_24px_80px_rgba(15,23,42,.10)]">
    <div className="relative h-48 overflow-hidden bg-gradient-to-br from-[#101d31] via-[#243a58] to-[#e76f3c] sm:h-64">{data.coverUrl && <img src={data.coverUrl} alt="" className="h-full w-full object-cover opacity-80" />}<div className="absolute inset-0 bg-gradient-to-t from-black/50 to-transparent" /></div>
    <div className="relative px-5 pb-8 sm:px-10"><div className="-mt-14 flex flex-col items-center gap-5 sm:-mt-16 sm:flex-row sm:items-end"><div className="flex h-28 w-28 items-center justify-center overflow-hidden rounded-full border-8 border-white bg-orange-100 text-3xl font-black text-[#e76f3c] shadow-lg">{data.avatarUrl ? <img src={data.avatarUrl} alt={data.displayName ?? ""} className="h-full w-full object-cover" /> : (data.displayName ?? "N").slice(0, 1)}</div><div className="flex-1 text-center sm:pb-2 sm:text-right"><h1 className="text-2xl font-black sm:text-3xl">{data.displayName ?? copy.defaultProfile}</h1>{data.title && <p className="mt-1 flex items-center justify-center gap-2 text-sm font-semibold text-[#e76f3c] sm:justify-start"><BriefcaseBusiness className="h-4 w-4" />{data.title}</p>}</div><div className="flex gap-2"><Button onClick={() => void share()} className="rounded-xl bg-[#e76f3c] shadow-lg shadow-orange-100"><Share2 className="ml-2 h-4 w-4" />{copy.share}</Button><Button onClick={shareWhatsApp} variant="outline" className="rounded-xl border-emerald-200 text-emerald-700">WhatsApp</Button></div></div>
      <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_240px]"><div><p className="max-w-2xl whitespace-pre-wrap text-sm leading-8 text-slate-600">{data.bio || copy.welcome}</p><div className="mt-6 flex flex-wrap gap-2">{data.phone && <a href={`tel:${data.phone}`} className="inline-flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-2 text-xs font-bold"><Phone className="h-4 w-4 text-[#e76f3c]" />{data.phone}</a>}{data.whatsapp && <a href={`https://wa.me/${data.whatsapp.replace(/\D/g, "")}`} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700"><MessageCircle className="h-4 w-4" />WhatsApp</a>}{data.email && <a href={`mailto:${data.email}`} className="inline-flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-2 text-xs font-bold"><Mail className="h-4 w-4 text-[#e76f3c]" />{copy.email}</a>}{data.websiteUrl && <a href={safeExternal(data.websiteUrl)} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-2 text-xs font-bold"><Globe2 className="h-4 w-4 text-[#e76f3c]" />الموقع</a>}{(data.city || data.address) && <span className="inline-flex items-center gap-2 rounded-xl bg-slate-50 px-3 py-2 text-xs font-bold"><MapPin className="h-4 w-4 text-[#e76f3c]" />{[data.city, data.address].filter(Boolean).join(" · ")}</span>}</div>
        {links.length > 0 && <section className="mt-8"><h2 className="text-sm font-black">{copy.links}</h2><div className="mt-3 flex flex-wrap gap-2">{links.map(([label, url, color]) => <a key={label} href={url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2 text-xs font-bold" style={{ color }}><ExternalLink className="h-4 w-4" />{label}</a>)}</div></section>}
        {products.length > 0 && <section className="mt-8"><h2 className="flex items-center gap-2 text-sm font-black"><ShoppingBag className="h-4 w-4 text-[#e76f3c]" />{copy.products}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{products.map((product) => <Card key={`${product.type ?? "product"}-${product.name}`} className="overflow-hidden rounded-2xl border-slate-100 shadow-none">{product.imageUrl && <img src={product.imageUrl} alt={product.name} className="h-36 w-full object-cover" />}<CardContent className="p-4"><div className="flex items-start justify-between gap-3"><h3 className="font-bold">{product.name}</h3>{product.price && <span className="shrink-0 rounded-full bg-orange-50 px-2 py-1 text-xs font-black text-[#e76f3c]">{product.price} {product.currency ?? "SAR"}</span>}</div>{product.type && <p className="mt-1 text-[11px] font-bold text-[#e76f3c]">{product.type}</p>}{product.description && <p className="mt-1 text-xs leading-6 text-slate-500">{product.description}</p>}</CardContent></Card>)}</div></section>}
        {visiblePaymentMethods.length > 0 && <section className="mt-8"><h2 className="flex items-center gap-2 text-sm font-black"><CreditCard className="h-4 w-4 text-[#e76f3c]" />{copy.paymentMethods}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{visiblePaymentMethods.map((method) => <Card key={method.name} className="rounded-2xl border-slate-100 shadow-none"><CardContent className="flex items-center gap-3 p-4">{method.imageUrl && <img src={method.imageUrl} alt="" className="h-10 w-10 rounded-xl object-cover" />}<div><h3 className="font-bold">{method.label ?? method.name}</h3>{method.instructions && <p className="mt-1 text-xs leading-5 text-slate-500">{method.instructions}</p>}</div></CardContent></Card>)}</div></section>}
        {data.services.length > 0 && <section className="mt-8"><h2 className="text-sm font-black">{copy.services}</h2><div className="mt-3 grid gap-3 sm:grid-cols-2">{data.services.map((service) => <Card key={service.name} className="rounded-2xl border-slate-100 shadow-none"><CardContent className="p-4"><h3 className="font-bold">{service.name}</h3>{service.description && <p className="mt-1 text-xs leading-6 text-slate-500">{service.description}</p>}{service.url && <a href={safeExternal(service.url)} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-[#e76f3c]">{copy.visit} <ExternalLink className="h-3 w-3" /></a>}</CardContent></Card>)}</div></section>}</div>
        <aside className="rounded-3xl bg-slate-50 p-4 text-center"><p className="text-xs font-bold text-slate-500">{copy.digitalCard}</p><div className="mt-4 overflow-hidden rounded-xl bg-white p-2"><Barcode value={publicUrl} width={1.3} height={54} displayValue={false} margin={4} /></div><button onClick={() => { void navigator.clipboard.writeText(publicUrl); toast.success(copy.copied); }} className="mt-3 inline-flex items-center gap-2 text-xs font-bold text-[#e76f3c]"><Copy className="h-4 w-4" />{copy.copy}</button><p className="mt-4 break-all font-mono text-[10px] text-slate-400" dir="ltr">{publicUrl}</p></aside></div>
    </div></div><div className="mt-5 text-center text-xs text-slate-400"><Link href="/">NFOOD</Link> · {language === "ar" ? "صفحة عامة قابلة للمشاركة" : language === "fr" ? "Profil public partageable" : language === "ur" ? "شیئر کرنے کے قابل عوامی پروفائل" : "Shareable public profile"}</div></div></main>;
}
