import { Link } from "wouter";
import { ArrowDownToLine, Library, LockKeyhole, Store } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";

export default function CustomerContentLibrary() {
  const { user } = useAuth();
  const library = trpc.platform.myContentLibrary.useQuery(undefined, { enabled: Boolean(user), retry: false });
  if (!user) return <main dir="rtl" className="grid min-h-screen place-items-center bg-[#f7f8fb] p-5"><Card className="w-full max-w-md rounded-3xl"><CardContent className="p-8 text-center"><LockKeyhole className="mx-auto h-10 w-10 text-[#e76f3c]" /><h1 className="mt-4 text-2xl font-black text-slate-900">مكتبة مشتريات المحتوى</h1><p className="mt-2 text-sm leading-7 text-slate-500">سجّل الدخول للوصول إلى الملفات التي اشتريتها رقميًا.</p><Button type="button" onClick={() => startLogin()} className="mt-5 rounded-xl bg-[#e76f3c]">تسجيل الدخول</Button></CardContent></Card></main>;
  return <main dir="rtl" className="min-h-screen bg-[#f7f8fb] p-5 text-slate-900 sm:p-8"><div className="mx-auto max-w-6xl"><header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-black text-[#e76f3c]"><Library className="h-4 w-4" /> ملفات NFOOD</p><h1 className="mt-2 text-3xl font-black">مكتبة مشتريات المحتوى</h1><p className="mt-2 text-sm leading-7 text-slate-500">تصل الملفات هنا تلقائيًا بعد إتمام الدفع التجاري، دون توصيل أو انتظار شحن.</p></div><div className="flex flex-wrap gap-2"><Link href="/content-market"><Button variant="outline" className="rounded-xl">العودة إلى Trend Kitchen</Button></Link><Link href="/customer-portal"><Button className="rounded-xl bg-[#e76f3c]">بوابة العميل</Button></Link></div></header>{library.isLoading ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[1, 2, 3, 4].map((item) => <div key={item} className="h-64 animate-pulse rounded-3xl bg-white" />)}</div> : library.isError ? <Card className="rounded-3xl border-red-100 bg-red-50"><CardContent className="p-7 text-center text-sm font-bold text-red-700">تعذر تحميل المكتبة حاليًا. حاول تحديث الصفحة.</CardContent></Card> : library.data?.length ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{library.data.map((entry) => <Card key={entry.entitlement.id} className="overflow-hidden rounded-3xl border-slate-200 bg-white shadow-sm"><div className="aspect-[4/3] overflow-hidden bg-slate-100"><img src={entry.media.publicUrl} alt={entry.listing.title} className="h-full w-full object-cover" loading="lazy" /></div><CardContent className="space-y-3 p-4"><div><h2 className="line-clamp-1 font-black">{entry.listing.title}</h2><p className="mt-1 text-xs text-slate-500">تمت الإضافة {new Date(entry.entitlement.deliveredAt).toLocaleDateString("ar-SA-u-ca-gregory-nu-latn")}</p></div><div className="flex items-center justify-between rounded-xl bg-emerald-50 px-3 py-2 text-xs"><span className="flex items-center gap-1 font-bold text-emerald-800"><Store className="h-3.5 w-3.5" />ملف مشتَرى</span><strong className="text-emerald-900">{entry.order.total} {entry.order.currencyCode}</strong></div><a href={entry.media.publicUrl} target="_blank" rel="noreferrer" download className="flex items-center justify-center gap-2 rounded-xl bg-[#e76f3c] px-3 py-2.5 text-xs font-black text-white transition hover:bg-[#d85e31]"><ArrowDownToLine className="h-4 w-4" />فتح الملف الأصلي</a></CardContent></Card>)}</div> : <Card className="rounded-3xl border-dashed border-slate-300 bg-white"><CardContent className="p-12 text-center"><Library className="mx-auto h-10 w-10 text-slate-300" /><h2 className="mt-4 text-xl font-black">المكتبة جاهزة</h2><p className="mt-2 text-sm leading-7 text-slate-500">بعد شراء المحتوى من حساب مطعم أو تاجر، سيظهر الملف هنا تلقائيًا.</p><Link href="/content-market"><Button className="mt-5 rounded-xl bg-[#e76f3c]">استكشاف Trend Kitchen</Button></Link></CardContent></Card>}</div></main>;
}
