import { useMemo, useState } from "react";
import { Link } from "wouter";
import { MapPin, Search, ShoppingBag, Store, CalendarDays } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";

export default function CustomerPortal() {
  const [query, setQuery] = useState("");
  const restaurants = trpc.platform.publicRestaurantDirectory.useQuery();
  const rows = useMemo(() => (restaurants.data ?? []).filter((restaurant) => `${restaurant.brandName ?? restaurant.name} ${restaurant.city ?? ""} ${restaurant.address ?? ""}`.toLowerCase().includes(query.toLowerCase())), [restaurants.data, query]);
  return <main dir="rtl" className="min-h-screen bg-[#f7f8fb] p-5 text-slate-900 sm:p-8"><div className="mx-auto max-w-6xl"><header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold text-[#e76f3c]">NFOOD · بوابة العميل</p><h1 className="mt-2 text-3xl font-black">اكتشف مطاعمك واطلب بسهولة</h1><p className="mt-2 text-sm text-slate-500">تصفح المنيو، أضف للسلة، أرسل الطلب أو احجز من صفحة المطعم العامة.</p></div><div className="flex gap-2"><Link href="/customer-profile"><Button variant="outline" className="rounded-xl">ملفي العام</Button></Link><Link href="/"><Button className="rounded-xl bg-[#e76f3c]">لوحتي</Button></Link></div></header><div className="mb-6 flex items-center gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm"><Search className="h-5 w-5 text-slate-400" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="ابحث باسم المطعم أو المدينة" className="h-8 border-0 p-0 shadow-none focus-visible:ring-0" /></div>{restaurants.isLoading ? <div className="grid gap-4 md:grid-cols-3">{[1,2,3].map((item) => <div key={item} className="h-56 animate-pulse rounded-3xl bg-white" />)}</div> : restaurants.isError ? <Card className="rounded-3xl"><CardContent className="p-8 text-center text-sm text-red-600">تعذر تحميل دليل المطاعم. Request ID: customer-directory</CardContent></Card> : rows.length === 0 ? <Card className="rounded-3xl"><CardContent className="p-12 text-center"><Store className="mx-auto h-10 w-10 text-slate-300" /><p className="mt-3 text-sm text-slate-500">لا توجد مطاعم مطابقة حاليًا.</p></CardContent></Card> : <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{rows.map((restaurant) => <Card key={restaurant.id} className="overflow-hidden rounded-3xl border-slate-200 bg-white shadow-sm"><div className="h-28" style={{ background: `linear-gradient(135deg, ${restaurant.brandColor ?? "#e76f3c"}, #101d31)` }}>{restaurant.brandLogoUrl && <img src={restaurant.brandLogoUrl} alt="" className="h-full w-full object-contain p-6" />}</div><CardContent className="p-5"><h2 className="text-lg font-black">{restaurant.brandName ?? restaurant.name}</h2><p className="mt-2 line-clamp-2 text-xs leading-6 text-slate-500">{restaurant.brandDescription || "صفحة مطعم عامة تشمل المنيو والطلب والحجز."}</p>{(restaurant.city || restaurant.address) && <p className="mt-3 flex items-center gap-1 text-xs text-slate-500"><MapPin className="h-4 w-4 text-[#e76f3c]" />{[restaurant.city, restaurant.address].filter(Boolean).join(" · ")}</p>}<div className="mt-5 grid grid-cols-2 gap-2"><Link href={`/restaurant/${restaurant.slug}`}><Button className="w-full rounded-xl bg-[#e76f3c]"><ShoppingBag className="ml-1 h-4 w-4" />المنيو والطلب</Button></Link><Link href={`/restaurant/${restaurant.slug}#reservation`}><Button variant="outline" className="w-full rounded-xl"><CalendarDays className="ml-1 h-4 w-4" />الحجز</Button></Link></div></CardContent></Card>)}</div>}</div></main>;
}
