import { Check, Eye, EyeOff, LockKeyhole, Mail, ShieldCheck } from "lucide-react";
import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { useLanguage } from "@/contexts/LanguageContext";
import LanguageSwitcher from "@/components/LanguageSwitcher";

const loginCopy = {
  ar: { checking:"جارٍ التحقق من الحساب...", toastSignedIn:"تم تسجيل الدخول بنجاح", toastInvalid:"بيانات الدخول غير صحيحة", eyebrow:"مساحتك التشغيلية تبدأ من هنا", heroTitle:"أدر نشاطك", heroTitleAccent:"بثقة أكبر.", heroDesc:"وصول آمن إلى متجرك أو مطعمك أو نشاطك، مع الإدارة والطلبات والعملاء والفروع والتقارير في مساحة واحدة.", feat1:"مساحة عمل موحدة لكل أنواع الأنشطة والفرق", feat2:"بياناتك محمية بصلاحيات واضحة", feat3:"متابعة مباشرة من أي جهاز", badge:"محمي بواسطة NFOOD 2026", backHome:"العودة إلى الصفحة الرئيسية", welcomeBack:"مرحبًا بعودتك", signIn:"تسجيل الدخول", signInDesc:"سجل الدخول للوصول إلى مساحة عملك المتكاملة.", email:"البريد الإلكتروني", password:"كلمة المرور", passwordPlaceholder:"اكتب كلمة المرور", showPassword:"إظهار كلمة المرور", remember:"تذكرني", forgot:"نسيت كلمة المرور؟", forgotToast:"أدخل بريدك وسنرسل لك رابط الاستعادة.", resetSent:"إذا كان البريد مسجلًا فسيصلك رابط الاستعادة.", resetTitle:"استعادة كلمة المرور", resetPassword:"كلمة المرور الجديدة", resetConfirm:"تأكيد كلمة المرور", resetAction:"تحديث كلمة المرور", resetDone:"تم تحديث كلمة المرور. يمكنك تسجيل الدخول الآن.", signingIn:"جارٍ تسجيل الدخول...", or:"أو", oauth:"المتابعة باستخدام Google", createAccount:"إنشاء حساب جديد", legal:"من خلال تسجيلك أنت توافق على شروط استخدام NFOOD وسياسة الخصوصية." },
  en: { checking:"Checking your account...", toastSignedIn:"Signed in successfully", toastInvalid:"Invalid sign-in credentials", eyebrow:"Your operations workspace starts here", heroTitle:"Run your business", heroTitleAccent:"with more confidence.", heroDesc:"Secure access to your store, restaurant, or business with operations, orders, customers, branches, and reports in one workspace.", feat1:"One workspace for every business type and team", feat2:"Your data protected by clear permissions", feat3:"Live follow-up from any device", badge:"Protected by NFOOD 2026", backHome:"Back to home", welcomeBack:"Welcome back", signIn:"Sign in", signInDesc:"Sign in to access your complete business workspace.", email:"Email", password:"Password", passwordPlaceholder:"Enter your password", showPassword:"Show password", remember:"Remember me", forgot:"Forgot password?", forgotToast:"Enter your email and we will send a recovery link.", resetSent:"If the email is registered, a recovery link will be sent.", resetTitle:"Reset password", resetPassword:"New password", resetConfirm:"Confirm password", resetAction:"Update password", resetDone:"Password updated. You can sign in now.", signingIn:"Signing in...", or:"or", oauth:"Sign in with Google", createAccount:"Create an account", legal:"By signing in you agree to NFOOD's Terms of Use and Privacy Policy." },
  fr: { checking:"Vérification de votre compte...", toastSignedIn:"Connexion réussie", toastInvalid:"Identifiants de connexion invalides", eyebrow:"Votre espace de travail commence ici", heroTitle:"Gérez votre activité", heroTitleAccent:"avec plus de confiance.", heroDesc:"Accès sécurisé à votre boutique, restaurant ou activité avec opérations, commandes, clients, sites et rapports dans un seul espace.", feat1:"Un espace unifié pour tous les types d’activité et équipes", feat2:"Vos données protégées par des permissions claires", feat3:"Suivi en direct depuis n'importe quel appareil", badge:"Protégé par NFOOD 2026", backHome:"Retour à l'accueil", welcomeBack:"Bon retour", signIn:"Se connecter", signInDesc:"Connectez-vous pour accéder à votre espace de travail complet.", email:"E-mail", password:"Mot de passe", passwordPlaceholder:"Saisissez votre mot de passe", showPassword:"Afficher le mot de passe", remember:"Se souvenir de moi", forgot:"Mot de passe oublié ?", forgotToast:"Saisissez votre e-mail et nous enverrons un lien de récupération.", resetSent:"Si l’e-mail est enregistré, un lien de récupération sera envoyé.", resetTitle:"Réinitialiser le mot de passe", resetPassword:"Nouveau mot de passe", resetConfirm:"Confirmer le mot de passe", resetAction:"Mettre à jour", resetDone:"Mot de passe mis à jour. Vous pouvez vous connecter.", signingIn:"Connexion en cours...", or:"ou", oauth:"Se connecter avec Google", createAccount:"Créer un compte", legal:"En vous connectant, vous acceptez les Conditions d'utilisation et la Politique de confidentialité de NFOOD." },
} as const;

export default function LoginPage() {
  const { language, direction } = useLanguage();
  const copy = language === "fr" ? loginCopy.fr : language === "en" ? loginCopy.en : loginCopy.ar;
  const { user, loading } = useAuth();
  const [, setLocation] = useLocation();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [resetMode, setResetMode] = useState(() => new URLSearchParams(window.location.search).has("reset"));
  const [resetPassword, setResetPassword] = useState("");
  const [resetConfirm, setResetConfirm] = useState("");
  const requestReset = trpc.auth.requestPasswordReset.useMutation({ onSuccess: () => toast.success(copy.resetSent), onError: (error) => toast.error(error.message) });
  const completeReset = trpc.auth.resetPassword.useMutation({ onSuccess: () => { toast.success(copy.resetDone); setResetMode(false); window.history.replaceState({}, "", "/login"); }, onError: (error) => toast.error(error.message) });
  const login = trpc.auth.testLogin.useMutation({ onSuccess: (result) => { toast.success(copy.toastSignedIn); const next = new URLSearchParams(window.location.search).get("next"); const safeNext = next?.startsWith("/") && !next.startsWith("//") ? next : result.role === "admin" ? "/admin" : "/"; setLocation(safeNext); }, onError: (error) => toast.error(error.message || copy.toastInvalid) });
  const features = [copy.feat1, copy.feat2, copy.feat3];
  useEffect(() => { if (!loading && user) setLocation(user.role === "admin" || user.testRole === "admin" ? "/admin" : "/"); }, [loading, user, setLocation]);

  if (loading || user) return <div className="flex min-h-screen items-center justify-center bg-[#071525] text-white">{copy.checking}</div>;
  return <div dir={direction} className="min-h-dvh bg-[#071525] text-white"><div className="grid min-h-dvh lg:grid-cols-[1.05fr_.95fr]">
    <section className="relative hidden overflow-hidden bg-[#0b1d35] p-12 lg:flex lg:flex-col lg:justify-between xl:p-16"><div className="absolute -left-32 -top-32 h-96 w-96 rounded-full bg-orange-500/15 blur-3xl"/><div className="relative"><button onClick={()=>setLocation("/")} className="flex items-center gap-3 text-right"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-orange-500 text-xl font-black">N</span><strong>NFOOD</strong></button><div className="mt-28 max-w-lg"><p className="text-sm font-bold text-orange-300">{copy.eyebrow}</p><h1 className="mt-4 text-5xl font-black leading-[1.25]">{copy.heroTitle}<br/><span className="text-orange-400">{copy.heroTitleAccent}</span></h1><p className="mt-6 text-base leading-8 text-slate-300">{copy.heroDesc}</p><div className="mt-10 space-y-4 text-sm text-slate-300">{features.map(item=><p key={item} className="flex items-center gap-3"><Check className="h-4 w-4 text-teal-300"/>{item}</p>)}</div></div></div><div className="relative flex items-center gap-3 text-xs text-slate-500"><ShieldCheck className="h-4 w-4 text-teal-400"/>{copy.badge}</div></section>
    <section className="flex min-h-dvh items-start justify-center overflow-y-auto bg-[#f8fafc] px-4 py-6 text-slate-900 sm:items-center sm:px-8 sm:py-10"><div className="w-full max-w-md"><div className="mb-8 flex items-center justify-between"><button type="button" onClick={()=>setLocation("/")} className="text-xs font-bold text-slate-500 hover:text-orange-600">{copy.backHome}</button><LanguageSwitcher compact/></div><div className="mb-8"><p className="text-sm font-bold text-orange-500">{copy.welcomeBack}</p><h2 className="mt-2 text-3xl font-black">{copy.signIn}</h2><p className="mt-3 text-sm leading-7 text-slate-500">{copy.signInDesc}</p></div>
    {resetMode ? <form onSubmit={e=>{e.preventDefault();const token=new URLSearchParams(window.location.search).get("reset");if(!token)return;if(resetPassword!==resetConfirm){toast.error(language==="ar"?"كلمتا المرور غير متطابقتين":"Passwords do not match");return;}completeReset.mutate({token,password:resetPassword});}} className="space-y-5"><h3 className="text-lg font-black">{copy.resetTitle}</h3><input type="password" minLength={8} required value={resetPassword} onChange={e=>setResetPassword(e.target.value)} placeholder={copy.resetPassword} className="h-12 w-full rounded-xl border bg-white px-4"/><input type="password" minLength={8} required value={resetConfirm} onChange={e=>setResetConfirm(e.target.value)} placeholder={copy.resetConfirm} className="h-12 w-full rounded-xl border bg-white px-4"/><button className="h-12 w-full rounded-xl bg-orange-500 font-black text-white">{copy.resetAction}</button></form> : <form onSubmit={e=>{e.preventDefault();if(email&&password)login.mutate({email,password});}} className="space-y-5"><label className="block"><span className="mb-2 block text-xs font-bold">{copy.email}</span><div className="relative"><Mail className="absolute right-3 top-3.5 h-4 w-4 text-slate-400"/><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} className="h-12 w-full rounded-xl border bg-white pr-10 pl-4" dir="ltr"/></div></label><label className="block"><span className="mb-2 block text-xs font-bold">{copy.password}</span><div className="relative"><LockKeyhole className="absolute right-3 top-3.5 h-4 w-4 text-slate-400"/><input type={showPassword?"text":"password"} required value={password} onChange={e=>setPassword(e.target.value)} className="h-12 w-full rounded-xl border bg-white pr-10 pl-11" dir="ltr"/><button type="button" aria-label={copy.showPassword} onClick={()=>setShowPassword(v=>!v)} className="absolute left-3 top-3.5 text-slate-400">{showPassword?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></label><div className="flex items-center justify-between text-xs"><button type="button" onClick={()=>email?requestReset.mutate({email}):toast.info(copy.forgotToast)} className="font-bold text-orange-600">{copy.forgot}</button></div><button type="submit" disabled={login.isPending} className="h-12 w-full rounded-xl bg-orange-500 font-black text-white disabled:opacity-60">{login.isPending?copy.signingIn:copy.signIn}</button></form>}
    </div></section></div></div>;
}
