import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { marketplaceCopy, marketplaceCountries, sectorMeta } from "@/lib/marketplaceExperience";
import { useLanguage } from "@/contexts/LanguageContext";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import { Globe2, Search, Store, MapPin, Moon, Sun, Heart, ShieldCheck, Truck, Headphones, CreditCard, ArrowLeft } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";

const fallbackHero="https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1800&q=85";

export default function MarketplaceLanding(){
 const {language,direction}=useLanguage(); const lang=language==="fr"?"fr":language==="en"?"en":"ar"; const copy=marketplaceCopy(lang);
 const [country,setCountry]=useState(()=>localStorage.getItem("nfood-market-country")||"SA"); const [search,setSearch]=useState(""); const [theme,setTheme]=useState<"light"|"dark">(()=>localStorage.getItem("nfood-market-theme")==="light"?"light":"dark");
 const appearanceQuery=trpc.marketplace.publicAppearance.useQuery(undefined,{retry:false}); const sectors=trpc.marketplace.publicSectors.useQuery(undefined,{retry:false}); const stores=trpc.marketplace.publicStores.useQuery({countryCode:country,search:search.trim()||undefined},{retry:false});
 const appearance=(appearanceQuery.data?.appearance||{}) as Record<string,any>; const primary=appearance.primaryColor||"#f97316"; const radius=`${appearance.cardRadius||24}px`; const countryInfo=marketplaceCountries.find(x=>x.code===country)??marketplaceCountries[0]; const sectorRows=sectors.data??[]; const storeRows=stores.data??[];
 useEffect(()=>{ if(appearance.theme==="light"||appearance.theme==="dark"){setTheme(appearance.theme)} else if(!localStorage.getItem("nfood-market-theme")) setTheme(matchMedia("(prefers-color-scheme: dark)").matches?"dark":"light")},[appearance.theme]);
 const title=lang==="ar"?(appearance.heroTitleAr||"اكتشف أفضل المطاعم والمتاجر في مدينتك"):lang==="fr"?(appearance.heroTitleFr||"Découvrez les meilleurs restaurants et boutiques de votre ville"):(appearance.heroTitleEn||"Discover the best restaurants and stores in your city");
 const featured=useMemo(()=>storeRows.slice(0,4),[storeRows]); const filteredSectors=useMemo(()=>sectorRows.filter(s=>!search.trim()||`${s.labelAr} ${s.labelEn} ${s.labelFr}`.toLowerCase().includes(search.toLowerCase())),[sectorRows,search]);
 const chooseCountry=(v:string)=>{setCountry(v);localStorage.setItem("nfood-market-country",v)}; const toggleTheme=()=>{const v=theme==="dark"?"light":"dark";setTheme(v);localStorage.setItem("nfood-market-theme",v)};
 const dark=theme==="dark"; const shell=dark?"bg-[#08111d] text-white":"bg-[#f8fafc] text-[#0b1729]"; const card=dark?"border-white/10 bg-[#101b2b]":"border-slate-200 bg-white";
 return <main dir={direction} className={`min-h-screen transition-colors duration-300 ${shell}`} style={{"--market-primary":primary,"--market-radius":radius} as React.CSSProperties}>
  <header className={`sticky top-0 z-50 border-b backdrop-blur-xl ${dark?"border-white/10 bg-[#08111d]/90":"border-slate-200 bg-white/90"}`}><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 md:px-8">
   <Link href="/marketplace" className="flex items-center gap-2">{appearanceQuery.data?.siteLogoUrl?<img src={appearanceQuery.data.siteLogoUrl} className="h-10 w-10 rounded-xl object-contain"/>:<span className="grid h-10 w-10 place-items-center rounded-xl text-xl font-black text-white" style={{background:primary}}>N</span>}<span><b className="block text-lg tracking-wide">{appearanceQuery.data?.siteName||"NFOOD"}</b><small className="opacity-50">{lang==="ar"?"مطاعم • مقاهي • متاجر":"Restaurants • Cafés • Stores"}</small></span></Link>
   <nav className="hidden items-center gap-7 text-sm font-bold lg:flex"><Link href="/">{lang==="ar"?"الرئيسية":"Home"}</Link><a href="#categories">{lang==="ar"?"التصنيفات":"Categories"}</a><a href="#stores">{lang==="ar"?"المتاجر":"Stores"}</a><a href="#offers">{lang==="ar"?"العروض":"Offers"}</a></nav>
   <div className="flex items-center gap-2"><button onClick={toggleTheme} className={`grid h-10 w-10 place-items-center rounded-xl border ${dark?"border-white/10 bg-white/5":"border-slate-200 bg-white"}`} aria-label="Theme">{dark?<Sun className="h-4 w-4"/>:<Moon className="h-4 w-4"/>}</button><LanguageSwitcher compact /><Link href="/login"><Button variant="ghost">{copy.login}</Button></Link></div>
  </div></header>

  <section className="relative min-h-[500px] overflow-hidden"><img src={appearance.heroImageUrl||fallbackHero} className="absolute inset-0 h-full w-full object-cover" alt=""/><div className="absolute inset-0 bg-gradient-to-r from-black/85 via-black/65 to-black/35"/><div className="relative mx-auto flex min-h-[500px] max-w-7xl items-center px-4 py-16 md:px-8"><div className="w-full max-w-3xl text-white">
   <span className="inline-flex rounded-full border border-white/20 bg-black/30 px-4 py-2 text-xs font-bold backdrop-blur">{countryInfo.flag} {countryInfo[lang]} · NFOOD</span><h1 className="mt-5 text-4xl font-black leading-tight md:text-6xl">{title}</h1><p className="mt-4 text-base text-white/80 md:text-xl">{appearance.heroSubtitleAr||copy.subtitle}</p>
   <div className="mt-7 flex overflow-hidden rounded-2xl bg-white p-1.5 shadow-2xl"><Search className="ms-3 mt-3 h-5 w-5 text-slate-400"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder={copy.search} className="h-11 flex-1 border-0 bg-transparent text-slate-900 shadow-none focus-visible:ring-0"/><Button className="h-11 rounded-xl px-7 text-white" style={{background:primary}}>{lang==="ar"?"بحث":"Search"}</Button></div>
   <div className="mt-3 grid gap-2 sm:grid-cols-2"><select value={country} onChange={e=>chooseCountry(e.target.value)} className="h-11 rounded-xl border border-white/20 bg-black/35 px-4 text-sm font-bold text-white backdrop-blur">{marketplaceCountries.map(c=><option className="text-black" key={c.code} value={c.code}>{c.flag} {c[lang]}</option>)}</select><Link href="/store-marketing" className="grid h-11 place-items-center rounded-xl border border-white/20 bg-white/10 text-sm font-bold backdrop-blur">{copy.merchant}</Link></div>
  </div></div></section>

  {appearance.showTrustBar!==false&&<section className={`mx-auto -mt-5 relative z-10 grid max-w-6xl grid-cols-2 gap-px overflow-hidden border shadow-xl md:grid-cols-4 ${card}`} style={{borderRadius:radius}}>{[[ShieldCheck,"متاجر موثوقة","جودة وخدمة مضمونة"],[CreditCard,"دفع آمن وسهل","خيارات دفع متعددة"],[Truck,"توصيل سريع","إلى باب منزلك"],[Headphones,"دعم على مدار الساعة","نحن دائماً هنا لمساعدتك"]].map(([I,a,b])=>{const Icon=I as typeof ShieldCheck;return <div key={a as string} className="flex items-center gap-3 p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-orange-50" style={{color:primary}}><Icon className="h-5 w-5"/></span><div><b className="text-sm">{a as string}</b><p className="mt-1 text-[11px] opacity-50">{b as string}</p></div></div>})}</section>}

  <section id="categories" className="mx-auto max-w-7xl px-4 py-14 md:px-8"><div className="mb-7 flex items-end justify-between"><div><p className="text-xs font-black" style={{color:primary}}>NFOOD</p><h2 className="mt-1 text-3xl font-black">{lang==="ar"?"تصفح حسب التصنيف":copy.activity}</h2></div></div><div className="flex gap-3 overflow-x-auto pb-3">{filteredSectors.map(s=>{const m=sectorMeta(s.slug);return <Link key={s.id} href={`/marketplace/sector/${s.slug}?country=${country}`} className={`min-w-36 border p-4 text-center transition hover:-translate-y-1 ${card}`} style={{borderRadius:radius}}><span className="text-4xl">{m.icon}</span><b className="mt-3 block text-sm">{lang==="ar"?m.ar:lang==="fr"?m.fr:m.en}</b></Link>})}</div></section>

  <section id="stores" className="mx-auto max-w-7xl px-4 pb-14 md:px-8"><div className="mb-7 flex items-end justify-between"><div><h2 className="text-3xl font-black">{lang==="ar"?"متاجر مميزة لك":copy.stores}</h2><p className="mt-2 text-sm opacity-50">{lang==="ar"?"مختارة بعناية لتمنحك أفضل التجارب":"Selected stores for a better experience"}</p></div></div>
   {stores.isLoading?<div className="grid grid-cols-2 gap-4 lg:grid-cols-4">{[1,2,3,4].map(x=><div key={x} className={`h-72 animate-pulse ${card}`} style={{borderRadius:radius}}/>)}</div>:featured.length?<div className="grid grid-cols-2 gap-3 md:gap-5 lg:grid-cols-4">{featured.map(store=>{const r=store.restaurant;const cover=(r as any)?.coverUrl;const meta=sectorMeta(store.sector);return <Link key={store.entityId} href={`/store/${store.entityId}?country=${country}`} className={`group overflow-hidden border shadow-sm transition hover:-translate-y-1 hover:shadow-xl ${card}`} style={{borderRadius:radius}}><div className="relative aspect-[4/3] overflow-hidden bg-slate-200">{cover?<img src={cover} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>:<div className="grid h-full place-items-center text-6xl">{meta.icon}</div>}<button className="absolute end-3 top-3 grid h-9 w-9 place-items-center rounded-full bg-black/35 text-white backdrop-blur"><Heart className="h-4 w-4"/></button></div><div className="p-4"><h3 className="truncate font-black">{store.customerName}</h3><p className="mt-1 flex items-center gap-1 text-xs opacity-50"><MapPin className="h-3 w-3"/>{r?.city||countryInfo[lang]}</p><div className="mt-3 flex items-center justify-between"><span className="text-xs font-bold" style={{color:primary}}>{meta.icon} {lang==="ar"?meta.ar:meta.en}</span><span className="text-xs opacity-50">{store.listingCount} {lang==="ar"?"صنف":"items"}</span></div></div></Link>})}</div>:<div className={`border border-dashed p-12 text-center ${card}`} style={{borderRadius:radius}}><Store className="mx-auto h-10 w-10 opacity-30"/><p className="mt-3 font-bold">{lang==="ar"?"نعمل على إضافة متاجر مميزة في هذه الدولة":"Great stores are coming to this country"}</p></div>}
  </section>

  {appearance.showPromo!==false&&<section id="offers" className="mx-auto max-w-7xl px-4 pb-14 md:px-8"><div className="relative overflow-hidden bg-gradient-to-r from-violet-900 via-fuchsia-800 to-orange-600 p-8 text-white md:p-10" style={{borderRadius:radius}}><div className="relative z-10 max-w-xl"><h2 className="text-3xl font-black">{appearance.promoTextAr||"اكتشف تجارب جديدة كل يوم!"}</h2><p className="mt-2 text-white/75">{lang==="ar"?"متاجر جديدة • أطباق مميزة • عروض حصرية":"New stores • special dishes • exclusive offers"}</p><a href="#stores" className="mt-5 inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-black text-slate-900">{lang==="ar"?"تصفح المتاجر الآن":"Browse stores"}<ArrowLeft className="h-4 w-4"/></a></div></div></section>}
  <footer className={`border-t px-4 py-10 ${dark?"border-white/10 bg-[#06101b]":"border-slate-200 bg-white"}`}><div className="mx-auto flex max-w-7xl flex-wrap items-center justify-between gap-4"><b className="text-xl">NFOOD</b><p className="text-xs opacity-50">© {new Date().getFullYear()} NFOOD · {lang==="ar"?"جميع الحقوق محفوظة":"All rights reserved"}</p></div></footer>
 </main>
}