import { useEffect, useMemo, useState } from "react";
import { useParams } from "wouter";
import { AlertCircle, CalendarDays, CheckCircle2, ChefHat, Clock3, Globe2, Instagram, MapPin, MessageCircle, Minus, Phone, Plus, ShoppingBag, Utensils } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import Barcode from "react-barcode";
import { trpc } from "@/lib/trpc";

const guestStatusLabels: Record<string, string> = { new: "جديد", preparing: "قيد التحضير", ready: "جاهز", completed: "مكتمل", cancelled: "ملغى" };

export default function RestaurantPublic() {
  const { slug = "" } = useParams<{ slug: string }>();
  const page = trpc.platform.publicRestaurantPage.useQuery({ slug }, { enabled: Boolean(slug), retry: false });
  const checkout = trpc.platform.guestCheckout.useMutation();
  const reservation = trpc.platform.createPublicReservation.useMutation();
  const [cart, setCart] = useState<Record<number, number>>({});
  const [selectedBranchId, setSelectedBranchId] = useState<number | null>(null);
  const [guestName, setGuestName] = useState("");
  const [guestPhone, setGuestPhone] = useState("");
  const [receipt, setReceipt] = useState<{ orderId: number; total: string } | null>(null);
  const [lookupOrderId, setLookupOrderId] = useState("");
  const [lookupPhone, setLookupPhone] = useState("");
  const [reservationName, setReservationName] = useState("");
  const [reservationPhone, setReservationPhone] = useState("");
  const [reservationPartySize, setReservationPartySize] = useState("2");
  const [reservationDate, setReservationDate] = useState("");
  const [reservationNotes, setReservationNotes] = useState("");
  const [reservationReceipt, setReservationReceipt] = useState<number | null>(null);
  const categories = useMemo(() => [...(page.data?.categories ?? [])].sort((a, b) => a.sortOrder - b.sortOrder), [page.data?.categories]);
  const items = page.data?.items ?? [];
  const branches = page.data?.branches ?? [];
  const brandColor = page.data?.restaurant.brandColor ?? "#e76f3c";
  const trackingQuery = trpc.platform.trackGuestOrder.useQuery({ slug, orderId: Number(lookupOrderId), guestPhone: lookupPhone.trim() }, { enabled: Boolean(slug) && Number(lookupOrderId) > 0 && lookupPhone.trim().length >= 7, retry: false });
  const reorder = trpc.platform.reorderGuestOrder.useMutation({ onSuccess: (result) => { setReceipt({ orderId: result.orderId, total: result.total }); setCart({}); setGuestName(""); setGuestPhone(""); } });

  useEffect(() => {
    if (!trackingQuery.data || trackingQuery.isError) return;
    const interval = window.setInterval(() => { void trackingQuery.refetch(); }, 5000);
    return () => window.clearInterval(interval);
  }, [trackingQuery.data, trackingQuery.isError, trackingQuery.refetch]);

  useEffect(() => {
    if (selectedBranchId === null && branches[0]) setSelectedBranchId(branches[0].id);
    if (selectedBranchId !== null && !branches.some((branch) => branch.id === selectedBranchId)) setSelectedBranchId(branches[0]?.id ?? null);
  }, [branches, selectedBranchId]);

  const cartItems = useMemo(() => items.filter((item) => (cart[item.id] ?? 0) > 0).map((item) => ({ ...item, quantity: cart[item.id] ?? 0 })), [items, cart]);
  const total = cartItems.reduce((sum, item) => sum + Number(item.price) * item.quantity, 0);
  const itemCount = cartItems.reduce((sum, item) => sum + item.quantity, 0);
  const updateCart = (itemId: number, delta: number) => setCart((current) => { const next = Math.max(0, (current[itemId] ?? 0) + delta); const copy = { ...current }; if (next === 0) delete copy[itemId]; else copy[itemId] = next; return copy; });
  const submitReservation = () => { if (!reservationName.trim() || reservationPhone.trim().length < 7 || !selectedBranchId || !reservationDate) return; reservation.mutate({ slug, branchId: selectedBranchId, customerName: reservationName.trim(), phone: reservationPhone.trim(), partySize: Number(reservationPartySize), reservedFor: new Date(reservationDate), notes: reservationNotes.trim() || undefined }, { onSuccess: (result) => { setReservationReceipt(result.id); setReservationName(""); setReservationPhone(""); setReservationNotes(""); } }); };
  const submitCheckout = () => {
    if (!selectedBranchId) return;
    if (guestName.trim().length < 2 || guestPhone.trim().length < 7) return;
    if (!cartItems.length) return;
    checkout.mutate({ slug, branchId: selectedBranchId, guestName: guestName.trim(), guestPhone: guestPhone.trim(), channel: "takeaway", items: cartItems.map((item) => ({ menuItemId: item.id, quantity: item.quantity })) }, { onSuccess: (result) => { setReceipt({ orderId: result.orderId, total: result.total }); setCart({}); setGuestName(""); setGuestPhone(""); }, onError: () => undefined });
  };

  if (page.isLoading) return <div dir="rtl" className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-5xl space-y-5"><div className="h-48 animate-pulse rounded-3xl bg-white" /><div className="grid gap-4 md:grid-cols-2"><div className="h-32 rounded-2xl bg-white" /><div className="h-32 rounded-2xl bg-white" /></div></div></div>;
  if (page.isError || !page.data) return <div dir="rtl" className="flex min-h-screen items-center justify-center bg-slate-50 p-6"><Card className="w-full max-w-md rounded-3xl border-red-100 bg-white shadow-sm"><CardContent className="p-8 text-center"><AlertCircle className="mx-auto mb-4 h-10 w-10 text-red-500" /><h1 className="text-xl font-bold text-slate-900">المطعم غير متاح</h1><p className="mt-2 text-sm leading-7 text-slate-500">قد يكون الرابط غير صحيح أو أن المطعم متوقف مؤقتًا. Request ID: public-restaurant-{slug}</p><Button className="mt-5 rounded-xl" onClick={() => page.refetch()}>إعادة المحاولة</Button></CardContent></Card></div>;

  const restaurantName = page.data.restaurant.brandName ?? page.data.restaurant.name;
  const menuUrl = `${window.location.origin}/restaurant/${encodeURIComponent(slug)}`;
  return <div dir="rtl" className="min-h-screen bg-[#f8fafc] pb-12 text-slate-900">
    <header className="relative overflow-hidden px-6 pb-14 pt-8 text-white" style={{ backgroundColor: brandColor }}><div className="absolute -left-20 -top-24 h-64 w-64 rounded-full bg-white/10" /><div className="relative mx-auto flex max-w-5xl items-start justify-between gap-5"><div className="max-w-2xl"><Badge className="mb-4 rounded-full border-white/20 bg-white/15 text-white hover:bg-white/15">طلب ضيف مباشر</Badge><h1 className="text-3xl font-black tracking-tight md:text-5xl">{restaurantName}</h1><p className="mt-4 max-w-xl text-sm leading-7 text-white/80">{page.data.restaurant.brandDescription || "اكتشف أصنافنا المختارة والمحضرة بعناية."}</p></div>{page.data.restaurant.brandLogoUrl ? <img src={page.data.restaurant.brandLogoUrl} alt={`شعار ${restaurantName}`} className="h-20 w-20 rounded-2xl bg-white object-contain p-2 shadow-lg" /> : <div className="flex h-20 w-20 items-center justify-center rounded-2xl bg-white/15"><ChefHat className="h-9 w-9" /></div>}</div></header>
    <main className="mx-auto -mt-8 max-w-5xl px-5"><Card className="rounded-3xl bg-white shadow-xl shadow-slate-200/50"><CardContent className="grid gap-4 p-4 md:grid-cols-[1fr_280px]"><div className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4"><div className="flex h-11 w-11 items-center justify-center rounded-xl" style={{ backgroundColor: `${brandColor}18`, color: brandColor }}><Utensils className="h-5 w-5" /></div><div><p className="text-sm font-bold">منيو {restaurantName}</p><p className="mt-1 text-xs text-slate-500">الأصناف المتاحة الآن</p></div></div><label className="text-xs font-bold text-slate-600">الفرع<select value={selectedBranchId ?? ""} onChange={(event) => setSelectedBranchId(Number(event.target.value))} disabled={branches.length === 0} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">{branches.length ? "اختر الفرع" : "لا توجد فروع مفتوحة"}</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}{branch.city ? ` · ${branch.city}` : ""}</option>)}</select></label></CardContent></Card>
      <div className="mt-6 grid gap-4 md:grid-cols-[220px_1fr]">
        <Card className="rounded-3xl border-slate-200 bg-white shadow-sm"><CardContent className="flex flex-col items-center gap-3 p-5"><p className="text-sm font-bold">باركود المنيو</p><Barcode value={menuUrl} width={1.2} height={62} displayValue={false} margin={0} /><p className="text-center text-[11px] text-slate-500">امسح الكود لفتح المنيو</p><Button variant="outline" className="rounded-xl text-xs" onClick={() => window.print()}>طباعة الباركود</Button></CardContent></Card>
        <Card className="rounded-3xl border-slate-200 bg-white shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Clock3 className="h-5 w-5" style={{ color: brandColor }} /> ساعات العمل والتواصل</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-2 sm:grid-cols-2">{branches.map((branch) => <div key={branch.id} className="rounded-xl bg-slate-50 p-3 text-sm"><p className="font-bold">{branch.name}</p><p className="mt-1 text-xs text-slate-500">{branch.openingTime && branch.closingTime ? `${branch.openingTime} — ${branch.closingTime}` : "ساعات العمل غير محددة"}</p></div>)}</div>{page.data.restaurant.address && <p className="flex items-center gap-2 text-sm text-slate-600"><MapPin className="h-4 w-4" style={{ color: brandColor }} />{page.data.restaurant.address}</p>}<div className="flex flex-wrap gap-2">{page.data.restaurant.phone && <a href={`tel:${page.data.restaurant.phone}`} className="flex items-center gap-1 rounded-xl bg-slate-50 px-3 py-2 text-xs font-semibold"><Phone className="h-3.5 w-3.5" /> اتصال</a>}{page.data.restaurant.whatsapp && <a href={`https://wa.me/${page.data.restaurant.whatsapp.replace(/\D/g, "")}`} target="_blank" rel="noreferrer" className="flex items-center gap-1 rounded-xl bg-emerald-50 px-3 py-2 text-xs font-semibold text-emerald-700"><MessageCircle className="h-3.5 w-3.5" /> واتساب</a>}{page.data.restaurant.instagramUrl && <a href={page.data.restaurant.instagramUrl} target="_blank" rel="noreferrer" className="flex items-center gap-1 rounded-xl bg-pink-50 px-3 py-2 text-xs font-semibold text-pink-700"><Instagram className="h-3.5 w-3.5" /> Instagram</a>}{page.data.restaurant.websiteUrl && <a href={page.data.restaurant.websiteUrl} target="_blank" rel="noreferrer" className="flex items-center gap-1 rounded-xl bg-blue-50 px-3 py-2 text-xs font-semibold text-blue-700"><Globe2 className="h-3.5 w-3.5" /> الموقع</a>}</div></CardContent></Card>
      </div>
      {page.data.restaurant.reservationEnabled && <Card className="mt-6 rounded-3xl border-slate-200 bg-white shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><CalendarDays className="h-5 w-5" style={{ color: brandColor }} /> احجز طاولتك</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Input value={reservationName} onChange={(event) => setReservationName(event.target.value)} placeholder="الاسم" className="rounded-xl" /><Input value={reservationPhone} onChange={(event) => setReservationPhone(event.target.value)} placeholder="رقم الهاتف" className="rounded-xl" dir="ltr" /><Input type="number" min={1} max={50} value={reservationPartySize} onChange={(event) => setReservationPartySize(event.target.value)} placeholder="عدد الأشخاص" className="rounded-xl" /><Input type="datetime-local" value={reservationDate} onChange={(event) => setReservationDate(event.target.value)} className="rounded-xl" /></div><Input value={reservationNotes} onChange={(event) => setReservationNotes(event.target.value)} placeholder="ملاحظات اختيارية" className="rounded-xl" />{reservation.isError && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">تعذر إرسال الحجز. Request ID: public-reservation-{slug}</p>}{reservationReceipt && <p className="rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700">تم استلام طلب الحجز رقم #{reservationReceipt}، وسيتواصل معك المطعم للتأكيد.</p>}<Button disabled={!selectedBranchId || !reservationName.trim() || reservationPhone.trim().length < 7 || !reservationDate || reservation.isPending} onClick={submitReservation} className="rounded-xl px-6 text-white" style={{ backgroundColor: brandColor }}>{reservation.isPending ? "جارٍ إرسال الحجز..." : "إرسال طلب الحجز"}</Button></CardContent></Card>}
      {receipt && <Card className="mt-6 rounded-3xl border-emerald-200 bg-emerald-50"><CardContent className="flex flex-wrap items-center gap-4 p-6"><CheckCircle2 className="h-8 w-8 text-emerald-600" /><div><h2 className="font-bold text-emerald-900">تم استلام طلبك</h2><p className="mt-1 text-sm text-emerald-800">رقم الطلب #{receipt.orderId} · الإجمالي {receipt.total} ر.س · الدفع نقدي عند الاستلام</p></div></CardContent></Card>}
      <Card className="mt-6 rounded-3xl border-slate-200 bg-white shadow-sm"><CardHeader><CardTitle className="text-base">تتبع طلب الضيف</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><Input value={lookupOrderId} onChange={(event) => setLookupOrderId(event.target.value.replace(/\D/g, ""))} placeholder="رقم الطلب" inputMode="numeric" className="rounded-xl" /><Input value={lookupPhone} onChange={(event) => setLookupPhone(event.target.value)} placeholder="رقم الهاتف" dir="ltr" className="rounded-xl" /><Button disabled={!trackingQuery.isEnabled || trackingQuery.isFetching} onClick={() => void trackingQuery.refetch()} className="rounded-xl text-white" style={{ backgroundColor: brandColor }}>{trackingQuery.isFetching ? "جارٍ التحقق..." : "تتبع"}</Button></div>{trackingQuery.isError && <p className="text-sm text-red-700">لم يتم العثور على طلب مطابق. Request ID: guest-track-{slug}</p>}{trackingQuery.data && <div className="space-y-3"><p className="rounded-xl bg-slate-50 p-3 text-sm">حالة الطلب: <strong>{guestStatusLabels[trackingQuery.data.status] ?? trackingQuery.data.status}</strong> · الدفع: <strong>{trackingQuery.data.paymentStatus === "unpaid" ? "غير مدفوع" : trackingQuery.data.paymentStatus}</strong> · الإجمالي: <strong>{trackingQuery.data.total} ر.س</strong></p><Button disabled={reorder.isPending} onClick={() => reorder.mutate({ slug, orderId: trackingQuery.data.id, guestPhone: lookupPhone.trim() })} variant="outline" className="rounded-xl">{reorder.isPending ? "جارٍ إنشاء الطلب..." : "إعادة الطلب"}</Button>{reorder.isError && <p className="text-sm text-red-700">تعذر إعادة الطلب. Request ID: guest-reorder-{slug}</p>}</div>}</CardContent></Card>
      {items.length === 0 ? <Card className="mt-8 rounded-3xl border-dashed bg-white"><CardContent className="p-10 text-center text-sm text-slate-500">لا توجد أصناف متاحة حاليًا.</CardContent></Card> : categories.length === 0 ? <Card className="mt-8 rounded-3xl border-dashed bg-white"><CardContent className="p-10 text-center text-sm text-slate-500">لا توجد أقسام منيو منشورة لعرض هذه الأصناف.</CardContent></Card> : <div className="mt-8 space-y-8">{categories.map((category) => { const categoryItems = items.filter((item) => item.categoryId === category.id); if (!categoryItems.length) return null; return <section key={category.id}><div className="mb-4 flex items-center gap-3"><h2 className="text-xl font-black">{category.name}</h2><span className="h-px flex-1 bg-slate-200" /></div><div className="grid gap-4 md:grid-cols-2">{categoryItems.map((item) => <Card key={item.id} className="overflow-hidden rounded-2xl border-slate-200 bg-white shadow-sm"><CardContent className="flex min-h-32 gap-4 p-4">{item.imageUrl ? <img src={item.imageUrl} alt={item.name} className="h-24 w-24 shrink-0 rounded-xl object-cover" /> : <div className="flex h-24 w-24 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-300"><Utensils className="h-7 w-7" /></div>}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><h3 className="font-bold">{item.name}</h3><strong className="shrink-0 text-sm" style={{ color: brandColor }}>{Number(item.price).toFixed(2)} ر.س</strong></div><p className="mt-2 text-xs leading-6 text-slate-500">{item.description || "صنف متاح ضمن قائمة المطعم."}</p><div className="mt-3 flex items-center gap-2"><Button size="icon" variant="outline" className="h-8 w-8 rounded-lg" onClick={() => updateCart(item.id, -1)} aria-label={`إنقاص ${item.name}`}><Minus className="h-3.5 w-3.5" /></Button><span className="min-w-5 text-center text-sm font-bold">{cart[item.id] ?? 0}</span><Button size="icon" className="h-8 w-8 rounded-lg text-white" style={{ backgroundColor: brandColor }} onClick={() => updateCart(item.id, 1)} aria-label={`إضافة ${item.name}`}><Plus className="h-3.5 w-3.5" /></Button></div></div></CardContent></Card>)}</div></section>; })}</div>}
      <Card className="mt-10 rounded-3xl border-slate-200 bg-white shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ShoppingBag className="h-5 w-5" style={{ color: brandColor }} /> سلة الضيف ({itemCount})</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><Input value={guestName} onChange={(event) => setGuestName(event.target.value)} placeholder="اسم الضيف" className="rounded-xl" /><Input value={guestPhone} onChange={(event) => setGuestPhone(event.target.value)} placeholder="رقم الهاتف" className="rounded-xl" dir="ltr" /></div>{checkout.isError && <p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">تعذر إرسال الطلب. تحقق من الفرع والأصناف وحاول مرة أخرى. Request ID: guest-checkout-{slug}</p>}<div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-4"><p className="text-lg font-black">الإجمالي: {total.toFixed(2)} ر.س</p><Button disabled={!selectedBranchId || !cartItems.length || guestName.trim().length < 2 || guestPhone.trim().length < 7 || checkout.isPending} onClick={submitCheckout} className="rounded-xl px-6 text-white" style={{ backgroundColor: brandColor }}>{checkout.isPending ? "جارٍ إرسال الطلب..." : "تأكيد الطلب والدفع نقدًا"}</Button></div><p className="text-xs leading-6 text-slate-500">لا يتم تحصيل أي مبلغ إلكتروني في هذا التدفق؛ يبقى الطلب غير مدفوع حتى الدفع النقدي عند الاستلام.</p></CardContent></Card>
    </main><footer className="mt-10 border-t border-slate-200 bg-white px-5 py-6 text-center text-xs text-slate-400">{restaurantName} · NFOOD</footer>
  </div>;
}
