import { useMemo } from "react";
import { useParams } from "wouter";
import { AlertCircle, ChefHat, Utensils } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";

export default function RestaurantPublic() {
  const { slug = "" } = useParams<{ slug: string }>();
  const page = trpc.platform.publicRestaurantPage.useQuery({ slug }, { enabled: Boolean(slug), retry: false });
  const categories = useMemo(() => [...(page.data?.categories ?? [])].sort((a, b) => a.sortOrder - b.sortOrder), [page.data?.categories]);
  const items = page.data?.items ?? [];
  const brandColor = page.data?.restaurant.brandColor ?? "#e76f3c";
  if (page.isLoading) return <div dir="rtl" className="min-h-screen bg-slate-50 p-6"><div className="mx-auto max-w-5xl space-y-5"><div className="h-48 animate-pulse rounded-3xl bg-white" /><div className="grid gap-4 md:grid-cols-2"><div className="h-32 animate-pulse rounded-2xl bg-white" /><div className="h-32 animate-pulse rounded-2xl bg-white" /></div></div></div>;
  if (page.isError || !page.data) return <div dir="rtl" className="flex min-h-screen items-center justify-center bg-slate-50 p-6"><Card className="w-full max-w-md rounded-3xl border-red-100 bg-white shadow-sm"><CardContent className="p-8 text-center"><AlertCircle className="mx-auto mb-4 h-10 w-10 text-red-500" /><h1 className="text-xl font-bold text-slate-900">المطعم غير متاح</h1><p className="mt-2 text-sm leading-7 text-slate-500">قد يكون الرابط غير صحيح أو أن المطعم متوقف مؤقتًا. Request ID: public-restaurant-{slug}</p><Button className="mt-5 rounded-xl" onClick={() => page.refetch()}>إعادة المحاولة</Button></CardContent></Card></div>;
  return <div dir="rtl" className="min-h-screen bg-[#f8fafc] text-slate-900" style={{ "--restaurant-brand": brandColor } as React.CSSProperties}>
    <header className="relative overflow-hidden px-6 pb-14 pt-8 text-white" style={{ backgroundColor: brandColor }}><div className="absolute -left-20 -top-24 h-64 w-64 rounded-full bg-white/10" /><div className="relative mx-auto flex max-w-5xl items-start justify-between gap-5"><div className="max-w-2xl"><Badge className="mb-4 rounded-full border-white/20 bg-white/15 text-white hover:bg-white/15">قائمة المطعم</Badge><h1 className="text-3xl font-black tracking-tight md:text-5xl">{page.data.restaurant.brandName ?? page.data.restaurant.name}</h1><p className="mt-4 max-w-xl text-sm leading-7 text-white/80">{page.data.restaurant.brandDescription || "اكتشف أصنافنا المختارة والمحضرة بعناية."}</p></div>{page.data.restaurant.brandLogoUrl ? <img src={page.data.restaurant.brandLogoUrl} alt={`شعار ${page.data.restaurant.brandName ?? page.data.restaurant.name}`} className="h-20 w-20 rounded-2xl bg-white object-contain p-2 shadow-lg" /> : <div className="flex h-20 w-20 items-center justify-center rounded-2xl bg-white/15"><ChefHat className="h-9 w-9" /></div>}</div></header>
    <main className="mx-auto -mt-8 max-w-5xl px-5 pb-16"><div className="rounded-3xl bg-white p-4 shadow-xl shadow-slate-200/50"><div className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4"><div className="flex h-11 w-11 items-center justify-center rounded-xl" style={{ backgroundColor: `${brandColor}18`, color: brandColor }}><Utensils className="h-5 w-5" /></div><div><p className="text-sm font-bold">منيو {page.data.restaurant.brandName ?? page.data.restaurant.name}</p><p className="mt-1 text-xs text-slate-500">الأصناف المتاحة الآن</p></div></div></div>{items.length === 0 ? <Card className="mt-8 rounded-3xl border-dashed bg-white"><CardContent className="p-10 text-center text-sm text-slate-500">لا توجد أصناف متاحة حاليًا.</CardContent></Card> : categories.length === 0 ? <Card className="mt-8 rounded-3xl border-dashed bg-white"><CardContent className="p-10 text-center text-sm text-slate-500">لا توجد أقسام منيو منشورة لعرض هذه الأصناف.</CardContent></Card> : <div className="mt-8 space-y-8">{categories.map((category) => { const categoryItems = items.filter((item) => item.categoryId === category.id); if (!categoryItems.length) return null; return <section key={category.id}><div className="mb-4 flex items-center gap-3"><h2 className="text-xl font-black">{category.name}</h2><span className="h-px flex-1 bg-slate-200" /></div><div className="grid gap-4 md:grid-cols-2">{categoryItems.map((item) => <Card key={item.id} className="overflow-hidden rounded-2xl border-slate-200 bg-white shadow-sm"><CardContent className="flex min-h-32 gap-4 p-4">{item.imageUrl ? <img src={item.imageUrl} alt={item.name} className="h-24 w-24 shrink-0 rounded-xl object-cover" /> : <div className="flex h-24 w-24 shrink-0 items-center justify-center rounded-xl bg-slate-100 text-slate-300"><Utensils className="h-7 w-7" /></div>}<div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><h3 className="font-bold">{item.name}</h3><strong className="shrink-0 text-sm" style={{ color: brandColor }}>{Number(item.price).toFixed(2)} ر.س</strong></div><p className="mt-2 text-xs leading-6 text-slate-500">{item.description || "صنف متاح ضمن قائمة المطعم."}</p></div></CardContent></Card>)}</div></section>; })}</div>}</main>
    <footer className="border-t border-slate-200 bg-white px-5 py-6 text-center text-xs text-slate-400">{page.data.restaurant.brandName ?? page.data.restaurant.name} · NFOOD</footer>
  </div>;
}
