import nodemailer from "nodemailer";
import { and, eq } from "drizzle-orm";
import { emailTemplates } from "../drizzle/schema";
import { decryptIntegrationSecret, getDb, getIntegrationSetting } from "./db";

export type EmailLocale = "ar" | "en" | "fr";
export type EmailEventKey = "account.welcome" | "account.email_verification" | "account.password_reset" | "account.otp" | "order.received" | "order.status" | "reservation.accepted" | "reservation.rejected" | "reservation.updated" | "reservation.cancelled" | "payment.receipt" | "payment.failed" | "payment.refunded" | "invoice.issued" | "invoice.overdue" | "subscription.activated" | "subscription.renewal_due" | "order.ready" | "order.completed" | "reservation.reminder" | "driver.assignment";

type EmailTemplateSeed = { eventKey: EmailEventKey; locale: EmailLocale; subject: string; htmlBody: string; textBody: string };

const seeds: EmailTemplateSeed[] = [
  { eventKey: "account.welcome", locale: "ar", subject: "مرحبًا بك في {{siteName}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>مرحبًا {{name}}</h2><p>تم إنشاء حسابك بنجاح في {{siteName}}.</p><p>المطعم المرتبط: {{restaurantName}}</p></div>", textBody: "مرحبًا {{name}}، تم إنشاء حسابك في {{siteName}}. المطعم المرتبط: {{restaurantName}}." },
  { eventKey: "account.email_verification", locale: "ar", subject: "تأكيد بريدك في {{siteName}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>تأكيد البريد الإلكتروني</h2><p>مرحبًا {{name}}،</p><p><a href=\"{{verifyUrl}}\">اضغط هنا لتأكيد بريدك الإلكتروني</a></p><p>ينتهي الرابط خلال 24 ساعة.</p></div>", textBody: "مرحبًا {{name}}، أكد بريدك الإلكتروني عبر الرابط: {{verifyUrl}}. ينتهي الرابط خلال 24 ساعة." },
  { eventKey: "account.password_reset", locale: "ar", subject: "إعادة تعيين كلمة مرور {{siteName}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>إعادة تعيين كلمة المرور</h2><p>مرحبًا {{name}}،</p><p><a href=\"{{resetUrl}}\">اضغط هنا لإنشاء كلمة مرور جديدة</a></p><p>ينتهي الرابط خلال ساعة واحدة.</p></div>", textBody: "مرحبًا {{name}}، افتح الرابط التالي لإعادة تعيين كلمة المرور: {{resetUrl}}. ينتهي خلال ساعة واحدة." },
  { eventKey: "account.otp", locale: "ar", subject: "رمز التحقق من {{siteName}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>رمز التحقق</h2><p>رمزك هو <strong style=\"font-size:28px;letter-spacing:6px\">{{code}}</strong></p><p>ينتهي خلال {{expiresMinutes}} دقائق.</p></div>", textBody: "رمز التحقق: {{code}}. ينتهي خلال {{expiresMinutes}} دقائق." },
  { eventKey: "order.received", locale: "ar", subject: "تم استلام طلبك #{{orderNumber}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>تم استلام الطلب</h2><p>مرحبًا {{name}}، استلم {{restaurantName}} طلبك رقم {{orderNumber}} بقيمة {{total}}.</p></div>", textBody: "مرحبًا {{name}}، تم استلام طلبك رقم {{orderNumber}} لدى {{restaurantName}} بقيمة {{total}}." },
  { eventKey: "order.status", locale: "ar", subject: "تحديث حالة الطلب #{{orderNumber}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>تحديث الطلب</h2><p>حالة طلبك رقم {{orderNumber}} الآن: <strong>{{status}}</strong>.</p></div>", textBody: "حالة طلبك رقم {{orderNumber}} الآن: {{status}}." },
  { eventKey: "reservation.accepted", locale: "ar", subject: "تم قبول حجزك في {{restaurantName}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>تم تأكيد الحجز</h2><p>مرحبًا {{name}}، موعدك {{reservedFor}} والطاولة {{tableName}} لعدد {{partySize}} أشخاص.</p></div>", textBody: "مرحبًا {{name}}، تم تأكيد حجزك في {{restaurantName}} بتاريخ {{reservedFor}}، الطاولة {{tableName}} لعدد {{partySize}}." },
  { eventKey: "reservation.rejected", locale: "ar", subject: "تعذر قبول حجزك في {{restaurantName}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>لم يتم قبول الحجز</h2><p>مرحبًا {{name}}، لم يتم قبول حجزك للموعد {{reservedFor}}. السبب: {{reason}}.</p></div>", textBody: "مرحبًا {{name}}، لم يتم قبول حجزك في {{restaurantName}} للموعد {{reservedFor}}. السبب: {{reason}}." },
  { eventKey: "reservation.updated", locale: "ar", subject: "تم تعديل حجزك في {{restaurantName}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>تحديث الحجز</h2><p>مرحبًا {{name}}، تم تحديث حجزك للموعد {{reservedFor}}. عدد الأشخاص: {{partySize}}.</p></div>", textBody: "مرحبًا {{name}}، تم تحديث حجزك في {{restaurantName}} للموعد {{reservedFor}}، وعدد الأشخاص {{partySize}}." },
  { eventKey: "reservation.cancelled", locale: "ar", subject: "تم إلغاء حجزك في {{restaurantName}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>تم إلغاء الحجز</h2><p>مرحبًا {{name}}، تم إلغاء حجزك للموعد {{reservedFor}}. السبب: {{reason}}.</p></div>", textBody: "مرحبًا {{name}}، تم إلغاء حجزك للموعد {{reservedFor}}. السبب: {{reason}}." },
  { eventKey: "payment.receipt", locale: "ar", subject: "إيصال الدفع للطلب #{{orderNumber}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>إيصال الدفع</h2><p>تم تسجيل دفعتك بقيمة {{total}} للطلب رقم {{orderNumber}}.</p></div>", textBody: "تم تسجيل دفعتك بقيمة {{total}} للطلب رقم {{orderNumber}}." },
  { eventKey: "invoice.issued", locale: "ar", subject: "فاتورتك #{{invoiceNumber}} من {{restaurantName}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>تم إصدار الفاتورة</h2><p>مرحبًا {{name}}، صدرت فاتورتك رقم {{invoiceNumber}} بقيمة {{total}}.</p><p>يمكنك مراجعتها من حسابك في NFOOD.</p></div>", textBody: "صدرت فاتورتك {{invoiceNumber}} من {{restaurantName}} بقيمة {{total}}. راجعها من حسابك في NFOOD." },
  { eventKey: "payment.failed", locale: "ar", subject: "تعذر إتمام الدفع للفاتورة #{{invoiceNumber}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>تعذر إتمام الدفع</h2><p>لم تكتمل عملية الدفع للفاتورة {{invoiceNumber}} بقيمة {{total}}.</p><p>الحالة: {{status}} · وسيلة الدفع: {{paymentMethod}}</p></div>", textBody: "تعذر إتمام الدفع للفاتورة {{invoiceNumber}} بقيمة {{total}}. الحالة: {{status}}. وسيلة الدفع: {{paymentMethod}}." },
  { eventKey: "payment.refunded", locale: "ar", subject: "تم تسجيل استرداد للفاتورة #{{invoiceNumber}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>تحديث الاسترداد</h2><p>تم تسجيل استرداد بقيمة {{refundAmount}} للفاتورة {{invoiceNumber}}.</p><p>حالة الدفع الحالية: {{status}}</p></div>", textBody: "تم تسجيل استرداد {{refundAmount}} للفاتورة {{invoiceNumber}}. الحالة الحالية: {{status}}." },
  { eventKey: "invoice.overdue", locale: "ar", subject: "فاتورة مستحقة #{{invoiceNumber}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>فاتورة مستحقة</h2><p>الفاتورة {{invoiceNumber}} بقيمة {{total}} مستحقة منذ {{dueDate}}.</p><p>يرجى مراجعة مركز الحسابات لإتمام السداد.</p></div>", textBody: "الفاتورة {{invoiceNumber}} بقيمة {{total}} مستحقة منذ {{dueDate}}. راجع مركز الحسابات لإتمام السداد." },
  { eventKey: "subscription.activated", locale: "ar", subject: "تم تفعيل اشتراك {{plan}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>تم تفعيل الاشتراك</h2><p>تم تفعيل باقة {{plan}} حتى {{periodEnd}}.</p><p>مرجع الفاتورة: {{invoiceNumber}}</p></div>", textBody: "تم تفعيل باقة {{plan}} حتى {{periodEnd}}. مرجع الفاتورة: {{invoiceNumber}}." },
  { eventKey: "subscription.renewal_due", locale: "ar", subject: "موعد تجديد اشتراك {{plan}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>موعد التجديد</h2><p>اشتراك {{plan}} يستحق التجديد بتاريخ {{dueDate}}.</p><p>المبلغ المستحق: {{total}} · الفاتورة: {{invoiceNumber}}</p></div>", textBody: "اشتراك {{plan}} يستحق التجديد بتاريخ {{dueDate}}. المبلغ {{total}}، الفاتورة {{invoiceNumber}}." },
  { eventKey: "order.ready", locale: "ar", subject: "طلبك #{{orderNumber}} جاهز", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>طلبك جاهز</h2><p>طلبك {{orderNumber}} لدى {{restaurantName}} جاهز. رمز الاستلام: {{qrCode}}.</p></div>", textBody: "طلبك {{orderNumber}} جاهز لدى {{restaurantName}}. رمز الاستلام: {{qrCode}}." },
  { eventKey: "order.completed", locale: "ar", subject: "اكتمل طلبك #{{orderNumber}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>شكرًا لك</h2><p>اكتمل طلبك {{orderNumber}} لدى {{restaurantName}}. الفاتورة محفوظة في حسابك.</p></div>", textBody: "اكتمل طلبك {{orderNumber}} لدى {{restaurantName}}. الفاتورة محفوظة في حسابك." },
  { eventKey: "reservation.reminder", locale: "ar", subject: "تذكير بحجزك في {{restaurantName}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>تذكير بالحجز</h2><p>موعد حجزك {{reservedFor}} للطاولة {{tableName}}. رمز التأكيد: {{qrCode}}.</p></div>", textBody: "تذكير بحجزك في {{restaurantName}}: {{reservedFor}}، الطاولة {{tableName}}، الرمز {{qrCode}}." },
  { eventKey: "driver.assignment", locale: "ar", subject: "تم إسناد طلب توصيل جديد #{{orderNumber}}", htmlBody: "<div dir=\"rtl\" style=\"font-family:Arial;line-height:1.8\"><h2>طلب توصيل جديد</h2><p>تم إسناد الطلب {{orderNumber}} إليك من {{restaurantName}}. العنوان: {{deliveryAddress}}.</p></div>", textBody: "تم إسناد الطلب {{orderNumber}} إليك من {{restaurantName}}. العنوان: {{deliveryAddress}}." },
];


const localizedCopy: Partial<Record<EmailEventKey, Record<Exclude<EmailLocale, "ar">, { subject: string; title: string; body: string; text: string }>>> = {
  "account.welcome": { en: { subject: "Welcome to {{siteName}}", title: "Welcome, {{name}}", body: "Your account has been created successfully. Linked business: {{restaurantName}}.", text: "Welcome {{name}}. Your {{siteName}} account is ready. Linked business: {{restaurantName}}." }, fr: { subject: "Bienvenue sur {{siteName}}", title: "Bienvenue, {{name}}", body: "Votre compte a été créé avec succès. Établissement associé : {{restaurantName}}.", text: "Bienvenue {{name}}. Votre compte {{siteName}} est prêt. Établissement associé : {{restaurantName}}." } },
  "account.email_verification": { en: { subject: "Verify your {{siteName}} email", title: "Verify your email", body: "Hello {{name}}. Confirm your email using this link: {{verifyUrl}}. The link expires in 24 hours.", text: "Hello {{name}}. Verify your email: {{verifyUrl}}. The link expires in 24 hours." }, fr: { subject: "Confirmez votre e-mail {{siteName}}", title: "Confirmez votre e-mail", body: "Bonjour {{name}}. Confirmez votre e-mail via ce lien : {{verifyUrl}}. Le lien expire dans 24 heures.", text: "Bonjour {{name}}. Confirmez votre e-mail : {{verifyUrl}}. Le lien expire dans 24 heures." } },
  "account.password_reset": { en: { subject: "Reset your {{siteName}} password", title: "Reset password", body: "Hello {{name}}. Create a new password here: {{resetUrl}}. The link expires in one hour.", text: "Hello {{name}}. Reset your password: {{resetUrl}}. The link expires in one hour." }, fr: { subject: "Réinitialisez votre mot de passe {{siteName}}", title: "Réinitialisation du mot de passe", body: "Bonjour {{name}}. Créez un nouveau mot de passe ici : {{resetUrl}}. Le lien expire dans une heure.", text: "Bonjour {{name}}. Réinitialisez votre mot de passe : {{resetUrl}}. Le lien expire dans une heure." } },
  "account.otp": { en: { subject: "Your {{siteName}} verification code", title: "Verification code", body: "Your verification code is {{code}}. It expires in {{expiresMinutes}} minutes.", text: "Verification code: {{code}}. Expires in {{expiresMinutes}} minutes." }, fr: { subject: "Votre code de vérification {{siteName}}", title: "Code de vérification", body: "Votre code de vérification est {{code}}. Il expire dans {{expiresMinutes}} minutes.", text: "Code de vérification : {{code}}. Expire dans {{expiresMinutes}} minutes." } },
  "order.received": { en: { subject: "Order #{{orderNumber}} received", title: "Order received", body: "{{restaurantName}} received your order #{{orderNumber}} for {{total}}.", text: "Your order #{{orderNumber}} was received by {{restaurantName}}. Total: {{total}}." }, fr: { subject: "Commande #{{orderNumber}} reçue", title: "Commande reçue", body: "{{restaurantName}} a reçu votre commande #{{orderNumber}} pour {{total}}.", text: "Votre commande #{{orderNumber}} a été reçue par {{restaurantName}}. Total : {{total}}." } },
  "order.status": { en: { subject: "Order #{{orderNumber}} status update", title: "Order update", body: "Your order #{{orderNumber}} is now: {{status}}.", text: "Order #{{orderNumber}} status: {{status}}." }, fr: { subject: "Mise à jour de la commande #{{orderNumber}}", title: "Mise à jour de la commande", body: "Votre commande #{{orderNumber}} est maintenant : {{status}}.", text: "Statut de la commande #{{orderNumber}} : {{status}}." } },
  "order.ready": { en: { subject: "Order #{{orderNumber}} is ready", title: "Your order is ready", body: "Order #{{orderNumber}} at {{restaurantName}} is ready. Pickup code: {{qrCode}}.", text: "Order #{{orderNumber}} is ready at {{restaurantName}}. Pickup code: {{qrCode}}." }, fr: { subject: "Commande #{{orderNumber}} prête", title: "Votre commande est prête", body: "La commande #{{orderNumber}} chez {{restaurantName}} est prête. Code de retrait : {{qrCode}}.", text: "Commande #{{orderNumber}} prête chez {{restaurantName}}. Code : {{qrCode}}." } },
  "order.completed": { en: { subject: "Order #{{orderNumber}} completed", title: "Thank you", body: "Your order #{{orderNumber}} at {{restaurantName}} is complete. Your invoice is saved in your account.", text: "Order #{{orderNumber}} at {{restaurantName}} is complete. Your invoice is in your account." }, fr: { subject: "Commande #{{orderNumber}} terminée", title: "Merci", body: "Votre commande #{{orderNumber}} chez {{restaurantName}} est terminée. Votre facture est enregistrée dans votre compte.", text: "Commande #{{orderNumber}} terminée chez {{restaurantName}}. Votre facture est dans votre compte." } },
  "reservation.accepted": { en: { subject: "Reservation confirmed at {{restaurantName}}", title: "Reservation confirmed", body: "Hello {{name}}. Your reservation is confirmed for {{reservedFor}}, table {{tableName}}, party of {{partySize}}.", text: "Reservation confirmed at {{restaurantName}} for {{reservedFor}}, table {{tableName}}, party of {{partySize}}." }, fr: { subject: "Réservation confirmée chez {{restaurantName}}", title: "Réservation confirmée", body: "Bonjour {{name}}. Votre réservation est confirmée pour {{reservedFor}}, table {{tableName}}, pour {{partySize}} personnes.", text: "Réservation confirmée chez {{restaurantName}} pour {{reservedFor}}, table {{tableName}}, {{partySize}} personnes." } },
  "reservation.rejected": { en: { subject: "Reservation unavailable at {{restaurantName}}", title: "Reservation not accepted", body: "Hello {{name}}. We could not accept your reservation for {{reservedFor}}. Reason: {{reason}}.", text: "Reservation at {{restaurantName}} for {{reservedFor}} was not accepted. Reason: {{reason}}." }, fr: { subject: "Réservation indisponible chez {{restaurantName}}", title: "Réservation non acceptée", body: "Bonjour {{name}}. Nous n’avons pas pu accepter votre réservation pour {{reservedFor}}. Motif : {{reason}}.", text: "Réservation chez {{restaurantName}} pour {{reservedFor}} non acceptée. Motif : {{reason}}." } },
  "reservation.updated": { en: { subject: "Reservation updated at {{restaurantName}}", title: "Reservation updated", body: "Hello {{name}}. Your reservation is now {{reservedFor}} for {{partySize}} guests.", text: "Your reservation at {{restaurantName}} was updated to {{reservedFor}} for {{partySize}} guests." }, fr: { subject: "Réservation modifiée chez {{restaurantName}}", title: "Réservation modifiée", body: "Bonjour {{name}}. Votre réservation est maintenant prévue le {{reservedFor}} pour {{partySize}} personnes.", text: "Votre réservation chez {{restaurantName}} a été modifiée : {{reservedFor}}, {{partySize}} personnes." } },
  "reservation.cancelled": { en: { subject: "Reservation cancelled at {{restaurantName}}", title: "Reservation cancelled", body: "Hello {{name}}. Your reservation for {{reservedFor}} was cancelled. Reason: {{reason}}.", text: "Your reservation at {{restaurantName}} for {{reservedFor}} was cancelled. Reason: {{reason}}." }, fr: { subject: "Réservation annulée chez {{restaurantName}}", title: "Réservation annulée", body: "Bonjour {{name}}. Votre réservation du {{reservedFor}} a été annulée. Motif : {{reason}}.", text: "Votre réservation chez {{restaurantName}} du {{reservedFor}} a été annulée. Motif : {{reason}}." } },
  "reservation.reminder": { en: { subject: "Reservation reminder at {{restaurantName}}", title: "Reservation reminder", body: "Your reservation is {{reservedFor}}, table {{tableName}}. Confirmation code: {{qrCode}}.", text: "Reservation reminder at {{restaurantName}}: {{reservedFor}}, table {{tableName}}, code {{qrCode}}." }, fr: { subject: "Rappel de réservation chez {{restaurantName}}", title: "Rappel de réservation", body: "Votre réservation est prévue le {{reservedFor}}, table {{tableName}}. Code de confirmation : {{qrCode}}.", text: "Rappel chez {{restaurantName}} : {{reservedFor}}, table {{tableName}}, code {{qrCode}}." } },
  "payment.receipt": { en: { subject: "Payment receipt for order #{{orderNumber}}", title: "Payment receipt", body: "We recorded your payment of {{total}} for order #{{orderNumber}}.", text: "Payment of {{total}} recorded for order #{{orderNumber}}." }, fr: { subject: "Reçu de paiement pour la commande #{{orderNumber}}", title: "Reçu de paiement", body: "Votre paiement de {{total}} pour la commande #{{orderNumber}} a été enregistré.", text: "Paiement de {{total}} enregistré pour la commande #{{orderNumber}}." } },
  "payment.failed": { en: { subject: "Payment failed for invoice #{{invoiceNumber}}", title: "Payment failed", body: "Payment for invoice {{invoiceNumber}} ({{total}}) was not completed. Status: {{status}}. Method: {{paymentMethod}}.", text: "Payment failed for invoice {{invoiceNumber}} ({{total}}). Status: {{status}}. Method: {{paymentMethod}}." }, fr: { subject: "Échec du paiement de la facture #{{invoiceNumber}}", title: "Échec du paiement", body: "Le paiement de la facture {{invoiceNumber}} ({{total}}) n’a pas abouti. Statut : {{status}}. Moyen : {{paymentMethod}}.", text: "Échec du paiement de la facture {{invoiceNumber}} ({{total}}). Statut : {{status}}. Moyen : {{paymentMethod}}." } },
  "payment.refunded": { en: { subject: "Refund recorded for invoice #{{invoiceNumber}}", title: "Refund update", body: "A refund of {{refundAmount}} was recorded for invoice {{invoiceNumber}}. Current status: {{status}}.", text: "Refund {{refundAmount}} recorded for invoice {{invoiceNumber}}. Status: {{status}}." }, fr: { subject: "Remboursement enregistré pour la facture #{{invoiceNumber}}", title: "Mise à jour du remboursement", body: "Un remboursement de {{refundAmount}} a été enregistré pour la facture {{invoiceNumber}}. Statut : {{status}}.", text: "Remboursement de {{refundAmount}} enregistré pour la facture {{invoiceNumber}}. Statut : {{status}}." } },
  "invoice.issued": { en: { subject: "Invoice #{{invoiceNumber}} from {{restaurantName}}", title: "Invoice issued", body: "Hello {{name}}. Invoice {{invoiceNumber}} for {{total}} has been issued and is available in your account.", text: "Invoice {{invoiceNumber}} from {{restaurantName}} for {{total}} is available in your account." }, fr: { subject: "Facture #{{invoiceNumber}} de {{restaurantName}}", title: "Facture émise", body: "Bonjour {{name}}. La facture {{invoiceNumber}} de {{total}} a été émise et est disponible dans votre compte.", text: "Facture {{invoiceNumber}} de {{restaurantName}} pour {{total}} disponible dans votre compte." } },
  "invoice.overdue": { en: { subject: "Invoice #{{invoiceNumber}} is overdue", title: "Invoice overdue", body: "Invoice {{invoiceNumber}} for {{total}} has been due since {{dueDate}}. Please review Account Center.", text: "Invoice {{invoiceNumber}} for {{total}} is overdue since {{dueDate}}. Review Account Center." }, fr: { subject: "Facture #{{invoiceNumber}} échue", title: "Facture échue", body: "La facture {{invoiceNumber}} de {{total}} est échue depuis le {{dueDate}}. Consultez le Centre des comptes.", text: "Facture {{invoiceNumber}} de {{total}} échue depuis {{dueDate}}. Consultez le Centre des comptes." } },
  "subscription.activated": { en: { subject: "{{plan}} subscription activated", title: "Subscription activated", body: "Your {{plan}} plan is active until {{periodEnd}}. Invoice reference: {{invoiceNumber}}.", text: "{{plan}} activated until {{periodEnd}}. Invoice: {{invoiceNumber}}." }, fr: { subject: "Abonnement {{plan}} activé", title: "Abonnement activé", body: "Votre offre {{plan}} est active jusqu’au {{periodEnd}}. Référence de facture : {{invoiceNumber}}.", text: "{{plan}} activé jusqu’au {{periodEnd}}. Facture : {{invoiceNumber}}." } },
  "subscription.renewal_due": { en: { subject: "{{plan}} subscription renewal", title: "Renewal due", body: "Your {{plan}} plan renews on {{dueDate}}. Amount due: {{total}}. Invoice: {{invoiceNumber}}.", text: "{{plan}} renewal due {{dueDate}}. Amount: {{total}}. Invoice: {{invoiceNumber}}." }, fr: { subject: "Renouvellement de l’abonnement {{plan}}", title: "Renouvellement à venir", body: "Votre offre {{plan}} est à renouveler le {{dueDate}}. Montant : {{total}}. Facture : {{invoiceNumber}}.", text: "Renouvellement {{plan}} le {{dueDate}}. Montant : {{total}}. Facture : {{invoiceNumber}}." } },
  "driver.assignment": { en: { subject: "New delivery order #{{orderNumber}} assigned", title: "New delivery assignment", body: "Order #{{orderNumber}} from {{restaurantName}} was assigned to you. Address: {{deliveryAddress}}.", text: "Order #{{orderNumber}} assigned from {{restaurantName}}. Address: {{deliveryAddress}}." }, fr: { subject: "Nouvelle livraison #{{orderNumber}} attribuée", title: "Nouvelle livraison", body: "La commande #{{orderNumber}} de {{restaurantName}} vous a été attribuée. Adresse : {{deliveryAddress}}.", text: "Commande #{{orderNumber}} attribuée depuis {{restaurantName}}. Adresse : {{deliveryAddress}}." } },
};

function emailShell(locale: EmailLocale, title: string, body: string) {
  const rtl = locale === "ar";
  return `<!doctype html><html lang="${locale}" dir="${rtl ? "rtl" : "ltr"}"><body style="margin:0;background:#f6f8fb;font-family:Arial,sans-serif;color:#111c2e"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="padding:28px 12px"><tr><td align="center"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="max-width:620px;background:#fff;border:1px solid #e5e7eb;border-radius:20px;overflow:hidden"><tr><td style="height:6px;background:#e76f3c"></td></tr><tr><td style="padding:28px"><div style="font-size:13px;font-weight:700;color:#2563eb;letter-spacing:.4px">FOONCARD · NFOOD</div><h1 style="margin:12px 0 16px;font-size:24px;line-height:1.35">${title}</h1><div style="font-size:15px;line-height:1.9;color:#475569">${body}</div><div style="margin-top:26px;padding-top:16px;border-top:1px solid #eef2f7;font-size:12px;color:#94a3b8">${rtl ? "رسالة آلية من Fooncard · NFOOD" : locale === "fr" ? "Message automatique de Fooncard · NFOOD" : "Automated message from Fooncard · NFOOD"}</div></td></tr></table></td></tr></table></body></html>`;
}

const localizedSeeds: EmailTemplateSeed[] = seeds.flatMap((seed) => {
  const translations = localizedCopy[seed.eventKey];
  const extras: EmailTemplateSeed[] = [];
  for (const locale of ["en", "fr"] as const) {
    const copy = translations?.[locale];
    if (copy) extras.push({ eventKey: seed.eventKey, locale, subject: copy.subject, htmlBody: emailShell(locale, copy.title, copy.body), textBody: copy.text });
  }
  return [{ ...seed, htmlBody: emailShell("ar", seed.subject, seed.htmlBody.replace(/^<div[^>]*>|<\/div>$/g, "")) }, ...extras];
});

type SmtpRuntimeConfig = { host: string; port: number; user: string; pass: string; fromEmail: string; fromName?: string; secure: boolean };
async function smtpRuntimeConfig(): Promise<SmtpRuntimeConfig | null> {
  const setting = await getIntegrationSetting("platform", "SMTP") ?? await getIntegrationSetting("platform", "smtp");
  if (setting?.status === "configured") {
    let meta: Record<string, unknown> = {};
    let secret: Record<string, unknown> = {};
    try { const parsed = setting.keyReference ? JSON.parse(setting.keyReference) : {}; if (parsed && typeof parsed === "object") meta = parsed as Record<string, unknown>; } catch {}
    try { const raw = setting.secretCiphertext ? decryptIntegrationSecret(setting.secretCiphertext) : ""; const parsed = raw ? JSON.parse(raw) : {}; if (parsed && typeof parsed === "object") secret = parsed as Record<string, unknown>; else if (raw) secret.password = raw; } catch { try { if (setting.secretCiphertext) secret.password = decryptIntegrationSecret(setting.secretCiphertext); } catch {} }
    const host = String(meta.host ?? "").trim(); const user = String(meta.username ?? meta.user ?? "").trim(); const pass = String(secret.password ?? secret.pass ?? "").trim(); const port = Number(meta.port ?? 587);
    if (host && user && pass && Number.isFinite(port)) return { host, port, user, pass, fromEmail: String(meta.fromEmail ?? user).trim() || user, fromName: String(meta.fromName ?? "NFOOD").trim() || "NFOOD", secure: meta.secure === true || String(meta.encryption ?? "").toLowerCase() === "ssl" || port === 465 };
  }
  const host = process.env.SMTP_HOST || process.env.MAIL_HOST; const user = process.env.SMTP_USER || process.env.MAIL_USERNAME; const pass = process.env.SMTP_PASSWORD || process.env.MAIL_PASSWORD;
  if (!host || !user || !pass) return null; const port = Number(process.env.SMTP_PORT || process.env.MAIL_PORT || 587);
  return { host, port, user, pass, fromEmail: process.env.SMTP_FROM_EMAIL || process.env.MAIL_FROM_ADDRESS || user, fromName: process.env.MAIL_FROM_NAME || "NFOOD", secure: port === 465 };
}
async function transporter() { const config = await smtpRuntimeConfig(); if (!config) return null; return { mailer: nodemailer.createTransport({ host: config.host, port: config.port, secure: config.secure, requireTLS: config.port === 587, auth: { user: config.user, pass: config.pass }, connectionTimeout: 15_000, greetingTimeout: 15_000, socketTimeout: 20_000 }), config }; }
function escape(value: unknown) { return String(value ?? "").replace(/[&<>\"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#039;" })[character] ?? character); }
export function renderEmailTemplate(template: string, data: Record<string, unknown>) { return template.replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g, (_, key: string) => escape(data[key])); }

export function getDefaultEmailTemplates() { return localizedSeeds.map((seed) => ({ ...seed, isEnabled: true, source: "default" as const })); }
export async function listEffectiveEmailTemplates(restaurantId: number) {
  const db = await getDb();
  if (!db) return getDefaultEmailTemplates();
  const rows = await db.select().from(emailTemplates).where(and(eq(emailTemplates.restaurantId, restaurantId), eq(emailTemplates.scope, "restaurant")));
  const byKey = new Map(rows.map((row) => [`${row.eventKey}:${row.locale}`, row]));
  return localizedSeeds.map((seed) => byKey.get(`${seed.eventKey}:${seed.locale}`) ?? { ...seed, isEnabled: true, source: "default" as const });
}
export async function getEffectiveEmailTemplate(input: { restaurantId?: number | null; eventKey: EmailEventKey; locale?: EmailLocale }) {
  const locale = input.locale ?? "ar";
  const db = await getDb();
  if (db && input.restaurantId) {
    const row = (await db.select().from(emailTemplates).where(and(eq(emailTemplates.restaurantId, input.restaurantId), eq(emailTemplates.scope, "restaurant"), eq(emailTemplates.eventKey, input.eventKey), eq(emailTemplates.locale, locale), eq(emailTemplates.isEnabled, true))).limit(1))[0];
    if (row) return row;
  }
  return localizedSeeds.find((seed) => seed.eventKey === input.eventKey && seed.locale === locale) ?? localizedSeeds.find((seed) => seed.eventKey === input.eventKey && seed.locale === "ar") ?? null;
}
export async function sendTemplatedEmail(input: { to?: string | null; restaurantId?: number | null; eventKey: EmailEventKey; locale?: EmailLocale; data: Record<string, unknown> }) {
  if (!input.to) return { sent: false as const, skipped: "no-recipient" as const };
  const transport = await transporter();
  if (!transport) return { sent: false as const, skipped: "smtp-not-configured" as const };
  const template = await getEffectiveEmailTemplate(input);
  if (!template || ("isEnabled" in template && template.isEnabled === false)) return { sent: false as const, skipped: "template-disabled" as const };
  try {
    const info = await transport.mailer.sendMail({ from: transport.config.fromName ? `"${transport.config.fromName.replace(/"/g, "")}" <${transport.config.fromEmail}>` : transport.config.fromEmail, to: input.to, subject: renderEmailTemplate(template.subject, input.data), text: renderEmailTemplate(template.textBody, input.data), html: renderEmailTemplate(template.htmlBody, input.data) });
    console.info("[Email] delivered", { eventKey: input.eventKey, recipientDomain: input.to.split("@")[1] ?? "unknown", messageId: info.messageId });
    return { sent: true as const };
  } catch (error) {
    console.error("[Email] delivery failed", { eventKey: input.eventKey, recipientDomain: input.to.split("@")[1] ?? "unknown", error: error instanceof Error ? error.message : String(error) });
    return { sent: false as const, skipped: "delivery-failed" as const };
  }
}
export { localizedSeeds as emailTemplateSeeds };
