import nodemailer from "nodemailer";

export type ReceiptLocale = "ar" | "en" | "fr";
export type ReceiptMessageTemplate = { subject?: string; header?: string; footer?: string };
export type ReceiptMessageTemplates = Record<ReceiptLocale, ReceiptMessageTemplate>;
export const defaultReceiptMessageTemplates: ReceiptMessageTemplates = {
  ar: { subject: "إيصال طلبك #{{orderId}} من {{restaurantName}}", header: "", footer: "شكراً لزيارتكم" },
  en: { subject: "Your receipt #{{orderId}} from {{restaurantName}}", header: "", footer: "Thank you for visiting us" },
  fr: { subject: "Votre reçu n°{{orderId}} de {{restaurantName}}", header: "", footer: "Merci de votre visite" },
};

export function resolveReceiptLocale(value?: string | null): ReceiptLocale { const code = (value || "ar").toLowerCase().split("-")[0]; return code === "en" || code === "fr" ? code : "ar"; }
export function parseReceiptMessageTemplates(raw?: string | null): ReceiptMessageTemplates { const result = JSON.parse(JSON.stringify(defaultReceiptMessageTemplates)) as ReceiptMessageTemplates; if (!raw) return result; try { const parsed = JSON.parse(raw) as Partial<Record<ReceiptLocale, ReceiptMessageTemplate>>; for (const locale of ["ar", "en", "fr"] as const) { const value = parsed[locale]; if (value && typeof value === "object") result[locale] = { ...result[locale], subject: typeof value.subject === "string" ? value.subject : result[locale].subject, header: typeof value.header === "string" ? value.header : result[locale].header, footer: typeof value.footer === "string" ? value.footer : result[locale].footer }; } } catch { /* fallback to defaults */ } return result; }
function interpolate(value: string, input: { orderId: number; restaurantName: string }) { return value.replace(/\{\{\s*(orderId|restaurantName)\s*\}\}/g, (_, key: "orderId" | "restaurantName") => String(input[key])); }
export function formatReceiptSubject(input: { orderId: number; restaurantName: string; locale?: ReceiptLocale; template?: ReceiptMessageTemplate }) { const locale = input.locale ?? "ar"; const fallback = defaultReceiptMessageTemplates[locale].subject!; return interpolate(input.template?.subject?.trim() || fallback, input); }

export type ReceiptDeliveryItem = { name: string; quantity: number; unitPrice: string | number };
export type ReceiptDeliveryPayload = { orderId: number; restaurantName: string; currency: string; items: ReceiptDeliveryItem[]; subtotal: string | number; discountAmount: string | number; discountPercent: string | number; taxAmount: string | number; taxPercent: string | number; total: string | number; locale?: ReceiptLocale; messageTemplate?: ReceiptMessageTemplate; headerText?: string | null; footerText?: string | null; logoUrl?: string | null };

type ReceiptCopy = { receipt: string; beforeDiscount: string; discount: string; tax: string; finalTotal: string; thankYou: string };
const copy: Record<ReceiptLocale, ReceiptCopy> = { ar: { receipt: "إيصال الطلب", beforeDiscount: "المجموع قبل الخصم", discount: "الخصم", tax: "الضريبة", finalTotal: "الإجمالي النهائي", thankYou: "شكراً لزيارتكم" }, en: { receipt: "Order receipt", beforeDiscount: "Subtotal", discount: "Discount", tax: "Tax", finalTotal: "Final total", thankYou: "Thank you for visiting us" }, fr: { receipt: "Reçu de commande", beforeDiscount: "Sous-total", discount: "Remise", tax: "Taxe", finalTotal: "Total final", thankYou: "Merci de votre visite" } };
function localizedTemplate(input: ReceiptDeliveryPayload) { const locale = input.locale ?? "ar"; const template = input.messageTemplate ?? {}; return { locale, header: template.header?.trim() || input.headerText?.trim() || input.restaurantName, footer: template.footer?.trim() || input.footerText?.trim() || copy[locale].thankYou }; }

export function formatReceiptDeliveryText(input: ReceiptDeliveryPayload) { const { locale, header, footer } = localizedTemplate(input); const labels = copy[locale]; const lines = [header, `${labels.receipt} #${input.orderId}`, "------------------------------", ...input.items.map((item) => `${item.name} × ${item.quantity}  ${Number(item.unitPrice) * item.quantity} ${input.currency}`), "------------------------------", `${labels.beforeDiscount}: ${input.subtotal} ${input.currency}`, `${labels.discount} (${input.discountPercent}%): -${input.discountAmount} ${input.currency}`, `${labels.tax} (${input.taxPercent}%): ${input.taxAmount} ${input.currency}`, `${labels.finalTotal}: ${input.total} ${input.currency}`, footer]; return lines.join("\n"); }
function escapeHtml(value: string) { return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character] ?? character); }
export function formatReceiptDeliveryHtml(input: ReceiptDeliveryPayload) { const { locale, header, footer } = localizedTemplate(input); const labels = copy[locale]; const logo = input.logoUrl && /^https?:\/\//i.test(input.logoUrl) ? `<img src="${escapeHtml(input.logoUrl)}" alt="${escapeHtml(input.restaurantName)}" style="max-width:140px;max-height:80px;object-fit:contain;margin-bottom:12px" />` : ""; const rows = input.items.map((item) => `<tr><td style="padding:7px 0;border-bottom:1px solid #eee">${escapeHtml(item.name)} × ${item.quantity}</td><td style="padding:7px 0;border-bottom:1px solid #eee;text-align:left">${escapeHtml(String(Number(item.unitPrice) * item.quantity))} ${escapeHtml(input.currency)}</td></tr>`).join(""); return `<div dir="${locale === "ar" ? "rtl" : "ltr"}" style="font-family:Arial,sans-serif;max-width:560px;margin:auto;color:#172033;line-height:1.7">${logo}<h2 style="margin:0 0 4px">${escapeHtml(header)}</h2><p style="margin:0 0 16px;color:#64748b">${escapeHtml(labels.receipt)} #${input.orderId}</p><table style="width:100%;border-collapse:collapse">${rows}</table><div style="margin-top:16px;border-top:1px solid #e2e8f0;padding-top:12px"><p>${escapeHtml(labels.beforeDiscount)}: <strong>${escapeHtml(String(input.subtotal))} ${escapeHtml(input.currency)}</strong></p><p style="color:#b45309">${escapeHtml(labels.discount)} (${escapeHtml(String(input.discountPercent))}%): <strong>-${escapeHtml(String(input.discountAmount))} ${escapeHtml(input.currency)}</strong></p><p>${escapeHtml(labels.tax)} (${escapeHtml(String(input.taxPercent))}%): <strong>${escapeHtml(String(input.taxAmount))} ${escapeHtml(input.currency)}</strong></p><p style="font-size:18px;border-top:1px solid #e2e8f0;padding-top:10px"><strong>${escapeHtml(labels.finalTotal)}: ${escapeHtml(String(input.total))} ${escapeHtml(input.currency)}</strong></p></div><p style="margin-top:22px;color:#64748b">${escapeHtml(footer)}</p></div>`; }

type SmtpConfig = { host: string; port: number; user: string; pass: string; from?: string; secure?: boolean };
export function parseSmtpConfig(secret?: string | null): SmtpConfig | null { if (!secret) return null; try { const parsed = JSON.parse(secret) as Partial<SmtpConfig>; if (typeof parsed.host === "string" && parsed.host && typeof parsed.user === "string" && parsed.user && typeof parsed.pass === "string" && parsed.pass) return { host: parsed.host, port: Number(parsed.port || 587), user: parsed.user, pass: parsed.pass, from: parsed.from, secure: parsed.secure }; } catch { return null; } return null; }
function getTransporter(secret?: string | null) { const custom = parseSmtpConfig(secret); const host = custom?.host || process.env.SMTP_HOST; const port = custom?.port || Number(process.env.SMTP_PORT || 587); const user = custom?.user || process.env.SMTP_USER; const pass = custom?.pass || process.env.SMTP_PASSWORD; if (!host || !user || !pass) return null; return { transporter: nodemailer.createTransport({ host, port, secure: custom?.secure ?? port === 465, auth: { user, pass } }), from: custom?.from || process.env.SMTP_FROM_EMAIL || user }; }
export async function sendReceiptEmail(input: { to: string; receipt: ReceiptDeliveryPayload; secret?: string | null }) { const connection = getTransporter(input.secret); if (!connection) return { sent: false as const, skipped: "smtp-not-configured" as const }; const { transporter, from } = connection; if (!transporter) return { sent: false as const, skipped: "smtp-not-configured" as const }; await transporter.sendMail({ from, to: input.to, subject: formatReceiptSubject({ orderId: input.receipt.orderId, restaurantName: input.receipt.restaurantName, locale: input.receipt.locale, template: input.receipt.messageTemplate }), text: formatReceiptDeliveryText(input.receipt), html: formatReceiptDeliveryHtml(input.receipt) }); return { sent: true as const }; }

type SmsConfig = { accountSid: string; authToken: string; from: string; apiUrl?: string };
export function parseTwilioSmsConfig(secret?: string | null, fallbackFrom?: string | null): SmsConfig | null { if (!secret) return null; try { const parsed = JSON.parse(secret) as Partial<SmsConfig>; if (parsed.accountSid && parsed.authToken && (parsed.from || fallbackFrom)) return { accountSid: parsed.accountSid, authToken: parsed.authToken, from: parsed.from || fallbackFrom!, apiUrl: parsed.apiUrl }; } catch { return null; } return null; }
export function buildTwilioSmsRequest(input: { to: string; body: string; config: SmsConfig }) { const apiUrl = input.config.apiUrl || `https://api.twilio.com/2010-04-01/Accounts/${encodeURIComponent(input.config.accountSid)}/Messages.json`; const body = new URLSearchParams({ To: input.to, From: input.config.from, Body: input.body }); const authorization = Buffer.from(`${input.config.accountSid}:${input.config.authToken}`).toString("base64"); return { apiUrl, body, headers: { Authorization: `Basic ${authorization}`, "Content-Type": "application/x-www-form-urlencoded" } }; }
export async function sendReceiptSms(input: { to: string; receipt: ReceiptDeliveryPayload; secret?: string | null; from?: string | null }) { const config = parseTwilioSmsConfig(input.secret, input.from); if (!config) return { sent: false as const, skipped: "sms-not-configured" as const }; const request = buildTwilioSmsRequest({ to: input.to, body: formatReceiptDeliveryText(input.receipt), config }); const response = await fetch(request.apiUrl, { method: "POST", headers: request.headers, body: request.body }); if (!response.ok) { const detail = await response.text().catch(() => ""); throw new Error(`SMS provider rejected the request (${response.status})${detail ? `: ${detail.slice(0, 180)}` : ""}`); } return { sent: true as const }; }
