import { z } from "zod";
import { COOKIE_NAME, TEST_SESSION_COOKIE } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, protectedProcedure, testRoleProcedure, adminProcedure, router } from "./_core/trpc";
import { branches, orders, orderItems, inventoryItems, employees, attendance, remoteWorkers, restaurants, users, subscriptions, roles, rolePermissions, permissions, menuCategories, menuItems, purchases, restaurantTables, campaigns, reservations, remoteTasks, remoteWorkerApplications, taskMessages, notifications, pushSubscriptions, testAccounts, authSessions, userSecurity, restaurantFeatures, featureDefinitions } from "../drizzle/schema";
import { getDb, getRestaurantById, getRestaurantByBarcode, listBranches, listEmployees, listInventory, listMenuCategories, listMenuItems, listOrders, listOrdersByRestaurant, listRestaurants, listSubscriptions, listRoles, listPermissions, listTables, listPurchases, listAttendance, listCampaigns, listCoupons, listRemoteWorkers, listRemoteTasks, listTaskMessages, listNotifications, getTestAccountByEmail, listAuthSessions, upsertUser, getUserByOpenId, listFeatureDefinitions, listRestaurantFeatures, getUserSecurity, getFeatureAccess, insertAuditLog, listAuditLogs, globalSearch, getRoleSummary, getPublicRestaurantPage, listRestaurantsWithBranchCount } from "./db";
import { and, eq, inArray } from "drizzle-orm";
import { TRPCError } from "@trpc/server";
import { nanoid } from "nanoid";
import { sendPushToUser } from "./push";
import { createHash, scryptSync, timingSafeEqual } from "node:crypto";
import { sdk } from "./_core/sdk";

function isAdminContext(ctx: { user: { role?: string; testRole?: string } | null }): boolean { return ctx.user?.role === "admin" || ctx.user?.testRole === "restaurant_admin"; }
function assertRestaurantAccess(ctx: { user: { role?: string; testRole?: string } | null }, restaurantId: number) {
  if (isAdminContext(ctx)) return;
  if (ctx.user?.testRole && restaurantId !== 1) throw new TRPCError({ code: "FORBIDDEN", message: "لا تملك صلاحية الوصول إلى هذا المطعم" });
}

export function getTaskNotificationRecipient(task: { createdByUserId: number; assignedWorkerUserId?: number | null }, actorUserId: number) { return actorUserId === task.createdByUserId ? task.assignedWorkerUserId ?? actorUserId : task.createdByUserId; }

export function assertRemoteTaskTransition(current: string, next: string, isAdmin: boolean) {
  const allowed: Record<string, string[]> = { published: ["reviewing", "cancelled"], reviewing: ["accepted", "cancelled"], accepted: ["in_progress", "cancelled"], in_progress: ["submitted", "cancelled"], submitted: ["completed", "cancelled"] };
  if (current === "completed" || current === "cancelled" || !allowed[current]?.includes(next)) throw new TRPCError({ code: "BAD_REQUEST", message: "انتقال حالة المهمة غير مسموح" });
}

async function getRemoteTaskAccess(ctx: { user: { id: number; testRole?: string } | null }, taskId: number) {
  if (!ctx.user) throw new TRPCError({ code: "UNAUTHORIZED", message: "يجب تسجيل الدخول" });
  const db = await getDb();
  if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" });
  const task = (await db.select().from(remoteTasks).where(eq(remoteTasks.id, taskId)).limit(1))[0];
  if (!task) throw new TRPCError({ code: "NOT_FOUND", message: "المهمة غير موجودة" });
  assertRestaurantAccess(ctx, task.restaurantId);
  const worker = (await db.select().from(remoteWorkers).where(and(eq(remoteWorkers.userId, ctx.user.id), eq(remoteWorkers.restaurantId, task.restaurantId))).limit(1))[0];
  if (!isAdminContext(ctx) && (!worker || (task.assignedWorkerId !== null && task.assignedWorkerId !== worker.id))) throw new TRPCError({ code: "FORBIDDEN", message: "لا تملك هذه المهمة" });
  return { db, task, worker };
}

export const appRouter = router({
  system: systemRouter,
  auth: router({
    testLogin: publicProcedure.input(z.object({ email: z.string().email(), password: z.string().min(1) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const hash = "scrypt$Ke89BlsJJa45L/5mz+r4yg==$7H6Z0FmUuzmpJS8AvEW4zw/z2mYsvIdhEF9ZDJBj6NmHJEzW9g1iz8GUdipDUe+PI60ecQJajl9NmtX4kSiVxg=="; const seeds = [{ email: "nfood@ret.com", displayName: "أدمن مطعم NFOOD", role: "restaurant_admin" }, { email: "nfood.waiter@ret.com", displayName: "نادل NFOOD", role: "waiter" }, { email: "nfood.kitchen@ret.com", displayName: "مطبخ NFOOD", role: "kitchen" }, { email: "nfood.cashier@ret.com", displayName: "كاشير NFOOD", role: "cashier" }, { email: "nfood.client@ret.com", displayName: "عميل NFOOD", role: "customer" }, { email: "nfood.driver@ret.com", displayName: "سائق NFOOD", role: "driver" }] as const; for (const seed of seeds) await db.insert(testAccounts).values({ ...seed, passwordHash: hash }).onDuplicateKeyUpdate({ set: { displayName: seed.displayName, role: seed.role, passwordHash: hash } }); const account = await getTestAccountByEmail(input.email); if (!account) throw new TRPCError({ code: "UNAUTHORIZED", message: "بيانات الدخول غير صحيحة" }); const [scheme, salt, storedKey] = account.passwordHash.split("$"); const derivedKey = scryptSync(input.password, Buffer.from(salt, "base64"), 64); if (scheme !== "scrypt" || !timingSafeEqual(derivedKey, Buffer.from(storedKey, "base64"))) throw new TRPCError({ code: "UNAUTHORIZED", message: "بيانات الدخول غير صحيحة" }); await upsertUser({ openId: `test_${account.id}`, name: account.displayName, email: account.email, loginMethod: "test" }); const sessionUser = await getUserByOpenId(`test_${account.id}`); const token = await sdk.signSession({ openId: `test_${account.id}`, appId: `test_${nanoid(12)}`, name: account.displayName }); if (sessionUser) await db.insert(authSessions).values({ userId: sessionUser.id, sessionTokenHash: createHash("sha256").update(token).digest("hex"), deviceLabel: "حساب اختبار", userAgent: ctx.req.get("user-agent") ?? null, ipAddress: ctx.req.ip ?? null, expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 12) }); ctx.res.cookie(TEST_SESSION_COOKIE, token, { httpOnly: true, sameSite: "lax", secure: true, path: "/", maxAge: 1000 * 60 * 60 * 12 }); return { success: true, role: account.role, name: account.displayName }; }),
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 });
      ctx.res.clearCookie(TEST_SESSION_COOKIE, { ...cookieOptions, maxAge: -1 });
      return { success: true } as const;
    }),
  }),
  platform: router({
    publicRestaurantPage: publicProcedure.input(z.object({ slug: z.string().min(2).max(160).regex(/^[a-z0-9-]+$/) })).query(async ({ input }) => { const page = await getPublicRestaurantPage(input.slug); if (!page) throw new TRPCError({ code: "NOT_FOUND", message: "المطعم غير متاح" }); return page; }),
    restaurants: protectedProcedure.query(({ ctx }) => isAdminContext(ctx) ? listRestaurants() : listRestaurants(1)),
    restaurantById: protectedProcedure.input(z.object({ id: z.number().int().positive() })).query(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.id); const restaurant = await getRestaurantById(input.id); if (!restaurant) throw new TRPCError({ code: "NOT_FOUND", message: "المطعم غير موجود" }); return restaurant; }),
    branding: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const restaurant = await getRestaurantById(input.restaurantId); if (!restaurant) throw new TRPCError({ code: "NOT_FOUND", message: "Restaurant not found" }); return { restaurantId: restaurant.id, slug: restaurant.slug, brandName: restaurant.brandName ?? restaurant.name, brandColor: restaurant.brandColor ?? "#e76f3c", brandLogoUrl: restaurant.brandLogoUrl ?? "", brandDescription: restaurant.brandDescription ?? "" }; }),
    updateBranding: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), brandName: z.string().min(2).max(160), brandColor: z.string().regex(/^#[0-9A-Fa-f]{6}$/), brandLogoUrl: z.string().url().max(500).or(z.literal("")), brandDescription: z.string().max(1000) })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); await db.update(restaurants).set({ brandName: input.brandName.trim(), brandColor: input.brandColor, brandLogoUrl: input.brandLogoUrl || null, brandDescription: input.brandDescription.trim() || null }).where(eq(restaurants.id, input.restaurantId)); return { success: true, restaurantId: input.restaurantId }; }),
    restaurantByBarcode: protectedProcedure.input(z.object({ barcode: z.string().min(6).max(64) })).query(async ({ ctx, input }) => { const restaurant = await getRestaurantByBarcode(input.barcode); if (!restaurant) throw new TRPCError({ code: "NOT_FOUND", message: "المطعم غير موجود" }); assertRestaurantAccess(ctx, restaurant.id); return restaurant; }),
    branches: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listBranches(input.restaurantId); }),
    restaurantRoles: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listRoles(input.restaurantId); }),
    restaurantPermissions: testRoleProcedure("restaurant_admin").query(() => listPermissions()),
    createRestaurantRole: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), name: z.string().min(2).max(80) })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(roles).values({ restaurantId: input.restaurantId, name: input.name.trim(), scope: "restaurant" }); return { success: true, id: Number(result[0].insertId) }; }),
    updateRestaurantRole: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), name: z.string().min(2).max(80) })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: roles.restaurantId }).from(roles).where(eq(roles.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Role belongs to another restaurant" }); await db.update(roles).set({ name: input.name.trim() }).where(eq(roles.id, input.id)); return { success: true, id: input.id }; }),
    deleteRestaurantRole: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: roles.restaurantId }).from(roles).where(eq(roles.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Role belongs to another restaurant" }); await db.delete(rolePermissions).where(eq(rolePermissions.roleId, input.id)); await db.delete(roles).where(eq(roles.id, input.id)); return { success: true, id: input.id }; }),
    restaurantRolePermissions: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), roleId: z.number().int().positive() })).query(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const role = await db.select({ restaurantId: roles.restaurantId }).from(roles).where(eq(roles.id, input.roleId)).limit(1); if (!role[0] || role[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Role belongs to another restaurant" }); return db.select({ permissionId: permissions.id, key: permissions.key, label: permissions.label }).from(rolePermissions).innerJoin(permissions, eq(rolePermissions.permissionId, permissions.id)).where(eq(rolePermissions.roleId, input.roleId)); }),
    setRestaurantRolePermissions: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), roleId: z.number().int().positive(), permissionIds: z.array(z.number().int().positive()).max(500) })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const role = await db.select({ restaurantId: roles.restaurantId }).from(roles).where(eq(roles.id, input.roleId)).limit(1); if (!role[0] || role[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Role belongs to another restaurant" }); const uniquePermissionIds = Array.from(new Set(input.permissionIds)); if (uniquePermissionIds.length) { const existingPermissions = await db.select({ id: permissions.id }).from(permissions).where(inArray(permissions.id, uniquePermissionIds)); if (existingPermissions.length !== uniquePermissionIds.length) throw new TRPCError({ code: "BAD_REQUEST", message: "يوجد معرف صلاحية غير صالح" }); } await db.delete(rolePermissions).where(eq(rolePermissions.roleId, input.roleId)); if (uniquePermissionIds.length) await db.insert(rolePermissions).values(uniquePermissionIds.map((permissionId) => ({ roleId: input.roleId, permissionId }))); return { success: true, roleId: input.roleId, permissionIds: uniquePermissionIds }; }),
    tables: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) return []; return db.select({ id: restaurantTables.id, branchId: restaurantTables.branchId, name: restaurantTables.name, seats: restaurantTables.seats, status: restaurantTables.status }).from(restaurantTables).innerJoin(branches, eq(restaurantTables.branchId, branches.id)).where(eq(branches.restaurantId, input.restaurantId)); }),
    menuCategories: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listMenuCategories(input.restaurantId); }),
    createMenuCategory: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), name: z.string().min(2), sortOrder: z.number().int().nonnegative().default(0) })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(menuCategories).values(input); return { success: true, id: Number(result[0].insertId) }; }),
    updateMenuCategory: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), name: z.string().min(2).optional(), sortOrder: z.number().int().nonnegative().optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: menuCategories.restaurantId }).from(menuCategories).where(eq(menuCategories.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Category belongs to another restaurant" }); const { id: _id, restaurantId: _restaurantId, ...changes } = input; await db.update(menuCategories).set(changes).where(eq(menuCategories.id, input.id)); return { success: true, id: input.id }; }),
    deleteMenuCategory: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: menuCategories.restaurantId }).from(menuCategories).where(eq(menuCategories.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Category belongs to another restaurant" }); await db.delete(menuCategories).where(eq(menuCategories.id, input.id)); return { success: true, id: input.id }; }),
    menuItems: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive().optional(), categoryId: z.number().int().positive().optional() }).optional()).query(({ ctx, input }) => { const restaurantId = input?.restaurantId; if (!restaurantId && !isAdminContext(ctx)) throw new TRPCError({ code: "FORBIDDEN", message: "Restaurant scope is required" }); if (restaurantId) assertRestaurantAccess(ctx, restaurantId); return listMenuItems(restaurantId, input?.categoryId); }),
    orders: protectedProcedure.input(z.object({ branchId: z.number().int().positive(), restaurantId: z.number().int().positive().optional() })).query(({ ctx, input }) => { const restaurantId = input.restaurantId; if (!restaurantId && !isAdminContext(ctx)) throw new TRPCError({ code: "FORBIDDEN", message: "Restaurant scope is required" }); if (restaurantId) assertRestaurantAccess(ctx, restaurantId); return listOrders(input.branchId, restaurantId); }),
    ordersByRestaurant: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listOrdersByRestaurant(input.restaurantId); }),
    inventory: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listInventory(input.restaurantId); }),
    employees: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listEmployees(input.restaurantId); }),
    tablesByBranch: protectedProcedure.input(z.object({ branchId: z.number().int().positive(), restaurantId: z.number().int().positive().optional() })).query(({ ctx, input }) => { const restaurantId = input.restaurantId; if (!restaurantId && !isAdminContext(ctx)) throw new TRPCError({ code: "FORBIDDEN", message: "Restaurant scope is required" }); if (restaurantId) assertRestaurantAccess(ctx, restaurantId); return listTables(input.branchId, restaurantId); }),
    purchases: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listPurchases(input.restaurantId); }),
    attendance: protectedProcedure.input(z.object({ employeeId: z.number().int().positive().optional(), restaurantId: z.number().int().positive().optional() }).optional()).query(({ ctx, input }) => { const restaurantId = input?.restaurantId; if (!restaurantId && !isAdminContext(ctx)) throw new TRPCError({ code: "FORBIDDEN", message: "Restaurant scope is required" }); if (restaurantId) assertRestaurantAccess(ctx, restaurantId); return listAttendance(input?.employeeId, restaurantId); }),
    attendanceByRestaurant: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive(), workDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional() })).query(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const rows = await db.select({ id: attendance.id, employeeId: attendance.employeeId, workDate: attendance.workDate, status: attendance.status, employeeName: employees.name }).from(attendance).innerJoin(employees, eq(attendance.employeeId, employees.id)).where(input.workDate ? and(eq(employees.restaurantId, input.restaurantId), eq(attendance.workDate, input.workDate)) : eq(employees.restaurantId, input.restaurantId)); return rows; }),
    reservations: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive(), kind: z.enum(["reservation", "waitlist"]).optional(), status: z.enum(["pending", "confirmed", "seated", "completed", "cancelled", "no_show"]).optional() })).query(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const filters = [eq(reservations.restaurantId, input.restaurantId)]; if (input.kind) filters.push(eq(reservations.kind, input.kind)); if (input.status) filters.push(eq(reservations.status, input.status)); return db.select().from(reservations).where(and(...filters)); }),
    createReservation: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive(), branchId: z.number().int().positive().nullable().optional(), kind: z.enum(["reservation", "waitlist"]).default("reservation"), customerName: z.string().trim().min(2).max(160), phone: z.string().trim().max(40).optional(), partySize: z.number().int().min(1).max(50), reservedFor: z.coerce.date(), notes: z.string().trim().max(1000).optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); if (!isAdminContext(ctx) && ctx.user?.testRole !== "waiter") throw new TRPCError({ code: "FORBIDDEN", message: "لا تملك صلاحية إنشاء حجز" }); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); if (input.branchId) { const branch = (await db.select({ restaurantId: branches.restaurantId }).from(branches).where(eq(branches.id, input.branchId)).limit(1))[0]; if (!branch || branch.restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Branch belongs to another restaurant" }); } const result = await db.insert(reservations).values({ ...input, createdByUserId: ctx.user?.id ?? null }); return { success: true, id: Number(result[0].insertId) }; }),
    updateReservationStatus: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), status: z.enum(["pending", "confirmed", "seated", "completed", "cancelled", "no_show"]) })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); if (!isAdminContext(ctx) && ctx.user?.testRole !== "waiter") throw new TRPCError({ code: "FORBIDDEN", message: "لا تملك صلاحية تحديث الحجز" }); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const existing = (await db.select().from(reservations).where(and(eq(reservations.id, input.id), eq(reservations.restaurantId, input.restaurantId))).limit(1))[0]; if (!existing) throw new TRPCError({ code: "NOT_FOUND", message: "الحجز غير موجود" }); await db.update(reservations).set({ status: input.status }).where(eq(reservations.id, input.id)); return { success: true }; }),
    campaigns: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listCampaigns(input.restaurantId); }),
    coupons: protectedProcedure.input(z.object({ campaignId: z.number().int().positive().optional(), restaurantId: z.number().int().positive().optional() }).optional()).query(({ ctx, input }) => { const restaurantId = input?.restaurantId; if (!restaurantId && !isAdminContext(ctx)) throw new TRPCError({ code: "FORBIDDEN", message: "Restaurant scope is required" }); if (restaurantId) assertRestaurantAccess(ctx, restaurantId); return listCoupons(input?.campaignId, restaurantId); }),
    auditLogs: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive().optional() }).optional()).query(({ ctx, input }) => { const restaurantId = input?.restaurantId; if (!restaurantId && !isAdminContext(ctx)) throw new TRPCError({ code: "FORBIDDEN", message: "Restaurant scope is required" }); if (restaurantId) assertRestaurantAccess(ctx, restaurantId); return listAuditLogs(restaurantId); }),
    globalSearch: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive(), query: z.string().max(120), limit: z.number().int().positive().max(50).default(20) })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return globalSearch(input.restaurantId, input.query, input.limit); }),
    roleSummary: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return getRoleSummary(input.restaurantId, ctx.user?.testRole, ctx.user?.id); }),
    createBranch: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), name: z.string().min(2), city: z.string().max(120).optional(), status: z.enum(["open", "closed"]).default("open"), openingTime: z.string().regex(/^\d{2}:\d{2}$/).optional(), closingTime: z.string().regex(/^\d{2}:\d{2}$/).optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(branches).values(input); return { success: true, id: Number(result[0].insertId) }; }),
    updateBranch: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), name: z.string().min(2).max(160).optional(), city: z.string().max(120).optional(), status: z.enum(["open", "closed"]).optional(), openingTime: z.string().regex(/^\d{2}:\d{2}$/).optional(), closingTime: z.string().regex(/^\d{2}:\d{2}$/).optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: branches.restaurantId }).from(branches).where(eq(branches.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Branch belongs to another restaurant" }); const { id: _id, restaurantId: _restaurantId, ...changes } = input; await db.update(branches).set(changes).where(eq(branches.id, input.id)); return { success: true, id: input.id }; }),
    deleteBranch: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: branches.restaurantId }).from(branches).where(eq(branches.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Branch belongs to another restaurant" }); await db.delete(branches).where(eq(branches.id, input.id)); return { success: true, id: input.id }; }),
    createMenuItem: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), categoryId: z.number().int().positive(), name: z.string().min(2), price: z.string(), description: z.string().optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const category = await db.select({ id: menuCategories.id }).from(menuCategories).where(and(eq(menuCategories.id, input.categoryId), eq(menuCategories.restaurantId, input.restaurantId))).limit(1); if (!category[0]) throw new TRPCError({ code: "FORBIDDEN", message: "التصنيف غير مرتبط بالمطعم" }); const result = await db.insert(menuItems).values({ ...input, description: input.description ?? null }); return { success: true, id: Number(result[0].insertId) }; }),
    updateMenuItem: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), name: z.string().min(2).optional(), price: z.string().optional(), isAvailable: z.boolean().optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: menuItems.restaurantId }).from(menuItems).where(eq(menuItems.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Menu item belongs to another restaurant" }); const { id: _id, restaurantId: _restaurantId, ...changes } = input; await db.update(menuItems).set(changes).where(eq(menuItems.id, input.id)); return { success: true, id: input.id }; }),
    deleteMenuItem: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: menuItems.restaurantId }).from(menuItems).where(eq(menuItems.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Menu item belongs to another restaurant" }); await db.delete(menuItems).where(eq(menuItems.id, input.id)); return { success: true, id: input.id }; }),
    createInventoryItem: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), name: z.string().min(2).max(160), unit: z.string().min(1).max(32), quantity: z.string().regex(/^\d+(\.\d{1,2})?$/).default("0"), minimumQuantity: z.string().regex(/^\d+(\.\d{1,2})?$/).default("0") })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(inventoryItems).values(input); return { success: true, id: Number(result[0].insertId) }; }),
    updateInventoryItem: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), name: z.string().min(2).max(160).optional(), unit: z.string().min(1).max(32).optional(), quantity: z.string().regex(/^\d+(\.\d{1,2})?$/).optional(), minimumQuantity: z.string().regex(/^\d+(\.\d{1,2})?$/).optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: inventoryItems.restaurantId }).from(inventoryItems).where(eq(inventoryItems.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Inventory item belongs to another restaurant" }); const { id: _id, restaurantId: _restaurantId, ...changes } = input; await db.update(inventoryItems).set(changes).where(eq(inventoryItems.id, input.id)); return { success: true, id: input.id }; }),
    deleteInventoryItem: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: inventoryItems.restaurantId }).from(inventoryItems).where(eq(inventoryItems.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Inventory item belongs to another restaurant" }); await db.delete(inventoryItems).where(eq(inventoryItems.id, input.id)); return { success: true, id: input.id }; }),
    createPurchase: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), supplier: z.string().min(2), total: z.string().regex(/^\d+(\.\d{1,2})?$/), status: z.enum(["draft", "received", "cancelled"]).default("received") })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(purchases).values(input); return { success: true, id: Number(result[0].insertId) }; }),
    updatePurchase: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), supplier: z.string().min(2).optional(), total: z.string().regex(/^\d+(\.\d{1,2})?$/).optional(), status: z.enum(["draft", "received", "cancelled"]).optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: purchases.restaurantId }).from(purchases).where(eq(purchases.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Purchase belongs to another restaurant" }); const { id: _id, restaurantId: _restaurantId, ...changes } = input; await db.update(purchases).set(changes).where(eq(purchases.id, input.id)); return { success: true, id: input.id }; }),
    deletePurchase: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: purchases.restaurantId }).from(purchases).where(eq(purchases.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Purchase belongs to another restaurant" }); await db.delete(purchases).where(eq(purchases.id, input.id)); return { success: true, id: input.id }; }),
    createEmployee: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), name: z.string().min(2).max(160), role: z.string().min(2).max(80), status: z.enum(["active", "inactive"]).default("active") })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(employees).values(input); return { success: true, id: Number(result[0].insertId) }; }),
    updateEmployee: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), name: z.string().min(2).max(160).optional(), role: z.string().min(2).max(80).optional(), status: z.enum(["active", "inactive"]).optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: employees.restaurantId }).from(employees).where(eq(employees.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Employee belongs to another restaurant" }); const { id: _id, restaurantId: _restaurantId, ...changes } = input; await db.update(employees).set(changes).where(eq(employees.id, input.id)); return { success: true, id: input.id }; }),
    deleteEmployee: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: employees.restaurantId }).from(employees).where(eq(employees.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Employee belongs to another restaurant" }); await db.delete(employees).where(eq(employees.id, input.id)); return { success: true, id: input.id }; }),
    recordAttendance: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), employeeId: z.number().int().positive(), workDate: z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/), status: z.enum(["present", "absent", "late"]) })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const employee = (await db.select({ restaurantId: employees.restaurantId }).from(employees).where(eq(employees.id, input.employeeId)).limit(1))[0]; if (!employee || employee.restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Employee belongs to another restaurant" }); const result = await db.insert(attendance).values({ employeeId: input.employeeId, workDate: input.workDate, status: input.status }); return { success: true, id: Number(result[0].insertId) }; }),
    createTable: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), branchId: z.number().int().positive(), name: z.string().min(1).max(80), seats: z.number().int().positive().max(50).default(2), status: z.enum(["available", "occupied", "reserved"]).default("available") })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const branch = (await db.select({ restaurantId: branches.restaurantId }).from(branches).where(eq(branches.id, input.branchId)).limit(1))[0]; if (!branch || branch.restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Branch belongs to another restaurant" }); const result = await db.insert(restaurantTables).values({ branchId: input.branchId, name: input.name, seats: input.seats, status: input.status }); return { success: true, id: Number(result[0].insertId) }; }),
    updateTableStatus: testRoleProcedure("restaurant_admin", "waiter", "cashier").input(z.object({ restaurantId: z.number().int().positive(), tableId: z.number().int().positive(), status: z.enum(["available", "occupied", "reserved"]) })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = (await db.select({ tableId: restaurantTables.id, restaurantId: branches.restaurantId }).from(restaurantTables).innerJoin(branches, eq(restaurantTables.branchId, branches.id)).where(eq(restaurantTables.id, input.tableId)).limit(1))[0]; if (!existing || existing.restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Table belongs to another restaurant" }); await db.update(restaurantTables).set({ status: input.status }).where(eq(restaurantTables.id, input.tableId)); return { success: true, status: input.status }; }),
    deleteTable: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), tableId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = (await db.select({ restaurantId: branches.restaurantId }).from(restaurantTables).innerJoin(branches, eq(restaurantTables.branchId, branches.id)).where(eq(restaurantTables.id, input.tableId)).limit(1))[0]; if (!existing || existing.restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Table belongs to another restaurant" }); await db.delete(restaurantTables).where(eq(restaurantTables.id, input.tableId)); return { success: true, id: input.tableId }; }),
    createCampaign: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), name: z.string().min(2), status: z.enum(["draft", "scheduled", "active", "ended"]).default("draft") })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(campaigns).values(input); return { success: true, id: Number(result[0].insertId) }; }),
    updateCampaign: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), name: z.string().min(2).optional(), status: z.enum(["draft", "scheduled", "active", "ended"]).optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: campaigns.restaurantId }).from(campaigns).where(eq(campaigns.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Campaign belongs to another restaurant" }); const { id: _id, restaurantId: _restaurantId, ...changes } = input; await db.update(campaigns).set(changes).where(eq(campaigns.id, input.id)); return { success: true, id: input.id }; }),
    deleteCampaign: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: campaigns.restaurantId }).from(campaigns).where(eq(campaigns.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Campaign belongs to another restaurant" }); await db.delete(campaigns).where(eq(campaigns.id, input.id)); return { success: true, id: input.id }; }),
    createOrder: testRoleProcedure("restaurant_admin", "waiter", "cashier").input(z.object({ restaurantId: z.number().int().positive(), branchId: z.number().int().positive(), tableName: z.string().max(80).optional(), channel: z.enum(["dine_in", "takeaway", "delivery"]), paymentMethod: z.enum(["cash", "card", "bank_transfer", "online", "other"]).default("cash"), items: z.array(z.object({ menuItemId: z.number().int().positive(), quantity: z.number().int().positive(), unitPrice: z.string().regex(/^\d+(\.\d{1,2})?$/) })).min(1), total: z.string().regex(/^\d+(\.\d{1,2})?$/) })).mutation(    async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const branch = await db.select({ id: branches.id }).from(branches).where(and(eq(branches.id, input.branchId), eq(branches.restaurantId, input.restaurantId))).limit(1); if (!branch[0]) throw new TRPCError({ code: "FORBIDDEN", message: "الفرع غير مرتبط بالمطعم" }); const menuIds = Array.from(new Set(input.items.map((item) => item.menuItemId))); const ownedItems = await db.select({ id: menuItems.id }).from(menuItems).where(and(eq(menuItems.restaurantId, input.restaurantId), inArray(menuItems.id, menuIds))); if (ownedItems.length !== menuIds.length) throw new TRPCError({ code: "FORBIDDEN", message: "يوجد صنف غير مرتبط بالمطعم" }); return db.transaction(async (tx) => { const [orderResult] = await tx.insert(orders).values({ restaurantId: input.restaurantId, branchId: input.branchId, tableName: input.tableName ?? null, channel: input.channel, paymentMethod: input.paymentMethod, paymentStatus: "unpaid", total: input.total, status: "new" }); const orderId = Number(orderResult.insertId); const rows = input.items.map((item) => ({ orderId, menuItemId: item.menuItemId, quantity: item.quantity, unitPrice: item.unitPrice })); await tx.insert(orderItems).values(rows); await insertAuditLog({ restaurantId: input.restaurantId, branchId: input.branchId, actorUserId: ctx.user?.id ?? null, actorRole: ctx.user?.testRole ?? ctx.user?.role ?? null, action: "order.create", entityType: "order", entityId: String(orderId), outcome: "success", requestId: nanoid(12) }); return { success: true, orderId, status: "new" as const }; }); }),
    updateOrderStatus: testRoleProcedure("restaurant_admin", "kitchen", "cashier").input(z.object({ restaurantId: z.number().int().positive(), orderId: z.number().int().positive(), status: z.enum(["new", "preparing", "ready", "completed", "cancelled"]) })).mutation(async ({ ctx, input }) => {
      assertRestaurantAccess(ctx, input.restaurantId);
      const db = await getDb();
      if (!db) throw new Error("Database is not available");
      const existing = await db.select({ restaurantId: orders.restaurantId }).from(orders).where(eq(orders.id, input.orderId)).limit(1);
      if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "الطلب غير مرتبط بالمطعم" });
      await db.update(orders).set({ status: input.status }).where(eq(orders.id, input.orderId));
      return { success: true, orderId: input.orderId, status: input.status };
    }),
  }),
  notifications: router({
    mine: protectedProcedure.query(({ ctx }) => listNotifications(ctx.user.id)),
    markRead: protectedProcedure.input(z.object({ notificationId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); await db.update(notifications).set({ readAt: new Date() }).where(and(eq(notifications.id, input.notificationId), eq(notifications.userId, ctx.user.id))); return { success: true }; }),
    pushSubscribe: protectedProcedure.input(z.object({ endpoint: z.string().url().max(1000), keys: z.object({ p256dh: z.string().min(16).max(255), auth: z.string().min(8).max(255) }), userAgent: z.string().max(500).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const existing = (await db.select({ id: pushSubscriptions.id }).from(pushSubscriptions).where(eq(pushSubscriptions.endpoint, input.endpoint)).limit(1))[0]; if (existing) await db.update(pushSubscriptions).set({ userId: ctx.user.id, p256dh: input.keys.p256dh, auth: input.keys.auth, userAgent: input.userAgent ?? null, lastSeenAt: new Date() }).where(eq(pushSubscriptions.id, existing.id)); else await db.insert(pushSubscriptions).values({ userId: ctx.user.id, endpoint: input.endpoint, p256dh: input.keys.p256dh, auth: input.keys.auth, userAgent: input.userAgent ?? null }); return { success: true }; }),
    pushUnsubscribe: protectedProcedure.input(z.object({ endpoint: z.string().url().max(1000) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); await db.delete(pushSubscriptions).where(and(eq(pushSubscriptions.endpoint, input.endpoint), eq(pushSubscriptions.userId, ctx.user.id))); return { success: true }; }),
  }),
  remote: router({
    workers: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listRemoteWorkers(input.restaurantId); }),
    currentWorker: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const worker = (await db.select().from(remoteWorkers).where(and(eq(remoteWorkers.restaurantId, input.restaurantId), eq(remoteWorkers.userId, ctx.user.id))).limit(1))[0]; return worker ?? null; }),
    createWorker: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), userId: z.number().int().positive(), role: z.string().min(2).max(80), isAvailable: z.boolean().default(true) })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const user = await db.select({ id: users.id }).from(users).where(eq(users.id, input.userId)).limit(1); if (!user[0]) throw new TRPCError({ code: "NOT_FOUND", message: "المستخدم غير موجود" }); const existing = await db.select({ id: remoteWorkers.id }).from(remoteWorkers).where(and(eq(remoteWorkers.restaurantId, input.restaurantId), eq(remoteWorkers.userId, input.userId))).limit(1); if (existing[0]) throw new TRPCError({ code: "CONFLICT", message: "المستخدم مرتبط بالفعل بالمطعم" }); const result = await db.insert(remoteWorkers).values(input); return { success: true, id: Number(result[0].insertId) }; }),
    updateWorker: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), role: z.string().min(2).max(80).optional(), isAvailable: z.boolean().optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const existing = await db.select({ restaurantId: remoteWorkers.restaurantId }).from(remoteWorkers).where(eq(remoteWorkers.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "العامل غير مرتبط بالمطعم" }); const { id: _id, restaurantId: _restaurantId, ...changes } = input; await db.update(remoteWorkers).set(changes).where(eq(remoteWorkers.id, input.id)); return { success: true, id: input.id }; }),
    deleteWorker: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const existing = await db.select({ restaurantId: remoteWorkers.restaurantId }).from(remoteWorkers).where(eq(remoteWorkers.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "العامل غير مرتبط بالمطعم" }); await db.delete(remoteWorkers).where(eq(remoteWorkers.id, input.id)); return { success: true, id: input.id }; }),
    tasks: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listRemoteTasks(input.restaurantId); }),
    messages: protectedProcedure.input(z.object({ taskId: z.number().int().positive() })).query(async ({ ctx, input }) => { await getRemoteTaskAccess(ctx, input.taskId); return listTaskMessages(input.taskId); }),
    applyAsRemoteWorker: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive(), role: z.string().min(2).max(80), message: z.string().max(2000).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const restaurant = (await db.select({ id: restaurants.id }).from(restaurants).where(eq(restaurants.id, input.restaurantId)).limit(1))[0]; if (!restaurant) throw new TRPCError({ code: "NOT_FOUND", message: "المطعم غير موجود" }); const existing = (await db.select({ id: remoteWorkerApplications.id, status: remoteWorkerApplications.status }).from(remoteWorkerApplications).where(and(eq(remoteWorkerApplications.restaurantId, input.restaurantId), eq(remoteWorkerApplications.applicantUserId, ctx.user!.id))).limit(1))[0]; if (existing?.status === "pending" || existing?.status === "approved") throw new TRPCError({ code: "CONFLICT", message: "لديك طلب قائم لهذا المطعم" }); const result = await db.insert(remoteWorkerApplications).values({ restaurantId: input.restaurantId, applicantUserId: ctx.user!.id, role: input.role, message: input.message ?? null, status: "pending" }); return { success: true, id: Number(result[0].insertId), status: "pending" as const }; }),
    myWorkerApplications: protectedProcedure.query(async ({ ctx }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); return db.select({ id: remoteWorkerApplications.id, restaurantId: remoteWorkerApplications.restaurantId, role: remoteWorkerApplications.role, message: remoteWorkerApplications.message, status: remoteWorkerApplications.status, createdAt: remoteWorkerApplications.createdAt, restaurantName: restaurants.name }).from(remoteWorkerApplications).innerJoin(restaurants, eq(remoteWorkerApplications.restaurantId, restaurants.id)).where(eq(remoteWorkerApplications.applicantUserId, ctx.user!.id)); }),
    workerApplications: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive() })).query(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); return db.select({ id: remoteWorkerApplications.id, applicantUserId: remoteWorkerApplications.applicantUserId, role: remoteWorkerApplications.role, message: remoteWorkerApplications.message, status: remoteWorkerApplications.status, createdAt: remoteWorkerApplications.createdAt, applicantName: users.name, applicantEmail: users.email }).from(remoteWorkerApplications).innerJoin(users, eq(remoteWorkerApplications.applicantUserId, users.id)).where(eq(remoteWorkerApplications.restaurantId, input.restaurantId)); }),
    reviewWorkerApplication: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), applicationId: z.number().int().positive(), status: z.enum(["approved", "rejected"]) })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const application = (await db.select().from(remoteWorkerApplications).where(eq(remoteWorkerApplications.id, input.applicationId)).limit(1))[0]; if (!application || application.restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "طلب التقديم غير مرتبط بالمطعم" }); if (application.status !== "pending") throw new TRPCError({ code: "BAD_REQUEST", message: "تمت مراجعة هذا الطلب مسبقًا" }); if (input.status === "approved") { const linked = (await db.select({ id: remoteWorkers.id }).from(remoteWorkers).where(and(eq(remoteWorkers.restaurantId, input.restaurantId), eq(remoteWorkers.userId, application.applicantUserId))).limit(1))[0]; if (!linked) await db.insert(remoteWorkers).values({ restaurantId: input.restaurantId, userId: application.applicantUserId, role: application.role, isAvailable: true }); } await db.update(remoteWorkerApplications).set({ status: input.status, reviewedByUserId: ctx.user!.id, reviewedAt: new Date() }).where(eq(remoteWorkerApplications.id, input.applicationId)); return { success: true, status: input.status }; }),
    createTask: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), assignedWorkerId: z.number().int().positive().optional(), type: z.enum(["orders", "reservations", "social", "support", "marketing", "other"]), title: z.string().min(2).max(180), description: z.string().max(5000).optional(), amount: z.string().regex(/^\d+(\.\d{1,2})?$/), currency: z.string().default("SAR"), paymentMethod: z.enum(["manual", "bank_transfer", "wallet", "pending_gateway"]).default("manual"), dueAt: z.string().datetime().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(remoteTasks).values({ ...input, createdByUserId: ctx.user!.id, assignedWorkerId: input.assignedWorkerId ?? null, description: input.description ?? null, dueAt: input.dueAt ? new Date(input.dueAt) : null }); const taskId = Number(result[0].insertId); let recipientUserId = ctx.user!.id; if (input.assignedWorkerId) { const worker = (await db.select({ userId: remoteWorkers.userId }).from(remoteWorkers).where(eq(remoteWorkers.id, input.assignedWorkerId)).limit(1))[0]; recipientUserId = worker?.userId ?? recipientUserId; } await db.insert(notifications).values({ userId: recipientUserId, taskId, type: "task", title: "تم إنشاء مهمة", body: `تم حفظ المهمة: ${input.title}` }); void sendPushToUser(recipientUserId, { title: "تم إنشاء مهمة", body: `تم حفظ المهمة: ${input.title}`, url: "/" }).catch((error) => console.warn("[Push] task notification failed", error)); return { success: true, id: taskId, status: "published" as const, paymentStatus: "unpaid" as const }; }),
    acceptTask: testRoleProcedure("restaurant_admin", "waiter", "kitchen", "cashier", "driver").input(z.object({ taskId: z.number().int().positive(), workerId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const access = await getRemoteTaskAccess(ctx, input.taskId); if (ctx.user?.testRole !== "restaurant_admin" && (!access.worker || access.worker.id !== input.workerId)) throw new TRPCError({ code: "FORBIDDEN", message: "لا يمكنك قبول المهمة بهذا العامل" }); const worker = (await access.db.select().from(remoteWorkers).where(and(eq(remoteWorkers.id, input.workerId), eq(remoteWorkers.restaurantId, access.task.restaurantId))).limit(1))[0]; if (!worker) throw new TRPCError({ code: "FORBIDDEN", message: "العامل غير مرتبط بالمطعم" }); if (access.task.status !== "published") throw new TRPCError({ code: "BAD_REQUEST", message: "لا يمكن قبول المهمة في حالتها الحالية" }); await access.db.update(remoteTasks).set({ assignedWorkerId: input.workerId, status: "accepted" }).where(eq(remoteTasks.id, input.taskId)); return { success: true, status: "accepted" as const }; }),
    updateTaskStatus: testRoleProcedure("restaurant_admin", "waiter", "kitchen", "cashier", "driver").input(z.object({ taskId: z.number().int().positive(), status: z.enum(["published", "reviewing", "accepted", "in_progress", "submitted", "completed", "cancelled"]) })).mutation(async ({ ctx, input }) => { const access = await getRemoteTaskAccess(ctx, input.taskId); const isAdmin = isAdminContext(ctx); assertRemoteTaskTransition(access.task.status, input.status, isAdmin); await access.db.update(remoteTasks).set({ status: input.status }).where(eq(remoteTasks.id, input.taskId)); return { success: true, status: input.status }; }),
    sendMessage: protectedProcedure.input(z.object({ taskId: z.number().int().positive(), body: z.string().min(1).max(5000) })).mutation(async ({ ctx, input }) => { const access = await getRemoteTaskAccess(ctx, input.taskId); const assignedWorkerUserId = access.task.assignedWorkerId ? ((await access.db.select({ userId: remoteWorkers.userId }).from(remoteWorkers).where(eq(remoteWorkers.id, access.task.assignedWorkerId)).limit(1))[0]?.userId ?? null) : null; const recipientUserId = getTaskNotificationRecipient({ createdByUserId: access.task.createdByUserId, assignedWorkerUserId }, ctx.user!.id); const result = await access.db.insert(taskMessages).values({ taskId: input.taskId, senderUserId: ctx.user!.id, body: input.body }); await access.db.insert(notifications).values({ userId: recipientUserId, taskId: input.taskId, type: "message", title: "رسالة مهمة جديدة", body: input.body }); void sendPushToUser(recipientUserId, { title: "رسالة مهمة جديدة", body: input.body, url: "/" }).catch((error) => console.warn("[Push] message notification failed", error)); return { success: true, id: Number(result[0].insertId) }; }),
  }),
  security: router({
    sessions: protectedProcedure.query(({ ctx }) => listAuthSessions(ctx.user.id)),
    security: protectedProcedure.query(({ ctx }) => getUserSecurity(ctx.user.id)),
    revokeSession: protectedProcedure.input(z.object({ sessionId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); await db.update(authSessions).set({ revokedAt: new Date() }).where(and(eq(authSessions.id, input.sessionId), eq(authSessions.userId, ctx.user.id))); return { success: true }; }),
    revokeAllSessions: protectedProcedure.mutation(async ({ ctx }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); await db.update(authSessions).set({ revokedAt: new Date() }).where(eq(authSessions.userId, ctx.user.id)); return { success: true }; }),
    setTwoFactor: protectedProcedure.input(z.object({ enabled: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); await db.insert(userSecurity).values({ userId: ctx.user.id, twoFactorEnabled: input.enabled }).onDuplicateKeyUpdate({ set: { twoFactorEnabled: input.enabled } }); return { success: true, enabled: input.enabled }; }),
  }),
  features: router({
    definitions: protectedProcedure.query(() => listFeatureDefinitions()),
    restaurant: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listRestaurantFeatures(input.restaurantId); }),
    access: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive(), key: z.string().min(1).max(120) })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return getFeatureAccess(input.restaurantId, input.key); }),
    setOverride: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), featureId: z.number().int().positive(), enabled: z.boolean(), limit: z.number().int().nonnegative().nullable().optional(), value: z.string().max(255).nullable().optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const existing = await db.select().from(restaurantFeatures).where(and(eq(restaurantFeatures.restaurantId, input.restaurantId), eq(restaurantFeatures.featureId, input.featureId))).limit(1); const values = { enabled: input.enabled, overrideLimit: input.limit ?? null, overrideValue: input.value ?? null }; if (existing[0]) await db.update(restaurantFeatures).set(values).where(eq(restaurantFeatures.id, existing[0].id)); else await db.insert(restaurantFeatures).values({ restaurantId: input.restaurantId, featureId: input.featureId, ...values }); await insertAuditLog({ restaurantId: input.restaurantId, actorUserId: ctx.user?.id ?? null, actorRole: ctx.user?.testRole ?? ctx.user?.role ?? null, action: "feature.override.update", entityType: "feature", entityId: String(input.featureId), outcome: "success", requestId: nanoid(12), metadata: JSON.stringify({ enabled: input.enabled, limit: input.limit ?? null }) }); return { success: true }; }),
  }),
  admin: router({
    restaurants: adminProcedure.query(() => listRestaurantsWithBranchCount()),
    createRestaurant: adminProcedure.input(z.object({ name: z.string().min(2), slug: z.string().min(2).max(160), plan: z.string().min(2).default("Growth") })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const barcode = `NFOOD-${nanoid(10).toUpperCase()}`; const result = await db.insert(restaurants).values({ ...input, barcode, status: "trial" }); return { success: true, id: Number(result[0].insertId), barcode }; }),
    updateRestaurant: adminProcedure.input(z.object({ id: z.number().int().positive(), name: z.string().min(2).max(160).optional(), slug: z.string().min(2).max(160).optional(), plan: z.string().min(2).optional(), status: z.enum(["active", "trial", "suspended"]).optional() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ id: restaurants.id }).from(restaurants).where(eq(restaurants.id, input.id)).limit(1); if (!existing[0]) throw new TRPCError({ code: "NOT_FOUND", message: "Restaurant not found" }); const { id: _id, ...changes } = input; await db.update(restaurants).set(changes).where(eq(restaurants.id, input.id)); return { success: true, id: input.id }; }),
    deleteRestaurant: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ id: restaurants.id }).from(restaurants).where(eq(restaurants.id, input.id)).limit(1); if (!existing[0]) throw new TRPCError({ code: "NOT_FOUND", message: "Restaurant not found" }); await db.update(restaurants).set({ status: "suspended" }).where(eq(restaurants.id, input.id)); return { success: true, id: input.id }; }),
    customers: adminProcedure.query(async () => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); return db.select({ id: users.id, name: users.name, email: users.email, loginMethod: users.loginMethod, createdAt: users.createdAt, lastSignedIn: users.lastSignedIn }).from(users).orderBy(users.createdAt); }),
    createCustomer: adminProcedure.input(z.object({ name: z.string().min(2).max(160), email: z.string().email().max(320).optional() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); if (input.email) { const duplicate = await db.select({ id: users.id }).from(users).where(eq(users.email, input.email)).limit(1); if (duplicate[0]) throw new TRPCError({ code: "CONFLICT", message: "البريد مستخدم مسبقًا" }); } const result = await db.insert(users).values({ openId: `manual_${nanoid(24)}`, name: input.name.trim(), email: input.email?.trim() || null, loginMethod: "admin_created", role: "user" }); return { success: true, id: Number(result[0].insertId) }; }),
    updateCustomer: adminProcedure.input(z.object({ id: z.number().int().positive(), name: z.string().min(2).max(160), email: z.string().email().max(320).optional() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const existing = await db.select({ id: users.id }).from(users).where(eq(users.id, input.id)).limit(1); if (!existing[0]) throw new TRPCError({ code: "NOT_FOUND", message: "Customer not found" }); await db.update(users).set({ name: input.name.trim(), email: input.email?.trim() || null }).where(eq(users.id, input.id)); return { success: true, id: input.id }; }),
    deleteCustomer: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const existing = await db.select({ id: users.id }).from(users).where(eq(users.id, input.id)).limit(1); if (!existing[0]) throw new TRPCError({ code: "NOT_FOUND", message: "Customer not found" }); await db.delete(users).where(eq(users.id, input.id)); return { success: true, id: input.id }; }),
    subscriptions: adminProcedure.input(z.object({ restaurantId: z.number().int().positive().optional() }).optional()).query(({ input }) => listSubscriptions(input?.restaurantId)),
    featureUsageMetrics: adminProcedure.query(async () => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const rows = await db.select({ featureId: featureDefinitions.id, key: featureDefinitions.key, label: featureDefinitions.label, enabled: restaurantFeatures.enabled, restaurantId: restaurantFeatures.restaurantId }).from(featureDefinitions).leftJoin(restaurantFeatures, eq(restaurantFeatures.featureId, featureDefinitions.id)); const byFeature = new Map<number, { featureId: number; key: string; label: string; configuredRestaurants: Set<number>; enabledRestaurants: Set<number> }>(); for (const row of rows) { const current = byFeature.get(row.featureId) ?? { featureId: row.featureId, key: row.key, label: row.label, configuredRestaurants: new Set<number>(), enabledRestaurants: new Set<number>() }; if (row.restaurantId !== null) { current.configuredRestaurants.add(row.restaurantId); if (row.enabled) current.enabledRestaurants.add(row.restaurantId); } byFeature.set(row.featureId, current); } return Array.from(byFeature.values()).map((item) => ({ featureId: item.featureId, key: item.key, label: item.label, configuredRestaurants: item.configuredRestaurants.size, enabledRestaurants: item.enabledRestaurants.size })).sort((a, b) => b.enabledRestaurants - a.enabledRestaurants || a.label.localeCompare(b.label)); }),
    saasMetrics: adminProcedure.query(async () => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const rows = await db.select({ status: subscriptions.status, plan: subscriptions.plan, monthlyPrice: subscriptions.monthlyPrice, cancelledAt: subscriptions.cancelledAt }).from(subscriptions); const activeRows = rows.filter((row) => row.status === "active"); const mrr = activeRows.reduce((sum, row) => sum + Number(row.monthlyPrice || 0), 0); const recentCutoff = Date.now() - 30 * 24 * 60 * 60 * 1000; const cancelledLast30Days = rows.filter((row) => row.status === "cancelled" && row.cancelledAt && row.cancelledAt.getTime() >= recentCutoff).length; const churnBase = activeRows.length + cancelledLast30Days; const byPlan = rows.reduce<Record<string, { active: number; mrr: number }>>((acc, row) => { if (!acc[row.plan]) acc[row.plan] = { active: 0, mrr: 0 }; if (row.status === "active") { acc[row.plan].active += 1; acc[row.plan].mrr += Number(row.monthlyPrice || 0); } return acc; }, {}); return { currency: "SAR", mrr, arr: mrr * 12, activeSubscriptions: activeRows.length, trialSubscriptions: rows.filter((row) => row.status === "trial").length, pastDueSubscriptions: rows.filter((row) => row.status === "past_due").length, cancelledLast30Days, churnRate: churnBase ? (cancelledLast30Days / churnBase) * 100 : 0, byPlan }; }),
    createSubscription: adminProcedure.input(z.object({ restaurantId: z.number().int().positive(), plan: z.string().min(2).max(64), monthlyPrice: z.string().regex(/^\d+(\.\d{1,2})?$/).default("0"), status: z.enum(["trial", "active", "past_due", "cancelled"]).default("trial") })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const restaurant = await db.select({ id: restaurants.id }).from(restaurants).where(eq(restaurants.id, input.restaurantId)).limit(1); if (!restaurant[0]) throw new TRPCError({ code: "NOT_FOUND", message: "Restaurant not found" }); const result = await db.insert(subscriptions).values({ ...input, cancelledAt: input.status === "cancelled" ? new Date() : null }); return { success: true, id: Number(result[0].insertId) }; }),
    updateSubscription: adminProcedure.input(z.object({ id: z.number().int().positive(), plan: z.string().min(2).max(64).optional(), monthlyPrice: z.string().regex(/^\d+(\.\d{1,2})?$/).optional(), status: z.enum(["trial", "active", "past_due", "cancelled"]).optional() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ id: subscriptions.id }).from(subscriptions).where(eq(subscriptions.id, input.id)).limit(1); if (!existing[0]) throw new TRPCError({ code: "NOT_FOUND", message: "Subscription not found" }); const { id: _id, ...changes } = input; await db.update(subscriptions).set({ ...changes, ...(input.status ? { cancelledAt: input.status === "cancelled" ? new Date() : null } : {}) }).where(eq(subscriptions.id, input.id)); return { success: true, id: input.id }; }),
    cancelSubscription: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ id: subscriptions.id }).from(subscriptions).where(eq(subscriptions.id, input.id)).limit(1); if (!existing[0]) throw new TRPCError({ code: "NOT_FOUND", message: "Subscription not found" }); await db.update(subscriptions).set({ status: "cancelled", cancelledAt: new Date() }).where(eq(subscriptions.id, input.id)); return { success: true, id: input.id, status: "cancelled" as const }; }),
    roles: adminProcedure.input(z.object({ restaurantId: z.number().int().positive().optional() }).optional()).query(({ input }) => listRoles(input?.restaurantId)),
    permissions: adminProcedure.query(() => listPermissions()),
    createRole: adminProcedure.input(z.object({ restaurantId: z.number().int().positive().optional(), name: z.string().min(2).max(80) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); if (input.restaurantId) { const restaurant = await db.select({ id: restaurants.id }).from(restaurants).where(eq(restaurants.id, input.restaurantId)).limit(1); if (!restaurant[0]) throw new TRPCError({ code: "NOT_FOUND", message: "Restaurant not found" }); } const result = await db.insert(roles).values({ restaurantId: input.restaurantId ?? null, name: input.name.trim(), scope: input.restaurantId ? "restaurant" : "platform" }); return { success: true, id: Number(result[0].insertId) }; }),
    updateRole: adminProcedure.input(z.object({ id: z.number().int().positive(), name: z.string().min(2).max(80) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ id: roles.id }).from(roles).where(eq(roles.id, input.id)).limit(1); if (!existing[0]) throw new TRPCError({ code: "NOT_FOUND", message: "Role not found" }); await db.update(roles).set({ name: input.name.trim() }).where(eq(roles.id, input.id)); return { success: true, id: input.id }; }),
    deleteRole: adminProcedure.input(z.object({ id: z.number().int().positive() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ id: roles.id }).from(roles).where(eq(roles.id, input.id)).limit(1); if (!existing[0]) throw new TRPCError({ code: "NOT_FOUND", message: "Role not found" }); await db.delete(rolePermissions).where(eq(rolePermissions.roleId, input.id)); await db.delete(roles).where(eq(roles.id, input.id)); return { success: true, id: input.id }; }),
    rolePermissions: adminProcedure.input(z.object({ roleId: z.number().int().positive() })).query(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const role = await db.select({ id: roles.id }).from(roles).where(eq(roles.id, input.roleId)).limit(1); if (!role[0]) throw new TRPCError({ code: "NOT_FOUND", message: "Role not found" }); return db.select({ permissionId: permissions.id, key: permissions.key, label: permissions.label }).from(rolePermissions).innerJoin(permissions, eq(rolePermissions.permissionId, permissions.id)).where(eq(rolePermissions.roleId, input.roleId)); }),
    setRolePermissions: adminProcedure.input(z.object({ roleId: z.number().int().positive(), permissionIds: z.array(z.number().int().positive()).max(500) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const role = await db.select({ id: roles.id }).from(roles).where(eq(roles.id, input.roleId)).limit(1); if (!role[0]) throw new TRPCError({ code: "NOT_FOUND", message: "Role not found" }); const uniquePermissionIds = Array.from(new Set(input.permissionIds)); if (uniquePermissionIds.length) { const existingPermissions = await db.select({ id: permissions.id }).from(permissions).where(inArray(permissions.id, uniquePermissionIds)); if (existingPermissions.length !== uniquePermissionIds.length) throw new TRPCError({ code: "BAD_REQUEST", message: "يوجد معرف صلاحية غير صالح" }); } await db.delete(rolePermissions).where(eq(rolePermissions.roleId, input.roleId)); if (uniquePermissionIds.length) await db.insert(rolePermissions).values(uniquePermissionIds.map((permissionId) => ({ roleId: input.roleId, permissionId }))); return { success: true, roleId: input.roleId, permissionIds: uniquePermissionIds }; }),
  }),
});

export type AppRouter = typeof appRouter;
