import { z } from "zod";
import { COOKIE_NAME, TEST_SESSION_COOKIE } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, protectedProcedure, testRoleProcedure, adminProcedure, router } from "./_core/trpc";
import { branches, orders, orderItems, inventoryItems, employees, attendance, remoteWorkers, restaurants, menuCategories, menuItems, purchases, restaurantTables, campaigns, remoteTasks, taskMessages, notifications, testAccounts, authSessions, userSecurity, restaurantFeatures } from "../drizzle/schema";
import { getDb, getRestaurantById, getRestaurantByBarcode, listBranches, listEmployees, listInventory, listMenuCategories, listMenuItems, listOrders, listRestaurants, listSubscriptions, listRoles, listPermissions, listTables, listPurchases, listAttendance, listCampaigns, listCoupons, listRemoteWorkers, listRemoteTasks, listTaskMessages, listNotifications, getTestAccountByEmail, listAuthSessions, upsertUser, getUserByOpenId, listFeatureDefinitions, listRestaurantFeatures, getUserSecurity, getFeatureAccess, insertAuditLog, listAuditLogs, globalSearch, getRoleSummary } from "./db";
import { and, eq } from "drizzle-orm";
import { TRPCError } from "@trpc/server";
import { nanoid } from "nanoid";
import { createHash, scryptSync, timingSafeEqual } from "node:crypto";
import { sdk } from "./_core/sdk";

function assertRestaurantAccess(ctx: { user: { testRole?: string } | null }, restaurantId: number) {
  if (ctx.user?.testRole && restaurantId !== 1) throw new TRPCError({ code: "FORBIDDEN", message: "لا تملك صلاحية الوصول إلى هذا المطعم" });
}

export function assertRemoteTaskTransition(current: string, next: string, isAdmin: boolean) {
  const allowed: Record<string, string[]> = { published: ["reviewing", "cancelled"], reviewing: ["accepted", "cancelled"], accepted: ["in_progress", "cancelled"], in_progress: ["submitted", "cancelled"], submitted: ["completed", "cancelled"] };
  if (current === "completed" || current === "cancelled" || !allowed[current]?.includes(next)) throw new TRPCError({ code: "BAD_REQUEST", message: "انتقال حالة المهمة غير مسموح" });
}

async function getRemoteTaskAccess(ctx: { user: { id: number; testRole?: string } | null }, taskId: number) {
  if (!ctx.user) throw new TRPCError({ code: "UNAUTHORIZED", message: "يجب تسجيل الدخول" });
  const db = await getDb();
  if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" });
  const task = (await db.select().from(remoteTasks).where(eq(remoteTasks.id, taskId)).limit(1))[0];
  if (!task) throw new TRPCError({ code: "NOT_FOUND", message: "المهمة غير موجودة" });
  assertRestaurantAccess(ctx, task.restaurantId);
  const worker = (await db.select().from(remoteWorkers).where(and(eq(remoteWorkers.userId, ctx.user.id), eq(remoteWorkers.restaurantId, task.restaurantId))).limit(1))[0];
  if (ctx.user.testRole !== "restaurant_admin" && (!worker || (task.assignedWorkerId !== null && task.assignedWorkerId !== worker.id))) throw new TRPCError({ code: "FORBIDDEN", message: "لا تملك هذه المهمة" });
  return { db, task, worker };
}

export const appRouter = router({
  system: systemRouter,
  auth: router({
    testLogin: publicProcedure.input(z.object({ email: z.string().email(), password: z.string().min(1) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const hash = "scrypt$Ke89BlsJJa45L/5mz+r4yg==$7H6Z0FmUuzmpJS8AvEW4zw/z2mYsvIdhEF9ZDJBj6NmHJEzW9g1iz8GUdipDUe+PI60ecQJajl9NmtX4kSiVxg=="; const seeds = [{ email: "nfood@ret.com", displayName: "أدمن مطعم NFOOD", role: "restaurant_admin" }, { email: "nfood.waiter@ret.com", displayName: "نادل NFOOD", role: "waiter" }, { email: "nfood.kitchen@ret.com", displayName: "مطبخ NFOOD", role: "kitchen" }, { email: "nfood.cashier@ret.com", displayName: "كاشير NFOOD", role: "cashier" }, { email: "nfood.client@ret.com", displayName: "عميل NFOOD", role: "customer" }, { email: "nfood.driver@ret.com", displayName: "سائق NFOOD", role: "driver" }] as const; for (const seed of seeds) await db.insert(testAccounts).values({ ...seed, passwordHash: hash }).onDuplicateKeyUpdate({ set: { displayName: seed.displayName, role: seed.role, passwordHash: hash } }); const account = await getTestAccountByEmail(input.email); if (!account) throw new TRPCError({ code: "UNAUTHORIZED", message: "بيانات الدخول غير صحيحة" }); const [scheme, salt, storedKey] = account.passwordHash.split("$"); const derivedKey = scryptSync(input.password, Buffer.from(salt, "base64"), 64); if (scheme !== "scrypt" || !timingSafeEqual(derivedKey, Buffer.from(storedKey, "base64"))) throw new TRPCError({ code: "UNAUTHORIZED", message: "بيانات الدخول غير صحيحة" }); await upsertUser({ openId: `test_${account.id}`, name: account.displayName, email: account.email, loginMethod: "test" }); const sessionUser = await getUserByOpenId(`test_${account.id}`); const token = await sdk.signSession({ openId: `test_${account.id}`, appId: `test_${nanoid(12)}`, name: account.displayName }); if (sessionUser) await db.insert(authSessions).values({ userId: sessionUser.id, sessionTokenHash: createHash("sha256").update(token).digest("hex"), deviceLabel: "حساب اختبار", userAgent: ctx.req.get("user-agent") ?? null, ipAddress: ctx.req.ip ?? null, expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 12) }); ctx.res.cookie(TEST_SESSION_COOKIE, token, { httpOnly: true, sameSite: "lax", secure: true, path: "/", maxAge: 1000 * 60 * 60 * 12 }); return { success: true, role: account.role, name: account.displayName }; }),
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 });
      ctx.res.clearCookie(TEST_SESSION_COOKIE, { ...cookieOptions, maxAge: -1 });
      return { success: true } as const;
    }),
  }),
  platform: router({
    restaurants: protectedProcedure.query(() => listRestaurants()),
    restaurantById: protectedProcedure.input(z.object({ id: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.id); return getRestaurantById(input.id); }),
    restaurantByBarcode: protectedProcedure.input(z.object({ barcode: z.string().min(6).max(64) })).query(({ input }) => getRestaurantByBarcode(input.barcode)),
    branches: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listBranches(input.restaurantId); }),
    menuCategories: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listMenuCategories(input.restaurantId); }),
    createMenuCategory: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), name: z.string().min(2), sortOrder: z.number().int().nonnegative().default(0) })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(menuCategories).values(input); return { success: true, id: Number(result[0].insertId) }; }),
    updateMenuCategory: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), name: z.string().min(2).optional(), sortOrder: z.number().int().nonnegative().optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: menuCategories.restaurantId }).from(menuCategories).where(eq(menuCategories.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Category belongs to another restaurant" }); const { id: _id, restaurantId: _restaurantId, ...changes } = input; await db.update(menuCategories).set(changes).where(eq(menuCategories.id, input.id)); return { success: true, id: input.id }; }),
    deleteMenuCategory: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: menuCategories.restaurantId }).from(menuCategories).where(eq(menuCategories.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Category belongs to another restaurant" }); await db.delete(menuCategories).where(eq(menuCategories.id, input.id)); return { success: true, id: input.id }; }),
    menuItems: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive().optional(), categoryId: z.number().int().positive().optional() }).optional()).query(({ ctx, input }) => { if (input?.restaurantId) assertRestaurantAccess(ctx, input.restaurantId); return listMenuItems(input?.restaurantId, input?.categoryId); }),
    orders: protectedProcedure.input(z.object({ branchId: z.number().int().positive() })).query(({ input }) => listOrders(input.branchId)),
    inventory: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listInventory(input.restaurantId); }),
    employees: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listEmployees(input.restaurantId); }),
    tables: protectedProcedure.input(z.object({ branchId: z.number().int().positive() })).query(({ input }) => listTables(input.branchId)),
    purchases: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listPurchases(input.restaurantId); }),
    attendance: protectedProcedure.input(z.object({ employeeId: z.number().int().positive().optional() }).optional()).query(({ input }) => listAttendance(input?.employeeId)),
    campaigns: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listCampaigns(input.restaurantId); }),
    coupons: protectedProcedure.input(z.object({ campaignId: z.number().int().positive().optional() }).optional()).query(({ input }) => listCoupons(input?.campaignId)),
    auditLogs: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive().optional() }).optional()).query(({ ctx, input }) => { if (input?.restaurantId) assertRestaurantAccess(ctx, input.restaurantId); return listAuditLogs(input?.restaurantId); }),
    globalSearch: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive(), query: z.string().max(120), limit: z.number().int().positive().max(50).default(20) })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return globalSearch(input.restaurantId, input.query, input.limit); }),
    roleSummary: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return getRoleSummary(input.restaurantId, ctx.user?.testRole, ctx.user?.id); }),
    createBranch: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), name: z.string().min(2), city: z.string().max(120).optional(), status: z.enum(["open", "closed"]).default("open") })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(branches).values(input); return { success: true, id: Number(result[0].insertId) }; }),
    updateBranch: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), name: z.string().min(2).max(160).optional(), city: z.string().max(120).optional(), status: z.enum(["open", "closed"]).optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: branches.restaurantId }).from(branches).where(eq(branches.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Branch belongs to another restaurant" }); const { id: _id, restaurantId: _restaurantId, ...changes } = input; await db.update(branches).set(changes).where(eq(branches.id, input.id)); return { success: true, id: input.id }; }),
    deleteBranch: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: branches.restaurantId }).from(branches).where(eq(branches.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Branch belongs to another restaurant" }); await db.delete(branches).where(eq(branches.id, input.id)); return { success: true, id: input.id }; }),
    createMenuItem: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), categoryId: z.number().int().positive(), name: z.string().min(2), price: z.string(), description: z.string().optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(menuItems).values({ ...input, description: input.description ?? null }); return { success: true, id: Number(result[0].insertId) }; }),
    updateMenuItem: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), name: z.string().min(2).optional(), price: z.string().optional(), isAvailable: z.boolean().optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: menuItems.restaurantId }).from(menuItems).where(eq(menuItems.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Menu item belongs to another restaurant" }); const { id: _id, restaurantId: _restaurantId, ...changes } = input; await db.update(menuItems).set(changes).where(eq(menuItems.id, input.id)); return { success: true, id: input.id }; }),
    deleteMenuItem: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: menuItems.restaurantId }).from(menuItems).where(eq(menuItems.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Menu item belongs to another restaurant" }); await db.delete(menuItems).where(eq(menuItems.id, input.id)); return { success: true, id: input.id }; }),
    createInventoryItem: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), name: z.string().min(2).max(160), unit: z.string().min(1).max(32), quantity: z.string().regex(/^\d+(\.\d{1,2})?$/).default("0"), minimumQuantity: z.string().regex(/^\d+(\.\d{1,2})?$/).default("0") })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(inventoryItems).values(input); return { success: true, id: Number(result[0].insertId) }; }),
    updateInventoryItem: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), name: z.string().min(2).max(160).optional(), unit: z.string().min(1).max(32).optional(), quantity: z.string().regex(/^\d+(\.\d{1,2})?$/).optional(), minimumQuantity: z.string().regex(/^\d+(\.\d{1,2})?$/).optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: inventoryItems.restaurantId }).from(inventoryItems).where(eq(inventoryItems.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Inventory item belongs to another restaurant" }); const { id: _id, restaurantId: _restaurantId, ...changes } = input; await db.update(inventoryItems).set(changes).where(eq(inventoryItems.id, input.id)); return { success: true, id: input.id }; }),
    deleteInventoryItem: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: inventoryItems.restaurantId }).from(inventoryItems).where(eq(inventoryItems.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Inventory item belongs to another restaurant" }); await db.delete(inventoryItems).where(eq(inventoryItems.id, input.id)); return { success: true, id: input.id }; }),
    createPurchase: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), supplier: z.string().min(2), total: z.string().regex(/^\d+(\.\d{1,2})?$/), status: z.enum(["draft", "received", "cancelled"]).default("received") })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(purchases).values(input); return { success: true, id: Number(result[0].insertId) }; }),
    updatePurchase: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), supplier: z.string().min(2).optional(), total: z.string().regex(/^\d+(\.\d{1,2})?$/).optional(), status: z.enum(["draft", "received", "cancelled"]).optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: purchases.restaurantId }).from(purchases).where(eq(purchases.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Purchase belongs to another restaurant" }); const { id: _id, restaurantId: _restaurantId, ...changes } = input; await db.update(purchases).set(changes).where(eq(purchases.id, input.id)); return { success: true, id: input.id }; }),
    deletePurchase: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: purchases.restaurantId }).from(purchases).where(eq(purchases.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Purchase belongs to another restaurant" }); await db.delete(purchases).where(eq(purchases.id, input.id)); return { success: true, id: input.id }; }),
    createEmployee: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), name: z.string().min(2).max(160), role: z.string().min(2).max(80), status: z.enum(["active", "inactive"]).default("active") })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(employees).values(input); return { success: true, id: Number(result[0].insertId) }; }),
    updateEmployee: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), name: z.string().min(2).max(160).optional(), role: z.string().min(2).max(80).optional(), status: z.enum(["active", "inactive"]).optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: employees.restaurantId }).from(employees).where(eq(employees.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Employee belongs to another restaurant" }); const { id: _id, restaurantId: _restaurantId, ...changes } = input; await db.update(employees).set(changes).where(eq(employees.id, input.id)); return { success: true, id: input.id }; }),
    deleteEmployee: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: employees.restaurantId }).from(employees).where(eq(employees.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Employee belongs to another restaurant" }); await db.delete(employees).where(eq(employees.id, input.id)); return { success: true, id: input.id }; }),
    recordAttendance: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), employeeId: z.number().int().positive(), workDate: z.string().regex(/^\\d{4}-\\d{2}-\\d{2}$/), status: z.enum(["present", "absent", "late"]) })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const employee = (await db.select({ restaurantId: employees.restaurantId }).from(employees).where(eq(employees.id, input.employeeId)).limit(1))[0]; if (!employee || employee.restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Employee belongs to another restaurant" }); const result = await db.insert(attendance).values({ employeeId: input.employeeId, workDate: input.workDate, status: input.status }); return { success: true, id: Number(result[0].insertId) }; }),
    updateTableStatus: testRoleProcedure("restaurant_admin", "waiter", "cashier").input(z.object({ restaurantId: z.number().int().positive(), tableId: z.number().int().positive(), status: z.enum(["available", "occupied", "reserved"]) })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = (await db.select({ tableId: restaurantTables.id, restaurantId: branches.restaurantId }).from(restaurantTables).innerJoin(branches, eq(restaurantTables.branchId, branches.id)).where(eq(restaurantTables.id, input.tableId)).limit(1))[0]; if (!existing || existing.restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Table belongs to another restaurant" }); await db.update(restaurantTables).set({ status: input.status }).where(eq(restaurantTables.id, input.tableId)); return { success: true, status: input.status }; }),
    createCampaign: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), name: z.string().min(2), status: z.enum(["draft", "scheduled", "active", "ended"]).default("draft") })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(campaigns).values(input); return { success: true, id: Number(result[0].insertId) }; }),
    updateCampaign: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive(), name: z.string().min(2).optional(), status: z.enum(["draft", "scheduled", "active", "ended"]).optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: campaigns.restaurantId }).from(campaigns).where(eq(campaigns.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Campaign belongs to another restaurant" }); const { id: _id, restaurantId: _restaurantId, ...changes } = input; await db.update(campaigns).set(changes).where(eq(campaigns.id, input.id)); return { success: true, id: input.id }; }),
    deleteCampaign: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), id: z.number().int().positive() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const existing = await db.select({ restaurantId: campaigns.restaurantId }).from(campaigns).where(eq(campaigns.id, input.id)).limit(1); if (!existing[0] || existing[0].restaurantId !== input.restaurantId) throw new TRPCError({ code: "FORBIDDEN", message: "Campaign belongs to another restaurant" }); await db.delete(campaigns).where(eq(campaigns.id, input.id)); return { success: true, id: input.id }; }),
    createOrder: testRoleProcedure("restaurant_admin", "waiter", "cashier").input(z.object({ restaurantId: z.number().int().positive(), branchId: z.number().int().positive(), tableName: z.string().max(80).optional(), channel: z.enum(["dine_in", "takeaway", "delivery"]), paymentMethod: z.enum(["cash", "card", "bank_transfer", "online", "other"]).default("cash"), items: z.array(z.object({ menuItemId: z.number().int().positive(), quantity: z.number().int().positive(), unitPrice: z.string().regex(/^\d+(\.\d{1,2})?$/) })).min(1), total: z.string().regex(/^\d+(\.\d{1,2})?$/) })).mutation(    async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); return db.transaction(async (tx) => { const [orderResult] = await tx.insert(orders).values({ restaurantId: input.restaurantId, branchId: input.branchId, tableName: input.tableName ?? null, channel: input.channel, paymentMethod: input.paymentMethod, paymentStatus: "unpaid", total: input.total, status: "new" }); const orderId = Number(orderResult.insertId); const rows = input.items.map((item) => ({ orderId, menuItemId: item.menuItemId, quantity: item.quantity, unitPrice: item.unitPrice })); await tx.insert(orderItems).values(rows); await insertAuditLog({ restaurantId: input.restaurantId, branchId: input.branchId, actorUserId: ctx.user?.id ?? null, actorRole: ctx.user?.testRole ?? ctx.user?.role ?? null, action: "order.create", entityType: "order", entityId: String(orderId), outcome: "success", requestId: nanoid(12) }); return { success: true, orderId, status: "new" as const }; }); }),
    updateOrderStatus: testRoleProcedure("restaurant_admin", "kitchen", "cashier").input(z.object({ orderId: z.number().int().positive(), status: z.enum(["new", "preparing", "ready", "completed", "cancelled"]) })).mutation(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new Error("Database is not available");
      await db.update(orders).set({ status: input.status }).where(eq(orders.id, input.orderId));
      return { success: true, orderId: input.orderId, status: input.status };
    }),
  }),
  notifications: router({
    mine: protectedProcedure.query(({ ctx }) => listNotifications(ctx.user.id)),
    markRead: protectedProcedure.input(z.object({ notificationId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); await db.update(notifications).set({ readAt: new Date() }).where(eq(notifications.id, input.notificationId)); return { success: true }; }),
  }),
  remote: router({
    workers: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ input }) => listRemoteWorkers(input.restaurantId)),
    tasks: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ input }) => listRemoteTasks(input.restaurantId)),
    messages: protectedProcedure.input(z.object({ taskId: z.number().int().positive() })).query(({ input }) => listTaskMessages(input.taskId)),
    createTask: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), assignedWorkerId: z.number().int().positive().optional(), type: z.enum(["orders", "reservations", "social", "support", "marketing", "other"]), title: z.string().min(2).max(180), description: z.string().max(5000).optional(), amount: z.string().regex(/^\d+(\.\d{1,2})?$/), currency: z.string().default("SAR"), paymentMethod: z.enum(["manual", "bank_transfer", "wallet", "pending_gateway"]).default("manual"), dueAt: z.string().datetime().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(remoteTasks).values({ ...input, createdByUserId: ctx.user!.id, assignedWorkerId: input.assignedWorkerId ?? null, description: input.description ?? null, dueAt: input.dueAt ? new Date(input.dueAt) : null }); const taskId = Number(result[0].insertId); await db.insert(notifications).values({ userId: ctx.user!.id, taskId, type: "task", title: "تم إنشاء مهمة", body: `تم حفظ المهمة: ${input.title}` }); return { success: true, id: taskId, status: "published" as const, paymentStatus: "unpaid" as const }; }),
    acceptTask: testRoleProcedure("restaurant_admin", "waiter", "kitchen", "cashier", "driver").input(z.object({ taskId: z.number().int().positive(), workerId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const access = await getRemoteTaskAccess(ctx, input.taskId); if (ctx.user?.testRole !== "restaurant_admin" && (!access.worker || access.worker.id !== input.workerId)) throw new TRPCError({ code: "FORBIDDEN", message: "لا يمكنك قبول المهمة بهذا العامل" }); const worker = (await access.db.select().from(remoteWorkers).where(and(eq(remoteWorkers.id, input.workerId), eq(remoteWorkers.restaurantId, access.task.restaurantId))).limit(1))[0]; if (!worker) throw new TRPCError({ code: "FORBIDDEN", message: "العامل غير مرتبط بالمطعم" }); if (access.task.status !== "published") throw new TRPCError({ code: "BAD_REQUEST", message: "لا يمكن قبول المهمة في حالتها الحالية" }); await access.db.update(remoteTasks).set({ assignedWorkerId: input.workerId, status: "accepted" }).where(eq(remoteTasks.id, input.taskId)); return { success: true, status: "accepted" as const }; }),
    updateTaskStatus: testRoleProcedure("restaurant_admin", "waiter", "kitchen", "cashier", "driver").input(z.object({ taskId: z.number().int().positive(), status: z.enum(["published", "reviewing", "accepted", "in_progress", "submitted", "completed", "cancelled"]) })).mutation(async ({ ctx, input }) => { const access = await getRemoteTaskAccess(ctx, input.taskId); const isAdmin = ctx.user?.testRole === "restaurant_admin"; assertRemoteTaskTransition(access.task.status, input.status, isAdmin); await access.db.update(remoteTasks).set({ status: input.status }).where(eq(remoteTasks.id, input.taskId)); return { success: true, status: input.status }; }),
    sendMessage: protectedProcedure.input(z.object({ taskId: z.number().int().positive(), body: z.string().min(1).max(5000) })).mutation(async ({ ctx, input }) => { const access = await getRemoteTaskAccess(ctx, input.taskId); const result = await access.db.insert(taskMessages).values({ taskId: input.taskId, senderUserId: ctx.user!.id, body: input.body }); await access.db.insert(notifications).values({ userId: ctx.user!.id, taskId: input.taskId, type: "message", title: "رسالة مهمة جديدة", body: input.body }); return { success: true, id: Number(result[0].insertId) }; }),
  }),
  security: router({
    sessions: protectedProcedure.query(({ ctx }) => listAuthSessions(ctx.user.id)),
    security: protectedProcedure.query(({ ctx }) => getUserSecurity(ctx.user.id)),
    revokeSession: protectedProcedure.input(z.object({ sessionId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); await db.update(authSessions).set({ revokedAt: new Date() }).where(and(eq(authSessions.id, input.sessionId), eq(authSessions.userId, ctx.user.id))); return { success: true }; }),
    revokeAllSessions: protectedProcedure.mutation(async ({ ctx }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); await db.update(authSessions).set({ revokedAt: new Date() }).where(eq(authSessions.userId, ctx.user.id)); return { success: true }; }),
    setTwoFactor: protectedProcedure.input(z.object({ enabled: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); await db.insert(userSecurity).values({ userId: ctx.user.id, twoFactorEnabled: input.enabled }).onDuplicateKeyUpdate({ set: { twoFactorEnabled: input.enabled } }); return { success: true, enabled: input.enabled }; }),
  }),
  features: router({
    definitions: protectedProcedure.query(() => listFeatureDefinitions()),
    restaurant: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listRestaurantFeatures(input.restaurantId); }),
    access: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive(), key: z.string().min(1).max(120) })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return getFeatureAccess(input.restaurantId, input.key); }),
    setOverride: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), featureId: z.number().int().positive(), enabled: z.boolean(), limit: z.number().int().nonnegative().nullable().optional(), value: z.string().max(255).nullable().optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const existing = await db.select().from(restaurantFeatures).where(and(eq(restaurantFeatures.restaurantId, input.restaurantId), eq(restaurantFeatures.featureId, input.featureId))).limit(1); const values = { enabled: input.enabled, overrideLimit: input.limit ?? null, overrideValue: input.value ?? null }; if (existing[0]) await db.update(restaurantFeatures).set(values).where(eq(restaurantFeatures.id, existing[0].id)); else await db.insert(restaurantFeatures).values({ restaurantId: input.restaurantId, featureId: input.featureId, ...values }); await insertAuditLog({ restaurantId: input.restaurantId, actorUserId: ctx.user?.id ?? null, actorRole: ctx.user?.testRole ?? ctx.user?.role ?? null, action: "feature.override.update", entityType: "feature", entityId: String(input.featureId), outcome: "success", requestId: nanoid(12), metadata: JSON.stringify({ enabled: input.enabled, limit: input.limit ?? null }) }); return { success: true }; }),
  }),
  admin: router({
    restaurants: adminProcedure.query(() => listRestaurants()),
    createRestaurant: adminProcedure.input(z.object({ name: z.string().min(2), slug: z.string().min(2).max(160), plan: z.string().min(2).default("Growth") })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const barcode = `NFOOD-${nanoid(10).toUpperCase()}`; const result = await db.insert(restaurants).values({ ...input, barcode, status: "trial" }); return { success: true, id: Number(result[0].insertId), barcode }; }),
    subscriptions: adminProcedure.input(z.object({ restaurantId: z.number().int().positive().optional() }).optional()).query(({ input }) => listSubscriptions(input?.restaurantId)),
    roles: adminProcedure.input(z.object({ restaurantId: z.number().int().positive().optional() }).optional()).query(({ input }) => listRoles(input?.restaurantId)),
    permissions: adminProcedure.query(() => listPermissions()),
  }),
});

export type AppRouter = typeof appRouter;
