import { z } from "zod";
import { COOKIE_NAME, TEST_SESSION_COOKIE } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { publicProcedure, protectedProcedure, testRoleProcedure, adminProcedure, router } from "./_core/trpc";
import { branches, orders, orderItems, restaurants, menuItems, purchases, restaurantTables, campaigns, remoteTasks, taskMessages, notifications, testAccounts, authSessions, userSecurity, restaurantFeatures } from "../drizzle/schema";
import { getDb, getRestaurantById, getRestaurantByBarcode, listBranches, listEmployees, listInventory, listMenuCategories, listMenuItems, listOrders, listRestaurants, listSubscriptions, listRoles, listPermissions, listTables, listPurchases, listAttendance, listCampaigns, listCoupons, listRemoteWorkers, listRemoteTasks, listTaskMessages, listNotifications, getTestAccountByEmail, listAuthSessions, upsertUser, getUserByOpenId, listFeatureDefinitions, listRestaurantFeatures, getUserSecurity, getFeatureAccess } from "./db";
import { and, eq } from "drizzle-orm";
import { TRPCError } from "@trpc/server";
import { nanoid } from "nanoid";
import { createHash, scryptSync, timingSafeEqual } from "node:crypto";
import { sdk } from "./_core/sdk";

function assertRestaurantAccess(ctx: { user: { testRole?: string } | null }, restaurantId: number) {
  if (ctx.user?.testRole && restaurantId !== 1) throw new TRPCError({ code: "FORBIDDEN", message: "لا تملك صلاحية الوصول إلى هذا المطعم" });
}

export const appRouter = router({
  system: systemRouter,
  auth: router({
    testLogin: publicProcedure.input(z.object({ email: z.string().email(), password: z.string().min(1) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const hash = "scrypt$Ke89BlsJJa45L/5mz+r4yg==$7H6Z0FmUuzmpJS8AvEW4zw/z2mYsvIdhEF9ZDJBj6NmHJEzW9g1iz8GUdipDUe+PI60ecQJajl9NmtX4kSiVxg=="; const seeds = [{ email: "nfood@ret.com", displayName: "أدمن مطعم NFOOD", role: "restaurant_admin" }, { email: "nfood.waiter@ret.com", displayName: "نادل NFOOD", role: "waiter" }, { email: "nfood.kitchen@ret.com", displayName: "مطبخ NFOOD", role: "kitchen" }, { email: "nfood.cashier@ret.com", displayName: "كاشير NFOOD", role: "cashier" }, { email: "nfood.client@ret.com", displayName: "عميل NFOOD", role: "customer" }, { email: "nfood.driver@ret.com", displayName: "سائق NFOOD", role: "driver" }] as const; for (const seed of seeds) await db.insert(testAccounts).values({ ...seed, passwordHash: hash }).onDuplicateKeyUpdate({ set: { displayName: seed.displayName, role: seed.role, passwordHash: hash } }); const account = await getTestAccountByEmail(input.email); if (!account) throw new TRPCError({ code: "UNAUTHORIZED", message: "بيانات الدخول غير صحيحة" }); const [scheme, salt, storedKey] = account.passwordHash.split("$"); const derivedKey = scryptSync(input.password, Buffer.from(salt, "base64"), 64); if (scheme !== "scrypt" || !timingSafeEqual(derivedKey, Buffer.from(storedKey, "base64"))) throw new TRPCError({ code: "UNAUTHORIZED", message: "بيانات الدخول غير صحيحة" }); await upsertUser({ openId: `test_${account.id}`, name: account.displayName, email: account.email, loginMethod: "test" }); const sessionUser = await getUserByOpenId(`test_${account.id}`); const token = await sdk.signSession({ openId: `test_${account.id}`, appId: "test", name: account.displayName }); if (sessionUser) await db.insert(authSessions).values({ userId: sessionUser.id, sessionTokenHash: createHash("sha256").update(token).digest("hex"), deviceLabel: "حساب اختبار", userAgent: ctx.req.get("user-agent") ?? null, ipAddress: ctx.req.ip ?? null, expiresAt: new Date(Date.now() + 1000 * 60 * 60 * 12) }); ctx.res.cookie(TEST_SESSION_COOKIE, token, { httpOnly: true, sameSite: "lax", secure: true, path: "/", maxAge: 1000 * 60 * 60 * 12 }); return { success: true, role: account.role, name: account.displayName }; }),
    me: publicProcedure.query(opts => opts.ctx.user),
    logout: publicProcedure.mutation(({ ctx }) => {
      const cookieOptions = getSessionCookieOptions(ctx.req);
      ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 });
      ctx.res.clearCookie(TEST_SESSION_COOKIE, { ...cookieOptions, maxAge: -1 });
      return { success: true } as const;
    }),
  }),
  platform: router({
    restaurants: protectedProcedure.query(() => listRestaurants()),
    restaurantById: protectedProcedure.input(z.object({ id: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.id); return getRestaurantById(input.id); }),
    restaurantByBarcode: protectedProcedure.input(z.object({ barcode: z.string().min(6).max(64) })).query(({ input }) => getRestaurantByBarcode(input.barcode)),
    branches: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listBranches(input.restaurantId); }),
    menuCategories: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listMenuCategories(input.restaurantId); }),
    menuItems: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive().optional(), categoryId: z.number().int().positive().optional() }).optional()).query(({ ctx, input }) => { if (input?.restaurantId) assertRestaurantAccess(ctx, input.restaurantId); return listMenuItems(input?.restaurantId, input?.categoryId); }),
    orders: protectedProcedure.input(z.object({ branchId: z.number().int().positive() })).query(({ input }) => listOrders(input.branchId)),
    inventory: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listInventory(input.restaurantId); }),
    employees: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listEmployees(input.restaurantId); }),
    tables: protectedProcedure.input(z.object({ branchId: z.number().int().positive() })).query(({ input }) => listTables(input.branchId)),
    purchases: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listPurchases(input.restaurantId); }),
    attendance: protectedProcedure.input(z.object({ employeeId: z.number().int().positive().optional() }).optional()).query(({ input }) => listAttendance(input?.employeeId)),
    campaigns: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return listCampaigns(input.restaurantId); }),
    coupons: protectedProcedure.input(z.object({ campaignId: z.number().int().positive().optional() }).optional()).query(({ input }) => listCoupons(input?.campaignId)),
    createBranch: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive(), name: z.string().min(2), city: z.string().optional() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(branches).values(input); return { success: true, id: Number(result[0].insertId) }; }),
    createMenuItem: testRoleProcedure("restaurant_admin").input(z.object({ categoryId: z.number().int().positive(), name: z.string().min(2), price: z.string(), description: z.string().optional() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(menuItems).values({ ...input, description: input.description ?? null }); return { success: true, id: Number(result[0].insertId) }; }),
    createPurchase: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), supplier: z.string().min(2), total: z.string() })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(purchases).values(input); return { success: true, id: Number(result[0].insertId) }; }),
    updateTableStatus: testRoleProcedure("restaurant_admin", "waiter", "cashier").input(z.object({ tableId: z.number().int().positive(), status: z.enum(["available", "occupied", "reserved"]) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); await db.update(restaurantTables).set({ status: input.status }).where(eq(restaurantTables.id, input.tableId)); return { success: true, status: input.status }; }),
    createCampaign: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), name: z.string().min(2), status: z.enum(["draft", "scheduled", "active", "ended"]).default("draft") })).mutation(async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(campaigns).values(input); return { success: true, id: Number(result[0].insertId) }; }),
    createOrder: testRoleProcedure("restaurant_admin", "waiter", "cashier").input(z.object({ restaurantId: z.number().int().positive(), branchId: z.number().int().positive(), tableName: z.string().max(80).optional(), channel: z.enum(["dine_in", "takeaway", "delivery"]), items: z.array(z.object({ menuItemId: z.number().int().positive(), quantity: z.number().int().positive(), unitPrice: z.string().regex(/^\d+(\.\d{1,2})?$/) })).min(1), total: z.string().regex(/^\d+(\.\d{1,2})?$/) })).mutation(    async ({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); const db = await getDb(); if (!db) throw new Error("Database is not available"); return db.transaction(async (tx) => { const [orderResult] = await tx.insert(orders).values({ restaurantId: input.restaurantId, branchId: input.branchId, tableName: input.tableName ?? null, channel: input.channel, total: input.total, status: "new" }); const orderId = Number(orderResult.insertId); const rows = input.items.map((item) => ({ orderId, menuItemId: item.menuItemId, quantity: item.quantity, unitPrice: item.unitPrice })); await tx.insert(orderItems).values(rows); return { success: true, orderId, status: "new" as const }; }); }),
    updateOrderStatus: testRoleProcedure("restaurant_admin", "kitchen", "cashier").input(z.object({ orderId: z.number().int().positive(), status: z.enum(["new", "preparing", "ready", "completed", "cancelled"]) })).mutation(async ({ input }) => {
      const db = await getDb();
      if (!db) throw new Error("Database is not available");
      await db.update(orders).set({ status: input.status }).where(eq(orders.id, input.orderId));
      return { success: true, orderId: input.orderId, status: input.status };
    }),
  }),
  notifications: router({
    mine: protectedProcedure.query(({ ctx }) => listNotifications(ctx.user.id)),
    markRead: protectedProcedure.input(z.object({ notificationId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); await db.update(notifications).set({ readAt: new Date() }).where(eq(notifications.id, input.notificationId)); return { success: true }; }),
  }),
  remote: router({
    workers: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ input }) => listRemoteWorkers(input.restaurantId)),
    tasks: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ input }) => listRemoteTasks(input.restaurantId)),
    messages: protectedProcedure.input(z.object({ taskId: z.number().int().positive() })).query(({ input }) => listTaskMessages(input.taskId)),
    createTask: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), assignedWorkerId: z.number().int().positive().optional(), type: z.enum(["orders", "reservations", "social", "support", "marketing", "other"]), title: z.string().min(2).max(180), description: z.string().max(5000).optional(), amount: z.string().regex(/^\d+(\.\d{1,2})?$/), currency: z.string().default("SAR"), paymentMethod: z.enum(["manual", "bank_transfer", "wallet", "pending_gateway"]).default("manual"), dueAt: z.string().datetime().optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(remoteTasks).values({ ...input, createdByUserId: ctx.user!.id, assignedWorkerId: input.assignedWorkerId ?? null, description: input.description ?? null, dueAt: input.dueAt ? new Date(input.dueAt) : null }); const taskId = Number(result[0].insertId); await db.insert(notifications).values({ userId: ctx.user!.id, taskId, type: "task", title: "تم إنشاء مهمة", body: `تم حفظ المهمة: ${input.title}` }); return { success: true, id: taskId, status: "published" as const, paymentStatus: "unpaid" as const }; }),
    acceptTask: testRoleProcedure("restaurant_admin", "waiter", "kitchen", "cashier", "driver").input(z.object({ taskId: z.number().int().positive(), workerId: z.number().int().positive() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); await db.update(remoteTasks).set({ assignedWorkerId: input.workerId, status: "accepted" }).where(eq(remoteTasks.id, input.taskId)); return { success: true, status: "accepted" as const }; }),
    updateTaskStatus: testRoleProcedure("restaurant_admin", "waiter", "kitchen", "cashier", "driver").input(z.object({ taskId: z.number().int().positive(), status: z.enum(["published", "reviewing", "accepted", "in_progress", "submitted", "completed", "cancelled"]) })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); await db.update(remoteTasks).set({ status: input.status }).where(eq(remoteTasks.id, input.taskId)); return { success: true, status: input.status }; }),
    sendMessage: protectedProcedure.input(z.object({ taskId: z.number().int().positive(), body: z.string().min(1).max(5000) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const result = await db.insert(taskMessages).values({ taskId: input.taskId, senderUserId: ctx.user.id, body: input.body }); await db.insert(notifications).values({ userId: ctx.user.id, taskId: input.taskId, type: "message", title: "رسالة مهمة جديدة", body: input.body }); return { success: true, id: Number(result[0].insertId) }; }),
  }),
  security: router({
    sessions: protectedProcedure.query(({ ctx }) => listAuthSessions(ctx.user.id)),
    security: protectedProcedure.query(({ ctx }) => getUserSecurity(ctx.user.id)),
    revokeSession: protectedProcedure.input(z.object({ sessionId: z.number().int().positive() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); await db.update(authSessions).set({ revokedAt: new Date() }).where(and(eq(authSessions.id, input.sessionId), eq(authSessions.userId, ctx.user.id))); return { success: true }; }),
    revokeAllSessions: protectedProcedure.mutation(async ({ ctx }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); await db.update(authSessions).set({ revokedAt: new Date() }).where(eq(authSessions.userId, ctx.user.id)); return { success: true }; }),
    setTwoFactor: protectedProcedure.input(z.object({ enabled: z.boolean() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); await db.insert(userSecurity).values({ userId: ctx.user.id, twoFactorEnabled: input.enabled }).onDuplicateKeyUpdate({ set: { twoFactorEnabled: input.enabled } }); return { success: true, enabled: input.enabled }; }),
  }),
  features: router({
    definitions: protectedProcedure.query(() => listFeatureDefinitions()),
    restaurant: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive() })).query(({ input }) => listRestaurantFeatures(input.restaurantId)),
    access: protectedProcedure.input(z.object({ restaurantId: z.number().int().positive(), key: z.string().min(1).max(120) })).query(({ ctx, input }) => { assertRestaurantAccess(ctx, input.restaurantId); return getFeatureAccess(input.restaurantId, input.key); }),
    setOverride: testRoleProcedure("restaurant_admin").input(z.object({ restaurantId: z.number().int().positive(), featureId: z.number().int().positive(), enabled: z.boolean(), limit: z.number().int().nonnegative().nullable().optional(), value: z.string().max(255).nullable().optional() })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Database is not available" }); const existing = await db.select().from(restaurantFeatures).where(and(eq(restaurantFeatures.restaurantId, input.restaurantId), eq(restaurantFeatures.featureId, input.featureId))).limit(1); const values = { enabled: input.enabled, overrideLimit: input.limit ?? null, overrideValue: input.value ?? null }; if (existing[0]) await db.update(restaurantFeatures).set(values).where(eq(restaurantFeatures.id, existing[0].id)); else await db.insert(restaurantFeatures).values({ restaurantId: input.restaurantId, featureId: input.featureId, ...values }); return { success: true }; }),
  }),
  admin: router({
    restaurants: adminProcedure.query(() => listRestaurants()),
    createRestaurant: adminProcedure.input(z.object({ name: z.string().min(2), slug: z.string().min(2).max(160), plan: z.string().min(2).default("Growth") })).mutation(async ({ input }) => { const db = await getDb(); if (!db) throw new Error("Database is not available"); const barcode = `NFOOD-${nanoid(10).toUpperCase()}`; const result = await db.insert(restaurants).values({ ...input, barcode, status: "trial" }); return { success: true, id: Number(result[0].insertId), barcode }; }),
    subscriptions: adminProcedure.input(z.object({ restaurantId: z.number().int().positive().optional() }).optional()).query(({ input }) => listSubscriptions(input?.restaurantId)),
    roles: adminProcedure.input(z.object({ restaurantId: z.number().int().positive().optional() }).optional()).query(({ input }) => listRoles(input?.restaurantId)),
    permissions: adminProcedure.query(() => listPermissions()),
  }),
});

export type AppRouter = typeof appRouter;
