export const TEAM_PERMISSION_CATALOG = [
  { key: "orders.read", label: "عرض الطلبات", group: "الطلبات" },
  { key: "orders.update", label: "تغيير حالات الطلبات", group: "الطلبات" },
  { key: "orders.cancel", label: "إلغاء الطلبات", group: "الطلبات" },
  { key: "pos.manage", label: "إدارة نقاط البيع والكاشير", group: "التشغيل" },
  { key: "kds.manage", label: "إدارة شاشة المطبخ", group: "التشغيل" },
  { key: "bar.manage", label: "إدارة البار والمشروبات", group: "التشغيل" },
  { key: "tables.manage", label: "إدارة الطاولات والتعيينات", group: "الصالة" },
  { key: "queue.manage", label: "إدارة قائمة الانتظار", group: "الصالة" },
  { key: "reception.manage", label: "إدارة الاستقبال وتسجيل الضيوف", group: "الاستقبال" },
  { key: "menu.read", label: "عرض المنيو", group: "المنيو" },
  { key: "menu.manage", label: "إدارة الأصناف والمنيو", group: "المنيو" },
  { key: "inventory.manage", label: "إدارة المخزون والجرد", group: "المخزون" },
  { key: "purchases.manage", label: "إدارة المشتريات والموردين", group: "المشتريات" },
  { key: "reservations.manage", label: "إدارة الحجوزات", group: "الحجوزات" },
  { key: "waiter_calls.read", label: "استقبال نداءات النادل", group: "التشغيل" },
  { key: "waiter_calls.update", label: "تأكيد وإغلاق نداءات النادل", group: "التشغيل" },
  { key: "delivery.manage", label: "إدارة التوصيل والسائقين", group: "التوصيل" },
  { key: "notifications.read", label: "استقبال إشعارات التشغيل والحجوزات", group: "الإشعارات" },
  { key: "studio.manage", label: "إدارة مساحة الاستوديو", group: "الاستوديو" },
  { key: "reports.read", label: "عرض التقارير التشغيلية", group: "التقارير" },
  { key: "finance.read", label: "عرض البيانات المالية", group: "المحاسبة" },
  { key: "finance.manage", label: "إدارة الحسابات والتسويات والمصروفات", group: "المحاسبة" },
  { key: "payroll.manage", label: "إدارة الرواتب والمستحقات", group: "المحاسبة" },
  { key: "team.manage", label: "إدارة الفريق والحسابات", group: "شؤون الموظفين" },
  { key: "hr.manage", label: "إدارة ملفات الموظفين والعقود والإجازات", group: "شؤون الموظفين" },
  { key: "attendance.manage", label: "إدارة الحضور والانصراف والورديات", group: "شؤون الموظفين" },
  { key: "assignments.manage", label: "إدارة تعيينات الموظفين والفروع والأقسام", group: "شؤون الموظفين" },
  { key: "customers.read", label: "عرض عملاء المطعم", group: "العملاء" },
  { key: "customers.password_reset", label: "تعيين كلمة مرور العميل", group: "العملاء" },
  { key: "settings.manage", label: "إدارة إعدادات المطعم", group: "الإدارة" },
  { key: "printers.manage", label: "إدارة الطابعات وقوالب الطباعة", group: "التشغيل" },
  { key: "translations.manage", label: "محرر ترجمة", group: "المنصة" },
] as const;

export type TeamPermission = (typeof TEAM_PERMISSION_CATALOG)[number]["key"];
export const DEFAULT_TEAM_ROLE_PERMISSIONS: Record<string, TeamPermission[]> = {
  restaurant_admin: TEAM_PERMISSION_CATALOG.map((permission) => permission.key),
  manager: ["orders.read","orders.update","orders.cancel","pos.manage","kds.manage","bar.manage","tables.manage","queue.manage","reception.manage","menu.read","menu.manage","inventory.manage","purchases.manage","reservations.manage","waiter_calls.read","waiter_calls.update","delivery.manage","notifications.read","reports.read","finance.read","team.manage","hr.manage","attendance.manage","assignments.manage","customers.read","settings.manage","printers.manage"],
  supervisor: ["orders.read","orders.update","pos.manage","kds.manage","bar.manage","tables.manage","queue.manage","reception.manage","menu.read","inventory.manage","reservations.manage","waiter_calls.read","waiter_calls.update","delivery.manage","notifications.read","reports.read","attendance.manage","assignments.manage","customers.read"],
  receptionist: ["orders.read","tables.manage","queue.manage","reception.manage","menu.read","reservations.manage","waiter_calls.read","notifications.read","customers.read"],
  accountant: ["orders.read","purchases.manage","reports.read","finance.read","finance.manage","payroll.manage","notifications.read"],
  hr: ["team.manage","hr.manage","attendance.manage","assignments.manage","payroll.manage","reports.read","notifications.read"],
  waiter: ["orders.read","orders.update","tables.manage","menu.read","reservations.manage","waiter_calls.read","waiter_calls.update","notifications.read"],
  kitchen: ["orders.read","orders.update","kds.manage","menu.read","inventory.manage","notifications.read"],
  bar: ["orders.read","orders.update","bar.manage","menu.read","inventory.manage","notifications.read"],
  cashier: ["orders.read","orders.update","orders.cancel","pos.manage","menu.read","finance.read","notifications.read"],
  driver: ["orders.read","orders.update","delivery.manage","notifications.read"],
  inventory: ["inventory.manage","purchases.manage","reports.read","notifications.read"],
  purchasing: ["inventory.manage","purchases.manage","finance.read","reports.read","notifications.read"],
  reservations: ["tables.manage","queue.manage","reception.manage","reservations.manage","customers.read","notifications.read"],
  customer: ["menu.read","orders.read"],
  translation_editor: ["translations.manage"],
};

export function roleHasDefaultPermission(role: string | undefined, permission: TeamPermission) {
  return Boolean(role && DEFAULT_TEAM_ROLE_PERMISSIONS[role]?.includes(permission));
}
