export const TEAM_PERMISSION_CATALOG = [
  { key: "orders.read", label: "عرض الطلبات", group: "الطلبات" },
  { key: "orders.create", label: "إنشاء طلب يدوي", group: "الطلبات" },
  { key: "orders.update", label: "تعديل الطلب وتغيير حالته", group: "الطلبات" },
  { key: "orders.transfer", label: "نقل الطلب بين الطاولات", group: "الطلبات" },
  { key: "orders.cancel_item", label: "إلغاء صنف من الطلب", group: "الطلبات" },
  { key: "orders.cancel", label: "إلغاء الطلب بالكامل", group: "الطلبات" },
  { key: "orders.discount", label: "تطبيق خصم على الطلب", group: "الطلبات" },
  { key: "orders.complimentary", label: "ضيافة / طلب مجاني", group: "الطلبات" },
  { key: "orders.refund", label: "استرجاع مبلغ", group: "الطلبات" },
  { key: "orders.print", label: "طباعة وإعادة طباعة الطلب", group: "الطلبات" },
  { key: "pos.manage", label: "استخدام نقطة البيع", group: "الكاشير وPOS" },
  { key: "pos.shift_open", label: "فتح وردية الكاشير", group: "الكاشير وPOS" },
  { key: "pos.shift_close", label: "إغلاق وردية الكاشير", group: "الكاشير وPOS" },
  { key: "pos.cash_drawer", label: "فتح درج النقد", group: "الكاشير وPOS" },
  { key: "pos.split_bill", label: "تقسيم الفاتورة", group: "الكاشير وPOS" },
  { key: "pos.settlement", label: "تسوية فرق الصندوق", group: "الكاشير وPOS" },
  { key: "kds.manage", label: "إدارة شاشة المطبخ", group: "المطبخ" },
  { key: "kds.prepare", label: "بدء وإنهاء التحضير", group: "المطبخ" },
  { key: "kds.sold_out", label: "تعليم صنف نافد", group: "المطبخ" },
  { key: "bar.manage", label: "إدارة البار والمشروبات", group: "البار والمقهى" },
  { key: "bar.prepare", label: "بدء وإنهاء تحضير المشروبات", group: "البار والمقهى" },
  { key: "tables.manage", label: "إدارة الطاولات", group: "الصالة والطاولات" },
  { key: "tables.assign", label: "تعيين ونقل النادل", group: "الصالة والطاولات" },
  { key: "tables.transfer", label: "نقل ودمج الطاولات", group: "الصالة والطاولات" },
  { key: "tables.fees", label: "إدارة رسوم الجلوس والحد الأدنى", group: "الصالة والطاولات" },
  { key: "tables.qr", label: "إدارة QR للطاولات", group: "الصالة والطاولات" },
  { key: "queue.manage", label: "إدارة قائمة الانتظار", group: "الاستقبال والحجوزات" },
  { key: "reception.manage", label: "إدارة الاستقبال وتسجيل الضيوف", group: "الاستقبال والحجوزات" },
  { key: "reservations.read", label: "عرض الحجوزات", group: "الاستقبال والحجوزات" },
  { key: "reservations.manage", label: "إنشاء وتعديل وإلغاء الحجوزات", group: "الاستقبال والحجوزات" },
  { key: "waiter_calls.read", label: "استقبال نداءات العملاء", group: "خدمة العملاء" },
  { key: "waiter_calls.update", label: "قبول وإغلاق نداءات العملاء", group: "خدمة العملاء" },
  { key: "menu.read", label: "عرض المنيو", group: "المنيو" },
  { key: "menu.manage", label: "إدارة الأصناف والفئات", group: "المنيو" },
  { key: "menu.prices", label: "تعديل الأسعار والخصومات", group: "المنيو" },
  { key: "menu.availability", label: "إخفاء صنف أو تعليمه نافدًا", group: "المنيو" },
  { key: "inventory.read", label: "عرض المخزون", group: "المخزون" },
  { key: "inventory.manage", label: "إدارة المخزون والجرد", group: "المخزون" },
  { key: "inventory.adjust", label: "تسوية وهالك المخزون", group: "المخزون" },
  { key: "inventory.transfer", label: "تحويل مخزون بين الفروع", group: "المخزون" },
  { key: "purchases.read", label: "عرض المشتريات", group: "المشتريات" },
  { key: "purchases.manage", label: "إدارة طلبات الشراء والموردين", group: "المشتريات" },
  { key: "purchases.approve", label: "اعتماد أو رفض المشتريات", group: "المشتريات" },
  { key: "purchases.receive", label: "استلام البضاعة والفواتير", group: "المشتريات" },
  { key: "delivery.manage", label: "إدارة التوصيل والسائقين", group: "التوصيل" },
  { key: "delivery.assign", label: "تعيين وإعادة تعيين السائق", group: "التوصيل" },
  { key: "delivery.collect", label: "تأكيد التحصيل النقدي", group: "التوصيل" },
  { key: "notifications.read", label: "استقبال إشعارات التشغيل", group: "الإشعارات" },
  { key: "reports.read", label: "عرض التقارير التشغيلية", group: "التقارير" },
  { key: "reports.export", label: "تصدير التقارير", group: "التقارير" },
  { key: "finance.read", label: "عرض البيانات المالية", group: "المحاسبة" },
  { key: "finance.manage", label: "إدارة الحسابات والمصروفات", group: "المحاسبة" },
  { key: "finance.close_day", label: "إقفال اليوم المالي", group: "المحاسبة" },
  { key: "payroll.manage", label: "إدارة الرواتب والمستحقات", group: "المحاسبة" },
  { key: "team.manage", label: "إدارة حسابات الموظفين", group: "الموظفون وHR" },
  { key: "hr.manage", label: "إدارة الملفات والعقود والإجازات", group: "الموظفون وHR" },
  { key: "attendance.manage", label: "إدارة الحضور والانصراف والورديات", group: "الموظفون وHR" },
  { key: "assignments.manage", label: "إدارة الفروع والأقسام والتعيينات", group: "الموظفون وHR" },
  { key: "permissions.manage", label: "منح وتعديل صلاحيات الموظفين", group: "الموظفون وHR" },
  { key: "customers.read", label: "عرض العملاء", group: "العملاء" },
  { key: "customers.password_reset", label: "إعادة تعيين كلمة مرور العميل", group: "العملاء" },
  { key: "settings.manage", label: "إدارة إعدادات المطعم", group: "الإدارة" },
  { key: "branches.manage", label: "إدارة الفروع", group: "الإدارة" },
  { key: "printers.manage", label: "إدارة الطابعات وقوالب الطباعة", group: "الإدارة" },
  { key: "studio.manage", label: "إدارة مساحة الاستوديو", group: "الاستوديو" },
  { key: "translations.manage", label: "إدارة الترجمات", group: "الإدارة" },
] as const;

export type TeamPermission = (typeof TEAM_PERMISSION_CATALOG)[number]["key"];
export const DEFAULT_TEAM_ROLE_PERMISSIONS: Record<string, TeamPermission[]> = {
  owner: TEAM_PERMISSION_CATALOG.map((permission) => permission.key),
  restaurant_admin: TEAM_PERMISSION_CATALOG.map((permission) => permission.key),
  manager: ["orders.read","orders.create","orders.update","orders.transfer","orders.cancel_item","orders.cancel","orders.discount","orders.print","pos.manage","pos.shift_open","pos.shift_close","kds.manage","bar.manage","tables.manage","tables.assign","tables.transfer","queue.manage","reception.manage","reservations.read","reservations.manage","waiter_calls.read","waiter_calls.update","menu.read","menu.manage","menu.availability","inventory.read","inventory.manage","purchases.read","purchases.manage","delivery.manage","notifications.read","reports.read","finance.read","team.manage","hr.manage","attendance.manage","assignments.manage","permissions.manage","customers.read","settings.manage","printers.manage"],
  supervisor: ["orders.read","orders.create","orders.update","orders.transfer","orders.cancel_item","orders.print","pos.manage","kds.manage","bar.manage","tables.manage","tables.assign","queue.manage","reception.manage","reservations.read","reservations.manage","waiter_calls.read","waiter_calls.update","menu.read","menu.availability","inventory.read","delivery.manage","notifications.read","reports.read","attendance.manage","assignments.manage","customers.read"],
  receptionist: ["orders.read","tables.manage","queue.manage","reception.manage","reservations.read","reservations.manage","waiter_calls.read","notifications.read","customers.read"],
  accountant: ["orders.read","purchases.read","reports.read","reports.export","finance.read","finance.manage","finance.close_day","payroll.manage","notifications.read"],
  hr: ["team.manage","hr.manage","attendance.manage","assignments.manage","permissions.manage","payroll.manage","reports.read","notifications.read"],
  waiter: ["orders.read","orders.create","orders.update","orders.print","tables.manage","menu.read","reservations.read","waiter_calls.read","waiter_calls.update","notifications.read"],
  kitchen: ["orders.read","orders.update","kds.manage","kds.prepare","kds.sold_out","menu.read","inventory.read","notifications.read"],
  bar: ["orders.read","orders.update","bar.manage","bar.prepare","menu.read","inventory.read","notifications.read"],
  barista: ["orders.read","orders.update","bar.manage","bar.prepare","menu.read","inventory.read","notifications.read"],
  cashier: ["orders.read","orders.create","orders.update","orders.print","pos.manage","pos.shift_open","pos.shift_close","pos.split_bill","menu.read","notifications.read"],
  driver: ["orders.read","orders.update","delivery.manage","notifications.read"],
  inventory: ["inventory.read","inventory.manage","inventory.adjust","inventory.transfer","purchases.read","reports.read","notifications.read"],
  purchasing: ["inventory.read","purchases.read","purchases.manage","purchases.receive","reports.read","notifications.read"],
  reservations: ["tables.manage","queue.manage","reception.manage","reservations.read","reservations.manage","customers.read","notifications.read"],
  customer: ["menu.read","orders.read"],
  translation_editor: ["translations.manage"],
};

export function roleHasDefaultPermission(role: string | undefined, permission: TeamPermission) {
  return Boolean(role && DEFAULT_TEAM_ROLE_PERMISSIONS[role]?.includes(permission));
}
