import { eq } from "drizzle-orm";
import { getDb } from "../server/db";
import { marketplaceListings, marketplaceSectors, marketplaceStorefrontSettings, platformEntities, storeCoupons, type PlatformSectorKey } from "../drizzle/schema";

const demos: Array<{sector: PlatformSectorKey; sectorAr:string; sectorEn:string; store:string; city:string; coupon:string; discount:number; cover:string; products:Array<[string,string,number,number|null,string,Record<string,unknown>]>}> = [
 {sector:"restaurant",sectorAr:"مطاعم",sectorEn:"Restaurants",store:"مذاق نجد",city:"الرياض",coupon:"TASTE15",discount:15,cover:"https://images.unsplash.com/photo-1517248135467-4c7edcad34c5",products:[["كبسة دجاج","الأطباق الرئيسية",42,49,"وجبة",{calories:720}],["برجر لحم","البرجر",29,35,"وجبة",{calories:610}],["سلطة فتوش","المقبلات",18,null,"طبق",{calories:180}],["موهيتو ليمون","المشروبات",14,18,"كوب",{calories:120}]]},
 {sector:"vegetables",sectorAr:"خضار وفواكه",sectorEn:"Fruit & Vegetables",store:"حصاد اليوم",city:"الرياض",coupon:"FRESH10",discount:10,cover:"https://images.unsplash.com/photo-1610348725531-843dff563e2c",products:[["طماطم محلية","الخضار",7,9,"كجم",{}],["برتقال","الفواكه",12,15,"كجم",{}],["سلة خضار أسبوعية","السلال",69,79,"سلة",{}],["تمر سكري","التمور",32,null,"كجم",{}]]},
 {sector:"grocery",sectorAr:"بقالة",sectorEn:"Grocery",store:"سلة البيت",city:"الرياض",coupon:"BASKET20",discount:20,cover:"https://images.unsplash.com/photo-1542838132-92c53300491e",products:[["أرز بسمتي 5 كجم","المواد الغذائية",39,45,"عبوة",{}],["حليب كامل الدسم","الألبان",7,null,"لتر",{}],["مياه 40 عبوة","المشروبات",18,22,"كرتون",{}],["مناديل عائلية","المنزل",24,29,"عبوة",{}]]},
 {sector:"laundry",sectorAr:"مغاسل",sectorEn:"Laundry",store:"نظيف بلس",city:"الرياض",coupon:"CLEAN15",discount:15,cover:"https://images.unsplash.com/photo-1545173168-9f1947eebb7f",products:[["غسيل وكوي ثوب","ملابس رجالية",12,15,"قطعة",{duration:"24 ساعة"}],["غسيل عباية","ملابس نسائية",18,22,"قطعة",{duration:"24 ساعة"}],["تنظيف بدلة","تنظيف جاف",35,45,"قطعة",{duration:"48 ساعة"}],["غسيل بطانية","المفروشات",30,null,"قطعة",{duration:"48 ساعة"}]]},
 {sector:"automotive",sectorAr:"سيارات",sectorEn:"Automotive",store:"درايف هاوس",city:"الرياض",coupon:"DRIVE5",discount:5,cover:"https://images.unsplash.com/photo-1492144534655-ae79c964c9d7",products:[["SUV X7 2026","SUV",134900,139900,"سيارة",{year:2026,mileage:0,finance:true}],["Sedan S5 2025","سيدان",89900,94900,"سيارة",{year:2025,mileage:1200,finance:true}],["City C3 2024","اقتصادية",62900,null,"سيارة",{year:2024,mileage:8500}],["EV E1","كهربائية",119900,125000,"سيارة",{year:2026,mileage:0,finance:true}]]},
 {sector:"beauty_salon",sectorAr:"صالونات وتجميل",sectorEn:"Beauty",store:"لمسة سبا",city:"الرياض",coupon:"RELAX20",discount:20,cover:"https://images.unsplash.com/photo-1560066984-138dadb4c035",products:[["عناية بالبشرة","العناية بالبشرة",180,220,"جلسة",{duration:"60 دقيقة"}],["مانيكير وباديكير","الأظافر",140,170,"جلسة",{duration:"75 دقيقة"}],["تصفيف شعر","الشعر",120,null,"جلسة",{duration:"45 دقيقة"}],["باقة سبا","الباقات",299,360,"جلسة",{duration:"120 دقيقة"}]]},
 {sector:"public_works",sectorAr:"خدمات وأعمال",sectorEn:"Services",store:"بيتك برو",city:"الرياض",coupon:"HOME10",discount:10,cover:"https://images.unsplash.com/photo-1581578731548-c64695cc6952",products:[["صيانة تكييف","التكييف",180,220,"زيارة",{duration:"60 دقيقة"}],["سباكة منزلية","السباكة",150,null,"زيارة",{duration:"60 دقيقة"}],["كهربائي","الكهرباء",160,190,"زيارة",{duration:"60 دقيقة"}],["تنظيف منزل","التنظيف",249,299,"خدمة",{duration:"3 ساعات"}]]},
 {sector:"fashion",sectorAr:"أزياء",sectorEn:"Fashion",store:"لوما فاشن",city:"الرياض",coupon:"STYLE15",discount:15,cover:"https://images.unsplash.com/photo-1445205170230-053b83016050",products:[["عباية كلاسيك","عبايات",199,249,"قطعة",{sizes:["S","M","L","XL"],colors:["أسود","كحلي"]}],["قميص كتان","رجالي",129,159,"قطعة",{sizes:["S","M","L","XL"]}],["حقيبة يومية","إكسسوارات",169,199,"قطعة",{colors:["بيج","أسود"]}],["فستان سهرة","فساتين",349,429,"قطعة",{sizes:["S","M","L"]}]]},
 {sector:"sweets",sectorAr:"حلويات",sectorEn:"Sweets",store:"سكر وزعفران",city:"الرياض",coupon:"SWEET12",discount:12,cover:"https://images.unsplash.com/photo-1578985545062-69928b1d9587",products:[["كيكة شوكولاتة","الكيك",120,145,"حبة",{}],["بوكس ميني حلى","البوكسات",89,99,"بوكس",{}],["تشيز كيك","التشيز كيك",110,null,"حبة",{}],["معمول فاخر","المعمول",65,75,"كجم",{}]]},
];

const extraProducts: Record<PlatformSectorKey, Array<[string,string,number,number|null,string,Record<string,unknown>]>> = {
 restaurant:[["مندي دجاج","الأطباق الرئيسية",39,45,"وجبة",{calories:690}],["مظبي لحم","الأطباق الرئيسية",58,65,"وجبة",{calories:810}],["شاورما دجاج","السندويتشات",18,22,"وجبة",{calories:430}],["برجر دجاج","البرجر",26,31,"وجبة",{calories:540}],["حمص","المقبلات",12,null,"طبق",{calories:240}],["متبل","المقبلات",13,15,"طبق",{calories:210}],["تبولة","السلطات",16,null,"طبق",{calories:150}],["سلطة سيزر","السلطات",24,28,"طبق",{calories:330}],["بطاطس مقلية","الإضافات",10,null,"طبق",{calories:310}],["أرز بشاور","الإضافات",9,null,"طبق",{calories:280}],["كنافة","الحلويات",19,23,"قطعة",{calories:390}],["أم علي","الحلويات",18,null,"طبق",{calories:410}],["عصير برتقال","المشروبات",13,16,"كوب",{calories:110}],["شاي أحمر","المشروبات",6,null,"كوب",{calories:20}],["قهوة عربية","المشروبات",10,null,"دلة",{calories:35}],["مياه معدنية","المشروبات",3,null,"عبوة",{calories:0}]],
 vegetables:[["خيار","الخضار",6,null,"كجم",{}],["بطاطس","الخضار",5,7,"كجم",{}],["بصل أحمر","الخضار",6,null,"كجم",{}],["فلفل رومي","الخضار",11,13,"كجم",{}],["كوسة","الخضار",8,null,"كجم",{}],["جزر","الخضار",7,null,"كجم",{}],["خس","الخضار",5,null,"حبة",{}],["باذنجان","الخضار",7,9,"كجم",{}],["تفاح أحمر","الفواكه",14,17,"كجم",{}],["موز","الفواكه",9,null,"كجم",{}],["عنب","الفواكه",18,22,"كجم",{}],["مانجو","الفواكه",16,null,"كجم",{}],["ليمون","الفواكه",8,null,"كجم",{}],["رمان","الفواكه",17,20,"كجم",{}],["سلة فواكه","السلال",79,89,"سلة",{}],["تمر خلاص","التمور",28,null,"كجم",{}]],
 grocery:[["سكر 2 كجم","المواد الغذائية",11,null,"عبوة",{}],["زيت دوار الشمس","المواد الغذائية",18,21,"عبوة",{}],["مكرونة","المواد الغذائية",6,null,"عبوة",{}],["طحين 2 كجم","المواد الغذائية",9,null,"عبوة",{}],["تونة","المعلبات",8,10,"علبة",{}],["فول مدمس","المعلبات",4,null,"علبة",{}],["لبن","الألبان",6,null,"لتر",{}],["زبادي 6 حبات","الألبان",12,14,"عبوة",{}],["جبنة كريمية","الألبان",14,null,"عبوة",{}],["عصير برتقال","المشروبات",10,null,"لتر",{}],["مشروب غازي","المشروبات",4,null,"عبوة",{}],["قهوة سريعة","المشروبات",22,26,"عبوة",{}],["منظف أرضيات","المنزل",15,null,"عبوة",{}],["سائل صحون","المنزل",11,13,"عبوة",{}],["أكياس نفايات","المنزل",13,null,"عبوة",{}],["ورق ألمنيوم","المنزل",12,null,"عبوة",{}]],
 laundry:[["غسيل ثوب","ملابس رجالية",8,null,"قطعة",{duration:"24 ساعة"}],["كوي ثوب","ملابس رجالية",6,null,"قطعة",{duration:"12 ساعة"}],["غسيل شماغ","ملابس رجالية",7,null,"قطعة",{duration:"24 ساعة"}],["غسيل قميص","ملابس رجالية",7,null,"قطعة",{duration:"24 ساعة"}],["غسيل فستان","ملابس نسائية",25,30,"قطعة",{duration:"48 ساعة"}],["كوي عباية","ملابس نسائية",10,null,"قطعة",{duration:"12 ساعة"}],["غسيل تنورة","ملابس نسائية",12,null,"قطعة",{duration:"24 ساعة"}],["تنظيف جاكيت","تنظيف جاف",28,32,"قطعة",{duration:"48 ساعة"}],["تنظيف معطف","تنظيف جاف",35,null,"قطعة",{duration:"48 ساعة"}],["تنظيف سجادة صغيرة","المفروشات",25,null,"قطعة",{duration:"72 ساعة"}],["تنظيف سجادة كبيرة","المفروشات",55,65,"قطعة",{duration:"72 ساعة"}],["غسيل لحاف","المفروشات",35,null,"قطعة",{duration:"48 ساعة"}],["غسيل ستارة","المفروشات",20,null,"متر",{duration:"72 ساعة"}],["تنظيف كنبة","المفروشات",45,55,"مقعد",{duration:"زيارة"}],["تعقيم ملابس","خدمات إضافية",8,null,"طلب",{duration:"24 ساعة"}],["توصيل واستلام","خدمات إضافية",15,null,"طلب",{duration:"حسب الموقع"}]],
 automotive:[["SUV X5 2025","SUV",119900,124900,"سيارة",{year:2025,mileage:4200,finance:true}],["SUV X3 2024","SUV",94900,null,"سيارة",{year:2024,mileage:11000}],["Sedan S7 2026","سيدان",109900,115000,"سيارة",{year:2026,mileage:0,finance:true}],["Sedan S3 2024","سيدان",71900,null,"سيارة",{year:2024,mileage:18000}],["City C2 2025","اقتصادية",68900,72900,"سيارة",{year:2025,mileage:6000}],["City C1 2023","اقتصادية",49900,null,"سيارة",{year:2023,mileage:29000}],["EV E2","كهربائية",139900,145000,"سيارة",{year:2026,mileage:0,finance:true}],["EV E3","كهربائية",159900,null,"سيارة",{year:2026,mileage:0,finance:true}],["Pickup P5","بيك أب",128900,134900,"سيارة",{year:2025,mileage:2500,finance:true}],["Pickup P3","بيك أب",99900,null,"سيارة",{year:2024,mileage:14000}],["Coupe C8","رياضية",189900,199900,"سيارة",{year:2025,mileage:3500}],["Sport R2","رياضية",229900,null,"سيارة",{year:2026,mileage:0}],["Van V5","فان",114900,119900,"سيارة",{year:2025,mileage:5000}],["Van V3","فان",89900,null,"سيارة",{year:2024,mileage:17000}],["4x4 D9","دفع رباعي",174900,184900,"سيارة",{year:2026,mileage:0,finance:true}],["4x4 D7","دفع رباعي",149900,null,"سيارة",{year:2025,mileage:8000}]],
 beauty_salon:[["قص شعر","الشعر",80,null,"جلسة",{duration:"30 دقيقة"}],["صبغة شعر","الشعر",250,290,"جلسة",{duration:"120 دقيقة"}],["بروتين شعر","الشعر",350,420,"جلسة",{duration:"150 دقيقة"}],["تسريحة مناسبة","الشعر",180,220,"جلسة",{duration:"60 دقيقة"}],["تنظيف بشرة","العناية بالبشرة",160,null,"جلسة",{duration:"60 دقيقة"}],["هيدرافيشل","العناية بالبشرة",260,310,"جلسة",{duration:"75 دقيقة"}],["ماسك ترطيب","العناية بالبشرة",90,null,"جلسة",{duration:"30 دقيقة"}],["مساج استرخاء","السبا",220,260,"جلسة",{duration:"60 دقيقة"}],["مساج أحجار ساخنة","السبا",280,null,"جلسة",{duration:"75 دقيقة"}],["حمام مغربي","السبا",240,290,"جلسة",{duration:"90 دقيقة"}],["باديكير","الأظافر",85,null,"جلسة",{duration:"45 دقيقة"}],["مانيكير","الأظافر",75,null,"جلسة",{duration:"40 دقيقة"}],["جل أظافر","الأظافر",110,130,"جلسة",{duration:"60 دقيقة"}],["مكياج ناعم","المكياج",200,null,"جلسة",{duration:"60 دقيقة"}],["مكياج سهرة","المكياج",320,380,"جلسة",{duration:"90 دقيقة"}],["باقة عروس","الباقات",899,1050,"باقة",{duration:"180 دقيقة"}]],
 public_works:[["كشف تسربات","السباكة",220,260,"زيارة",{duration:"90 دقيقة"}],["تغيير خلاط","السباكة",120,null,"زيارة",{duration:"45 دقيقة"}],["تسليك صرف","السباكة",180,null,"زيارة",{duration:"60 دقيقة"}],["تركيب إنارة","الكهرباء",130,null,"زيارة",{duration:"60 دقيقة"}],["فحص لوحة كهرباء","الكهرباء",200,240,"زيارة",{duration:"90 دقيقة"}],["تركيب مفتاح","الكهرباء",90,null,"زيارة",{duration:"30 دقيقة"}],["تنظيف مكيف سبليت","التكييف",120,null,"وحدة",{duration:"60 دقيقة"}],["تعبئة فريون","التكييف",190,220,"وحدة",{duration:"60 دقيقة"}],["تركيب مكيف","التكييف",350,null,"وحدة",{duration:"120 دقيقة"}],["تنظيف شقة","التنظيف",199,239,"خدمة",{duration:"3 ساعات"}],["تنظيف فيلا","التنظيف",399,469,"خدمة",{duration:"5 ساعات"}],["تنظيف خزانات","التنظيف",280,null,"خدمة",{duration:"3 ساعات"}],["مكافحة حشرات","خدمات منزلية",250,300,"خدمة",{duration:"2 ساعة"}],["دهان غرفة","خدمات منزلية",450,null,"خدمة",{duration:"يوم"}],["تركيب ستائر","خدمات منزلية",180,null,"زيارة",{duration:"90 دقيقة"}],["تركيب أثاث","خدمات منزلية",220,260,"زيارة",{duration:"120 دقيقة"}]],
 fashion:[["عباية كلوش","عبايات",229,269,"قطعة",{sizes:["S","M","L","XL"]}],["عباية رسمية","عبايات",279,329,"قطعة",{sizes:["S","M","L","XL"]}],["قميص رسمي","رجالي",149,179,"قطعة",{sizes:["S","M","L","XL"]}],["تيشيرت قطن","رجالي",79,null,"قطعة",{sizes:["S","M","L","XL"]}],["بنطال كلاسيك","رجالي",139,159,"قطعة",{sizes:["30","32","34","36"]}],["فستان يومي","فساتين",229,null,"قطعة",{sizes:["S","M","L"]}],["فستان ميدي","فساتين",289,329,"قطعة",{sizes:["S","M","L"]}],["طقم نسائي","نسائي",249,null,"طقم",{sizes:["S","M","L"]}],["بلوزة ساتان","نسائي",119,139,"قطعة",{sizes:["S","M","L"]}],["تنورة ميدي","نسائي",129,null,"قطعة",{sizes:["S","M","L"]}],["حقيبة كتف","إكسسوارات",189,219,"قطعة",{}],["محفظة جلد","إكسسوارات",99,null,"قطعة",{}],["حزام جلد","إكسسوارات",89,null,"قطعة",{}],["نظارة شمسية","إكسسوارات",149,179,"قطعة",{}],["شال فاخر","إكسسوارات",79,null,"قطعة",{}],["حذاء كاجوال","أحذية",219,249,"زوج",{sizes:["38","39","40","41","42"]}]],
 sweets:[["كيكة فانيلا","الكيك",105,null,"حبة",{}],["كيكة ريد فيلفت","الكيك",135,155,"حبة",{}],["كيكة زعفران","الكيك",145,null,"حبة",{}],["ميني كيك 6 حبات","البوكسات",75,85,"بوكس",{}],["بوكس ضيافة","البوكسات",129,149,"بوكس",{}],["بوكس شوكولاتة","البوكسات",110,null,"بوكس",{}],["تشيز كيك لوتس","التشيز كيك",125,140,"حبة",{}],["تشيز كيك توت","التشيز كيك",120,null,"حبة",{}],["معمول تمر","المعمول",55,null,"كجم",{}],["معمول فستق","المعمول",85,95,"كجم",{}],["بقلاوة مشكلة","حلويات شرقية",95,110,"كجم",{}],["كنافة جبن","حلويات شرقية",70,null,"صينية",{}],["بسبوسة","حلويات شرقية",45,null,"صينية",{}],["كوكيز شوكولاتة","كوكيز",48,55,"بوكس",{}],["براونيز","كوكيز",58,null,"بوكس",{}],["تارت فواكه","التارت",95,110,"حبة",{}]]
};
for (const demo of demos) demo.products.push(...extraProducts[demo.sector]);

async function main(){
 const db=await getDb(); if(!db) throw new Error("DATABASE_URL is required");
 for(let i=0;i<demos.length;i++){
  const d=demos[i], entityId=("demo_"+d.sector).slice(0,30);
  await db.insert(marketplaceSectors).values({slug:d.sector,labelAr:d.sectorAr,labelEn:d.sectorEn,labelFr:d.sectorEn,sortOrder:i,isActive:true}).onDuplicateKeyUpdate({set:{labelAr:d.sectorAr,labelEn:d.sectorEn,isActive:true}});
  const sector=(await db.select().from(marketplaceSectors).where(eq(marketplaceSectors.slug,d.sector)).limit(1))[0];
  await db.insert(platformEntities).values({id:entityId,customerName:d.store,email:`${d.sector}@demo.nfood.local`,countryCode:"SA",city:d.city,timezone:"Asia/Riyadh",currencyCode:"SAR",primaryLanguage:"ar",sector:d.sector,status:true,plan:"Pro",taxId:`DEMO-${String(i+1).padStart(3,"0")}`}).onDuplicateKeyUpdate({set:{customerName:d.store,countryCode:"SA",city:d.city,sector:d.sector,status:true}});
  await db.delete(marketplaceListings).where(eq(marketplaceListings.entityId,entityId));
  await db.delete(storeCoupons).where(eq(storeCoupons.entityId,entityId));
  await db.insert(marketplaceStorefrontSettings).values({entityId,heroTitle:d.store,heroSubtitle:`متجر تجريبي متكامل لنشاط ${d.sectorAr}`,coverUrl:d.cover,sectorConfigJson:JSON.stringify({gallery:[d.cover],businessHours:{daily:["09:00","23:00"]}}),isPublished:true}).onDuplicateKeyUpdate({set:{heroTitle:d.store,coverUrl:d.cover,isPublished:true}});
  await db.insert(marketplaceListings).values(d.products.map((p,n)=>({entityId,sectorId:sector.id,title:p[0],description:`${p[1]} — خيار مختار من ${d.store}`,imageUrl:d.cover,price:p[2].toFixed(2),compareAtPrice:p[3]?.toFixed(2)??null,currencyCode:"SAR",unit:p[4],stockQuantity:d.sector==="automotive"?1:25,status:"active" as const,isFeatured:n===0,sortOrder:n,tagsJson:JSON.stringify([p[1]]),metadataJson:JSON.stringify({category:p[1],...p[5]})})));
  await db.insert(storeCoupons).values({entityId,code:d.coupon,description:`خصم تجريبي لنشاط ${d.sectorAr}`,discountType:"percent",discountValue:d.discount.toFixed(2),minOrderAmount:"0.00",perUserLimit:1,isActive:true});
 }
 console.log(`Seeded ${demos.length} demo stores with 20 items per sector, categories, discounts and coupons.`);
}
main().catch((e)=>{console.error(e);process.exit(1)});