import { eq } from "drizzle-orm";
import { getDb } from "../server/db";
import { marketplaceListings, marketplaceSectors, marketplaceStorefrontSettings, platformEntities, storeCoupons, type PlatformSectorKey } from "../drizzle/schema";

const demos: Array<{sector: PlatformSectorKey; sectorAr:string; sectorEn:string; store:string; city:string; coupon:string; discount:number; cover:string; products:Array<[string,string,number,number|null,string,Record<string,unknown>]>}> = [
 {sector:"restaurant",sectorAr:"مطاعم",sectorEn:"Restaurants",store:"مذاق نجد",city:"الرياض",coupon:"TASTE15",discount:15,cover:"https://images.unsplash.com/photo-1517248135467-4c7edcad34c5",products:[["كبسة دجاج","الأطباق الرئيسية",42,49,"وجبة",{calories:720}],["برجر لحم","البرجر",29,35,"وجبة",{calories:610}],["سلطة فتوش","المقبلات",18,null,"طبق",{calories:180}],["موهيتو ليمون","المشروبات",14,18,"كوب",{calories:120}]]},
 {sector:"vegetables",sectorAr:"خضار وفواكه",sectorEn:"Fruit & Vegetables",store:"حصاد اليوم",city:"الرياض",coupon:"FRESH10",discount:10,cover:"https://images.unsplash.com/photo-1610348725531-843dff563e2c",products:[["طماطم محلية","الخضار",7,9,"كجم",{}],["برتقال","الفواكه",12,15,"كجم",{}],["سلة خضار أسبوعية","السلال",69,79,"سلة",{}],["تمر سكري","التمور",32,null,"كجم",{}]]},
 {sector:"grocery",sectorAr:"بقالة",sectorEn:"Grocery",store:"سلة البيت",city:"الرياض",coupon:"BASKET20",discount:20,cover:"https://images.unsplash.com/photo-1542838132-92c53300491e",products:[["أرز بسمتي 5 كجم","المواد الغذائية",39,45,"عبوة",{}],["حليب كامل الدسم","الألبان",7,null,"لتر",{}],["مياه 40 عبوة","المشروبات",18,22,"كرتون",{}],["مناديل عائلية","المنزل",24,29,"عبوة",{}]]},
 {sector:"laundry",sectorAr:"مغاسل",sectorEn:"Laundry",store:"نظيف بلس",city:"الرياض",coupon:"CLEAN15",discount:15,cover:"https://images.unsplash.com/photo-1545173168-9f1947eebb7f",products:[["غسيل وكوي ثوب","ملابس رجالية",12,15,"قطعة",{duration:"24 ساعة"}],["غسيل عباية","ملابس نسائية",18,22,"قطعة",{duration:"24 ساعة"}],["تنظيف بدلة","تنظيف جاف",35,45,"قطعة",{duration:"48 ساعة"}],["غسيل بطانية","المفروشات",30,null,"قطعة",{duration:"48 ساعة"}]]},
 {sector:"automotive",sectorAr:"سيارات",sectorEn:"Automotive",store:"درايف هاوس",city:"الرياض",coupon:"DRIVE5",discount:5,cover:"https://images.unsplash.com/photo-1492144534655-ae79c964c9d7",products:[["SUV X7 2026","SUV",134900,139900,"سيارة",{year:2026,mileage:0,finance:true}],["Sedan S5 2025","سيدان",89900,94900,"سيارة",{year:2025,mileage:1200,finance:true}],["City C3 2024","اقتصادية",62900,null,"سيارة",{year:2024,mileage:8500}],["EV E1","كهربائية",119900,125000,"سيارة",{year:2026,mileage:0,finance:true}]]},
 {sector:"beauty_salon",sectorAr:"صالونات وتجميل",sectorEn:"Beauty",store:"لمسة سبا",city:"الرياض",coupon:"RELAX20",discount:20,cover:"https://images.unsplash.com/photo-1560066984-138dadb4c035",products:[["عناية بالبشرة","العناية بالبشرة",180,220,"جلسة",{duration:"60 دقيقة"}],["مانيكير وباديكير","الأظافر",140,170,"جلسة",{duration:"75 دقيقة"}],["تصفيف شعر","الشعر",120,null,"جلسة",{duration:"45 دقيقة"}],["باقة سبا","الباقات",299,360,"جلسة",{duration:"120 دقيقة"}]]},
 {sector:"public_works",sectorAr:"خدمات وأعمال",sectorEn:"Services",store:"بيتك برو",city:"الرياض",coupon:"HOME10",discount:10,cover:"https://images.unsplash.com/photo-1581578731548-c64695cc6952",products:[["صيانة تكييف","التكييف",180,220,"زيارة",{duration:"60 دقيقة"}],["سباكة منزلية","السباكة",150,null,"زيارة",{duration:"60 دقيقة"}],["كهربائي","الكهرباء",160,190,"زيارة",{duration:"60 دقيقة"}],["تنظيف منزل","التنظيف",249,299,"خدمة",{duration:"3 ساعات"}]]},
 {sector:"fashion",sectorAr:"أزياء",sectorEn:"Fashion",store:"لوما فاشن",city:"الرياض",coupon:"STYLE15",discount:15,cover:"https://images.unsplash.com/photo-1445205170230-053b83016050",products:[["عباية كلاسيك","عبايات",199,249,"قطعة",{sizes:["S","M","L","XL"],colors:["أسود","كحلي"]}],["قميص كتان","رجالي",129,159,"قطعة",{sizes:["S","M","L","XL"]}],["حقيبة يومية","إكسسوارات",169,199,"قطعة",{colors:["بيج","أسود"]}],["فستان سهرة","فساتين",349,429,"قطعة",{sizes:["S","M","L"]}]]},
 {sector:"sweets",sectorAr:"حلويات",sectorEn:"Sweets",store:"سكر وزعفران",city:"الرياض",coupon:"SWEET12",discount:12,cover:"https://images.unsplash.com/photo-1578985545062-69928b1d9587",products:[["كيكة شوكولاتة","الكيك",120,145,"حبة",{}],["بوكس ميني حلى","البوكسات",89,99,"بوكس",{}],["تشيز كيك","التشيز كيك",110,null,"حبة",{}],["معمول فاخر","المعمول",65,75,"كجم",{}]]},
];

async function main(){
 const db=await getDb(); if(!db) throw new Error("DATABASE_URL is required");
 for(let i=0;i<demos.length;i++){
  const d=demos[i], entityId=("demo_"+d.sector).slice(0,30);
  await db.insert(marketplaceSectors).values({slug:d.sector,labelAr:d.sectorAr,labelEn:d.sectorEn,labelFr:d.sectorEn,sortOrder:i,isActive:true}).onDuplicateKeyUpdate({set:{labelAr:d.sectorAr,labelEn:d.sectorEn,isActive:true}});
  const sector=(await db.select().from(marketplaceSectors).where(eq(marketplaceSectors.slug,d.sector)).limit(1))[0];
  await db.insert(platformEntities).values({id:entityId,customerName:d.store,email:`${d.sector}@demo.nfood.local`,countryCode:"SA",city:d.city,timezone:"Asia/Riyadh",currencyCode:"SAR",primaryLanguage:"ar",sector:d.sector,status:true,plan:"Pro",taxId:`DEMO-${String(i+1).padStart(3,"0")}`}).onDuplicateKeyUpdate({set:{customerName:d.store,countryCode:"SA",city:d.city,sector:d.sector,status:true}});
  await db.delete(marketplaceListings).where(eq(marketplaceListings.entityId,entityId));
  await db.delete(storeCoupons).where(eq(storeCoupons.entityId,entityId));
  await db.insert(marketplaceStorefrontSettings).values({entityId,heroTitle:d.store,heroSubtitle:`متجر تجريبي متكامل لنشاط ${d.sectorAr}`,coverUrl:d.cover,sectorConfigJson:JSON.stringify({gallery:[d.cover],businessHours:{daily:["09:00","23:00"]}}),isPublished:true}).onDuplicateKeyUpdate({set:{heroTitle:d.store,coverUrl:d.cover,isPublished:true}});
  await db.insert(marketplaceListings).values(d.products.map((p,n)=>({entityId,sectorId:sector.id,title:p[0],description:`${p[1]} — خيار مختار من ${d.store}`,imageUrl:d.cover,price:p[2].toFixed(2),compareAtPrice:p[3]?.toFixed(2)??null,currencyCode:"SAR",unit:p[4],stockQuantity:d.sector==="automotive"?1:25,status:"active" as const,isFeatured:n===0,sortOrder:n,tagsJson:JSON.stringify([p[1]]),metadataJson:JSON.stringify({category:p[1],...p[5]})})));
  await db.insert(storeCoupons).values({entityId,code:d.coupon,description:`خصم تجريبي لنشاط ${d.sectorAr}`,discountType:"percent",discountValue:d.discount.toFixed(2),minOrderAmount:"0.00",perUserLimit:1,isActive:true});
 }
 console.log(`Seeded ${demos.length} demo stores with products, categories, discounts and coupons.`);
}
main().catch((e)=>{console.error(e);process.exit(1)});