import { useMemo, useState } from "react";
import { Eye, Search, ShieldCheck, UserCog, UserRoundCheck, UserRoundX } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { filterManagedAccounts, summarizeManagedAccounts } from "@/lib/accountManagement";

const roleLabels: Record<string, string> = { admin: "Admin", restaurant_admin: "مدير مطعم", waiter: "نادل", kitchen: "Kitchen", bar: "Bar", cashier: "كاشير", customer: "Customer", driver: "Driver" };
type AccountRole = "admin" | "restaurant_admin" | "waiter" | "kitchen" | "bar" | "cashier" | "customer" | "driver";
type Account = { id: number; restaurantId: number | null; email: string; displayName: string; role: AccountRole; isActive: boolean; createdAt: Date | string | number };
type StatusFilter = "all" | "active" | "inactive";

function formatCreatedAt(value: Account["createdAt"]) {
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "—" : new Intl.DateTimeFormat("en-GB", { calendar: "gregory", numberingSystem: "latn", dateStyle: "medium" }).format(date);
}

export default function AccountManagementPanel() {
  const accountsQuery = trpc.admin.accountDirectory.useQuery(undefined, { retry: false });
  const utils = trpc.useUtils();
  const updateAccount = trpc.admin.updateManagedAccount.useMutation({ onSuccess: () => { void utils.admin.accountDirectory.invalidate(); setSelected(null); } });
  const enterAccount = trpc.admin.enterManagedAccount.useMutation({ onSuccess: () => window.location.reload() });
  const [search, setSearch] = useState("");
  const [roleFilter, setRoleFilter] = useState<"all" | AccountRole>("all");
  const [statusFilter, setStatusFilter] = useState<StatusFilter>("all");
  const [selected, setSelected] = useState<Account | null>(null);
  const [inspector, setInspector] = useState<Account | null>(null);
  const [draft, setDraft] = useState({ email: "", displayName: "", role: "customer" as AccountRole, isActive: true, password: "" });
  const accounts = (accountsQuery.data ?? []) as Account[];
  const stats = useMemo(() => summarizeManagedAccounts(accounts), [accounts]);
  const rows = useMemo(() => filterManagedAccounts(accounts, { search, role: roleFilter, status: statusFilter }), [accounts, roleFilter, search, statusFilter]);
  const openEditor = (account: Account) => { setSelected(account); setDraft({ email: account.email, displayName: account.displayName, role: account.role, isActive: account.isActive, password: "" }); };
  const save = () => { if (!selected || draft.displayName.trim().length < 2 || !draft.email.includes("@")) return; updateAccount.mutate({ id: selected.id, email: draft.email.trim(), displayName: draft.displayName.trim(), role: draft.role, isActive: draft.isActive, password: draft.password.trim() || undefined }); };
  const toggleActive = (account: Account) => updateAccount.mutate({ id: account.id, email: account.email, displayName: account.displayName, role: account.role, isActive: !account.isActive });

  return <section dir="rtl" className="space-y-5">
    <div className="flex flex-wrap items-end justify-between gap-4">
      <div><p className="text-xs font-bold text-[#e76f3c]">إدارة الوصول</p><h2 className="mt-2 text-2xl font-black">مركز الحسابات</h2><p className="mt-2 text-sm text-slate-500">تحكم مركزي في حسابات المطاعم والعملاء والسائقين وفرق التشغيل.</p></div>
      <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
        {[{ label: "إجمالي الحسابات", value: stats.total }, { label: "نشطة", value: stats.active }, { label: "معطلة", value: stats.inactive }, { label: "مطاعم مرتبطة", value: stats.restaurants }].map((stat) => <div key={stat.label} className="min-w-24 rounded-2xl border border-slate-200 bg-white px-3 py-2 text-center shadow-sm"><p className="text-[10px] font-bold text-slate-400">{stat.label}</p><p className="mt-1 text-lg font-black text-slate-900">{stat.value.toLocaleString("en-US", { maximumFractionDigits: 0 })}</p></div>)}
      </div>
    </div>
    <Card className="rounded-3xl border-slate-200 bg-white shadow-sm">
      <CardHeader className="border-b border-slate-100 pb-4"><div className="flex flex-wrap items-center justify-between gap-3"><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-5 w-5 text-[#e76f3c]" /> الحسابات المحلية والأدوار</CardTitle><div className="relative w-full max-w-sm"><Search className="absolute right-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ابحث بالاسم أو البريد أو الدور أو رقم المطعم" className="rounded-xl pr-9" /></div></div><div className="mt-3 flex flex-wrap gap-2"><select value={statusFilter} onChange={(event) => setStatusFilter(event.target.value as StatusFilter)} className="h-9 rounded-xl border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-700"><option value="all">كل الحالات</option><option value="active">نشطة فقط</option><option value="inactive">معطلة فقط</option></select><select value={roleFilter} onChange={(event) => setRoleFilter(event.target.value as "all" | AccountRole)} className="h-9 rounded-xl border border-slate-200 bg-white px-3 text-xs font-semibold text-slate-700"><option value="all">كل الأدوار</option>{Object.entries(roleLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><span className="inline-flex h-9 items-center rounded-xl bg-slate-50 px-3 text-xs font-bold text-slate-500">عرض {rows.length.toLocaleString("en-US", { maximumFractionDigits: 0 })} من {accounts.length.toLocaleString("en-US", { maximumFractionDigits: 0 })}</span></div></CardHeader>
      <CardContent className="p-5">
        {accountsQuery.isLoading ? <div className="space-y-3"><div className="h-16 animate-pulse rounded-xl bg-slate-100" /><div className="h-16 animate-pulse rounded-xl bg-slate-100" /></div> : accountsQuery.isError ? <div className="rounded-xl bg-red-50 p-5 text-sm text-red-700">تعذر تحميل الحسابات. Request ID: admin-account-directory <Button variant="outline" className="mr-3 rounded-lg" onClick={() => void accountsQuery.refetch()}>إعادة المحاولة</Button></div> : rows.length === 0 ? <div className="rounded-2xl bg-slate-50 p-10 text-center text-sm text-slate-500">لا توجد حسابات مطابقة للفلاتر الحالية.</div> : <div className="space-y-3">{rows.map((account) => <div key={account.id} className="flex flex-wrap items-center justify-between gap-4 rounded-2xl border border-slate-100 bg-slate-50/70 p-4 transition hover:border-orange-200 hover:bg-orange-50/30"><div className="flex min-w-0 items-center gap-3"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${account.isActive ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-500"}`}>{account.isActive ? <UserRoundCheck className="h-5 w-5" /> : <UserRoundX className="h-5 w-5" />}</div><div className="min-w-0"><p className="truncate font-bold">{account.displayName}</p><p className="truncate text-xs text-slate-500" dir="ltr">{account.email}</p><p className="mt-1 text-[10px] font-semibold text-slate-400">ID {account.id.toLocaleString("en-US", { maximumFractionDigits: 0 })} · المطعم {account.restaurantId?.toLocaleString("en-US", { maximumFractionDigits: 0 }) ?? "غير مرتبط"}</p></div></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-white px-3 py-1 text-xs font-semibold text-slate-600">{roleLabels[account.role]}</span><span className={`rounded-full px-3 py-1 text-xs font-semibold ${account.isActive ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-500"}`}>{account.isActive ? "نشط" : "معطل"}</span><Button variant="outline" size="sm" className="rounded-xl" onClick={() => setInspector(account)}><Eye className="ml-1 h-4 w-4" />فحص</Button><Button variant="outline" size="sm" className="rounded-xl" disabled={enterAccount.isPending || !account.isActive} onClick={() => enterAccount.mutate({ id: account.id })}>دخول</Button><Button variant="outline" size="sm" className="rounded-xl" onClick={() => openEditor(account)}><UserCog className="ml-1 h-4 w-4" />تعديل</Button><Button variant="outline" size="sm" className="rounded-xl" disabled={updateAccount.isPending} onClick={() => toggleActive(account)}>{account.isActive ? "تعطيل" : "تمكين"}</Button></div></div>)}</div>}
      </CardContent>
    </Card>
    <Dialog open={Boolean(inspector)} onOpenChange={(open) => !open && setInspector(null)}><DialogContent dir="rtl" className="rounded-3xl sm:max-w-lg"><DialogHeader><DialogTitle>فحص الحساب</DialogTitle><DialogDescription>ملخص الهوية والصلاحيات والارتباط دون تعديل البيانات.</DialogDescription></DialogHeader>{inspector && <div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-400">الاسم</p><p className="mt-1 font-bold">{inspector.displayName}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-400">رقم الحساب</p><p className="mt-1 font-bold">{inspector.id.toLocaleString("en-US", { maximumFractionDigits: 0 })}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-400">البريد</p><p className="mt-1 break-all font-bold" dir="ltr">{inspector.email}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-400">الدور</p><p className="mt-1 font-bold">{roleLabels[inspector.role]}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-400">المطعم المرتبط</p><p className="mt-1 font-bold">{inspector.restaurantId?.toLocaleString("en-US", { maximumFractionDigits: 0 }) ?? "غير مرتبط"}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs text-slate-400">تاريخ الإنشاء</p><p className="mt-1 font-bold" dir="ltr">{formatCreatedAt(inspector.createdAt)}</p></div></div>}</DialogContent></Dialog>
    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent dir="rtl" className="rounded-3xl sm:max-w-lg"><DialogHeader><DialogTitle>تعديل الحساب</DialogTitle><DialogDescription>تعديل مباشر من Admin. لا تظهر كلمة المرور الحالية؛ أدخل كلمة جديدة فقط عند الحاجة.</DialogDescription></DialogHeader><div className="space-y-4"><label className="block text-sm font-semibold">الاسم<Input value={draft.displayName} onChange={(event) => setDraft({ ...draft, displayName: event.target.value })} className="mt-2 rounded-xl" /></label><label className="block text-sm font-semibold">البريد<Input value={draft.email} onChange={(event) => setDraft({ ...draft, email: event.target.value })} dir="ltr" className="mt-2 rounded-xl" /></label><label className="block text-sm font-semibold">الدور<select value={draft.role} onChange={(event) => setDraft({ ...draft, role: event.target.value as AccountRole })} className="mt-2 h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm">{Object.entries(roleLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="block text-sm font-semibold">كلمة مرور جديدة اختيارية<Input value={draft.password} onChange={(event) => setDraft({ ...draft, password: event.target.value })} type="password" autoComplete="new-password" placeholder="اتركها فارغة للإبقاء على الحالية" className="mt-2 rounded-xl" /></label><label className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-sm font-semibold">الحساب مفعل<input type="checkbox" checked={draft.isActive} onChange={(event) => setDraft({ ...draft, isActive: event.target.checked })} className="h-4 w-4 accent-[#e76f3c]" /></label><Button disabled={updateAccount.isPending || draft.displayName.trim().length < 2 || !draft.email.includes("@")} onClick={save} className="w-full rounded-xl bg-[#e76f3c] hover:bg-[#d85f2e]">{updateAccount.isPending ? "جارٍ الحفظ..." : "حفظ التعديلات"}</Button>{updateAccount.isError && <p className="text-sm text-red-600">تعذر حفظ الحساب. تحقق من البريد والبيانات ثم حاول مرة أخرى.</p>}</div></DialogContent></Dialog>
  </section>;
}
