import { Activity, BarChart3, ClipboardList, CircleDollarSign, LogIn } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";

export function ActivityAnalyticsPanel({ restaurantId, title = "النشاط والمبيعات" }: { restaurantId?: number; title?: string }) {
  const summary = trpc.platform.activitySummary.useQuery(restaurantId ? { restaurantId } : undefined, { retry: false, refetchInterval: 30000 });
  const maxSales = Math.max(...(summary.data?.days ?? []).map((day) => day.sales), 1);
  return <Card className="mt-5 rounded-2xl border-slate-200 bg-white shadow-sm" dir="rtl">
    <CardHeader className="flex flex-row items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-base"><BarChart3 className="h-5 w-5 text-[#e76f3c]" />{title}</CardTitle><p className="mt-1 text-xs text-slate-500">بيانات حقيقية مجمعة لآخر 7 أيام، مع سجل النشاط الخاص بالنطاق المحدد.</p></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[10px] font-semibold text-emerald-700">تحديث كل 30 ثانية</span></CardHeader>
    <CardContent className="space-y-5">
      {summary.isError && <div className="rounded-xl border border-red-200 bg-red-50 p-3 text-xs text-red-700">تعذر تحميل التحليلات. Request ID: activity-summary</div>}
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[{ label: "كل الطلبات", value: summary.data?.totals.orders ?? 0, icon: ClipboardList }, { label: "مكتملة", value: summary.data?.totals.completed ?? 0, icon: Activity }, { label: "طلبات نشطة", value: summary.data?.totals.active ?? 0, icon: LogIn }, { label: "المبيعات", value: `${(summary.data?.totals.sales ?? 0).toFixed(2)} SAR`, icon: CircleDollarSign }, { label: "أحداث النشاط", value: summary.data?.totals.auditEvents ?? 0, icon: Activity }].map((item) => { const Icon = item.icon; return <div key={item.label} className="rounded-xl border border-slate-100 bg-slate-50 p-3"><div className="flex items-center justify-between text-slate-500"><span className="text-[11px]">{item.label}</span><Icon className="h-4 w-4 text-[#e76f3c]" /></div><p className="mt-2 text-lg font-bold text-slate-900">{summary.isLoading ? "…" : item.value}</p></div>; })}</div>
      <div className="rounded-xl border border-slate-100 bg-slate-50 p-4"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-bold text-slate-700">حركة المبيعات اليومية</p><p className="text-[10px] text-slate-400">القيمة بالريال السعودي</p></div><div className="flex h-36 items-end gap-2">{(summary.data?.days ?? []).map((day) => <div key={day.date} className="flex min-w-0 flex-1 flex-col items-center gap-1"><div className="w-full rounded-t-md bg-orange-400 transition-all" style={{ height: `${Math.max(4, (day.sales / maxSales) * 108)}px` }} title={`${day.sales.toFixed(2)} SAR · ${day.orders} طلب`} /><span className="truncate text-[9px] text-slate-500">{day.date}</span></div>)}</div></div>
      <div><p className="mb-2 text-xs font-bold text-slate-700">آخر أحداث الدخول والتشغيل</p><div className="space-y-2">{(summary.data?.recentEvents ?? []).slice(0, 5).map((event) => <div key={event.id} className="flex items-center justify-between rounded-lg border border-slate-100 px-3 py-2 text-xs"><span className="font-medium text-slate-700">{event.action}</span><span className="text-slate-400">{new Date(event.createdAt).toLocaleString("ar-SA-u-ca-gregory-nu-latn")}</span></div>)}{!summary.isLoading && !(summary.data?.recentEvents?.length) && <p className="rounded-lg bg-slate-50 p-3 text-xs text-slate-500">لا توجد أحداث مسجلة ضمن هذا النطاق بعد.</p>}</div></div>
    </CardContent>
  </Card>;
}
