import { useMemo, useState } from "react";
import { Clock3, MapPin, Plus, Save, Trash2, Truck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

export function DeliveryOperationsPanel({ restaurantId, branchId }: { restaurantId: number; branchId?: number }) {
  const utils = trpc.useUtils();
  const [zone, setZone] = useState<{ id?: number; name: string; centerLatitude: string; centerLongitude: string; radiusKm: string; deliveryFee: string; minimumOrder: string }>({ name: "", centerLatitude: "24.7136", centerLongitude: "46.6753", radiusKm: "5", deliveryFee: "15", minimumOrder: "0" });
  const [point, setPoint] = useState({ name: "", address: "", openingTime: "09:00", closingTime: "23:00" });
  const [slot, setSlot] = useState({ dayOfWeek: "0", startTime: "18:00", endTime: "23:00", capacity: "10", slotDurationMinutes: "60" });
  const zones = trpc.platform.deliveryZones.useQuery({ restaurantId, branchId }, { enabled: Boolean(restaurantId), retry: false });
  const points = trpc.platform.pickupPointsManage.useQuery({ restaurantId, branchId: branchId ?? 0 }, { enabled: Boolean(branchId), retry: false });
  const slots = trpc.platform.reservationSlotsManage.useQuery({ restaurantId, branchId: branchId ?? 0 }, { enabled: Boolean(branchId), retry: false });
  const saveZone = trpc.platform.saveDeliveryZone.useMutation({ onSuccess: () => { toast.success("تم حفظ نطاق التوصيل"); void utils.platform.deliveryZones.invalidate(); setZone({ name: "", centerLatitude: zone.centerLatitude, centerLongitude: zone.centerLongitude, radiusKm: "5", deliveryFee: "15", minimumOrder: "0" }); }, onError: (error) => toast.error(`تعذر حفظ النطاق: ${error.message}`) });
  const savePoint = trpc.platform.savePickupPoint.useMutation({ onSuccess: () => { toast.success("تم حفظ نقطة الاستلام"); void utils.platform.pickupPointsManage.invalidate(); setPoint({ name: "", address: "", openingTime: point.openingTime, closingTime: point.closingTime }); }, onError: (error) => toast.error(`تعذر حفظ نقطة الاستلام: ${error.message}`) });
  const saveSlot = trpc.platform.saveReservationSlot.useMutation({ onSuccess: () => { toast.success("تم حفظ الفترة الزمنية"); void utils.platform.reservationSlotsManage.invalidate(); setSlot({ ...slot, startTime: "18:00", endTime: "23:00" }); }, onError: (error) => toast.error(`تعذر حفظ الفترة: ${error.message}`) });
  const dayLabels = useMemo(() => ["الأحد", "الاثنين", "الثلاثاء", "الأربعاء", "الخميس", "الجمعة", "السبت"], []);
  const submitZone = () => { if (!zone.name.trim() || !branchId) return; saveZone.mutate({ id: zone.id, restaurantId, branchId, name: zone.name.trim(), centerLatitude: Number(zone.centerLatitude), centerLongitude: Number(zone.centerLongitude), radiusKm: Number(zone.radiusKm), deliveryFee: Number(zone.deliveryFee), minimumOrder: Number(zone.minimumOrder), isActive: true }); };
  const submitPoint = () => { if (!point.name.trim() || !branchId) return; savePoint.mutate({ restaurantId, branchId, name: point.name.trim(), address: point.address.trim() || null, openingTime: point.openingTime, closingTime: point.closingTime, isActive: true }); };
  const submitSlot = () => { if (!branchId) return; saveSlot.mutate({ restaurantId, branchId, dayOfWeek: Number(slot.dayOfWeek), startTime: slot.startTime, endTime: slot.endTime, capacity: Number(slot.capacity), slotDurationMinutes: Number(slot.slotDurationMinutes), isActive: true }); };
  return <div className="space-y-6" dir="rtl">
    <div><p className="text-xs font-black uppercase tracking-[.2em] text-[#e76f3c]">تشغيل المطعم</p><h2 className="mt-1 text-2xl font-black text-slate-900">التوصيل والحجز والاستلام</h2><p className="mt-2 text-sm text-slate-500">عدّل مصفوفة الأسعار ونطاق الخدمة والفترات المتاحة لكل فرع.</p></div>
    {!branchId && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">اختر فرعًا مفتوحًا أولًا لإدارة إعدادات التوصيل والحجز.</div>}
    <section className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <Card className="rounded-3xl border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Truck className="h-5 w-5 text-[#e76f3c]" />مصفوفة رسوم التوصيل</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Input placeholder="اسم النطاق" value={zone.name} onChange={(e) => setZone({ ...zone, name: e.target.value })} /><Input type="number" step="0.1" placeholder="نصف القطر كم" value={zone.radiusKm} onChange={(e) => setZone({ ...zone, radiusKm: e.target.value })} /><Input type="number" step="0.000001" placeholder="خط العرض" value={zone.centerLatitude} onChange={(e) => setZone({ ...zone, centerLatitude: e.target.value })} /><Input type="number" step="0.000001" placeholder="خط الطول" value={zone.centerLongitude} onChange={(e) => setZone({ ...zone, centerLongitude: e.target.value })} /><Input type="number" step="0.01" placeholder="رسوم التوصيل ر.س" value={zone.deliveryFee} onChange={(e) => setZone({ ...zone, deliveryFee: e.target.value })} /><Input type="number" step="0.01" placeholder="الحد الأدنى للطلب" value={zone.minimumOrder} onChange={(e) => setZone({ ...zone, minimumOrder: e.target.value })} /></div><Button onClick={submitZone} disabled={!branchId || saveZone.isPending} className="rounded-xl bg-[#e76f3c] text-white"><Save className="ml-2 h-4 w-4" />حفظ النطاق</Button><div className="space-y-2">{zones.data?.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-2xl bg-slate-50 p-3 text-sm"><div><p className="font-black">{item.name}</p><p className="text-xs text-slate-500">نطاق {item.radiusKm} كم · {item.deliveryFee} ر.س · حد أدنى {item.minimumOrder} ر.س</p></div><div className="flex items-center gap-2"><Button type="button" variant="ghost" size="sm" className="rounded-lg text-xs" onClick={() => setZone({ id: item.id, name: item.name, centerLatitude: String(item.centerLatitude), centerLongitude: String(item.centerLongitude), radiusKm: String(item.radiusKm), deliveryFee: String(item.deliveryFee), minimumOrder: String(item.minimumOrder) })}>تعديل</Button><span className="rounded-full bg-emerald-100 px-2 py-1 text-xs font-bold text-emerald-700">نشط</span></div></div>)}</div></CardContent></Card>
      <Card className="rounded-3xl border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><MapPin className="h-5 w-5 text-[#e76f3c]" />نقاط الاستلام</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Input placeholder="اسم النقطة" value={point.name} onChange={(e) => setPoint({ ...point, name: e.target.value })} /><Input placeholder="العنوان" value={point.address} onChange={(e) => setPoint({ ...point, address: e.target.value })} /><Input type="time" value={point.openingTime} onChange={(e) => setPoint({ ...point, openingTime: e.target.value })} /><Input type="time" value={point.closingTime} onChange={(e) => setPoint({ ...point, closingTime: e.target.value })} /></div><Button onClick={submitPoint} disabled={!branchId || savePoint.isPending} variant="outline" className="rounded-xl"><Plus className="ml-2 h-4 w-4" />إضافة نقطة استلام</Button><div className="space-y-2">{points.data?.map((item) => <div key={item.id} className="rounded-2xl bg-slate-50 p-3 text-sm"><p className="font-black">{item.name}</p><p className="text-xs text-slate-500">{item.address || "العنوان غير مضاف"} · {item.openingTime || "--:--"}–{item.closingTime || "--:--"}</p></div>)}</div><p className="text-xs text-slate-500">تظهر النقاط الفعالة للعميل عند اختيار السفري.</p></CardContent></Card>
    </section>
    <Card className="rounded-3xl border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Clock3 className="h-5 w-5 text-[#e76f3c]" />الفترات الزمنية للحجز</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><select value={slot.dayOfWeek} onChange={(e) => setSlot({ ...slot, dayOfWeek: e.target.value })} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-sm">{dayLabels.map((day, index) => <option key={day} value={index}>{day}</option>)}</select><Input type="time" value={slot.startTime} onChange={(e) => setSlot({ ...slot, startTime: e.target.value })} /><Input type="time" value={slot.endTime} onChange={(e) => setSlot({ ...slot, endTime: e.target.value })} /><Input type="number" min="1" placeholder="السعة" value={slot.capacity} onChange={(e) => setSlot({ ...slot, capacity: e.target.value })} /><Input type="number" min="15" step="15" placeholder="مدة الفترة بالدقائق" value={slot.slotDurationMinutes} onChange={(e) => setSlot({ ...slot, slotDurationMinutes: e.target.value })} /></div><Button onClick={submitSlot} disabled={!branchId || saveSlot.isPending} className="rounded-xl bg-slate-900 text-white"><Save className="ml-2 h-4 w-4" />حفظ الفترة</Button><div className="flex flex-wrap gap-2">{slots.data?.map((item) => <span key={item.id} className="rounded-full bg-orange-50 px-3 py-2 text-xs font-bold text-orange-800">{dayLabels[item.dayOfWeek]} · {item.startTime}–{item.endTime} · {item.capacity} مقاعد</span>)}</div></CardContent></Card>
  </div>;
}
