import { Facebook, Instagram, LifeBuoy, Linkedin, MessageCircle, Moon, Sun, Youtube } from "lucide-react";
import { Link } from "wouter";
import { useLanguage } from "@/contexts/LanguageContext";
import { useTheme } from "@/contexts/ThemeContext";

export const SUPPORT_WHATSAPP_URL = "https://wa.me/966569867000?text=Hello%20NFOOD%20Support";
export const SUPPORT_ROUTE = "/support";

export default function FloatingSupportActions() {
  const { language } = useLanguage();
  const { theme, toggleTheme } = useTheme();
  const copy = language === "fr" ? { chat: "Discuter avec l’administration", support: "Support technique", instagram: "Instagram", facebook: "Facebook", linkedin: "LinkedIn", youtube: "YouTube" } : language === "en" ? { chat: "Chat with admin", support: "Technical support", instagram: "Instagram", facebook: "Facebook", linkedin: "LinkedIn", youtube: "YouTube" } : { chat: "الدردشة مع الإدارة", support: "الدعم الفني", instagram: "Instagram", facebook: "فيسبوك", linkedin: "LinkedIn", youtube: "يوتيوب" };
  const socialLinks = [{ label: copy.instagram, href: "https://instagram.com/nfood", icon: Instagram, color: "hover:bg-pink-500" }, { label: copy.facebook, href: "https://facebook.com/nfood", icon: Facebook, color: "hover:bg-blue-600" }, { label: copy.linkedin, href: "https://linkedin.com/company/nfood", icon: Linkedin, color: "hover:bg-sky-600" }, { label: copy.youtube, href: "https://youtube.com/@nfood", icon: Youtube, color: "hover:bg-red-600" }];
  return <><div className="pointer-events-none fixed inset-x-0 bottom-5 z-[65] flex justify-center"><div className="pointer-events-auto flex items-center gap-2 rounded-full border border-white/70 bg-white/90 p-2 shadow-2xl shadow-slate-900/20 backdrop-blur-xl transition hover:-translate-y-1 dark:border-slate-700 dark:bg-slate-900/90"><a href={SUPPORT_WHATSAPP_URL} target="_blank" rel="noreferrer" aria-label={copy.chat} title={copy.chat} className="relative flex h-12 w-12 items-center justify-center rounded-full bg-[#25D366] text-white shadow-lg transition hover:scale-110 active:scale-95 motion-safe:animate-[nfood-cart-pulse_2.2s_ease-in-out_infinite]"><span className="absolute inset-0 rounded-full bg-[#25D366]/30 motion-safe:animate-ping" aria-hidden="true" /><MessageCircle className="relative h-6 w-6" /></a><Link href={SUPPORT_ROUTE} aria-label={copy.support} title={copy.support} className="flex h-12 w-12 items-center justify-center rounded-full bg-[#172235] text-white shadow-lg transition hover:scale-110 active:scale-95"><LifeBuoy className="h-5 w-5" /></Link>{toggleTheme && <button type="button" onClick={toggleTheme} aria-label={theme === "dark" ? "Light mode" : "Dark mode"} title={theme === "dark" ? "Light mode" : "Dark mode"} className="flex h-12 w-12 items-center justify-center rounded-full bg-slate-100 text-slate-800 transition hover:scale-110 active:scale-95 dark:bg-slate-800 dark:text-white">{theme === "dark" ? <Sun className="h-5 w-5" /> : <Moon className="h-5 w-5" />}</button>}</div></div><div className="fixed bottom-5 left-4 z-[64] hidden items-center gap-1.5 rounded-2xl border border-white/70 bg-white/85 p-1.5 shadow-xl backdrop-blur-xl sm:flex dark:border-slate-700 dark:bg-slate-900/85" dir="ltr">{socialLinks.map(({ label, href, icon: Icon, color }) => <a key={label} href={href} target="_blank" rel="noreferrer" aria-label={label} title={label} className={`flex h-9 w-9 items-center justify-center rounded-xl bg-slate-100 text-slate-600 transition hover:-translate-y-1 hover:text-white active:scale-95 motion-safe:hover:animate-pulse dark:bg-slate-800 dark:text-slate-200 ${color}`}><Icon className="h-4 w-4" /></a>)}</div></>;
}
