import { useMemo, useState } from "react";
import { Download, FileText, Save, Clock3, Activity, AlertTriangle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { Order } from "@/components/homeNavigation";
import { trpc } from "@/lib/trpc";

type Props = { restaurantId: number; orders: Order[] };
const statusLabel: Record<string, string> = { new: "جديد", preparing: "قيد التحضير", ready: "جاهز", completed: "مكتمل", cancelled: "ملغى" };
function dayBounds() { const start = new Date(); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + 1); end.setMilliseconds(-1); return { from: start, to: end }; }
function formatDuration(seconds: number) { if (!seconds) return "—"; const minutes = Math.floor(seconds / 60); const rest = seconds % 60; return `${minutes} د ${rest} ث`; }
function downloadCsv(filename: string, rows: string[][]) { const csv = "\uFEFF" + rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }

export function KitchenPerformancePanel({ restaurantId, orders }: Props) {
  const [bounds] = useState(dayBounds);
  const [selectedOrderId, setSelectedOrderId] = useState<number | null>(orders[0] ? Number(orders[0].id) : null);
  const slaQuery = trpc.admin.kitchenSla.useQuery({ restaurantId }, { refetchInterval: 10000 });
  const reportQuery = trpc.admin.dailyOrderPerformance.useQuery({ restaurantId, from: bounds.from, to: bounds.to }, { refetchInterval: 15000 });
  const selected = orders.find((order) => Number(order.id) === selectedOrderId);
  const historyQuery = trpc.admin.orderStatusHistory.useQuery({ restaurantId, orderId: selectedOrderId ?? 0 }, { enabled: Boolean(selectedOrderId), refetchInterval: 10000 });
  const saveSla = trpc.admin.saveKitchenSla.useMutation({ onSuccess: () => void slaQuery.refetch() });
  const report = reportQuery.data;
  const reportRows = useMemo(() => {
    const rows: string[][] = [["رقم الطلب", "الحالة", "وقت الإنشاء", "زمن التحضير", "عدد الانتقالات"]];
    for (const item of report?.orders ?? []) rows.push([String(item.id), statusLabel[item.status] ?? item.status, new Date(item.createdAt).toLocaleString("ar-SA"), formatDuration(item.preparationSeconds), String(item.transitions.length)]);
    return rows;
  }, [report]);
  const printPdf = () => {
    const popup = window.open("", "nfood-daily-performance", "width=900,height=700"); if (!popup) return;
    const rows = reportRows.slice(1).map((row) => `<tr>${row.map((cell) => `<td>${cell}</td>`).join("")}</tr>`).join("");
    popup.document.write(`<html dir="rtl"><head><title>تقرير أداء الطلبات اليومي</title><style>body{font-family:Arial,sans-serif;padding:28px;color:#1f2937}h1{color:#5a214f}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{border:1px solid #ddd;padding:8px;text-align:right;font-size:12px}th{background:#f7ede5}.summary{display:flex;gap:18px;margin:18px 0;font-weight:bold}@media print{button{display:none}}</style></head><body><h1>NFOOD — تقرير أداء الطلبات اليومي</h1><p>${new Date().toLocaleDateString("ar-SA")}</p><div class="summary"><span>الإجمالي: ${report?.summary.total ?? 0}</span><span>المكتملة: ${report?.summary.completed ?? 0}</span><span>المتأخرة: ${report?.summary.delayed ?? 0}</span><span>المتوسط: ${formatDuration(report?.summary.averagePreparationSeconds ?? 0)}</span></div><table><thead><tr>${reportRows[0].map((cell) => `<th>${cell}</th>`).join("")}</tr></thead><tbody>${rows}</tbody></table><script>window.onload=()=>{window.focus();window.print()}</script></body></html>`);
    popup.document.close();
  };
  return <div className="grid gap-4 xl:grid-cols-2" dir="rtl">
    <Card className="rounded-2xl border-slate-200 shadow-sm"><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-sm"><Clock3 className="h-4 w-4 text-[#e76f3c]" />وقت التأخير حسب قسم المطبخ</CardTitle></CardHeader><CardContent className="space-y-2">{slaQuery.isError ? <p className="text-xs text-red-700">تعذر تحميل إعدادات SLA.</p> : (slaQuery.data ?? []).length === 0 ? <p className="text-xs text-slate-500">أضف أقسام المطبخ أولًا لتخصيص أوقات التأخير.</p> : (slaQuery.data ?? []).map((section) => <div key={section.id} className="flex items-center gap-2 rounded-xl border border-slate-100 bg-slate-50 p-2"><span className="min-w-0 flex-1 truncate text-xs font-bold text-slate-700">{section.name}</span><Input aria-label={`SLA ${section.name}`} type="number" min={1} max={240} defaultValue={section.thresholdMinutes ?? 15} className="h-8 w-24 text-center text-xs" onBlur={(event) => { const value = Number(event.target.value); if (Number.isInteger(value) && value >= 1 && value <= 240) void saveSla.mutateAsync({ restaurantId, kitchenSectionId: section.id, thresholdMinutes: value }); }} /><span className="text-[10px] text-slate-500">دقيقة</span><Save className="h-3.5 w-3.5 text-emerald-600" /></div>)}</CardContent></Card>
    <Card className="rounded-2xl border-slate-200 shadow-sm"><CardHeader className="pb-3"><CardTitle className="flex items-center justify-between gap-2 text-sm"><span className="flex items-center gap-2"><Activity className="h-4 w-4 text-blue-600" />أداء اليوم</span><span className="flex gap-2"><Button size="sm" variant="outline" className="h-8 rounded-lg text-[11px]" disabled={!report} onClick={() => report && downloadCsv(`nfood-order-performance-${restaurantId}.csv`, reportRows)}><Download className="ml-1 h-3.5 w-3.5" />CSV</Button><Button size="sm" variant="outline" className="h-8 rounded-lg text-[11px]" disabled={!report} onClick={printPdf}><FileText className="ml-1 h-3.5 w-3.5" />PDF</Button></span></CardTitle></CardHeader><CardContent>{reportQuery.isLoading ? <p className="text-xs text-slate-500">جارٍ إعداد التقرير...</p> : reportQuery.isError ? <p className="text-xs text-red-700">تعذر إعداد تقرير الأداء.</p> : <div className="grid grid-cols-4 gap-2 text-center"><div className="rounded-xl bg-slate-50 p-2"><b className="block text-lg">{report?.summary.total ?? 0}</b><span className="text-[10px] text-slate-500">طلب</span></div><div className="rounded-xl bg-emerald-50 p-2"><b className="block text-lg text-emerald-700">{report?.summary.completed ?? 0}</b><span className="text-[10px] text-slate-500">مكتمل</span></div><div className="rounded-xl bg-red-50 p-2"><b className="block text-lg text-red-700">{report?.summary.delayed ?? 0}</b><span className="text-[10px] text-slate-500">متأخر</span></div><div className="rounded-xl bg-orange-50 p-2"><b className="block text-sm text-orange-700">{formatDuration(report?.summary.averagePreparationSeconds ?? 0)}</b><span className="text-[10px] text-slate-500">متوسط التحضير</span></div></div>}</CardContent></Card>
    <Card className="rounded-2xl border-slate-200 shadow-sm xl:col-span-2"><CardHeader className="pb-3"><CardTitle className="text-sm">السجل الزمني للطلبات</CardTitle></CardHeader><CardContent className="grid gap-4 lg:grid-cols-[240px_1fr]"> <div className="max-h-56 space-y-2 overflow-auto">{orders.slice(0, 30).map((order) => <button key={order.id} type="button" onClick={() => setSelectedOrderId(Number(order.id))} className={`flex w-full items-center justify-between rounded-xl border p-2 text-right text-xs ${selectedOrderId === Number(order.id) ? "border-[#e76f3c] bg-orange-50" : "border-slate-100 bg-slate-50"}`}><span className="font-bold">{order.id}</span><span className="text-slate-500">{statusLabel[order.status] ?? order.status}</span></button>)}</div><div>{!selected ? <p className="text-xs text-slate-500">اختر طلبًا لعرض انتقالاته.</p> : historyQuery.isLoading ? <p className="text-xs text-slate-500">جارٍ تحميل السجل...</p> : (historyQuery.data ?? []).length === 0 ? <p className="text-xs text-slate-500">لا توجد انتقالات مسجلة لهذا الطلب بعد.</p> : <div className="space-y-2">{historyQuery.data?.map((entry) => <div key={entry.id} className="flex items-center gap-3 rounded-xl border border-slate-100 bg-slate-50 p-3 text-xs"><span className="h-2 w-2 shrink-0 rounded-full bg-blue-600" /><div className="min-w-0 flex-1"><p className="font-bold">{entry.fromStatus ? `${statusLabel[entry.fromStatus] ?? entry.fromStatus} ← ` : "بدأ الطلب ← "}{statusLabel[entry.toStatus] ?? entry.toStatus}</p><p className="mt-1 text-[10px] text-slate-500">{new Date(entry.createdAt).toLocaleString("ar-SA")} · مدة المرحلة: {formatDuration(Number(entry.durationSeconds ?? 0))}</p></div>{Number(entry.durationSeconds ?? 0) > 900 && <AlertTriangle className="h-4 w-4 text-red-600" />}</div>)}</div>}</div></CardContent></Card>
  </div>;
}
