import { useMemo, useState } from "react";
import { Activity, AlertTriangle, BarChart3, Clock3, Download, FileText, Save } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import type { Order } from "@/components/homeNavigation";
import { trpc } from "@/lib/trpc";

type Props = { restaurantId: number; orders: Order[] };
type ChartSection = "all" | string;
const statusLabel: Record<string, string> = { new: "جديد", preparing: "قيد التحضير", ready: "جاهز", completed: "مكتمل", cancelled: "ملغى" };

function dateInputValue(date: Date) { return date.toISOString().slice(0, 10); }
function rangeBounds(fromValue: string, toValue: string) { return { from: new Date(`${fromValue}T00:00:00`), to: new Date(`${toValue}T23:59:59.999`) }; }
function formatDuration(seconds: number) { if (!seconds) return "—"; const minutes = Math.floor(seconds / 60); const rest = seconds % 60; return `${minutes} د ${rest} ث`; }
function downloadCsv(filename: string, rows: string[][]) { const csv = "\uFEFF" + rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = filename; anchor.click(); URL.revokeObjectURL(url); }

export function KitchenPerformancePanel({ restaurantId, orders }: Props) {
  const today = useMemo(() => dateInputValue(new Date()), []);
  const [fromValue, setFromValue] = useState(today);
  const [toValue, setToValue] = useState(today);
  const [selectedOrderId, setSelectedOrderId] = useState<number | null>(orders[0] ? Number(orders[0].id) : null);
  const [chartSection, setChartSection] = useState<ChartSection>("all");
  const bounds = useMemo(() => rangeBounds(fromValue, toValue), [fromValue, toValue]);
  const validRange = bounds.from.getTime() <= bounds.to.getTime();
  const slaQuery = trpc.admin.kitchenSla.useQuery({ restaurantId }, { refetchInterval: 10000 });
  const reportQuery = trpc.admin.dailyOrderPerformance.useQuery({ restaurantId, from: bounds.from, to: bounds.to }, { enabled: validRange, refetchInterval: 15000 });
  const selected = orders.find((order) => Number(order.id) === selectedOrderId);
  const selectedThresholdMinutes = selected?.kitchenSectionId ? slaQuery.data?.find((section) => section.id === selected.kitchenSectionId)?.thresholdMinutes ?? 15 : 15;
  const historyQuery = trpc.admin.orderStatusHistory.useQuery({ restaurantId, orderId: selectedOrderId ?? 0 }, { enabled: Boolean(selectedOrderId), refetchInterval: 10000 });
  const saveSla = trpc.admin.saveKitchenSla.useMutation({ onSuccess: () => void slaQuery.refetch() });
  const report = reportQuery.data;
  const sectionStats = useMemo(() => (report?.bySection ?? []).filter((item) => chartSection === "all" || String(item.sectionId ?? "unassigned") === chartSection), [chartSection, report?.bySection]);
  const maxSectionAverage = Math.max(1, ...sectionStats.map((item) => Number(item.averagePreparationSeconds ?? 0)));
  const maxHourAverage = Math.max(1, ...(report?.byHour ?? []).map((item) => Number(item.averagePreparationSeconds ?? 0)));
  const reportRows = useMemo(() => {
    const rows: string[][] = [["رقم الطلب", "القسم", "الحالة", "وقت الإنشاء", "زمن التحضير", "التأخير", "عدد الانتقالات"]];
    for (const item of report?.orders ?? []) rows.push([String(item.id), item.sectionName ?? "غير موزع", statusLabel[item.status] ?? item.status, new Date(item.createdAt).toLocaleString("ar-SA-u-ca-gregory-nu-latn"), formatDuration(item.preparationSeconds), item.delayed ? "نعم" : "لا", String(item.transitions.length)]);
    return rows;
  }, [report]);
  const printPdf = () => {
    if (!report) return;
    const popup = window.open("", "nfood-performance-report", "width=980,height=760"); if (!popup) return;
    const rows = reportRows.slice(1).map((row) => `<tr>${row.map((cell) => `<td>${cell}</td>`).join("")}</tr>`).join("");
    popup.document.write(`<html dir="rtl"><head><title>تقرير أداء الطلبات</title><style>body{font-family:Tahoma,Arial,sans-serif;padding:28px;color:#1f2937}h1{color:#5a214f;margin-bottom:6px}.meta{color:#64748b;font-size:12px}.summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:18px 0}.summary span{background:#f7ede5;border-radius:10px;padding:10px;font-weight:bold;font-size:12px}table{width:100%;border-collapse:collapse;margin-top:18px}th,td{border:1px solid #ddd;padding:8px;text-align:right;font-size:11px}th{background:#f7ede5}@media print{button{display:none}}</style></head><body><h1>NFOOD — تقرير أداء الطلبات</h1><p class="meta">النطاق: ${fromValue} إلى ${toValue}</p><div class="summary"><span>الإجمالي: ${report.summary.total}</span><span>المكتملة: ${report.summary.completed}</span><span>المتأخرة: ${report.summary.delayed}</span><span>متوسط التحضير: ${formatDuration(report.summary.averagePreparationSeconds)}</span></div><table><thead><tr>${reportRows[0].map((cell) => `<th>${cell}</th>`).join("")}</tr></thead><tbody>${rows}</tbody></table><script>window.onload=()=>{window.focus();window.print()}</script></body></html>`);
    popup.document.close();
  };
  return <div className="grid gap-4 xl:grid-cols-2" dir="rtl">
    <Card className="rounded-2xl border-slate-200 shadow-sm"><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-sm"><Clock3 className="h-4 w-4 text-[#e76f3c]" />وقت التأخير حسب قسم المطبخ</CardTitle></CardHeader><CardContent className="space-y-2">{slaQuery.isError ? <p className="text-xs text-red-700">تعذر تحميل إعدادات SLA.</p> : (slaQuery.data ?? []).length === 0 ? <p className="text-xs text-slate-500">أضف أقسام المطبخ أولًا لتخصيص أوقات التأخير.</p> : (slaQuery.data ?? []).map((section) => <div key={section.id} className="flex items-center gap-2 rounded-xl border border-slate-100 bg-slate-50 p-2"><span className="min-w-0 flex-1 truncate text-xs font-bold text-slate-700">{section.name}</span><Input aria-label={`SLA ${section.name}`} type="number" min={1} max={240} defaultValue={section.thresholdMinutes ?? 15} className="h-8 w-24 text-center text-xs" onBlur={(event) => { const value = Number(event.target.value); if (Number.isInteger(value) && value >= 1 && value <= 240) void saveSla.mutateAsync({ restaurantId, kitchenSectionId: section.id, thresholdMinutes: value }); }} /><span className="text-[10px] text-slate-500">دقيقة</span><Save className="h-3.5 w-3.5 text-emerald-600" /></div>)}</CardContent></Card>
    <Card className="rounded-2xl border-slate-200 shadow-sm"><CardHeader className="pb-3"><CardTitle className="flex flex-wrap items-center justify-between gap-2 text-sm"><span className="flex items-center gap-2"><Activity className="h-4 w-4 text-blue-600" />أداء الطلبات حسب النطاق</span><span className="flex gap-2"><Button size="sm" variant="outline" className="h-8 rounded-lg text-[11px]" disabled={!report || !validRange} onClick={() => report && downloadCsv(`nfood-order-performance-${restaurantId}-${fromValue}-${toValue}.csv`, reportRows)}><Download className="ml-1 h-3.5 w-3.5" />CSV</Button><Button size="sm" variant="outline" className="h-8 rounded-lg text-[11px]" disabled={!report || !validRange} onClick={printPdf}><FileText className="ml-1 h-3.5 w-3.5" />PDF</Button></span></CardTitle><div className="grid gap-2 sm:grid-cols-2"><label className="text-[11px] font-bold text-slate-600">من<Input type="date" value={fromValue} onChange={(event) => setFromValue(event.target.value)} className="mt-1 h-9 text-xs" /></label><label className="text-[11px] font-bold text-slate-600">إلى<Input type="date" value={toValue} onChange={(event) => setToValue(event.target.value)} className="mt-1 h-9 text-xs" /></label></div>{!validRange && <p className="text-xs font-bold text-red-700">يجب أن يكون تاريخ البداية قبل تاريخ النهاية أو مساويًا له.</p>}</CardHeader><CardContent>{reportQuery.isLoading ? <p className="text-xs text-slate-500">جارٍ إعداد التقرير...</p> : reportQuery.isError ? <p className="text-xs text-red-700">تعذر إعداد تقرير الأداء.</p> : <div className="grid grid-cols-4 gap-2 text-center"><div className="rounded-xl bg-slate-50 p-2"><b className="block text-lg">{report?.summary.total ?? 0}</b><span className="text-[10px] text-slate-500">طلب</span></div><div className="rounded-xl bg-emerald-50 p-2"><b className="block text-lg text-emerald-700">{report?.summary.completed ?? 0}</b><span className="text-[10px] text-slate-500">مكتمل</span></div><div className="rounded-xl bg-red-50 p-2"><b className="block text-lg text-red-700">{report?.summary.delayed ?? 0}</b><span className="text-[10px] text-slate-500">متأخر</span></div><div className="rounded-xl bg-orange-50 p-2"><b className="block text-sm text-orange-700">{formatDuration(report?.summary.averagePreparationSeconds ?? 0)}</b><span className="text-[10px] text-slate-500">متوسط التحضير</span></div></div>}</CardContent></Card>
    <Card className="rounded-2xl border-slate-200 shadow-sm xl:col-span-2"><CardHeader className="pb-3"><CardTitle className="flex items-center gap-2 text-sm"><BarChart3 className="h-4 w-4 text-[#e76f3c]" />تحليل الأقسام وساعات الذروة</CardTitle><div className="flex flex-wrap gap-2 pt-2"><button type="button" onClick={() => setChartSection("all")} aria-pressed={chartSection === "all"} className={`rounded-lg px-3 py-1.5 text-[11px] font-bold ${chartSection === "all" ? "bg-[#111c2e] text-white" : "bg-slate-100 text-slate-600"}`}>كل الأقسام</button>{(report?.bySection ?? []).map((item) => { const key = String(item.sectionId ?? "unassigned"); return <button key={key} type="button" onClick={() => setChartSection(key)} aria-pressed={chartSection === key} className={`rounded-lg px-3 py-1.5 text-[11px] font-bold ${chartSection === key ? "bg-[#e76f3c] text-white" : "bg-slate-100 text-slate-600"}`}>{item.sectionName}</button>; })}</div></CardHeader><CardContent className="grid gap-5 lg:grid-cols-2"><div><p className="mb-2 text-xs font-black text-slate-700">متوسط التحضير حسب القسم</p><div className="space-y-2">{sectionStats.length === 0 ? <p className="rounded-xl bg-slate-50 p-4 text-xs text-slate-500">لا توجد بيانات ضمن النطاق.</p> : sectionStats.map((item) => <div key={String(item.sectionId ?? "unassigned")} title={`${item.sectionName}: ${formatDuration(Number(item.averagePreparationSeconds ?? 0))}`}><div className="mb-1 flex justify-between text-[10px] font-bold text-slate-600"><span>{item.sectionName}</span><span>{formatDuration(Number(item.averagePreparationSeconds ?? 0))} · {item.delayed} متأخر</span></div><div className="h-3 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#e76f3c] transition-all" style={{ width: `${Math.max(4, (Number(item.averagePreparationSeconds ?? 0) / maxSectionAverage) * 100)}%` }} /></div></div>)}</div></div><div><p className="mb-2 text-xs font-black text-slate-700">ساعة الذروة ومتوسط التحضير</p><div className="flex h-40 items-end gap-1 rounded-xl bg-slate-50 p-3">{(report?.byHour ?? []).length === 0 ? <p className="m-auto text-xs text-slate-500">لا توجد بيانات ضمن النطاق.</p> : (report?.byHour ?? []).map((item) => <button key={item.hour} type="button" title={`${item.hour}:00 · ${item.orders} طلب · ${item.delayed} متأخر`} className="group flex min-w-0 flex-1 flex-col items-center justify-end gap-1" style={{ height: "100%" }}><span className="text-[9px] text-slate-500 opacity-0 transition group-hover:opacity-100">{item.orders}</span><span className="w-full rounded-t-md bg-[#5a214f] transition-all group-hover:bg-[#e76f3c]" style={{ height: `${Math.max(8, (Number(item.averagePreparationSeconds ?? 0) / maxHourAverage) * 112)}px` }} /><span className="text-[9px] text-slate-500">{String(item.hour).padStart(2, "0")}</span></button>)}</div></div></CardContent></Card>
    <Card className="rounded-2xl border-slate-200 shadow-sm xl:col-span-2"><CardHeader className="pb-3"><CardTitle className="text-sm">السجل الزمني للطلبات</CardTitle></CardHeader><CardContent className="grid gap-4 lg:grid-cols-[240px_1fr]"> <div className="max-h-56 space-y-2 overflow-auto">{orders.slice(0, 30).map((order) => <button key={order.id} type="button" onClick={() => setSelectedOrderId(Number(order.id))} className={`flex w-full items-center justify-between rounded-xl border p-2 text-right text-xs ${selectedOrderId === Number(order.id) ? "border-[#e76f3c] bg-orange-50" : "border-slate-100 bg-slate-50"}`}><span className="font-bold">{order.id}</span><span className="text-slate-500">{statusLabel[order.status] ?? order.status}</span></button>)}</div><div>{!selected ? <p className="text-xs text-slate-500">اختر طلبًا لعرض انتقالاته.</p> : historyQuery.isLoading ? <p className="text-xs text-slate-500">جارٍ تحميل السجل...</p> : (historyQuery.data ?? []).length === 0 ? <p className="text-xs text-slate-500">لا توجد انتقالات مسجلة لهذا الطلب بعد.</p> : <div className="space-y-2">{historyQuery.data?.map((entry) => <div key={entry.id} className="flex items-center gap-3 rounded-xl border border-slate-100 bg-slate-50 p-3 text-xs"><span className="h-2 w-2 shrink-0 rounded-full bg-blue-600" /><div className="min-w-0 flex-1"><p className="font-bold">{entry.fromStatus ? `${statusLabel[entry.fromStatus] ?? entry.fromStatus} ← ` : "بدأ الطلب ← "}{statusLabel[entry.toStatus] ?? entry.toStatus}</p><p className="mt-1 text-[10px] text-slate-500">{new Date(entry.createdAt).toLocaleString("ar-SA-u-ca-gregory-nu-latn")} · مدة المرحلة: {formatDuration(Number(entry.durationSeconds ?? 0))}</p></div>{Number(entry.durationSeconds ?? 0) > selectedThresholdMinutes * 60 && <AlertTriangle className="h-4 w-4 text-red-600" />}</div>)}</div>}</div></CardContent></Card>
  </div>;
}
