import { useEffect, useMemo, useState } from "react";
import { BadgeCheck, Copy, KeyRound, Link2, RefreshCw, ShieldCheck, UserRound } from "lucide-react";
import { toast } from "sonner";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";

type Role = "customer" | "restaurant" | "driver";
type Plan = { key: string; label: string; role: Role; enabled: boolean; price: string };
type Override = { userId: number; role: Role; enabled: boolean };

const roleLabels: Record<Role, string> = { customer: "العملاء", restaurant: "المطاعم", driver: "السائقون" };
const roleKeys: Role[] = ["customer", "restaurant", "driver"];
const fallbackPlans: Plan[] = [
  { key: "customer-basic", label: "Customer Profile", role: "customer", enabled: true, price: "0.00" },
  { key: "restaurant-business", label: "Restaurant Profile", role: "restaurant", enabled: true, price: "0.00" },
];

export function ProfileGovernanceCenter() {
  const governance = trpc.admin.profileGovernance.useQuery(undefined, { retry: false });
  const customerAccounts = trpc.admin.customerAccounts.useQuery(undefined, { retry: false });
  const update = trpc.admin.updateProfileGovernance.useMutation({ onSuccess: async () => { await governance.refetch(); toast.success("تم حفظ سياسات وباقات الـProfile"); }, onError: (error) => toast.error(error.message) });
  const generate = trpc.admin.generateProfileKey.useMutation({ onSuccess: async (result) => { setGenerated(result.rawCode); await governance.refetch(); toast.success("تم توليد مفتاح جديد، احتفظ به قبل إغلاق النافذة"); }, onError: (error) => toast.error(error.message) });
  const bind = trpc.admin.bindProfileKey.useMutation({ onSuccess: async () => { await governance.refetch(); setBindingCode(""); setBoundFlash(true); window.setTimeout(() => setBoundFlash(false), 2200); toast.success("تم ربط المفتاح بالـProfile"); }, onError: (error) => toast.error(error.message) });
  const [policies, setPolicies] = useState<Record<Role, boolean>>({ customer: true, restaurant: true, driver: false });
  const [plans, setPlans] = useState<Plan[]>(fallbackPlans);
  const [overrides, setOverrides] = useState<Override[]>([]);
  const [overrideUserId, setOverrideUserId] = useState("");
  const [overrideRole, setOverrideRole] = useState<Role>("customer");
  const [generated, setGenerated] = useState("");
  const [generateRole, setGenerateRole] = useState<Role>("customer");
  const [bindingCode, setBindingCode] = useState("");
  const [bindingRole, setBindingRole] = useState<Role>("customer");
  const [bindingUserId, setBindingUserId] = useState("");
  const [customerProfileId, setCustomerProfileId] = useState("");
  const [restaurantId, setRestaurantId] = useState("");
  const [search, setSearch] = useState("");
  const [filterRole, setFilterRole] = useState<"all" | Role>("all");
  const [confirmAction, setConfirmAction] = useState<"generate" | "bind" | null>(null);
  const [boundFlash, setBoundFlash] = useState(false);

  useEffect(() => {
    if (!governance.data) return;
    setPolicies({ customer: governance.data.policies.customer, restaurant: governance.data.policies.restaurant, driver: governance.data.policies.driver });
    setPlans(governance.data.plans.length ? governance.data.plans.map((plan) => ({ ...plan, price: String(plan.price ?? "0.00") })) : fallbackPlans);
    setOverrides(governance.data.overrides ?? []);
  }, [governance.data]);

  const counts = useMemo(() => Object.fromEntries((governance.data?.codeStats ?? []).map((item) => [item.status, item.total])) as Record<string, number>, [governance.data?.codeStats]);
  const save = () => update.mutate({ profileCustomerEnabled: policies.customer, profileRestaurantEnabled: policies.restaurant, profileDriverEnabled: policies.driver, profilePlans: plans.map((plan) => ({ ...plan, price: /^\d+(\.\d{1,2})?$/.test(plan.price.trim()) ? plan.price.trim() : "0.00" })), profileAccountOverrides: overrides });
  const addOverride = () => { const userId = Number(overrideUserId); if (!Number.isInteger(userId) || userId <= 0) return toast.error("أدخل userId صحيحًا"); setOverrides((current) => [...current.filter((item) => item.userId !== userId), { userId, role: overrideRole, enabled: true }]); setOverrideUserId(""); };
  const filteredPlans = plans.filter((plan) => (filterRole === "all" || plan.role === filterRole) && `${plan.label} ${plan.key}`.toLowerCase().includes(search.trim().toLowerCase()));
  const filteredBindings = (governance.data?.bindings ?? []).filter((binding) => (filterRole === "all" || binding.targetRole === filterRole) && `${binding.id} ${binding.codeId} ${binding.userId} ${binding.customerProfileId ?? ""} ${binding.restaurantId ?? ""}`.includes(search.trim()));
  const activePlans = plans.filter((plan) => plan.enabled).length;
  const boundCount = counts.bound ?? 0;
  const availableCount = counts.available ?? 0;
  const disabledCount = counts.disabled ?? 0;
  const addPlan = () => setPlans((current) => [...current, { key: `profile-${Date.now()}`, label: "باقة Profile جديدة", role: "customer", enabled: true, price: "0.00" }]);
  const patchPlan = (index: number, patch: Partial<Plan>) => setPlans((current) => current.map((plan, itemIndex) => itemIndex === index ? { ...plan, ...patch } : plan));
  const patchPlanByKey = (key: string, patch: Partial<Plan>) => setPlans((current) => current.map((plan) => plan.key === key ? { ...plan, ...patch } : plan));
  const confirmAndRun = () => { if (confirmAction === "generate") { setGenerated(""); generate.mutate({ targetRole: generateRole }); } if (confirmAction === "bind") bind.mutate({ code: bindingCode, userId: Number(bindingUserId), targetRole: bindingRole, ...(bindingRole === "customer" ? { customerProfileId: Number(customerProfileId) } : bindingRole === "restaurant" ? { restaurantId: Number(restaurantId) } : {}) }); setConfirmAction(null); };

  return <section className="space-y-4" dir="rtl" aria-labelledby="profile-governance-title">
    {confirmAction && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="profile-confirm-title"><div className="w-full max-w-sm animate-in zoom-in-95 rounded-2xl bg-white p-5 shadow-2xl duration-200 dark:bg-slate-900"><div className="mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-orange-100 text-orange-600 dark:bg-orange-500/15"><ShieldCheck className="h-6 w-6" /></div><h3 id="profile-confirm-title" className="text-base font-black text-slate-950 dark:text-white">تأكيد الإجراء</h3><p className="mt-2 text-sm leading-6 text-slate-500">{confirmAction === "generate" ? `سيتم توليد مفتاح جديد للـ${roleLabels[generateRole]}. سيظهر المفتاح مرة واحدة فقط.` : "سيتم ربط المفتاح بالحساب والـProfile المحددين. راجع البيانات قبل المتابعة."}</p><div className="mt-5 flex gap-2"><Button type="button" variant="outline" onClick={() => setConfirmAction(null)} className="flex-1 rounded-xl text-xs">إلغاء</Button><Button type="button" onClick={confirmAndRun} className="flex-1 rounded-xl bg-[#e76f3c] text-xs hover:bg-[#d85f2e]">تأكيد ومتابعة</Button></div></div></div>}
    {boundFlash && <div className="animate-in slide-in-from-top-2 rounded-2xl border border-emerald-200 bg-emerald-50 p-3 text-sm font-black text-emerald-800 duration-300 dark:border-emerald-500/30 dark:bg-emerald-500/10 dark:text-emerald-200" role="status">تم ربط البطاقة بالـProfile بنجاح</div>}
    <Card className="overflow-hidden rounded-2xl border-slate-200/80 bg-white shadow-sm dark:border-slate-700/80 dark:bg-slate-900/90">
      <CardHeader className="border-b border-slate-100 bg-gradient-to-l from-orange-50 to-white pb-4 dark:border-slate-800 dark:from-orange-500/10 dark:to-slate-900">
        <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-[10px] font-black uppercase tracking-[0.18em] text-orange-600">Profile Control Center</p><CardTitle id="profile-governance-title" className="mt-1 text-lg font-black text-slate-950 dark:text-white">صلاحيات الـProfile والباقات والمفاتيح</CardTitle><p className="mt-1 text-xs text-slate-500 dark:text-slate-400">تحكم في أهلية إنشاء Profile، ثم ولّد المفتاح أو اربطه بشكل مستقل مع عرض بيانات الربط.</p></div><ShieldCheck className="h-7 w-7 text-orange-500" /></div>
      </CardHeader>
      <CardContent className="space-y-5 p-4">
        <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-2xl bg-emerald-50 p-3 dark:bg-emerald-500/10"><p className="text-[10px] font-bold text-emerald-700">بطاقات مربوطة</p><p className="mt-1 text-2xl font-black text-emerald-800 dark:text-emerald-200">{boundCount}</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-emerald-100 dark:bg-emerald-900"><div className="h-full rounded-full bg-emerald-500 transition-all duration-500" style={{ width: `${Math.min(100, boundCount * 10)}%` }} /></div></div><div className="rounded-2xl bg-orange-50 p-3 dark:bg-orange-500/10"><p className="text-[10px] font-bold text-orange-700">مفاتيح متاحة</p><p className="mt-1 text-2xl font-black text-orange-800 dark:text-orange-200">{availableCount}</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-orange-100 dark:bg-orange-900"><div className="h-full rounded-full bg-orange-500 transition-all duration-500" style={{ width: `${Math.min(100, availableCount * 10)}%` }} /></div></div><div className="rounded-2xl bg-red-50 p-3 dark:bg-red-500/10"><p className="text-[10px] font-bold text-red-700">مفاتيح معطلة</p><p className="mt-1 text-2xl font-black text-red-800 dark:text-red-200">{disabledCount}</p><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-red-100 dark:bg-red-900"><div className="h-full rounded-full bg-red-500 transition-all duration-500" style={{ width: `${Math.min(100, disabledCount * 10)}%` }} /></div></div><div className="rounded-2xl bg-violet-50 p-3 dark:bg-violet-500/10"><p className="text-[10px] font-bold text-violet-700">الباقات النشطة</p><p className="mt-1 text-2xl font-black text-violet-800 dark:text-violet-200">{activePlans}</p><p className="mt-2 text-[10px] text-violet-600">من أصل {plans.length} باقة</p></div></div>
        <div className="flex flex-col gap-2 rounded-2xl border border-slate-100 bg-slate-50/70 p-3 sm:flex-row dark:border-slate-800 dark:bg-slate-800/40"><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ابحث باسم الباقة أو المفتاح أو userId أو رقم الربط…" aria-label="البحث في مركز Profile" className="rounded-xl bg-white text-xs dark:bg-slate-900" /><select value={filterRole} onChange={(event) => setFilterRole(event.target.value as "all" | Role)} aria-label="تصفية نوع الحساب" className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-xs dark:border-slate-700 dark:bg-slate-900"><option value="all">كل الأنواع</option>{roleKeys.map((role) => <option key={role} value={role}>{roleLabels[role]}</option>)}</select></div>
        <div className="grid gap-3 md:grid-cols-3">{roleKeys.map((role) => <button key={role} type="button" onClick={() => setPolicies((current) => ({ ...current, [role]: !current[role] }))} className={`flex items-center justify-between rounded-2xl border p-3 text-right transition ${policies[role] ? "border-emerald-200 bg-emerald-50/80 dark:border-emerald-500/30 dark:bg-emerald-500/10" : "border-slate-200 bg-slate-50 dark:border-slate-700 dark:bg-slate-800/70"}`}><span><span className="block text-sm font-black text-slate-900 dark:text-white">{roleLabels[role]}</span><span className="mt-1 block text-[11px] text-slate-500">{policies[role] ? "مسموح بإنشاء Profile" : "غير مسموح حاليًا"}</span></span><span className={`relative h-6 w-11 rounded-full p-1 ${policies[role] ? "bg-emerald-500" : "bg-slate-300 dark:bg-slate-600"}`}><span className={`block h-4 w-4 rounded-full bg-white shadow transition-transform ${policies[role] ? "translate-x-0" : "translate-x-5"}`} /></span></button>)}</div>
        <div className="rounded-2xl border border-slate-100 bg-slate-50/70 p-3 dark:border-slate-800 dark:bg-slate-800/40"><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-black text-slate-900 dark:text-white">باقات Profile</p><p className="text-[11px] text-slate-500">يمكن تفعيل باقة مجانية أو مدفوعة لكل نوع حساب، وتعديلها لاحقًا من نفس المكان.</p></div><Button type="button" variant="outline" onClick={addPlan} className="rounded-xl text-xs">إضافة باقة</Button></div><div className="space-y-2">{filteredPlans.map((plan, index) => <div key={`${plan.key}-${index}`} className="grid gap-2 rounded-xl border border-slate-200 bg-white p-3 md:grid-cols-[1.2fr_1.4fr_1fr_0.7fr_auto] dark:border-slate-700 dark:bg-slate-900"><Input value={plan.label} onChange={(event) => patchPlanByKey(plan.key, { label: event.target.value })} aria-label="اسم باقة Profile" className="rounded-lg text-xs" /><select value={plan.role} onChange={(event) => patchPlanByKey(plan.key, { role: event.target.value as Role })} className="h-10 rounded-lg border border-slate-200 bg-white px-2 text-xs dark:border-slate-700 dark:bg-slate-900"><option value="customer">العملاء</option><option value="restaurant">المطاعم</option><option value="driver">السائقون</option></select><Input value={plan.price} onChange={(event) => patchPlanByKey(plan.key, { price: event.target.value })} dir="ltr" aria-label="سعر الباقة" className="rounded-lg text-xs" placeholder="0.00" /><button type="button" onClick={() => patchPlanByKey(plan.key, { enabled: !plan.enabled })} className={`rounded-lg px-2 text-xs font-bold ${plan.enabled ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{plan.enabled ? "مفعلة" : "متوقفة"}</button><span className="flex items-center text-[10px] text-slate-400" dir="ltr">{plan.key}</span></div>)}</div></div>
        <div className="flex justify-end"><Button type="button" onClick={save} disabled={update.isPending} className="rounded-xl bg-[#e76f3c] px-5 text-xs font-black hover:bg-[#d85f2e]">{update.isPending ? "جارٍ الحفظ…" : "حفظ سياسات وباقات Profile"}</Button></div>
      </CardContent>
    </Card>

    <Card className="rounded-2xl border-slate-200/80 bg-white shadow-sm dark:border-slate-700/80 dark:bg-slate-900/90"><CardHeader><CardTitle className="flex items-center gap-2 text-sm font-black"><UserRound className="h-4 w-4 text-orange-500" />استثناءات الحسابات</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-xs text-slate-500">الإعداد العام يحدد القاعدة، ويمكن هنا تجاوزها لحساب محدد. اكتب userId ثم اختر نوع الحساب وأضفه إلى قائمة الاستثناءات.</p><div className="grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><Input value={overrideUserId} onChange={(event) => setOverrideUserId(event.target.value)} inputMode="numeric" dir="ltr" placeholder="userId" className="rounded-xl text-xs" /><select value={overrideRole} onChange={(event) => setOverrideRole(event.target.value as Role)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-xs dark:border-slate-700 dark:bg-slate-900">{roleKeys.map((role) => <option key={role} value={role}>{roleLabels[role]}</option>)}</select><Button type="button" onClick={addOverride} variant="outline" className="rounded-xl text-xs">إضافة استثناء</Button></div>{overrides.length > 0 && <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4">{overrides.map((item) => <div key={`${item.userId}-${item.role}`} className="flex items-center justify-between gap-2 rounded-xl border border-slate-100 bg-slate-50 p-2.5 text-xs dark:border-slate-800 dark:bg-slate-800/60"><span><b>user #{item.userId}</b><span className="mr-1 text-slate-500">· {roleLabels[item.role]}</span></span><button type="button" onClick={() => setOverrides((current) => current.map((entry) => entry.userId === item.userId ? { ...entry, enabled: !entry.enabled } : entry))} className={`rounded-lg px-2 py-1 font-bold ${item.enabled ? "bg-emerald-100 text-emerald-700" : "bg-red-100 text-red-700"}`}>{item.enabled ? "مسموح" : "ممنوع"}</button></div>)}</div>}</CardContent></Card>

    <div className="grid gap-4 xl:grid-cols-2">
      <Card className="rounded-2xl border-slate-200/80 bg-white shadow-sm dark:border-slate-700/80 dark:bg-slate-900/90"><CardHeader><CardTitle className="flex items-center gap-2 text-sm font-black"><KeyRound className="h-4 w-4 text-orange-500" />توليد مفتاح مستقل</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-xs text-slate-500">التوليد مفتوح للإدارة. المفتاح الخام يظهر مرة واحدة فقط؛ لا يتم تخزينه، ويُحفظ hash آمن في النظام.</p><div className="flex gap-2"><select value={generateRole} onChange={(event) => setGenerateRole(event.target.value as Role)} className="h-10 flex-1 rounded-xl border border-slate-200 bg-white px-3 text-xs dark:border-slate-700 dark:bg-slate-900">{roleKeys.map((role) => <option key={role} value={role}>{roleLabels[role]}</option>)}</select><Button type="button" onClick={() => setConfirmAction("generate")} disabled={generate.isPending} className="rounded-xl bg-[#101d31] text-xs">{generate.isPending ? "جارٍ…" : "توليد المفتاح"}</Button></div>{generated && <div className="animate-in zoom-in-95 rounded-xl border border-amber-200 duration-300 bg-amber-50 p-3 dark:border-amber-500/30 dark:bg-amber-500/10"><p className="text-[11px] font-bold text-amber-800 dark:text-amber-200">احفظ هذا المفتاح الآن؛ لن يظهر مرة أخرى.</p><div className="mt-2 flex items-center gap-2"><code dir="ltr" className="min-w-0 flex-1 break-all rounded-lg bg-white px-2 py-2 text-xs font-bold text-slate-900">{generated}</code><Button type="button" size="sm" variant="outline" onClick={() => { void navigator.clipboard?.writeText(generated); toast.success("تم نسخ المفتاح"); }} className="rounded-lg"><Copy className="h-3.5 w-3.5" /></Button></div></div>}<div className="grid grid-cols-4 gap-2">{["available", "bound", "disabled", "reserved"].map((status) => <div key={status} className="rounded-xl bg-slate-50 p-2 text-center dark:bg-slate-800/70"><p className="text-lg font-black text-slate-900 dark:text-white">{counts[status] ?? 0}</p><p className="text-[10px] text-slate-500">{status}</p></div>)}</div></CardContent></Card>
      <Card className="rounded-2xl border-slate-200/80 bg-white shadow-sm dark:border-slate-700/80 dark:bg-slate-900/90"><CardHeader><CardTitle className="flex items-center gap-2 text-sm font-black"><Link2 className="h-4 w-4 text-emerald-600" />ربط المفتاح بـProfile</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-xs text-slate-500">اختر اسم العميل وProfile الخاص به، ثم أدخل المفتاح الخام لربط بطاقة NFC بالملف الصحيح.</p><div className="grid gap-2 sm:grid-cols-2"><select value={bindingRole} onChange={(event) => setBindingRole(event.target.value as Role)} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-xs dark:border-slate-700 dark:bg-slate-900">{roleKeys.map((role) => <option key={role} value={role}>{roleLabels[role]}</option>)}</select>{bindingRole === "customer" ? <select value={customerProfileId} onChange={(event) => { const account = (customerAccounts.data?.customers ?? []).find((item) => String(item.customerProfileId ?? "") === event.target.value); setCustomerProfileId(event.target.value); setBindingUserId(account?.userId ? String(account.userId) : ""); }} className="h-10 rounded-xl border border-slate-200 bg-white px-3 text-xs dark:border-slate-700 dark:bg-slate-900"><option value="">اختر Profile العميل بالاسم</option>{(customerAccounts.data?.customers ?? []).filter((item) => item.userId && item.customerProfileId).map((item) => <option key={item.customerProfileId} value={item.customerProfileId ?? ""}>{item.displayName} · {item.email}</option>)}</select> : <Input value={bindingUserId} onChange={(event) => setBindingUserId(event.target.value)} inputMode="numeric" dir="ltr" placeholder="معرّف الحساب userId" className="rounded-xl text-xs" />}<Input value={bindingRole === "customer" ? customerProfileId : restaurantId} onChange={(event) => bindingRole === "customer" ? setCustomerProfileId(event.target.value) : setRestaurantId(event.target.value)} inputMode="numeric" dir="ltr" readOnly={bindingRole === "customer"} placeholder={bindingRole === "customer" ? "معرّف Profile العميل" : "معرّف المطعم"} className="rounded-xl text-xs" /><Input value={bindingCode} onChange={(event) => setBindingCode(event.target.value)} dir="ltr" placeholder="المفتاح الخام المراد ربطه" className="rounded-xl text-xs sm:col-span-2" /></div><Button type="button" onClick={() => setConfirmAction("bind")} disabled={bind.isPending || !bindingCode || !Number(bindingUserId) || (bindingRole === "customer" ? !Number(customerProfileId) : bindingRole === "restaurant" ? !Number(restaurantId) : false)} className="w-full rounded-xl bg-emerald-600 text-xs hover:bg-emerald-700">{bind.isPending ? "جارٍ الربط…" : "ربط المفتاح الآن"}</Button></CardContent></Card>
    </div>

    <Card className="rounded-2xl border-slate-200/80 bg-white shadow-sm dark:border-slate-700/80 dark:bg-slate-900/90"><CardHeader><div className="flex items-center justify-between gap-2"><CardTitle className="flex items-center gap-2 text-sm font-black"><BadgeCheck className="h-4 w-4 text-emerald-600" />بيانات الربط الأخيرة</CardTitle><Button type="button" variant="ghost" size="sm" onClick={() => void governance.refetch()} className="rounded-lg text-xs"><RefreshCw className="ml-1 h-3.5 w-3.5" />تحديث</Button></div></CardHeader><CardContent>{governance.isLoading ? <p className="text-xs text-slate-500">جارٍ تحميل بيانات الربط…</p> : governance.isError ? <p className="rounded-xl bg-red-50 p-3 text-xs text-red-700">تعذر تحميل بيانات الربط.</p> : (governance.data?.bindings ?? []).length === 0 ? <p className="rounded-xl bg-slate-50 p-3 text-xs text-slate-500 dark:bg-slate-800/70">لا توجد بطاقات مربوطة بعد. يمكنك توليد أول مفتاح من البطاقة أعلاه.</p> : <div className="space-y-2">{filteredBindings.map((binding) => <div key={binding.id} className="grid gap-1 rounded-xl border border-slate-100 bg-slate-50 p-3 text-xs dark:border-slate-800 dark:bg-slate-800/60 sm:grid-cols-2 lg:grid-cols-4"><span><b>Binding:</b> #{binding.id}</span><span><b>Code:</b> #{binding.codeId}</span><span><b>Owner:</b> user #{binding.userId}</span><span><b>النوع:</b> {roleLabels[binding.targetRole as Role] ?? binding.targetRole}</span><span><b>Profile:</b> {binding.customerProfileId ? `#${binding.customerProfileId}` : "—"}</span><span><b>المطعم:</b> {binding.restaurantId ? `#${binding.restaurantId}` : "—"}</span><span className="text-slate-500 sm:col-span-2 lg:col-span-2"><b>أنشئ في:</b> {new Date(binding.createdAt).toLocaleString("ar-SA-u-ca-gregory-nu-latn")}</span></div>)}</div>}</CardContent></Card>
  </section>;
}
