import { useEffect, useMemo, useState } from "react";
import { QRCodeSVG } from "qrcode.react";
import Barcode from "react-barcode";
import { Check, Download, ExternalLink, Hash, Link2, Printer, QrCode, RefreshCw, ShieldCheck, Sparkles, Star, Table2, UserRound, X } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { useLanguage } from "@/contexts/LanguageContext";
import { buildStableQrMenuUrl } from "@/lib/qrUrl";

type QrType = "table" | "order" | "waiter_call" | "custom";
type QrPurpose = "menu" | "table_service" | "waiter_call" | "google_reviews" | "custom";
type QrCodeRow = { id: number; type: QrType; purpose: string; targetUrl: string | null; token: string; label: string; tableId: number | null; orderId: number | null; amount: string | null; status: "active" | "used" | "disabled" | "expired"; expiresAt: Date | string | null; createdAt: Date | string };

type Copy = {
  title: string; subtitle: string; fixedId: string; fixedIdHelp: string; branch: string; noBranch: string; tableQr: string; tableQrHelp: string; waiterQr: string; waiterQrHelp: string; orderQr: string; orderQrHelp: string; createTables: string; createWaiter: string; selected: string; allTables: string; noTables: string; orderNumber: string; expiry: string; hours: string; createOrder: string; active: string; disabled: string; expired: string; used: string; print: string; download: string; disable: string; empty: string; generated: string; invalidOrder: string; noCodes: string; stableNote: string; copied: string; close: string; customTitle: string; customHelp: string; purpose: string; purposeMenu: string; purposeTable: string; purposeWaiter: string; purposeGoogle: string; purposeCustom: string; tableOptional: string; labelOptional: string; targetUrl: string; targetUrlHelp: string; createCustom: string; requiredUrl: string; menuId: string;
};
const copies: Record<"ar" | "en" | "fr" | "ur", Copy> = {
  ar: { title: "تخصيص QR والباركود", subtitle: "أنشئ رموزًا تشغيلية مستقلة للفرع دون ربطها بعنوان متغير.", fixedId: "المعرّف الثابت للمطعم", fixedIdHelp: "هذا المعرّف لا يعتمد على اسم الرابط أو الـ slug؛ لذلك تظل رموز QR صالحة عند تغيير بيانات الموقع.", branch: "الفرع الحالي", noBranch: "اختر فرعًا من مساحة العمل أولًا.", tableQr: "QR الطاولات", tableQrHelp: "رمز يفتح المنيو مع تحديد الطاولة تلقائيًا.", waiterQr: "استدعاء النادل", waiterQrHelp: "رمز مستقل لكل طاولة لإرسال طلب خدمة إلى فريق المطعم.", orderQr: "QR الطلبات", orderQrHelp: "رمز خاص بطلب محدد، مع حفظ إجمالي الطلب ووقت انتهاء اختياري.", createTables: "إنشاء رموز الطاولات", createWaiter: "إنشاء رموز استدعاء النادل", selected: "محدد", allTables: "تحديد الكل", noTables: "لا توجد طاولات لهذا الفرع بعد.", orderNumber: "رقم الطلب", expiry: "مدة الصلاحية", hours: "ساعة", createOrder: "إنشاء QR للطلب", active: "نشط", disabled: "معطل", expired: "منتهي", used: "مستخدم", print: "طباعة", download: "تنزيل", disable: "تعطيل", empty: "لم يتم إنشاء رموز في هذا القسم بعد.", generated: "تم تحديث رموز QR بنجاح", invalidOrder: "أدخل رقم طلب صحيحًا", noCodes: "لا توجد رموز", stableNote: "لا نستخدم barcode إدخال المنتجات هنا؛ هذا المركز مخصص لرموز التشغيل فقط.", copied: "تم تجهيز الملف للتنزيل", close: "إغلاق", customTitle: "مولد QR المخصص", customHelp: "اختر الغرض والطاولة، ثم اطبع رمزًا ثابتًا يعتمد على هوية المطعم.", purpose: "نوع الاستخدام", purposeMenu: "منيو المطعم", purposeTable: "طاولة تناول طعام", purposeWaiter: "نداء النادل", purposeGoogle: "تقييمات Google", purposeCustom: "رابط مخصص", tableOptional: "الطاولة (اختياري)", labelOptional: "اسم البطاقة (اختياري)", targetUrl: "الرابط المستهدف", targetUrlHelp: "مطلوب لتقييم Google أو الرابط المخصص ويجب أن يبدأ بـ https://", createCustom: "إنشاء رمز ثابت", requiredUrl: "أدخل رابطًا آمنًا يبدأ بـ https://", menuId: "هوية المطعم الثابتة" },
  en: { title: "QR & barcode customization", subtitle: "Create operational codes for a branch without coupling them to a changing URL.", fixedId: "Restaurant stable identifier", fixedIdHelp: "This identifier is independent from the URL slug, so QR codes keep working when site details change.", branch: "Current branch", noBranch: "Choose a branch from the workspace first.", tableQr: "Table QR", tableQrHelp: "Opens the menu with the table selected automatically.", waiterQr: "Call waiter", waiterQrHelp: "A separate code for each table that sends a service request to the restaurant team.", orderQr: "Order QR", orderQrHelp: "A code for one order, storing its total and an optional expiry time.", createTables: "Create table codes", createWaiter: "Create waiter-call codes", selected: "selected", allTables: "Select all", noTables: "No tables exist for this branch yet.", orderNumber: "Order number", expiry: "Validity", hours: "hours", createOrder: "Create order QR", active: "Active", disabled: "Disabled", expired: "Expired", used: "Used", print: "Print", download: "Download", disable: "Disable", empty: "No codes have been created in this section yet.", generated: "QR codes updated successfully", invalidOrder: "Enter a valid order number", noCodes: "No codes", stableNote: "Product-entry barcodes are not managed here; this center is for operational codes only.", copied: "File prepared for download", close: "Close", customTitle: "Custom QR generator", customHelp: "Choose a purpose and table, then print a stable code based on the restaurant identity.", purpose: "Use case", purposeMenu: "Restaurant menu", purposeTable: "Dining table", purposeWaiter: "Call waiter", purposeGoogle: "Google reviews", purposeCustom: "Custom link", tableOptional: "Table (optional)", labelOptional: "Card name (optional)", targetUrl: "Target URL", targetUrlHelp: "Required for Google reviews or a custom link; must start with https://", createCustom: "Create stable code", requiredUrl: "Enter a secure URL starting with https://", menuId: "Stable restaurant identity" },
  fr: { title: "Personnalisation QR et codes-barres", subtitle: "Créez des codes opérationnels sans les lier à une URL qui peut changer.", fixedId: "Identifiant stable du restaurant", fixedIdHelp: "Cet identifiant est indépendant du slug ; les QR restent donc valides si les informations du site changent.", branch: "Succursale actuelle", noBranch: "Choisissez d’abord une succursale dans l’espace de travail.", tableQr: "QR des tables", tableQrHelp: "Ouvre le menu avec la table sélectionnée automatiquement.", waiterQr: "Appel serveur", waiterQrHelp: "Un code par table pour envoyer une demande de service à l’équipe.", orderQr: "QR des commandes", orderQrHelp: "Un code lié à une commande, avec son total et une expiration facultative.", createTables: "Créer les codes des tables", createWaiter: "Créer les codes d’appel", selected: "sélectionnées", allTables: "Tout sélectionner", noTables: "Aucune table pour cette succursale.", orderNumber: "Numéro de commande", expiry: "Validité", hours: "heures", createOrder: "Créer le QR de commande", active: "Actif", disabled: "Désactivé", expired: "Expiré", used: "Utilisé", print: "Imprimer", download: "Télécharger", disable: "Désactiver", empty: "Aucun code créé dans cette section.", generated: "QR mis à jour", invalidOrder: "Saisissez un numéro valide", noCodes: "Aucun code", stableNote: "Les codes-barres de saisie des produits ne sont pas gérés ici ; ce centre concerne les codes opérationnels.", copied: "Fichier prêt au téléchargement", close: "Fermer", customTitle: "Générateur QR personnalisé", customHelp: "Choisissez un usage et une table, puis imprimez un code stable lié à l’identité du restaurant.", purpose: "Usage", purposeMenu: "Menu du restaurant", purposeTable: "Table de repas", purposeWaiter: "Appel serveur", purposeGoogle: "Avis Google", purposeCustom: "Lien personnalisé", tableOptional: "Table (facultatif)", labelOptional: "Nom de la carte (facultatif)", targetUrl: "URL cible", targetUrlHelp: "Requis pour Google ou un lien personnalisé ; doit commencer par https://", createCustom: "Créer un code stable", requiredUrl: "Saisissez une URL sécurisée commençant par https://", menuId: "Identité stable du restaurant" },
  ur: { title: "QR اور بارکوڈ تخصیص", subtitle: "برانچ کے لیے ایسے عملی کوڈ بنائیں جو تبدیل ہونے والے URL سے منسلک نہ ہوں۔", fixedId: "ریستوران کا مستقل شناختی نمبر", fixedIdHelp: "یہ شناختی نمبر URL کے slug سے آزاد ہے، اس لیے سائٹ کی معلومات بدلنے پر بھی QR فعال رہیں گے۔", branch: "موجودہ برانچ", noBranch: "پہلے ورک اسپیس سے برانچ منتخب کریں۔", tableQr: "ٹیبل QR", tableQrHelp: "مینو کو منتخب ٹیبل کے ساتھ کھولتا ہے۔", waiterQr: "ویٹر بلائیں", waiterQrHelp: "ہر ٹیبل کے لیے سروس درخواست کا الگ کوڈ۔", orderQr: "آرڈر QR", orderQrHelp: "ایک آرڈر کا کوڈ، رقم اور اختیاری میعاد کے ساتھ۔", createTables: "ٹیبل کوڈ بنائیں", createWaiter: "ویٹر کال کوڈ بنائیں", selected: "منتخب", allTables: "سب منتخب کریں", noTables: "اس برانچ میں ابھی ٹیبل نہیں ہیں۔", orderNumber: "آرڈر نمبر", expiry: "مدت", hours: "گھنٹے", createOrder: "آرڈر QR بنائیں", active: "فعال", disabled: "غیر فعال", expired: "میعاد ختم", used: "استعمال شدہ", print: "پرنٹ", download: "ڈاؤن لوڈ", disable: "غیر فعال کریں", empty: "اس حصے میں ابھی کوئی کوڈ نہیں بنایا گیا۔", generated: "QR کامیابی سے اپ ڈیٹ ہو گئے", invalidOrder: "درست آرڈر نمبر درج کریں", noCodes: "کوڈ نہیں", stableNote: "پروڈکٹ انٹری بارکوڈ یہاں منظم نہیں ہوتے؛ یہ مرکز صرف عملی کوڈز کے لیے ہے۔", copied: "فائل ڈاؤن لوڈ کے لیے تیار ہے", close: "بند کریں", customTitle: "حسب ضرورت QR جنریٹر", customHelp: "مقصد اور ٹیبل منتخب کریں، پھر ریستوران کی مستقل شناخت سے جڑا کوڈ پرنٹ کریں۔", purpose: "استعمال کی قسم", purposeMenu: "ریستوران مینو", purposeTable: "کھانے کی میز", purposeWaiter: "ویٹر بلائیں", purposeGoogle: "Google ریویوز", purposeCustom: "حسب ضرورت لنک", tableOptional: "ٹیبل (اختیاری)", labelOptional: "کارڈ کا نام (اختیاری)", targetUrl: "مطلوبہ URL", targetUrlHelp: "Google یا حسب ضرورت لنک کے لیے ضروری؛ https:// سے شروع ہونا چاہیے۔", createCustom: "مستقل کوڈ بنائیں", requiredUrl: "https:// سے شروع ہونے والا محفوظ URL درج کریں", menuId: "ریستوران کی مستقل شناخت" },
};

function formatDate(value: Date | string | null, language: string) {
  if (!value) return "—";
  return new Intl.DateTimeFormat(language === "ar" ? "ar-SA" : language === "fr" ? "fr-FR" : language === "ur" ? "ur-PK" : "en-US", { dateStyle: "short", timeStyle: "short" }).format(new Date(value));
}

export function QROperationsPanel({ restaurantId, branchId }: { restaurantId: number; branchId?: number }) {
  const { language } = useLanguage();
  const copy = copies[language] ?? copies.en;
  const effectiveBranchId = branchId ?? 0;
  const query = trpc.platform.qrCodes.useQuery({ restaurantId, branchId: effectiveBranchId }, { enabled: Boolean(restaurantId && effectiveBranchId), retry: false });
  const [selectedTableIds, setSelectedTableIds] = useState<number[]>([]);
  const [orderId, setOrderId] = useState("");
  const [expiresHours, setExpiresHours] = useState("24");
  const [customPurpose, setCustomPurpose] = useState<QrPurpose>("menu");
  const [customTableId, setCustomTableId] = useState("");
  const [customLabel, setCustomLabel] = useState("");
  const [customTargetUrl, setCustomTargetUrl] = useState("");
  const utils = trpc.useUtils();
  const refresh = () => void utils.platform.qrCodes.invalidate({ restaurantId, branchId: effectiveBranchId });
  const tableMutation = trpc.platform.createTableQrCodes.useMutation({ onSuccess: () => { toast.success(copy.generated); refresh(); }, onError: error => toast.error(error.message) });
  const waiterMutation = trpc.platform.createWaiterCallQrCodes.useMutation({ onSuccess: () => { toast.success(copy.generated); refresh(); }, onError: error => toast.error(error.message) });
  const orderMutation = trpc.platform.createOrderQrCode.useMutation({ onSuccess: () => { toast.success(copy.generated); setOrderId(""); refresh(); }, onError: error => toast.error(error.message) });
  const customMutation = trpc.platform.createCustomQrCode.useMutation({ onSuccess: () => { toast.success(copy.generated); setCustomLabel(""); setCustomTargetUrl(""); refresh(); }, onError: error => toast.error(error.message) });
  const disableMutation = trpc.platform.disableQrCode.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });
  const tables = query.data?.tables ?? [];
  const codes = (query.data?.codes ?? []) as QrCodeRow[];
  const grouped = useMemo(() => ({ table: codes.filter(code => code.type === "table"), waiter_call: codes.filter(code => code.type === "waiter_call"), order: codes.filter(code => code.type === "order"), custom: codes.filter(code => code.type === "custom") }), [codes]);
  useEffect(() => { if (tables.length && selectedTableIds.length === 0) setSelectedTableIds(tables.map(table => table.id)); }, [tables, selectedTableIds.length]);
  const stableUrl = (token: string) => buildStableQrMenuUrl(window.location.origin, query.data?.fixedIdentifier ?? "", token);
  const statusLabel = (status: QrCodeRow["status"]) => ({ active: copy.active, disabled: copy.disabled, expired: copy.expired, used: copy.used })[status];
  const purposeLabel = (purpose: string) => ({ menu: copy.purposeMenu, table_service: copy.purposeTable, waiter_call: copy.purposeWaiter, google_reviews: copy.purposeGoogle, custom: copy.purposeCustom }[purpose] ?? purpose);
  const codeValue = (code: QrCodeRow) => code.targetUrl?.trim() || stableUrl(code.token);
  const printCodes = (items: QrCodeRow[]) => {
    if (!items.length) return toast.info(copy.noCodes);
    const cards = items.map(code => { const svg = document.querySelector(`[data-qr-id="${code.id}"] svg`)?.outerHTML ?? ""; return `<article><div class="qr">${svg}</div><h2>${code.label}</h2><p>${codeValue(code)}</p><div class="barcode"><svg>${document.querySelector(`[data-barcode-id="${code.id}"] svg`)?.innerHTML ?? ""}</svg></div></article>`; }).join("");
    const popup = window.open("", "nfood-qr-print", "width=900,height=700");
    if (!popup) return window.print();
    popup.document.write(`<html dir="rtl"><head><title>NFOOD QR</title><style>body{font-family:Arial,sans-serif;padding:24px;color:#111}main{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}article{border:1px solid #ddd;border-radius:16px;padding:14px;text-align:center;break-inside:avoid}.qr svg{width:170px;height:170px}.barcode{overflow:hidden;margin-top:6px}.barcode svg{width:200px;height:55px}h2{font-size:15px;margin:10px 0 5px}p{font:10px monospace;word-break:break-all;color:#555}</style></head><body><main>${cards}</main><script>window.onload=()=>{window.focus();window.print()}</script></body></html>`);
    popup.document.close();
  };
  const downloadCode = (code: QrCodeRow) => {
    const svg = document.querySelector(`[data-qr-id="${code.id}"] svg`) as SVGSVGElement | null;
    if (!svg) return;
    const blob = new Blob([new XMLSerializer().serializeToString(svg)], { type: "image/svg+xml;charset=utf-8" });
    const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `nfood-${code.type}-${code.id}.svg`; anchor.click(); URL.revokeObjectURL(url); toast.success(copy.copied);
  };
  const toggleTable = (id: number) => setSelectedTableIds(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id]);
  const createOrder = () => { const parsed = Number(orderId); if (!Number.isInteger(parsed) || parsed <= 0) return toast.error(copy.invalidOrder); orderMutation.mutate({ restaurantId, branchId: effectiveBranchId, orderId: parsed, expiresHours: Math.max(1, Math.min(168, Number(expiresHours) || 24)) }); };
  const createCustom = () => { const needsUrl = customPurpose === "google_reviews" || customPurpose === "custom"; if (needsUrl && !/^https:\/\//i.test(customTargetUrl.trim())) return toast.error(copy.requiredUrl); customMutation.mutate({ restaurantId, branchId: effectiveBranchId, tableId: customTableId ? Number(customTableId) : null, purpose: customPurpose, label: customLabel.trim() || undefined, targetUrl: customTargetUrl.trim() || null }); };
  const renderCode = (code: QrCodeRow) => (
    <div key={code.id} data-qr-id={code.id} className="group rounded-2xl border border-slate-700/80 bg-slate-950/70 p-3 transition hover:-translate-y-0.5 hover:border-orange-400/70 hover:shadow-lg hover:shadow-orange-950/30">
      <div className="flex items-start justify-between gap-2">
        <div><p className="text-sm font-black text-white">{code.label}</p><div className="mt-1 flex flex-wrap items-center gap-1.5 text-[10px] text-slate-400"><span>{purposeLabel(code.purpose)}</span>{code.tableId && <><span>·</span><span><Table2 className="inline h-3 w-3" /> #{code.tableId}</span></>}<span>·</span><span>{formatDate(code.createdAt, language)}</span></div></div>
        <Badge className={code.status === "active" ? "bg-emerald-500/15 text-emerald-300" : "bg-slate-700 text-slate-300"}>{statusLabel(code.status)}</Badge>
      </div>
      <div className="mt-3 grid place-items-center rounded-xl bg-white p-2"><QRCodeSVG value={codeValue(code)} size={148} level="H" includeMargin /></div>
      <div data-barcode-id={code.id} className="mt-2 overflow-hidden rounded-lg bg-white px-1 py-1"><Barcode value={code.token} height={38} width={1.35} displayValue={false} margin={0} /></div>
      <p className="mt-2 truncate font-mono text-[9px] text-slate-500" title={codeValue(code)}>{codeValue(code)}</p>
      {code.amount && <p className="mt-1 text-xs font-bold text-amber-300">{Number(code.amount).toLocaleString(language === "ar" ? "ar-SA" : language === "fr" ? "fr-FR" : "en-US")} {query.data?.currencyCode ?? "SAR"}</p>}
      {code.expiresAt && <p className="mt-1 text-[10px] text-slate-400">{copy.expiry}: {formatDate(code.expiresAt, language)}</p>}
      <div className="mt-3 flex gap-2"><Button type="button" size="sm" onClick={() => downloadCode(code)} className="h-8 flex-1 gap-1 rounded-lg bg-white/10 text-[10px] text-white hover:bg-white/20"><Download className="h-3.5 w-3.5" />{copy.download}</Button><Button type="button" size="sm" variant="outline" onClick={() => disableMutation.mutate({ restaurantId, branchId: effectiveBranchId, id: code.id })} disabled={code.status !== "active" || disableMutation.isPending} className="h-8 gap-1 rounded-lg border-white/15 bg-transparent text-[10px] text-slate-300"><X className="h-3.5 w-3.5" />{copy.disable}</Button></div>
    </div>
  );
  const sections: Array<{ key: QrType; title: string; items: QrCodeRow[] }> = [
    { key: "table", title: copy.tableQr, items: grouped.table },
    { key: "waiter_call", title: copy.waiterQr, items: grouped.waiter_call },
    { key: "order", title: copy.orderQr, items: grouped.order },
    { key: "custom", title: copy.customTitle, items: grouped.custom },
  ];
  if (!effectiveBranchId) return <Card className="rounded-3xl border-slate-700 bg-[#111c2e] text-white"><CardContent className="p-8 text-center text-sm text-slate-300">{copy.noBranch}</CardContent></Card>;
  return (
    <div className="space-y-4" data-testid="qr-operations-panel">
      <Card className="overflow-hidden rounded-3xl border-slate-700 bg-[#111c2e] text-white shadow-xl shadow-slate-950/20">
        <CardHeader className="border-b border-white/10 bg-gradient-to-l from-orange-500/15 via-transparent to-transparent p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><CardTitle className="flex items-center gap-2 text-xl font-black"><QrCode className="h-5 w-5 text-orange-300" />{copy.title}</CardTitle><p className="mt-2 max-w-2xl text-xs leading-6 text-slate-300">{copy.subtitle}</p></div><Badge className="gap-1 bg-emerald-400/10 text-emerald-300"><ShieldCheck className="h-3.5 w-3.5" />{copy.branch}: {query.data?.branch.name ?? "—"}</Badge></div></CardHeader>
        <CardContent className="space-y-4 p-5">
          <div className="grid gap-3 lg:grid-cols-[1fr_auto]"><div className="rounded-2xl border border-orange-400/25 bg-orange-500/10 p-4"><p className="flex items-center gap-2 text-xs font-black text-orange-200"><Hash className="h-4 w-4" />{copy.fixedId}</p><p className="mt-2 break-all font-mono text-lg font-black tracking-wider text-white">{query.data?.fixedIdentifier ?? "—"}</p><p className="mt-2 text-[11px] leading-5 text-orange-100/70">{copy.fixedIdHelp}</p></div><div className="flex items-center gap-2 rounded-2xl border border-white/10 bg-slate-950/40 p-4 text-[11px] leading-5 text-slate-300"><Sparkles className="h-5 w-5 shrink-0 text-cyan-300" />{copy.stableNote}</div></div>
          <div className="grid gap-3 lg:grid-cols-3">
            <section className="rounded-2xl border border-cyan-400/20 bg-cyan-500/5 p-4"><div className="flex items-start justify-between gap-2"><div><h3 className="flex items-center gap-2 text-sm font-black text-cyan-100"><QrCode className="h-4 w-4" />{copy.tableQr}</h3><p className="mt-1 text-[11px] leading-5 text-slate-400">{copy.tableQrHelp}</p></div><Badge className="bg-cyan-500/15 text-cyan-200">{grouped.table.length}</Badge></div><div className="mt-3 max-h-36 space-y-1.5 overflow-y-auto pr-1">{tables.length ? tables.map(table => <label key={table.id} className="flex cursor-pointer items-center gap-2 rounded-lg bg-white/5 px-2.5 py-2 text-xs text-slate-200 hover:bg-white/10"><input type="checkbox" checked={selectedTableIds.includes(table.id)} onChange={() => toggleTable(table.id)} className="accent-cyan-400" />{table.name}<span className="mr-auto text-[10px] text-slate-500">{table.seats}</span></label>) : <p className="py-4 text-center text-xs text-slate-500">{copy.noTables}</p>}</div><div className="mt-3 flex gap-2"><Button type="button" size="sm" onClick={() => setSelectedTableIds(tables.map(table => table.id))} variant="outline" className="h-8 flex-1 border-white/15 bg-transparent text-[10px] text-slate-300">{copy.allTables} · {selectedTableIds.length}</Button><Button type="button" size="sm" onClick={() => tableMutation.mutate({ restaurantId, branchId: effectiveBranchId, tableIds: selectedTableIds })} disabled={!selectedTableIds.length || tableMutation.isPending} className="h-8 flex-1 bg-cyan-500 text-[10px] text-slate-950 hover:bg-cyan-400">{tableMutation.isPending ? <RefreshCw className="h-3.5 w-3.5 animate-spin" /> : <Check className="h-3.5 w-3.5" />}{copy.createTables}</Button></div></section>
            <section className="rounded-2xl border border-violet-400/20 bg-violet-500/5 p-4"><div className="flex items-start justify-between gap-2"><div><h3 className="flex items-center gap-2 text-sm font-black text-violet-100"><UserRound className="h-4 w-4" />{copy.waiterQr}</h3><p className="mt-1 text-[11px] leading-5 text-slate-400">{copy.waiterQrHelp}</p></div><Badge className="bg-violet-500/15 text-violet-200">{grouped.waiter_call.length}</Badge></div><p className="mt-5 text-xs leading-5 text-slate-300">{copy.selected}: <strong>{selectedTableIds.length}</strong></p><Button type="button" onClick={() => waiterMutation.mutate({ restaurantId, branchId: effectiveBranchId, tableIds: selectedTableIds })} disabled={!selectedTableIds.length || waiterMutation.isPending} className="mt-3 h-9 w-full gap-2 bg-violet-500 text-xs text-white hover:bg-violet-400">{waiterMutation.isPending ? <RefreshCw className="h-4 w-4 animate-spin" /> : <UserRound className="h-4 w-4" />}{copy.createWaiter}</Button></section>
            <section className="rounded-2xl border border-amber-400/20 bg-amber-500/5 p-4"><div className="flex items-start justify-between gap-2"><div><h3 className="flex items-center gap-2 text-sm font-black text-amber-100"><QrCode className="h-4 w-4" />{copy.orderQr}</h3><p className="mt-1 text-[11px] leading-5 text-slate-400">{copy.orderQrHelp}</p></div><Badge className="bg-amber-500/15 text-amber-200">{grouped.order.length}</Badge></div><div className="mt-4 grid gap-2"><Input value={orderId} onChange={event => setOrderId(event.target.value.replace(/\D/g, ""))} inputMode="numeric" placeholder={copy.orderNumber} className="h-9 border-white/10 bg-slate-950/60 text-white placeholder:text-slate-500" /><div className="grid grid-cols-[1fr_auto] gap-2"><Input value={expiresHours} onChange={event => setExpiresHours(event.target.value.replace(/\D/g, ""))} inputMode="numeric" placeholder={copy.expiry} className="h-9 border-white/10 bg-slate-950/60 text-white placeholder:text-slate-500" /><span className="flex items-center rounded-lg bg-white/5 px-2 text-[10px] text-slate-400">{copy.hours}</span></div><Button type="button" onClick={createOrder} disabled={!orderId || orderMutation.isPending} className="h-9 gap-2 bg-amber-400 text-xs font-black text-slate-950 hover:bg-amber-300">{orderMutation.isPending ? <RefreshCw className="h-4 w-4 animate-spin" /> : <QrCode className="h-4 w-4" />}{copy.createOrder}</Button></div></section>
          </div>
          <div className="flex flex-wrap items-center justify-between gap-2 rounded-2xl border border-white/10 bg-slate-950/35 p-3"><p className="text-xs text-slate-400"><strong className="text-white">{codes.length}</strong> {language === "en" ? copy.noCodes : "رمز محفوظ"}</p><Button type="button" onClick={() => printCodes(codes)} variant="outline" className="h-8 gap-2 border-white/15 bg-transparent text-xs text-white"><Printer className="h-3.5 w-3.5" />{copy.print}</Button></div>
          <section data-testid="custom-qr-builder" className="rounded-2xl border border-pink-400/25 bg-gradient-to-br from-pink-500/10 via-white/[0.03] to-cyan-500/10 p-4">
            <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="flex items-center gap-2 text-sm font-black text-white"><Sparkles className="h-4 w-4 text-pink-300" />{copy.customTitle}</h3><p className="mt-1 text-[11px] leading-5 text-slate-300">{copy.customHelp}</p></div><Badge className="bg-pink-400/15 text-pink-200"><Hash className="h-3 w-3" /> {copy.menuId}: {query.data?.fixedIdentifier ?? "—"}</Badge></div>
            <div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4">
              <label className="space-y-1.5 text-[11px] font-bold text-slate-300"><span>{copy.purpose}</span><select value={customPurpose} onChange={event => setCustomPurpose(event.target.value as QrPurpose)} className="h-10 w-full rounded-xl border border-white/10 bg-slate-950/70 px-3 text-xs text-white outline-none focus:border-pink-300"><option value="menu">{copy.purposeMenu}</option><option value="table_service">{copy.purposeTable}</option><option value="waiter_call">{copy.purposeWaiter}</option><option value="google_reviews">{copy.purposeGoogle}</option><option value="custom">{copy.purposeCustom}</option></select></label>
              <label className="space-y-1.5 text-[11px] font-bold text-slate-300"><span>{copy.tableOptional}</span><select value={customTableId} onChange={event => setCustomTableId(event.target.value)} className="h-10 w-full rounded-xl border border-white/10 bg-slate-950/70 px-3 text-xs text-white outline-none focus:border-pink-300"><option value="">—</option>{tables.map(table => <option key={table.id} value={table.id}>{table.name} · {table.seats}</option>)}</select></label>
              <label className="space-y-1.5 text-[11px] font-bold text-slate-300"><span>{copy.labelOptional}</span><Input value={customLabel} onChange={event => setCustomLabel(event.target.value)} maxLength={160} placeholder={copy.labelOptional} className="h-10 border-white/10 bg-slate-950/70 text-xs text-white placeholder:text-slate-500" /></label>
              {(customPurpose === "google_reviews" || customPurpose === "custom") && <label className="space-y-1.5 text-[11px] font-bold text-slate-300"><span>{copy.targetUrl}</span><Input value={customTargetUrl} onChange={event => setCustomTargetUrl(event.target.value)} type="url" inputMode="url" placeholder="https://" className="h-10 border-white/10 bg-slate-950/70 text-xs text-white placeholder:text-slate-500" /><span className="block text-[10px] font-normal leading-4 text-slate-500">{copy.targetUrlHelp}</span></label>}
            </div>
            <div className="mt-3 flex flex-wrap items-center justify-between gap-3"><p className="flex items-center gap-2 text-[10px] leading-5 text-slate-400"><ShieldCheck className="h-3.5 w-3.5 shrink-0 text-emerald-300" />{copy.fixedIdHelp}</p><Button type="button" onClick={createCustom} disabled={customMutation.isPending || !effectiveBranchId} className="h-9 gap-2 rounded-xl bg-pink-500 px-4 text-xs font-black text-white hover:bg-pink-400">{customMutation.isPending ? <RefreshCw className="h-4 w-4 animate-spin" /> : <QrCode className="h-4 w-4" />}{copy.createCustom}</Button></div>
          </section>
        </CardContent>
      </Card>
      <div className="grid gap-4 xl:grid-cols-3">{sections.map(section => <Card key={section.key} className="rounded-3xl border-slate-700 bg-[#111c2e] text-white"><CardHeader className="flex flex-row items-center justify-between space-y-0 p-4"><CardTitle className="text-sm font-black">{section.title}</CardTitle><Badge className="bg-white/10 text-slate-300">{section.items.length}</Badge></CardHeader><CardContent className="grid gap-3 p-4 sm:grid-cols-2 xl:grid-cols-1">{section.items.length ? section.items.map(renderCode) : <div className="rounded-2xl border border-dashed border-slate-700 p-7 text-center text-xs text-slate-500">{copy.empty}</div>}</CardContent></Card>)}</div>
    </div>
  );
}
