import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronLeft, Building2, Sparkles, Store, UserRound, Utensils, WalletCards } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";

const plans = [
  { value: "Free", label: "البداية", price: "مجانية", description: "لإطلاق مطعمك وتجربة الأساسيات", features: ["فرع رئيسي", "منيو رقمي", "طلبات QR"] },
  { value: "Starter", label: "Starter", price: "تُحدد لاحقًا", description: "للمطاعم الصغيرة والفرق الناشئة", features: ["فروع إضافية", "تقارير موسعة", "إدارة الفريق"] },
  { value: "Growth", label: "Growth", price: "تُحدد لاحقًا", description: "للمطاعم النشطة ومتعددة القنوات", features: ["POS وKDS", "حملات وولاء", "تحليلات متقدمة"] },
  { value: "Enterprise", label: "Enterprise", price: "مخصص", description: "للشركات وسلاسل المطاعم", features: ["White Label", "دعم مخصص", "صلاحيات متقدمة"] },
] as const;

const steps = ["نوع الحساب", "بياناتك", "الباقة", "التأكيد"];

export function RegisterScreen({ onBack, onOAuth }: { onBack: () => void; onOAuth: () => void }) {
  const [step, setStep] = useState(0);
  const [accountType, setAccountType] = useState<"restaurant" | "driver">("restaurant");
  const [restaurantName, setRestaurantName] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [password, setPassword] = useState("");
  const [plan, setPlan] = useState<(typeof plans)[number]["value"]>("Free");
  const register = trpc.auth.registerRestaurant.useMutation({ onSuccess: () => { toast.success("تم إنشاء حساب المطعم وتسجيل الدخول"); window.location.href = "/"; }, onError: (error) => toast.error(error.message || "تعذر إنشاء الحساب") });
  const selectedPlan = useMemo(() => plans.find((item) => item.value === plan) ?? plans[0], [plan]);
  const canContinue = step === 0 ? Boolean(accountType) : step === 1 ? restaurantName.trim().length >= 2 && /\S+@\S+\.\S+/.test(email) && phone.trim().length >= 7 && password.length >= 6 : true;
  const next = () => { if (!canContinue) { toast.error(step === 1 ? "أكمل البيانات المطلوبة بصيغة صحيحة" : "اختر نوع الحساب للمتابعة"); return; } setStep((current) => Math.min(3, current + 1)); };
  const submit = () => register.mutate({ restaurantName: restaurantName.trim(), email: email.trim(), phone: phone.trim(), password, plan });
  return <div dir="rtl" className="min-h-screen overflow-hidden bg-[#f7f8fb] text-slate-900"><div className="mx-auto grid min-h-screen max-w-6xl lg:grid-cols-[0.8fr_1.2fr]">
    <aside className="relative hidden overflow-hidden bg-[#101d31] p-10 text-white lg:flex lg:flex-col lg:justify-between"><div className="absolute -left-24 top-24 h-64 w-64 rounded-full bg-orange-400/20 blur-3xl" /><div className="absolute -bottom-32 -right-20 h-80 w-80 rounded-full bg-sky-400/10 blur-3xl" /><div className="relative"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#e76f3c] shadow-lg shadow-orange-500/20"><Utensils className="h-6 w-6" /></div><div><p className="text-lg font-black">NFOOD</p><p className="text-[10px] tracking-[0.2em] text-slate-400">RESTAURANT OPERATING SYSTEM</p></div></div><div className="mt-24 max-w-sm"><p className="mb-4 flex items-center gap-2 text-sm font-semibold text-orange-200"><Sparkles className="h-4 w-4" /> بداية مختلفة لمطعمك</p><h1 className="text-4xl font-black leading-[1.25]">حوّل فكرة مطعمك إلى تجربة رقمية متكاملة.</h1><p className="mt-5 text-sm leading-7 text-slate-300">من أول طلب إلى آخر تقرير، اجمع عمليات المطعم في مساحة واحدة مصممة للسرعة والوضوح.</p></div></div><div className="relative grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl border border-white/10 bg-white/5 p-3"><Store className="mx-auto mb-2 h-5 w-5 text-orange-300" /><p className="text-[11px] text-slate-300">منيو ذكي</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-3"><WalletCards className="mx-auto mb-2 h-5 w-5 text-orange-300" /><p className="text-[11px] text-slate-300">طلبات موحدة</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-3"><Sparkles className="mx-auto mb-2 h-5 w-5 text-orange-300" /><p className="text-[11px] text-slate-300">نمو أسرع</p></div></div></aside>
    <main className="flex items-center justify-center p-5 sm:p-8"><Card className="w-full max-w-2xl rounded-[2rem] border-white/70 bg-white/90 shadow-[0_24px_80px_rgba(15,23,42,0.10)] backdrop-blur"><CardContent className="p-6 sm:p-10"><div className="mb-8 flex items-center justify-between gap-4"><button type="button" onClick={onBack} className="flex items-center gap-1 text-xs font-bold text-slate-500 transition hover:text-[#e76f3c]"><ArrowRight className="h-4 w-4" /> العودة للدخول</button><div className="flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-orange-100 text-[#e76f3c]"><Building2 className="h-5 w-5" /></div><span className="font-black tracking-tight">انضم إلى NFOOD</span></div></div><div className="mb-8"><div className="mb-3 flex items-center justify-between text-[11px] font-bold text-slate-400"><span>الخطوة {step + 1} من {steps.length}</span><span className="text-[#e76f3c]">{steps[step]}</span></div><div className="flex gap-1.5">{steps.map((item, index) => <div key={item} className={`h-1.5 flex-1 rounded-full transition ${index <= step ? "bg-[#e76f3c]" : "bg-slate-100"}`} />)}</div></div>
      {step === 0 && <section><p className="text-2xl font-black tracking-tight">كيف ستستخدم NFOOD؟</p><p className="mt-2 text-sm leading-6 text-slate-500">اختر مساحتك الآن، ويمكنك إضافة بقية الأدوار من داخل المنصة لاحقًا.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><button type="button" onClick={() => setAccountType("restaurant")} className={`group rounded-3xl border p-5 text-right transition ${accountType === "restaurant" ? "border-[#e76f3c] bg-orange-50 shadow-lg shadow-orange-100" : "border-slate-200 bg-white hover:-translate-y-0.5 hover:border-orange-200"}`}><div className="flex items-center justify-between"><div className={`flex h-12 w-12 items-center justify-center rounded-2xl ${accountType === "restaurant" ? "bg-[#e76f3c] text-white" : "bg-slate-100 text-slate-500"}`}><Store className="h-6 w-6" /></div>{accountType === "restaurant" && <Check className="h-5 w-5 text-[#e76f3c]" />}</div><h2 className="mt-5 text-lg font-black">مطعم أو نشاط تجاري</h2><p className="mt-2 text-xs leading-6 text-slate-500">أنشئ مساحة مطعم، أضف الفروع والفريق، وابدأ استقبال الطلبات.</p></button><button type="button" onClick={() => { setAccountType("driver"); toast.info("سيتم ربط تسجيل السائق بأقرب مطاعم متاحة بعد تفعيل ملف التوصيل"); }} className={`group rounded-3xl border p-5 text-right transition ${accountType === "driver" ? "border-sky-400 bg-sky-50 shadow-lg shadow-sky-100" : "border-slate-200 bg-white hover:-translate-y-0.5 hover:border-sky-200"}`}><div className="flex items-center justify-between"><div className={`flex h-12 w-12 items-center justify-center rounded-2xl ${accountType === "driver" ? "bg-sky-500 text-white" : "bg-slate-100 text-slate-500"}`}><UserRound className="h-6 w-6" /></div>{accountType === "driver" && <Check className="h-5 w-5 text-sky-500" />}</div><h2 className="mt-5 text-lg font-black">انضم كسائق</h2><p className="mt-2 text-xs leading-6 text-slate-500">سجّل اهتمامك، وسيظهر لك مسار الانضمام إلى مطاعم التوصيل عند تفعيل ملف السائق.</p></button></div></section>}
      {step === 1 && <section><p className="text-2xl font-black tracking-tight">لنجهّز مساحتك</p><p className="mt-2 text-sm leading-6 text-slate-500">بيانات بسيطة الآن، ثم ستكمل إعداد المطعم من لوحة التحكم.</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="space-y-2 text-xs font-bold sm:col-span-2">اسم المطعم أو النشاط<Input autoFocus value={restaurantName} onChange={(event) => setRestaurantName(event.target.value)} placeholder="مثال: مطعم نكهة" className="mt-1 h-12 rounded-2xl border-slate-200 bg-slate-50/70 px-4" /></label><label className="space-y-2 text-xs font-bold">البريد الإلكتروني<Input type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" dir="ltr" className="mt-1 h-12 rounded-2xl border-slate-200 bg-slate-50/70 px-4" /></label><label className="space-y-2 text-xs font-bold">رقم الجوال<Input type="tel" autoComplete="tel" value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="+966 5x xxx xxxx" dir="ltr" className="mt-1 h-12 rounded-2xl border-slate-200 bg-slate-50/70 px-4" /></label><label className="space-y-2 text-xs font-bold sm:col-span-2">كلمة مرور آمنة<Input type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="6 أحرف على الأقل" dir="ltr" className="mt-1 h-12 rounded-2xl border-slate-200 bg-slate-50/70 px-4" /><span className={`mt-1 block text-[11px] ${password.length >= 6 ? "text-emerald-600" : "text-slate-400"}`}>{password.length >= 6 ? "كلمة المرور مناسبة" : "استخدم 6 أحرف أو أكثر"}</span></label></div></section>}
      {step === 2 && <section><p className="text-2xl font-black tracking-tight">اختر نقطة البداية</p><p className="mt-2 text-sm leading-6 text-slate-500">لا يوجد دفع الآن. يمكنك تغيير الباقة لاحقًا حسب نمو المطعم.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{plans.map((item) => <button type="button" key={item.value} onClick={() => setPlan(item.value)} className={`relative rounded-3xl border p-5 text-right transition ${plan === item.value ? "border-[#e76f3c] bg-orange-50 shadow-lg shadow-orange-100" : "border-slate-200 bg-white hover:border-orange-200"}`}>{plan === item.value && <span className="absolute left-4 top-4 rounded-full bg-[#e76f3c] px-2 py-1 text-[10px] font-bold text-white">مختارة</span>}<p className="text-base font-black">{item.label}</p><p className="mt-1 text-sm font-bold text-[#e76f3c]">{item.price}</p><p className="mt-2 text-xs leading-5 text-slate-500">{item.description}</p><div className="mt-4 space-y-1.5">{item.features.map((feature) => <p key={feature} className="flex items-center gap-1.5 text-[11px] text-slate-600"><Check className="h-3.5 w-3.5 text-emerald-500" /> {feature}</p>)}</div></button>)}</div></section>}
      {step === 3 && <section><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-3xl bg-emerald-100 text-emerald-600"><Check className="h-8 w-8" /></div><p className="mt-6 text-center text-2xl font-black">مستعدون للانطلاق</p><p className="mx-auto mt-2 max-w-md text-center text-sm leading-7 text-slate-500">سيُنشأ حساب <strong className="text-slate-800">{restaurantName || "مطعمك"}</strong> على باقة <strong className="text-[#e76f3c]">{selectedPlan.label}</strong>، ثم تنتقل مباشرة إلى لوحة التحكم.</p><div className="mx-auto mt-7 max-w-md rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm"><div className="flex items-center justify-between border-b border-slate-200 pb-3"><span className="text-slate-500">البريد</span><strong dir="ltr">{email}</strong></div><div className="flex items-center justify-between pt-3"><span className="text-slate-500">الهاتف</span><strong dir="ltr">{phone}</strong></div></div></section>}
      <div className="mt-9 flex items-center gap-3"><Button type="button" variant="outline" onClick={() => step === 0 ? onBack() : setStep((current) => current - 1)} className="h-12 rounded-2xl px-5">{step === 0 ? "إلغاء" : <><ArrowRight className="ml-1 h-4 w-4" /> السابق</>}</Button>{step < 3 ? <Button type="button" onClick={next} className="h-12 flex-1 rounded-2xl bg-[#e76f3c] text-base font-bold shadow-lg shadow-orange-200 hover:bg-[#d85f2e]">التالي <ArrowLeft className="mr-1 h-4 w-4" /></Button> : <Button type="button" disabled={register.isPending || accountType !== "restaurant"} onClick={submit} className="h-12 flex-1 rounded-2xl bg-[#e76f3c] text-base font-bold shadow-lg shadow-orange-200 hover:bg-[#d85f2e]">{register.isPending ? "جارٍ إنشاء المساحة..." : "إنشاء المساحة والدخول"}</Button>}</div><Button type="button" variant="ghost" onClick={onOAuth} className="mt-3 h-10 w-full rounded-2xl text-xs text-slate-500">أو تابع بسرعة عبر Google / OAuth <ChevronLeft className="mr-1 h-4 w-4" /></Button></CardContent></Card></main></div></div>;
}
