import { useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronLeft, Building2, Sparkles, Store, UserRound, Utensils, WalletCards } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { useLanguage } from "@/contexts/LanguageContext";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import { DriverApplicationDialog } from "@/components/DriverApplicationDialog";
import { validateRegistrationContact } from "@/lib/registrationValidation";

const plans = [
  { value: "Free", label: "البداية", price: "مجانية", description: "لإطلاق مطعمك وتجربة الأساسيات", features: ["فرع رئيسي", "منيو رقمي", "طلبات QR"] },
  { value: "Starter", label: "Starter", price: "تُحدد لاحقًا", description: "للمطاعم الصغيرة والفرق الناشئة", features: ["فروع إضافية", "تقارير موسعة", "إدارة الفريق"] },
  { value: "Growth", label: "Growth", price: "تُحدد لاحقًا", description: "للمطاعم النشطة ومتعددة القنوات", features: ["POS وKDS", "حملات وولاء", "تحليلات متقدمة"] },
  { value: "Enterprise", label: "Enterprise", price: "مخصص", description: "للشركات وسلاسل المطاعم", features: ["White Label", "دعم مخصص", "صلاحيات متقدمة"] },
] as const;
const steps = ["نوع الحساب", "البيانات", "المستندات أو الباقة", "المراجعة"];
type VehicleType = "bicycle" | "motorcycle" | "car" | "van" | "other";

export function RegisterScreen({ onBack, onOAuth }: { onBack: () => void; onOAuth: () => void }) {
  const { t, direction } = useLanguage();
  const [step, setStep] = useState(0);
  const [accountType, setAccountType] = useState<"restaurant" | "driver">("restaurant");
  const nameLabel = accountType === "driver" ? t("name") : t("restaurant");
  const [name, setName] = useState("");
  const [country, setCountry] = useState("السعودية");
  const [city, setCity] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [vehicleType, setVehicleType] = useState<VehicleType>("car");
  const [files, setFiles] = useState<Record<string, File | undefined>>({});
  const [applicationId, setApplicationId] = useState<number | null>(null);
  const [temporaryPassword, setTemporaryPassword] = useState("");
  const [plan, setPlan] = useState<(typeof plans)[number]["value"]>("Free");
  const [driverDialogOpen, setDriverDialogOpen] = useState(false);
  const restaurantRegister = trpc.auth.registerRestaurant.useMutation({ onSuccess: (result) => { setTemporaryPassword(result.temporaryPassword); toast.success("تم إنشاء الحساب. احفظ كلمة المرور وأكمل تأكيد البريد لاحقًا."); }, onError: (error) => toast.error(error.message || "تعذر إنشاء الحساب") });
  const driverRegister = trpc.auth.submitDriverApplication.useMutation({ onSuccess: (result) => { setApplicationId(result.applicationId); toast.success(result.message); }, onError: (error) => toast.error(error.message || "تعذر إرسال طلب السائق") });
  const uploadDriverFile = trpc.auth.uploadDriverFile.useMutation();
  const selectedPlan = useMemo(() => plans.find((item) => item.value === plan) ?? plans[0], [plan]);
  const validContact = validateRegistrationContact({ name, city, email, phone, country }, accountType === "restaurant");
  const canContinue = step === 0 || step === 1 ? validContact && (accountType === "driver" || country.trim().length >= 2) : true;
  const next = () => { if (!canContinue) { toast.error("أكمل البيانات المطلوبة بصيغة صحيحة"); return; } setStep((current) => Math.min(3, current + 1)); };
  const fileToBase64 = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("تعذر قراءة الملف")); reader.readAsDataURL(file); });
  const submit = async () => { if (accountType === "restaurant") { restaurantRegister.mutate({ restaurantName: name.trim(), country: country.trim(), city: city.trim(), email: email.trim(), phone: phone.trim(), plan }); return; } try { const uploaded = await Promise.all(Object.entries(files).filter((entry): entry is [string, File] => Boolean(entry[1])).map(async ([key, file]) => [key, (await uploadDriverFile.mutateAsync({ fileName: file.name, contentType: file.type, base64: await fileToBase64(file) })).url] as const)); const urls = Object.fromEntries(uploaded); driverRegister.mutate({ fullName: name.trim(), email: email.trim(), phone: phone.trim(), city: city.trim(), vehicleType, identityDocumentUrl: urls.identity, licenseDocumentUrl: urls.license, vehicleFrontUrl: urls.front, vehicleBackUrl: urls.back, vehicleLeftUrl: urls.left, vehicleRightUrl: urls.right }); } catch (error) { toast.error(error instanceof Error ? error.message : "تعذر رفع ملفات السائق"); } };
  const pickFile = (key: string, file?: File) => setFiles((current) => ({ ...current, [key]: file }));
  return <div dir={direction} className="min-h-screen bg-[#f7f8fb] text-slate-900"><DriverApplicationDialog open={driverDialogOpen} onClose={() => setDriverDialogOpen(false)} /><div className="mx-auto grid min-h-screen max-w-6xl lg:grid-cols-[0.8fr_1.2fr]">
    <aside className="relative hidden overflow-hidden bg-[#101d31] p-10 text-white lg:flex lg:flex-col lg:justify-between"><div><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#e76f3c]"><Utensils className="h-6 w-6" /></div><div><p className="text-lg font-black">NFOOD</p><p className="text-[10px] tracking-[0.2em] text-slate-400">RESTAURANT OPERATING SYSTEM</p></div></div><div className="mt-24 max-w-sm"><p className="mb-4 flex items-center gap-2 text-sm font-semibold text-orange-200"><Sparkles className="h-4 w-4" /> بداية مختلفة</p><h1 className="text-4xl font-black leading-[1.25]">انضم إلى تجربة تشغيل أكثر ذكاءً.</h1><p className="mt-5 text-sm leading-7 text-slate-300">تسجيل واضح، مراجعة آمنة، ومسار مناسب لكل شريك وسائق.</p></div></div><div className="grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl border border-white/10 bg-white/5 p-3"><Store className="mx-auto mb-2 h-5 w-5 text-orange-300" /><p className="text-[11px] text-slate-300">منيو ذكي</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-3"><WalletCards className="mx-auto mb-2 h-5 w-5 text-orange-300" /><p className="text-[11px] text-slate-300">عمليات موحدة</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-3"><Sparkles className="mx-auto mb-2 h-5 w-5 text-orange-300" /><p className="text-[11px] text-slate-300">نمو أسرع</p></div></div></aside>
    <main className="flex items-center justify-center p-5 sm:p-8"><div className="fixed right-5 top-5 z-20"><LanguageSwitcher compact /></div><Card className="w-full max-w-2xl rounded-[2rem] border-white/70 bg-white/90 shadow-2xl"><CardContent className="p-6 sm:p-10"><div className="mb-8 flex items-center justify-between"><button type="button" onClick={onBack} className="flex items-center gap-1 text-xs font-bold text-slate-500 hover:text-[#e76f3c]"><ArrowRight className="h-4 w-4" /> {t("back")}</button><div className="flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-orange-100 text-[#e76f3c]"><Building2 className="h-5 w-5" /></div><span className="font-black">انضم إلى NFOOD</span></div></div><div className="mb-8"><div className="mb-3 flex items-center justify-between text-[11px] font-bold text-slate-400"><span>{t("status")} {step + 1} / {steps.length}</span><span className="text-[#e76f3c]">{steps[step]}</span></div><div className="flex gap-1.5">{steps.map((item, index) => <div key={item} className={`h-1.5 flex-1 rounded-full ${index <= step ? "bg-[#e76f3c]" : "bg-slate-100"}`} />)}</div></div>
      {step === 0 && <section><p className="text-2xl font-black">كيف ستستخدم NFOOD؟</p><p className="mt-2 text-sm leading-6 text-slate-500">اختر المسار المناسب، ثم أكمل الخطوات حتى الإرسال.</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><button type="button" onClick={() => setAccountType("restaurant")} className={`rounded-3xl border p-5 text-right ${accountType === "restaurant" ? "border-[#e76f3c] bg-orange-50 shadow-lg" : "border-slate-200 bg-white"}`}><Store className="h-7 w-7 text-[#e76f3c]" /><h2 className="mt-5 text-lg font-black">مطعم أو نشاط تجاري</h2><p className="mt-2 text-xs leading-6 text-slate-500">أنشئ مساحة المطعم والفروع والفريق.</p></button><button type="button" onClick={() => { setAccountType("driver"); setDriverDialogOpen(true); }} className={`rounded-3xl border p-5 text-right ${accountType === "driver" ? "border-sky-400 bg-sky-50 shadow-lg" : "border-slate-200 bg-white"}`}><UserRound className="h-7 w-7 text-sky-500" /><h2 className="mt-5 text-lg font-black">انضم كسائق</h2><p className="mt-2 text-xs leading-6 text-slate-500">أرسل ملفك للمراجعة ثم نربطك بالفرق المناسبة.</p></button></div></section>}
      {step === 1 && <section><p className="text-2xl font-black">{accountType === "driver" ? "بيانات السائق" : "بيانات المطعم"}</p><p className="mt-2 text-sm leading-6 text-slate-500">هذه البيانات أساسية لإكمال الطلب.</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="space-y-2 text-xs font-bold sm:col-span-2">{nameLabel}<Input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder={accountType === "driver" ? "الاسم كما في الهوية" : "مثال: مطعم نكهة"} className="mt-1 h-12 rounded-2xl bg-slate-50/70 px-4" /></label>{accountType === "restaurant" && <label className="space-y-2 text-xs font-bold">{t("country")}<Input value={country} onChange={(event) => setCountry(event.target.value)} placeholder="السعودية" className="mt-1 h-12 rounded-2xl bg-slate-50/70 px-4" /></label>}<label className="space-y-2 text-xs font-bold">{t("city")}<Input value={city} onChange={(event) => setCity(event.target.value)} placeholder="الرياض" className="mt-1 h-12 rounded-2xl bg-slate-50/70 px-4" /></label><label className="space-y-2 text-xs font-bold">{t("email")}<Input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" dir="ltr" className="mt-1 h-12 rounded-2xl bg-slate-50/70 px-4" /></label><label className="space-y-2 text-xs font-bold">{t("phone")}<Input type="tel" value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="+966 5x xxx xxxx" dir="ltr" className="mt-1 h-12 rounded-2xl bg-slate-50/70 px-4" /></label>{accountType === "driver" ? <label className="space-y-2 text-xs font-bold sm:col-span-2">نوع وسيلة التوصيل<select value={vehicleType} onChange={(event) => setVehicleType(event.target.value as VehicleType)} className="mt-1 h-12 w-full rounded-2xl border border-slate-200 bg-slate-50/70 px-4"><option value="car">سيارة</option><option value="motorcycle">دراجة نارية</option><option value="bicycle">دراجة</option><option value="van">شاحنة صغيرة</option><option value="other">وسيلة أخرى</option></select></label> : <div className="rounded-2xl border border-orange-200 bg-orange-50 p-4 text-xs leading-6 text-orange-900 sm:col-span-2"><strong>كلمة المرور تُنشأ تلقائيًا</strong><p className="mt-1">سيولّد النظام كلمة مرور مؤقتة من ستة أرقام وتظهر لك مرة واحدة بعد إنشاء الحساب.</p></div>}</div></section>}
      {step === 2 && accountType === "driver" && <section><p className="text-2xl font-black">{t("documents")}</p><p className="mt-2 text-sm leading-6 text-slate-500">أرفق الهوية والرخصة وصور المركبة للمراجعة. سيتم حفظ الملفات في التخزين الآمن عند تفعيل الرفع.</p><div className="mt-7 grid gap-4 sm:grid-cols-2">{[["identity", "صورة الهوية"], ["license", "رخصة القيادة"], ["front", "المركبة من الأمام"], ["back", "المركبة من الخلف"], ["left", "المركبة من اليسار"], ["right", "المركبة من اليمين"]].map(([key, label]) => <label key={key} className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-4 text-xs font-bold">{label}<input type="file" accept="image/*,.pdf" onChange={(event) => pickFile(key, event.target.files?.[0])} className="mt-3 block w-full text-xs font-normal" />{files[key] && <span className="mt-2 block truncate text-emerald-700">تم اختيار: {files[key]?.name}</span>}</label>)}</div></section>}
      {step === 2 && accountType === "restaurant" && <section><p className="text-2xl font-black">{t("subscription")}</p><p className="mt-2 text-sm leading-6 text-slate-500">لا يوجد دفع الآن.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{plans.map((item) => <button type="button" key={item.value} onClick={() => setPlan(item.value)} className={`rounded-3xl border p-5 text-right ${plan === item.value ? "border-[#e76f3c] bg-orange-50 shadow-lg" : "border-slate-200 bg-white"}`}><p className="font-black">{item.label}</p><p className="mt-1 text-sm font-bold text-[#e76f3c]">{item.price}</p><p className="mt-2 text-xs leading-5 text-slate-500">{item.description}</p>{item.features.map((feature) => <p key={feature} className="mt-2 flex items-center gap-1 text-[11px] text-slate-600"><Check className="h-3.5 w-3.5 text-emerald-500" />{feature}</p>)}</button>)}</div></section>}
      {step === 3 && <section><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-3xl bg-emerald-100 text-emerald-600"><Check className="h-8 w-8" /></div><p className="mt-6 text-center text-2xl font-black">{accountType === "driver" ? "طلبك قيد التحقق" : "مستعدون للانطلاق"}</p><p className="mx-auto mt-2 max-w-md text-center text-sm leading-7 text-slate-500">{accountType === "driver" ? "تم استلام بياناتك. سيجري فريق NFOOD التحقق من المعلومات، وسيصل إشعار إلى بريدك عند الموافقة على انضمامك." : <>سيُنشأ حساب <strong className="text-slate-800">{name || "مطعمك"}</strong> على باقة <strong className="text-[#e76f3c]">{selectedPlan.label}</strong>.</>}</p><div className="mx-auto mt-7 max-w-md rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm">{applicationId && <div className="mb-3 rounded-xl bg-sky-100 p-3 text-center text-xs text-sky-900">رقم طلب الانضمام: <strong>{applicationId}</strong></div>}<div className="flex items-center justify-between border-b border-slate-200 pb-3"><span className="text-slate-500">البريد</span><strong dir="ltr">{email}</strong></div><div className="flex items-center justify-between border-b border-slate-200 py-3"><span className="text-slate-500">الموقع</span><strong>{accountType === "restaurant" ? `${country} · ` : ""}{city}</strong></div><div className="flex items-center justify-between pt-3"><span className="text-slate-500">الهاتف</span><strong dir="ltr">{phone}</strong></div>{temporaryPassword && <div className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3"><p className="text-xs text-emerald-700">كلمة المرور المؤقتة — احفظها الآن</p><strong className="mt-1 block text-center font-mono text-2xl tracking-[0.35em] text-emerald-900" dir="ltr">{temporaryPassword}</strong></div>}</div></section>}
      <div className="mt-9 flex items-center gap-3"><Button type="button" variant="outline" onClick={() => step === 0 ? onBack() : setStep((current) => current - 1)} className="h-12 rounded-2xl px-5">{step === 0 ? "إلغاء" : <><ArrowRight className="ml-1 h-4 w-4" /> {t("back")}</>}</Button>{step < 3 ? <Button type="button" onClick={next} className="h-12 flex-1 rounded-2xl bg-[#e76f3c] text-base font-bold hover:bg-[#d85f2e]">{t("next")} <ArrowLeft className="mr-1 h-4 w-4" /></Button> : <Button type="button" disabled={restaurantRegister.isPending || driverRegister.isPending || uploadDriverFile.isPending || Boolean(applicationId)} onClick={submit} className="h-12 flex-1 rounded-2xl bg-[#e76f3c] text-base font-bold hover:bg-[#d85f2e]">{restaurantRegister.isPending || driverRegister.isPending || uploadDriverFile.isPending ? "جارٍ رفع الملفات..." : accountType === "driver" ? `${t("submit")} ${t("joinRestaurant")}` : t("createAccount")}</Button>}</div><Button type="button" variant="ghost" onClick={onOAuth} className="mt-3 h-10 w-full rounded-2xl text-xs text-slate-500">أو تابع بسرعة عبر Google / OAuth <ChevronLeft className="mr-1 h-4 w-4" /></Button></CardContent></Card></main></div></div>;
}
