import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronLeft, Building2, Sparkles, Store, UserRound, Utensils, WalletCards } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { toast } from "sonner";
import { useLanguage } from "@/contexts/LanguageContext";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import { DriverApplicationDialog } from "@/components/DriverApplicationDialog";
import { validateRegistrationContact } from "@/lib/registrationValidation";

const plans = [
  { value: "Free", label: "البداية", price: "مجانية", description: "لإطلاق مطعمك وتجربة الأساسيات", features: ["فرع رئيسي", "منيو رقمي", "طلبات QR"] },
  { value: "Starter", label: "Starter", price: "تُحدد لاحقًا", description: "للمطاعم الصغيرة والفرق الناشئة", features: ["فروع إضافية", "تقارير موسعة", "إدارة الفريق"] },
  { value: "Growth", label: "Growth", price: "تُحدد لاحقًا", description: "للمطاعم النشطة ومتعددة القنوات", features: ["POS وKDS", "حملات وولاء", "تحليلات متقدمة"] },
  { value: "Business", label: "Business", price: "399 ر.س / شهريًا", description: "للفرق متعددة الفروع", features: ["فروع متعددة", "التوصيل والتسويق", "API والتكاملات"] },
  { value: "Enterprise", label: "Enterprise", price: "مخصص", description: "للشركات وسلاسل المطاعم", features: ["White Label", "دعم مخصص", "صلاحيات متقدمة"] },
] as const;
const steps = ["type", "data", "docs", "review"] as const; const stepLabels = { ar: ["نوع الحساب", "البيانات", "المستندات أو الباقة", "المراجعة"], en: ["Account type", "Details", "Documents or plan", "Review"], fr: ["Type de compte", "Données", "Documents ou forfait", "Vérification"] } as const;
const registrationCopy = {
  ar: { join: "انضم إلى NFOOD", different: "بداية مختلفة", hero: "انضم إلى تجربة تشغيل أكثر ذكاءً.", safe: "تسجيل واضح، مراجعة آمنة، ومسار مناسب لكل شريك وسائق.", smartMenu: "منيو ذكي", unified: "عمليات موحدة", faster: "نمو أسرع", chooseTitle: "كيف ستستخدم NFOOD؟", chooseDesc: "اختر المسار المناسب، ثم أكمل الخطوات حتى الإرسال.", restaurantPath: "مطعم أو نشاط تجاري", restaurantDesc: "أنشئ مساحة المطعم والفروع والفريق.", driverPath: "انضم كسائق", driverDesc: "أرسل ملفك للمراجعة ثم نربطك بالفرق المناسبة.", restaurantData: "بيانات المطعم", driverData: "بيانات السائق", required: "هذه البيانات أساسية لإكمال الطلب.", exampleRestaurant: "مثال: مطعم نكهة", identityName: "الاسم كما في الهوية", countryPlaceholder: "السعودية", cityPlaceholder: "الرياض", vehicle: "نوع وسيلة التوصيل", car: "سيارة", motorcycle: "دراجة نارية", bicycle: "دراجة", van: "شاحنة صغيرة", other: "وسيلة أخرى", autoPassword: "كلمة المرور تُنشأ تلقائيًا", passwordDesc: "سيولّد النظام كلمة مرور مؤقتة من ستة أرقام وتظهر لك مرة واحدة بعد إنشاء الحساب.", noPayment: "لا يوجد دفع الآن.", documentsDesc: "أرفق الهوية والرخصة وصور المركبة للمراجعة.", id: "صورة الهوية", license: "رخصة القيادة", front: "المركبة من الأمام", back: "المركبة من الخلف", left: "المركبة من اليسار", right: "المركبة من اليمين", selected: "تم اختيار:", ready: "مستعدون للانطلاق", driverPending: "طلبك قيد التحقق", reviewDesc: "تم استلام بياناتك. سيجري فريق NFOOD التحقق من المعلومات، وسيصل إشعار إلى بريدك عند الموافقة على انضمامك.", created: "سيُنشأ حساب", onPlan: "على باقة", restaurant: "مطعمك", application: "رقم طلب الانضمام", email: "البريد", location: "الموقع", phone: "الهاتف", temporary: "كلمة المرور المؤقتة — احفظها الآن", cancel: "إلغاء", submitFiles: "جارٍ رفع الملفات...", create: "إنشاء الحساب", joinSubmit: "إرسال طلب الانضمام", oauth: "أو تابع بسرعة عبر Google / OAuth", demo: "وضع Demo: Google/OAuth غير مفعّل حاليًا." },
  en: { join: "Join NFOOD", different: "A better starting point", hero: "Join a smarter restaurant operating experience.", safe: "Clear onboarding, secure review, and a path built for every restaurant partner and driver.", smartMenu: "Smart menu", unified: "Unified operations", faster: "Faster growth", chooseTitle: "How will you use NFOOD?", chooseDesc: "Choose the right path, then complete the steps to submit.", restaurantPath: "Restaurant or business", restaurantDesc: "Create your restaurant workspace, branches, and team.", driverPath: "Join as a driver", driverDesc: "Submit your profile for review and connect with restaurant teams.", restaurantData: "Restaurant data", driverData: "Driver data", required: "This information is required to complete your application.", exampleRestaurant: "Example: Flavour Restaurant", identityName: "Full name as shown on ID", countryPlaceholder: "Saudi Arabia", cityPlaceholder: "Riyadh", vehicle: "Delivery vehicle", car: "Car", motorcycle: "Motorcycle", bicycle: "Bicycle", van: "Van", other: "Other", autoPassword: "Password created automatically", passwordDesc: "The system will generate a temporary six-digit password and show it once after account creation.", noPayment: "No payment is required now.", documentsDesc: "Attach your ID, license, and vehicle photos for review.", id: "ID photo", license: "Driving license", front: "Vehicle front", back: "Vehicle back", left: "Vehicle left", right: "Vehicle right", selected: "Selected:", ready: "Ready to get started", driverPending: "Application under review", reviewDesc: "We received your details. The NFOOD team will review them and email you when your application is approved.", created: "An account will be created for", onPlan: "on the", restaurant: "your restaurant", application: "Application number", email: "Email", location: "Location", phone: "Phone", temporary: "Temporary password — save it now", cancel: "Cancel", submitFiles: "Uploading files...", create: "Create account", joinSubmit: "Submit driver application", oauth: "Or continue quickly with Google / OAuth", demo: "Demo mode: Google/OAuth is not enabled yet." },
  fr: { join: "Rejoindre NFOOD", different: "Un meilleur départ", hero: "Rejoignez une expérience de gestion plus intelligente.", safe: "Inscription claire, vérification sécurisée et parcours conçu pour chaque restaurant et chauffeur.", smartMenu: "Menu intelligent", unified: "Opérations unifiées", faster: "Croissance rapide", chooseTitle: "Comment utiliserez-vous NFOOD ?", chooseDesc: "Choisissez le parcours adapté, puis complétez les étapes avant l’envoi.", restaurantPath: "Restaurant ou entreprise", restaurantDesc: "Créez l’espace de votre restaurant, vos succursales et votre équipe.", driverPath: "Rejoindre comme chauffeur", driverDesc: "Envoyez votre profil pour vérification et rejoignez les équipes.", restaurantData: "Données du restaurant", driverData: "Données du chauffeur", required: "Ces informations sont nécessaires pour compléter votre demande.", exampleRestaurant: "Exemple : Restaurant Saveur", identityName: "Nom complet sur la pièce d’identité", countryPlaceholder: "Arabie saoudite", cityPlaceholder: "Riyad", vehicle: "Véhicule de livraison", car: "Voiture", motorcycle: "Moto", bicycle: "Vélo", van: "Fourgonnette", other: "Autre", autoPassword: "Mot de passe créé automatiquement", passwordDesc: "Le système générera un mot de passe temporaire à six chiffres et l’affichera une seule fois après la création du compte.", noPayment: "Aucun paiement n’est requis maintenant.", documentsDesc: "Ajoutez votre pièce d’identité, votre permis et les photos du véhicule.", id: "Pièce d’identité", license: "Permis de conduire", front: "Avant du véhicule", back: "Arrière du véhicule", left: "Côté gauche", right: "Côté droit", selected: "Sélectionné :", ready: "Prêt à commencer", driverPending: "Demande en vérification", reviewDesc: "Nous avons reçu vos informations. L’équipe NFOOD les vérifiera et vous écrira par e-mail.", created: "Un compte sera créé pour", onPlan: "avec le forfait", restaurant: "votre restaurant", application: "Numéro de demande", email: "E-mail", location: "Localisation", phone: "Téléphone", temporary: "Mot de passe temporaire — sauvegardez-le", cancel: "Annuler", submitFiles: "Envoi des fichiers...", create: "Créer le compte", joinSubmit: "Envoyer la demande chauffeur", oauth: "Ou continuer rapidement avec Google / OAuth", demo: "Mode démo : Google/OAuth n’est pas encore activé." }
} as const;
type VehicleType = "bicycle" | "motorcycle" | "car" | "van" | "other";

export function RegisterScreen({ onBack, onOAuth }: { onBack: () => void; onOAuth: () => void }) {
  const { t, direction, language } = useLanguage(); const copy = registrationCopy[language === "fr" ? "fr" : language === "en" ? "en" : "ar"];
  const [step, setStep] = useState(() => typeof window !== "undefined" && window.location.pathname === "/restaurant/register" ? 1 : 0);
  const [accountType, setAccountType] = useState<"restaurant" | "driver">("restaurant");
  const nameLabel = accountType === "driver" ? copy.driverData : copy.restaurantData;
  const [name, setName] = useState("");
  const [country, setCountry] = useState(""); useEffect(() => { if (!country) setCountry(copy.countryPlaceholder); }, [copy.countryPlaceholder, country]);
  const [city, setCity] = useState("");
  const [email, setEmail] = useState("");
  const [phone, setPhone] = useState("");
  const [vehicleType, setVehicleType] = useState<VehicleType>("car");
  const [files, setFiles] = useState<Record<string, File | undefined>>({});
  const [applicationId, setApplicationId] = useState<number | null>(null);
  const [temporaryPassword, setTemporaryPassword] = useState("");
  const [plan, setPlan] = useState<(typeof plans)[number]["value"]>(() => { if (typeof window === "undefined") return "Free"; const requested = new URLSearchParams(window.location.search).get("plan"); return plans.some((item) => item.value === requested) ? requested as (typeof plans)[number]["value"] : "Free"; });
  const [driverDialogOpen, setDriverDialogOpen] = useState(false);
  const restaurantRegister = trpc.auth.registerRestaurant.useMutation({ onSuccess: (result) => { setTemporaryPassword(result.temporaryPassword); toast.success(language === "en" ? "Account created. Save the password and verify your email later." : language === "fr" ? "Compte créé. Enregistrez le mot de passe et confirmez votre e-mail plus tard." : "تم إنشاء الحساب. احفظ كلمة المرور وأكمل تأكيد البريد لاحقًا."); }, onError: (error) => toast.error(error.message || (language === "en" ? "Could not create the account" : language === "fr" ? "Impossible de créer le compte" : "تعذر إنشاء الحساب")) });
  const driverRegister = trpc.auth.submitDriverApplication.useMutation({ onSuccess: (result) => { setApplicationId(result.applicationId); toast.success(result.message); }, onError: (error) => toast.error(error.message || (language === "en" ? "Could not submit the driver application" : language === "fr" ? "Impossible d’envoyer la demande chauffeur" : "تعذر إرسال طلب السائق")) });
  const uploadDriverFile = trpc.auth.uploadDriverFile.useMutation();
  const displayPlans = useMemo(() => { if (language === "ar") return plans; const en = [{ label: "Free", price: "Free", description: "Start with NFOOD", features: ["Digital menu", "One branch", "QR orders"] }, { label: "Starter", price: "To be defined", description: "For small restaurants and new teams", features: ["Additional branches", "Expanded reports", "Team management"] }, { label: "Growth", price: "To be defined", description: "For active, multi-channel restaurants", features: ["POS and KDS", "Campaigns and loyalty", "Advanced analytics"] }, { label: "Business", price: "SAR 399 / month", description: "For multi-branch teams", features: ["Multiple branches", "Delivery and marketing", "API and integrations"] }, { label: "Enterprise", price: "Custom", description: "For restaurant groups and chains", features: ["White label", "Dedicated support", "Advanced permissions"] }]; const fr = [{ label: "Gratuit", price: "Gratuit", description: "Pour commencer avec NFOOD", features: ["Menu numérique", "Une succursale", "Commandes QR"] }, { label: "Starter", price: "À définir", description: "Pour les petits restaurants", features: ["Succursales supplémentaires", "Rapports étendus", "Gestion d’équipe"] }, { label: "Growth", price: "À définir", description: "Pour les restaurants multi-canaux", features: ["POS et KDS", "Campagnes et fidélité", "Analyses avancées"] }, { label: "Business", price: "399 SAR / mois", description: "Pour les équipes multi-sites", features: ["Plusieurs succursales", "Livraison et marketing", "API et intégrations"] }, { label: "Enterprise", price: "Sur mesure", description: "Pour les groupes et chaînes", features: ["Marque blanche", "Support dédié", "Permissions avancées"] }]; const localized = language === "fr" ? fr : en; return plans.map((item, index) => ({ ...item, ...localized[index] })); }, [language]); const selectedPlan = useMemo(() => displayPlans.find((item) => item.value === plan) ?? displayPlans[0], [displayPlans, plan]);
  const validContact = validateRegistrationContact({ name, city, email, phone, country }, accountType === "restaurant");
  const canContinue = step === 0 || step === 1 ? validContact && (accountType === "driver" || country.trim().length >= 2) : true;
  const next = () => { if (!canContinue) { toast.error(language === "en" ? "Complete the required fields with valid values." : language === "fr" ? "Complétez les champs obligatoires avec des valeurs valides." : "أكمل البيانات المطلوبة بصيغة صحيحة"); return; } setStep((current) => Math.min(3, current + 1)); };
  const fileToBase64 = (file: File) => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error(language === "en" ? "Could not read the file" : language === "fr" ? "Impossible de lire le fichier" : "تعذر قراءة الملف")); reader.readAsDataURL(file); });
  const submit = async () => { if (accountType === "restaurant") { restaurantRegister.mutate({ restaurantName: name.trim(), country: country.trim(), city: city.trim(), email: email.trim(), phone: phone.trim(), plan }); return; } try { const uploaded = await Promise.all(Object.entries(files).filter((entry): entry is [string, File] => Boolean(entry[1])).map(async ([key, file]) => [key, (await uploadDriverFile.mutateAsync({ fileName: file.name, contentType: file.type, base64: await fileToBase64(file) })).url] as const)); const urls = Object.fromEntries(uploaded); driverRegister.mutate({ fullName: name.trim(), email: email.trim(), phone: phone.trim(), city: city.trim(), vehicleType, identityDocumentUrl: urls.identity, licenseDocumentUrl: urls.license, vehicleFrontUrl: urls.front, vehicleBackUrl: urls.back, vehicleLeftUrl: urls.left, vehicleRightUrl: urls.right }); } catch (error) { toast.error(error instanceof Error ? error.message : language === "en" ? "Could not upload driver files" : language === "fr" ? "Impossible d’envoyer les fichiers chauffeur" : "تعذر رفع ملفات السائق"); } };
  const pickFile = (key: string, file?: File) => setFiles((current) => ({ ...current, [key]: file }));
  return <div dir={direction} className="min-h-screen bg-[#f7f8fb] text-slate-900"><DriverApplicationDialog open={driverDialogOpen} onClose={() => setDriverDialogOpen(false)} /><div className="mx-auto grid min-h-screen max-w-6xl lg:grid-cols-[0.8fr_1.2fr]">
    <aside className="relative hidden overflow-hidden bg-[#101d31] p-10 text-white lg:flex lg:flex-col lg:justify-between"><div><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-[#e76f3c]"><Utensils className="h-6 w-6" /></div><div><p className="text-lg font-black">NFOOD</p><p className="text-[10px] tracking-[0.2em] text-slate-400">RESTAURANT OPERATING SYSTEM</p></div></div><div className="mt-24 max-w-sm"><p className="mb-4 flex items-center gap-2 text-sm font-semibold text-orange-200"><Sparkles className="h-4 w-4" /> {copy.different}</p><h1 className="text-4xl font-black leading-[1.25]">{copy.hero}</h1><p className="mt-5 text-sm leading-7 text-slate-300">{copy.safe}</p></div></div><div className="grid grid-cols-3 gap-3 text-center"><div className="rounded-2xl border border-white/10 bg-white/5 p-3"><Store className="mx-auto mb-2 h-5 w-5 text-orange-300" /><p className="text-[11px] text-slate-300">{copy.smartMenu}</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-3"><WalletCards className="mx-auto mb-2 h-5 w-5 text-orange-300" /><p className="text-[11px] text-slate-300">{copy.unified}</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-3"><Sparkles className="mx-auto mb-2 h-5 w-5 text-orange-300" /><p className="text-[11px] text-slate-300">{copy.faster}</p></div></div></aside>
    <main className="flex items-center justify-center p-5 sm:p-8"><div className="fixed right-5 top-5 z-20"><LanguageSwitcher compact /></div><Card className="w-full max-w-2xl rounded-[2rem] border-white/70 bg-white/90 shadow-2xl"><CardContent className="p-6 sm:p-10"><div className="mb-8 flex items-center justify-between"><button type="button" onClick={onBack} className="flex items-center gap-1 text-xs font-bold text-slate-500 hover:text-[#e76f3c]"><ArrowRight className="h-4 w-4" /> {t("back")}</button><div className="flex items-center gap-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-orange-100 text-[#e76f3c]"><Building2 className="h-5 w-5" /></div><span className="font-black">{copy.join}</span></div></div><div className="mb-8"><div className="mb-3 flex items-center justify-between text-[11px] font-bold text-slate-400"><span>{t("status")} {step + 1} / {steps.length}</span><span className="text-[#e76f3c]">{stepLabels[language === "fr" ? "fr" : language === "en" ? "en" : "ar"][step]}</span></div><div className="flex gap-1.5">{steps.map((item, index) => <div key={item} className={`h-1.5 flex-1 rounded-full ${index <= step ? "bg-[#e76f3c]" : "bg-slate-100"}`} />)}</div></div>
      {step === 0 && <section><p className="text-2xl font-black">{copy.chooseTitle}</p><p className="mt-2 text-sm leading-6 text-slate-500">{copy.chooseDesc}</p><div className="mt-7 grid gap-4 sm:grid-cols-2"><button type="button" onClick={() => { setAccountType("restaurant"); setStep(1); }} className={`rounded-3xl border p-5 text-right ${accountType === "restaurant" ? "border-[#e76f3c] bg-orange-50 shadow-lg" : "border-slate-200 bg-white"}`}><Store className="h-7 w-7 text-[#e76f3c]" /><h2 className="mt-5 text-lg font-black">{copy.restaurantPath}</h2><p className="mt-2 text-xs leading-6 text-slate-500">{copy.restaurantDesc}</p></button><button type="button" onClick={() => { setAccountType("driver"); setDriverDialogOpen(true); }} className={`rounded-3xl border p-5 text-right ${accountType === "driver" ? "border-sky-400 bg-sky-50 shadow-lg" : "border-slate-200 bg-white"}`}><UserRound className="h-7 w-7 text-sky-500" /><h2 className="mt-5 text-lg font-black">{copy.driverPath}</h2><p className="mt-2 text-xs leading-6 text-slate-500">{copy.driverDesc}</p></button></div></section>}
      {step === 1 && <section><p className="text-2xl font-black">{accountType === "driver" ? copy.driverData : copy.restaurantData}</p><p className="mt-2 text-sm leading-6 text-slate-500">{copy.required}</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><label className="space-y-2 text-xs font-bold sm:col-span-2">{nameLabel}<Input autoFocus value={name} onChange={(event) => setName(event.target.value)} placeholder={accountType === "driver" ? copy.identityName : copy.exampleRestaurant} className="mt-1 h-12 rounded-2xl bg-slate-50/70 px-4" /></label>{accountType === "restaurant" && <label className="space-y-2 text-xs font-bold">{t("country")}<Input value={country} onChange={(event) => setCountry(event.target.value)} placeholder={copy.countryPlaceholder} className="mt-1 h-12 rounded-2xl bg-slate-50/70 px-4" /></label>}<label className="space-y-2 text-xs font-bold">{t("city")}<Input value={city} onChange={(event) => setCity(event.target.value)} placeholder={copy.cityPlaceholder} className="mt-1 h-12 rounded-2xl bg-slate-50/70 px-4" /></label><label className="space-y-2 text-xs font-bold">{t("email")}<Input type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" dir="ltr" className="mt-1 h-12 rounded-2xl bg-slate-50/70 px-4" /></label><label className="space-y-2 text-xs font-bold">{t("phone")}<Input type="tel" value={phone} onChange={(event) => setPhone(event.target.value)} placeholder="+966 5x xxx xxxx" dir="ltr" className="mt-1 h-12 rounded-2xl bg-slate-50/70 px-4" /></label>{accountType === "driver" ? <label className="space-y-2 text-xs font-bold sm:col-span-2">{copy.vehicle}<select value={vehicleType} onChange={(event) => setVehicleType(event.target.value as VehicleType)} className="mt-1 h-12 w-full rounded-2xl border border-slate-200 bg-slate-50/70 px-4"><option value="car">{copy.car}</option><option value="motorcycle">{copy.motorcycle}</option><option value="bicycle">{copy.bicycle}</option><option value="van">{copy.van}</option><option value="other">{copy.other}</option></select></label> : <div className="rounded-2xl border border-orange-200 bg-orange-50 p-4 text-xs leading-6 text-orange-900 sm:col-span-2"><strong>{copy.autoPassword}</strong><p className="mt-1">{copy.passwordDesc}</p></div>}</div></section>}
      {step === 2 && accountType === "driver" && <section><p className="text-2xl font-black">{t("documents")}</p><p className="mt-2 text-sm leading-6 text-slate-500">{copy.documentsDesc}</p><div className="mt-7 grid gap-4 sm:grid-cols-2">{[["identity", copy.id], ["license", copy.license], ["front", copy.front], ["back", copy.back], ["left", copy.left], ["right", copy.right]].map(([key, label]) => <label key={key} className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-4 text-xs font-bold">{label}<input type="file" accept="image/*,.pdf" onChange={(event) => pickFile(key, event.target.files?.[0])} className="mt-3 block w-full text-xs font-normal" />{files[key] && <span className="mt-2 block truncate text-emerald-700">{copy.selected} {files[key]?.name}</span>}</label>)}</div></section>}
      {step === 2 && accountType === "restaurant" && <section><p className="text-2xl font-black">{t("subscription")}</p><p className="mt-2 text-sm leading-6 text-slate-500">{copy.noPayment}</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{displayPlans.map((item) => <button type="button" key={item.value} onClick={() => setPlan(item.value)} className={`rounded-3xl border p-5 text-right ${plan === item.value ? "border-[#e76f3c] bg-orange-50 shadow-lg" : "border-slate-200 bg-white"}`}><p className="font-black">{item.label}</p><p className="mt-1 text-sm font-bold text-[#e76f3c]">{item.price}</p><p className="mt-2 text-xs leading-5 text-slate-500">{item.description}</p>{item.features.map((feature) => <p key={feature} className="mt-2 flex items-center gap-1 text-[11px] text-slate-600"><Check className="h-3.5 w-3.5 text-emerald-500" />{feature}</p>)}</button>)}</div></section>}
      {step === 3 && <section><div className="mx-auto flex h-16 w-16 items-center justify-center rounded-3xl bg-emerald-100 text-emerald-600"><Check className="h-8 w-8" /></div><p className="mt-6 text-center text-2xl font-black">{accountType === "driver" ? copy.driverPending : copy.ready}</p><p className="mx-auto mt-2 max-w-md text-center text-sm leading-7 text-slate-500">{accountType === "driver" ? copy.reviewDesc : <>{copy.created} <strong className="text-slate-800">{name || copy.restaurant}</strong> {copy.onPlan} <strong className="text-[#e76f3c]">{selectedPlan.label}</strong>.</>}</p><div className="mx-auto mt-7 max-w-md rounded-2xl border border-slate-200 bg-slate-50 p-4 text-sm">{applicationId && <div className="mb-3 rounded-xl bg-sky-100 p-3 text-center text-xs text-sky-900">{copy.application}: <strong>{applicationId}</strong></div>}<div className="flex items-center justify-between border-b border-slate-200 pb-3"><span className="text-slate-500">{copy.email}</span><strong dir="ltr">{email}</strong></div><div className="flex items-center justify-between border-b border-slate-200 py-3"><span className="text-slate-500">{copy.location}</span><strong>{accountType === "restaurant" ? `${country} · ` : ""}{city}</strong></div><div className="flex items-center justify-between pt-3"><span className="text-slate-500">{copy.phone}</span><strong dir="ltr">{phone}</strong></div>{temporaryPassword && <div className="mt-3 rounded-xl border border-emerald-200 bg-emerald-50 p-3"><p className="text-xs text-emerald-700">{copy.temporary}</p><strong className="mt-1 block text-center font-mono text-2xl tracking-[0.35em] text-emerald-900" dir="ltr">{temporaryPassword}</strong></div>}</div></section>}
      <div className="mt-9 flex items-center gap-3"><Button type="button" variant="outline" onClick={() => step === 0 ? onBack() : setStep((current) => current - 1)} className="h-12 rounded-2xl px-5">{step === 0 ? copy.cancel : <><ArrowRight className="ml-1 h-4 w-4" /> {t("back")}</>}</Button>{step < 3 ? <Button type="button" onClick={next} className="h-12 flex-1 rounded-2xl bg-[#e76f3c] text-base font-bold hover:bg-[#d85f2e]">{t("next")} <ArrowLeft className="mr-1 h-4 w-4" /></Button> : <Button type="button" disabled={restaurantRegister.isPending || driverRegister.isPending || uploadDriverFile.isPending || Boolean(applicationId)} onClick={submit} className="h-12 flex-1 rounded-2xl bg-[#e76f3c] text-base font-bold hover:bg-[#d85f2e]">{restaurantRegister.isPending || driverRegister.isPending || uploadDriverFile.isPending ? copy.submitFiles : accountType === "driver" ? copy.joinSubmit : copy.create}</Button>}</div><Button type="button" variant="ghost" onClick={onOAuth} className="mt-3 h-10 w-full rounded-2xl text-xs text-slate-500">{copy.oauth} <ChevronLeft className="mr-1 h-4 w-4" /></Button><p className="mt-2 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-center text-[11px] leading-5 text-amber-800">{copy.demo}</p></CardContent></Card></main></div></div>;
}
