import { useEffect, useState } from "react";
import { Edit3, KeyRound, Mail, Phone, Plus, ShieldCheck, UserRoundCheck, UserRoundX, Utensils } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";

type TeamRole = "restaurant_admin" | "waiter" | "kitchen" | "bar" | "cashier" | "driver" | "customer";
const roleLabels: Record<TeamRole, string> = { restaurant_admin: "مدير مطعم", waiter: "نادل", kitchen: "مطبخ", bar: "بار", cashier: "كاشير", driver: "سائق", customer: "عميل" };

export function RestaurantTeamAccountsPanel({ restaurantId }: { restaurantId: number }) {
  const utils = trpc.useUtils();
  const query = trpc.platform.teamAccounts.useQuery({ restaurantId }, { retry: false });
  const branches = trpc.platform.branches.useQuery({ restaurantId }, { retry: false });
  const create = trpc.platform.createTeamAccount.useMutation({ onSuccess: async () => { toast.success("تم حفظ حساب الفريق"); await utils.platform.teamAccounts.invalidate({ restaurantId }); resetForm(); }, onError: (error) => toast.error(error.message || "تعذر إنشاء الحساب") });
  const update = trpc.platform.updateTeamAccount.useMutation({ onSuccess: async () => { toast.success("تم تحديث الحساب"); await utils.platform.teamAccounts.invalidate({ restaurantId }); resetForm(); }, onError: (error) => toast.error(error.message || "تعذر تحديث الحساب") });
  const assign = trpc.platform.replaceWaiterTableAssignments.useMutation({ onSuccess: async (result) => { toast.success(`تم ربط ${result.assignedTableIds.length} طاولات بالنادل`); setAssigningUserId(null); setSelectedTableIds([]); }, onError: (error) => toast.error(error.message || "تعذر حفظ طاولات النادل") });
  const [open, setOpen] = useState(false);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [form, setForm] = useState({ displayName: "", email: "", phone: "", password: "", role: "waiter" as TeamRole });
  const [assigningUserId, setAssigningUserId] = useState<number | null>(null);
  const [selectedBranchId, setSelectedBranchId] = useState("");
  const [selectedTableIds, setSelectedTableIds] = useState<number[]>([]);
  const tableQuery = trpc.platform.tablesByBranch.useQuery({ restaurantId, branchId: Number(selectedBranchId) }, { enabled: Boolean(selectedBranchId), retry: false });
  const accounts = query.data ?? [];
  const waiterAccounts = accounts.filter((account) => account.role === "waiter" && account.userId);
  const resetForm = () => { setForm({ displayName: "", email: "", phone: "", password: "", role: "waiter" }); setEditingId(null); setOpen(false); };
  const editAccount = (account: (typeof accounts)[number]) => { setEditingId(account.id); setForm({ displayName: account.displayName, email: account.email, phone: account.phone ?? "", password: "", role: account.role as TeamRole }); setOpen(true); };
  useEffect(() => { if (!selectedBranchId && branches.data?.[0]) setSelectedBranchId(String(branches.data[0].id)); }, [branches.data, selectedBranchId]);
  const toggleTable = (id: number) => setSelectedTableIds((current) => current.includes(id) ? current.filter((tableId) => tableId !== id) : [...current, id]);
  return <Card className="rounded-2xl border-slate-200 bg-white shadow-sm">
    <CardHeader className="flex flex-row items-center justify-between gap-3 border-b border-slate-100"><div><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-5 w-5 text-[#e76f3c]" /> حسابات الفريق والصلاحيات</CardTitle><p className="mt-1 text-xs text-slate-500">أضف حسابات دخول مستقلة للنادل والسائق، ثم اربط النادل بالطاولات الخاصة به.</p></div><Button type="button" onClick={() => setOpen((value) => !value)} className="rounded-xl bg-[#e76f3c] text-xs hover:bg-[#d85f2e]"><Plus className="ms-1 h-4 w-4" /> حساب جديد</Button></CardHeader>
    <CardContent className="space-y-3 p-4">
      {open && <div className="grid gap-2 rounded-2xl border border-orange-100 bg-orange-50/50 p-4 sm:grid-cols-2"><label className="text-xs font-bold">الاسم<Input value={form.displayName} onChange={(event) => setForm({ ...form, displayName: event.target.value })} className="mt-1 rounded-xl bg-white" placeholder="مثال: أحمد" /></label><label className="text-xs font-bold">البريد الإلكتروني<Input value={form.email} onChange={(event) => !editingId && setForm({ ...form, email: event.target.value })} readOnly={Boolean(editingId)} dir="ltr" type="email" className={`mt-1 rounded-xl bg-white ${editingId ? "cursor-not-allowed opacity-70" : ""}`} placeholder="ahmad@example.com" /></label><label className="text-xs font-bold">رقم الجوال<Input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} dir="ltr" className="mt-1 rounded-xl bg-white" placeholder="05xxxxxxxx" /></label><label className="text-xs font-bold">كلمة المرور<Input value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} dir="ltr" type="password" autoComplete="new-password" className="mt-1 rounded-xl bg-white" placeholder={editingId ? "اتركها فارغة للإبقاء عليها" : "8 أحرف على الأقل"} /></label><label className="text-xs font-bold">الدور<select value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value as TeamRole })} className="mt-1 h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm">{(["waiter", "driver", "kitchen", "bar", "cashier"] as TeamRole[]).map((value) => <option key={value} value={value}>{roleLabels[value]}</option>)}</select></label><div className="flex items-end gap-2"><Button type="button" disabled={create.isPending || update.isPending || form.displayName.trim().length < 2 || !form.email.includes("@") || (!editingId && form.password.length < 8)} onClick={() => editingId ? update.mutate({ restaurantId, id: editingId, displayName: form.displayName.trim(), phone: form.phone.trim() || null, password: form.password.trim() || undefined, role: form.role }) : create.mutate({ restaurantId, displayName: form.displayName.trim(), email: form.email.trim(), phone: form.phone.trim() || undefined, password: form.password, role: form.role })} className="h-10 flex-1 rounded-xl bg-[#111c2e]">{create.isPending || update.isPending ? "جارٍ الحفظ..." : editingId ? "حفظ التعديل" : "حفظ الحساب"}</Button><Button type="button" variant="outline" onClick={resetForm} className="h-10 rounded-xl">إلغاء</Button></div></div>}
      {query.isLoading ? <div className="h-24 animate-pulse rounded-xl bg-slate-100" /> : query.isError ? <div className="rounded-xl bg-red-50 p-4 text-sm text-red-700">تعذر تحميل حسابات الفريق. <button type="button" className="font-bold underline" onClick={() => void query.refetch()}>إعادة المحاولة</button></div> : accounts.length === 0 ? <div className="rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-500">لا توجد حسابات فريق إضافية بعد.</div> : accounts.map((account) => <div key={account.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-100 bg-slate-50/70 p-3"><div className="flex min-w-0 items-center gap-3"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${account.isActive ? "bg-emerald-100 text-emerald-700" : "bg-slate-200 text-slate-500"}`}>{account.isActive ? <UserRoundCheck className="h-5 w-5" /> : <UserRoundX className="h-5 w-5" />}</div><div className="min-w-0"><p className="truncate text-sm font-bold">{account.displayName}</p><div className="mt-1 flex flex-wrap gap-2 text-[10px] text-slate-500"><span><Mail className="me-1 inline h-3 w-3" />{account.email}</span>{account.phone && <span dir="ltr"><Phone className="me-1 inline h-3 w-3" />{account.phone}</span>}<span><KeyRound className="me-1 inline h-3 w-3" />{roleLabels[account.role as TeamRole] ?? account.role}</span><span>أُنشئ {new Date(account.createdAt).toLocaleDateString("ar-SA-u-ca-gregory-nu-latn")}</span></div></div></div><div className="flex items-center gap-2"><Button type="button" variant="outline" size="sm" onClick={() => editAccount(account)} className="rounded-lg text-xs"><Edit3 className="me-1 h-3 w-3" />تعديل</Button>{account.role === "waiter" && <Button type="button" variant="outline" size="sm" disabled={!account.userId} onClick={() => { setAssigningUserId(account.userId); setSelectedTableIds([]); }} className="rounded-lg text-xs"><Utensils className="me-1 h-3 w-3" />طاولاته</Button>}<Button type="button" variant="outline" size="sm" disabled={update.isPending} onClick={() => update.mutate({ restaurantId, id: account.id, isActive: !account.isActive })} className={`rounded-lg text-xs ${account.isActive ? "text-red-600" : "text-emerald-700"}`}>{account.isActive ? "إيقاف الحساب" : "تنشيط الحساب"}</Button></div></div>)}
      {assigningUserId && <div className="rounded-2xl border border-orange-200 bg-orange-50/60 p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-black">تعيين طاولات النادل</p><p className="mt-1 text-xs text-slate-500">اختر الفرع ثم الطاولات. يمكن ربط عشر طاولات أو أي عدد حسب تشغيل المطعم.</p></div><Button type="button" variant="outline" size="sm" onClick={() => setAssigningUserId(null)}>إغلاق</Button></div><select value={selectedBranchId} onChange={(event) => { setSelectedBranchId(event.target.value); setSelectedTableIds([]); }} className="mt-3 h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm"><option value="">اختر الفرع</option>{(branches.data ?? []).map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4">{(tableQuery.data ?? []).map((table) => <button type="button" key={table.id} onClick={() => toggleTable(table.id)} className={`rounded-xl border px-3 py-2 text-xs font-bold ${selectedTableIds.includes(table.id) ? "border-[#e76f3c] bg-[#e76f3c] text-white" : "border-slate-200 bg-white text-slate-700"}`}>{table.name}</button>)}</div><Button type="button" disabled={!selectedBranchId || assign.isPending} onClick={() => assign.mutate({ restaurantId, branchId: Number(selectedBranchId), waiterUserId: assigningUserId, tableIds: selectedTableIds })} className="mt-4 w-full rounded-xl bg-[#111c2e]">{assign.isPending ? "جارٍ حفظ الطاولات..." : `حفظ ربط ${selectedTableIds.length} طاولات`}</Button></div>}
    </CardContent>
  </Card>;
}
