import { useEffect, useMemo, useState } from "react";
import { Activity, Check, Filter, ShieldCheck } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";

export function RestaurantAccessControlPanel({ restaurantId }: { restaurantId: number }) {
  const utils = trpc.useUtils();
  const roles = trpc.platform.restaurantRoles.useQuery({ restaurantId }, { retry: false });
  const permissions = trpc.platform.restaurantPermissions.useQuery(undefined, { retry: false });
  const [roleId, setRoleId] = useState<number | null>(null);
  const selectedRole = useMemo(() => roles.data?.find((role) => role.id === roleId) ?? roles.data?.[0], [roles.data, roleId]);
  const rolePermissions = trpc.platform.restaurantRolePermissions.useQuery({ restaurantId, roleId: selectedRole?.id ?? 0 }, { enabled: Boolean(selectedRole?.id), retry: false });
  const [selected, setSelected] = useState<string[]>([]);
  const [activityFilter, setActivityFilter] = useState("");
  const activity = trpc.platform.activityAuditLogs.useQuery({ restaurantId, action: activityFilter.trim() || undefined, limit: 100 }, { retry: false });
  const save = trpc.platform.setRestaurantRolePermissions.useMutation({ onSuccess: async () => { toast.success("تم حفظ صلاحيات الدور"); await rolePermissions.refetch(); }, onError: (error) => toast.error(error.message || "تعذر حفظ الصلاحيات") });
  useEffect(() => { if (selectedRole?.id && !roleId) setRoleId(selectedRole.id); }, [roleId, selectedRole?.id]);
  useEffect(() => { setSelected((rolePermissions.data ?? []).map((permission) => permission.key)); }, [rolePermissions.data]);
  const grouped = useMemo(() => (permissions.data ?? []).reduce<Record<string, typeof permissions.data>>((groups, permission) => { const group = permission.key.split(".")[0] ?? "general"; (groups[group] ??= []).push(permission); return groups; }, {}), [permissions.data]);
  const toggle = (key: string) => setSelected((current) => current.includes(key) ? current.filter((item) => item !== key) : [...current, key]);
  const permissionIds = (permissions.data ?? []).filter((permission) => selected.includes(permission.key)).map((permission) => permission.id);
  return <div className="grid gap-4 xl:grid-cols-[1.05fr_1fr]">
    <Card className="rounded-2xl border-slate-200 bg-white shadow-sm"><CardHeader className="border-b border-slate-100"><CardTitle className="flex items-center gap-2 text-base"><ShieldCheck className="h-5 w-5 text-[#e76f3c]" /> الصلاحيات التفصيلية حسب الدور</CardTitle><p className="mt-1 text-xs text-slate-500">مثال: يمكن منح النادل إدارة الطلبات فقط، مع حجب التقارير والبيانات المالية.</p></CardHeader><CardContent className="space-y-4 p-4"><select value={selectedRole?.id ?? ""} onChange={(event) => setRoleId(Number(event.target.value))} className="h-10 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm">{(roles.data ?? []).map((role) => <option key={role.id} value={role.id}>{role.name}</option>)}</select>{rolePermissions.isLoading ? <div className="h-28 animate-pulse rounded-xl bg-slate-100" /> : <div className="grid gap-3 sm:grid-cols-2">{Object.entries(grouped).map(([group, items]) => <div key={group} className="rounded-xl border border-slate-100 p-3"><p className="mb-2 text-xs font-black text-slate-700">{group}</p>{(items ?? []).map((permission) => <label key={permission.id} className="flex cursor-pointer items-center gap-2 py-1.5 text-xs text-slate-600"><input type="checkbox" checked={selected.includes(permission.key)} onChange={() => toggle(permission.key)} className="h-4 w-4 accent-[#e76f3c]" /><span>{permission.label}</span>{selected.includes(permission.key) && <Check className="ms-auto h-3.5 w-3.5 text-emerald-600" />}</label>)}</div>)}</div>}<Button type="button" disabled={save.isPending || !selectedRole?.id} onClick={() => save.mutate({ restaurantId, roleId: selectedRole!.id, permissionIds })} className="w-full rounded-xl bg-[#111c2e]">{save.isPending ? "جارٍ الحفظ..." : "حفظ صلاحيات الدور"}</Button></CardContent></Card>
    <Card className="rounded-2xl border-slate-200 bg-white shadow-sm"><CardHeader className="border-b border-slate-100"><CardTitle className="flex items-center gap-2 text-base"><Activity className="h-5 w-5 text-[#e76f3c]" /> سجل نشاط المطعم</CardTitle><p className="mt-1 text-xs text-slate-500">تتبع تغييرات الحسابات وانتقالات حالات الطلبات مع الفاعل والتوقيت.</p></CardHeader><CardContent className="space-y-3 p-4"><div className="flex gap-2"><Input value={activityFilter} onChange={(event) => setActivityFilter(event.target.value)} placeholder="فلترة الحدث مثل order.status.updated" dir="ltr" className="rounded-xl" /><Button type="button" variant="outline" onClick={() => void activity.refetch()} className="rounded-xl"><Filter className="h-4 w-4" /></Button></div>{activity.isLoading ? <div className="h-28 animate-pulse rounded-xl bg-slate-100" /> : activity.isError ? <div className="rounded-xl bg-red-50 p-4 text-sm text-red-700">تعذر تحميل سجل النشاط. <button type="button" className="font-bold underline" onClick={() => void activity.refetch()}>إعادة المحاولة</button></div> : activity.data?.length ? <div className="max-h-[420px] space-y-2 overflow-auto">{activity.data.map((event) => <div key={event.id} className="rounded-xl border border-slate-100 bg-slate-50/70 p-3"><div className="flex items-center justify-between gap-2"><code className="text-[11px] font-bold text-[#111c2e]">{event.action}</code><span className="text-[10px] text-slate-400">{new Date(event.createdAt).toLocaleString("ar-SA")}</span></div><p className="mt-1 text-[11px] text-slate-500">الدور: {event.actorRole ?? "غير معروف"} · العنصر: {event.entityType ?? "—"} #{event.entityId ?? "—"}</p></div>)}</div> : <div className="rounded-xl bg-slate-50 p-6 text-center text-sm text-slate-500">لا توجد أحداث مطابقة.</div>}</CardContent></Card>
  </div>;
}
